
bg e022,42
wait 1000
bg black,42
bgcopy ;背景をリセット

fede 0,2000
E_A
wait 2000


if %UMINEKOEND < 1 mov %UMINEKOEND,1 : mov %END_FLG,1 ;クリアフラグの変更

	saveoff            ;セーブオフで、処理を高速化する。
	erasetextwindow 0  ;テキストエフェクトを切る事で処理を高速化
	rmode 0            ;右クリックのメニュー表示の無効化
	textoff

goto *b_title
;reset

*higan2_opning
texton
csp -1

bg black,2
bgcopy ;背景をリセット

setwindow 31,16,22,16,26,26,0,2,20,1,1,#999999,0,0,639,479

!sd

mono 0
E_A

wait 2000

bg gakkou_01,2

bgm1 1

