;Chapter 5
;　午前８時５０分。@
`　8:50AM`@
br
;　普段なら登校してきた生徒たちはまっすぐ教室に向かい、@始業のベルと共に担任が入ってくるまで、クラスメートたちとのおしゃべりに盛り上がる。@そんな時間。\
`　Normally, attending students would be heading straight for their classrooms, `@`and until the start of the first bell, they'd strike up conversation with their fellow classmates. `@`It was that time of the day.`\

bg black,22
bg usagi_01,2

;　しかしこの日のこの時間は少し様子が違った。@
`　However, at this hour things were a little different today.`@
br
;　かなりの数の生徒たちが、校舎に入ろうとはせず、@校舎裏にあるうさぎ小屋の前に集まっていたのだ。\
`　Instead of a lot of students gathering to enter the school building, `@`they gathered in front of some rabbit cages behind the building.`\

bg black,22

me2v 17,70

;　悲鳴を上げる子、呆然と立ち尽くす子、近くの排水溝に嘔吐する子。@
`　Some were screaming, some stood dumbfounded, and some were vomiting in the nearby storm drain.`@
;　……目の前の光景に対し、彼らがとった行動は実に様々だった。@
`　...Their reactions to the spectacle that lay before them was of all varities.`@
br
;　しかし、よくよく観察してみれば、@彼らの瞳の奥に同じ色が浮かんでいることが分かっただろう。\
`　However, if one carefully observes, `@`they would be able to tell that in the depths of their eyes they all had the same look.`\
mono 2

bg Different_spiral_1a,22

;　それは「好奇」の色。@
`　That was the look of 'curiosity.'`@
br
;　息を呑んで目を見開く男子生徒も、@友人同士で身を寄せ合い、今にも泣きだしそうな女生徒たちも、実は同じことを思っていた。\
`　For the male students who caught their breath and opened their eyes, `@`they huddled with their friends, and even the girls who seemed about to cry, were really thinking the same thing.`\

;　……これって…………なんかスゴイ。@
`　...This was ...somehow amazing.`@
br
;　こんなにも残酷な光景を見るのは、彼らにとって初めてのことだったからだ。@
`　After all, this was the first time they had seen such a cruel spectacle before.`@
br
;　ドラマでも、アニメでも、ましてや漫画でもない。@現実世界で。@しかも自分たちが毎日通う学校で。\
`　It wasn't in a drama, anime, or even manga. `@`It was in the real world. `@`Moreover, at the school they go to every day.`\

textoff

bg black,22
mono 0

fede 0,1000
E_A

bg blood_1aR,22
;quakey 2,200

bgm1 13

;　…………小屋の中は、一面の赤黒い血の海だった。\
`　......Inside the pen, the bottom was a sea of dark red blood.`\

;　耳を力任せに引き千切られたうさぎ。@
`　Rabbits that have had their ears torn apart.`@
br
;　しっぽ、前足、後ろ足……鋭利な刃物か何かで、@胴体からすべての器官を切り取られたうさぎ。@
`　Tails, front legs, back legs, and all their organs from their torsos --`@` Rabbits diced up with some kind of sharp instrument... 
br
;　全身が紫に変色するほど殴られ、短い手足がありえない方向に折れ曲がっているうさぎ。\
`　Rabbits with their whole bodies turned purple from being beaten, and their tiny limbs bent in impossible directions.`\


;　「残酷」という言葉がぴったりと当てはまる、この上なく凄惨な光景だった。@
`　There had never been such a gruesome scene more befitting of the word "cruel."
br
;　しかも何匹かのうさぎはそんな状態であるにも関わらず、まだ生きていた。@
`　Furthermore, regardless of how many rabbits were in that state, they were still alive.`@
;　血を流し、震えながらも、弱々しく息をしていた。@
`　Blood flowing, as they shivered, they let out shallow breaths.`@
br
;　しかし、誰一人として手当てをしようとする生徒はいない。\
`　But there was no one among the students who could treat them.`\

bg black,22

me1v 5,50

;　いくら幼い彼らでも理解していたのだ。@どんな処置をしたところでこのうさぎたちは助からない。@
`　Despite how young they were, they understood. `@`No matter what kind of measures they took, these rabbits could not be saved.`@
br
;　いや……、こんな状態で助かってしまったら、その方がよっぽど悲劇だということを。\
`　Rather... they realized that if they saved the rabbits as they were, then that would be even more cruel.`\

bg usagi_01,22

;　騒ぎを聞きつけ、職員室から教師たちが駆けつけた。@
`　Hearing the commotion, the teachers ran out of the staff room.`@
br
;　彼らもうさぎ小屋を覗き込むと一様に青褪めて絶句したが、@かろうじて平静を取り戻すと生徒たちに教室で待機するよう指示を出した。\
`　Although they all too turned pale and were at a loss for words after taking a look at the rabbit pens, `@`they managed to restore some order and directed the students to wait in their classrooms.`\

;　しかし、子供たちがいなくなってからも、教師たちはしばらく動けず、@惨殺されたうさぎたちをただただ痛々しく見つめ続けた。\
`　However, even after the children had gone, the teachers didn't move for some time, `@`they merely painfully continued to watch the massacred rabbits.`\

;mbg white,1
;mcbg 22

se1v 13,40

;　その時、小屋の隅の方で、何かが動いた気がした。@
`　At that moment, they sensed that something moved from the corner of the pen.`@
br
;　そこにはうさぎたちが掘った穴があった。@その中から、恐る恐るこちらの様子を伺うように一匹のうさぎが顔を出したのだ。\
`　There was a hole that the rabbits had dug. `@`And from inside, the head of one terrified rabbit looking on at the scene popped out.`\

;「……不幸中の幸い、だな。」@
`"...Every cloud has a silver lining, apparently.`@
br
;　教師の一人が呟いた。@
`　One of the teachers muttered.`@
;　すると、それが合図かのように、穴の中から次々にうさぎたちが現れた。\
`　And, as if that was their signal, one after another rabbits began to come out of the hole.`\

;　多少足を引きずっているものもいるが、どのうさぎも大きな怪我はしていないようだった。@
`　Although some were dragging their legs, none of them seemed to have any major injuries.`@
br
;　赤い血の海の中を動き回る真っ白なうさぎたち……。@何とも現実離れしたその光景に、再び言葉をなくす教師たち。\
`　The white rabbits move around the sea of red blood... `@`Caught in the scene disconnected from reality, once again the teachers were at a loss for words.`\

;　しかし、不意にその沈黙を破り、一人の若い教師が疑問を口にした。@
`　However, the silence was abruptly cut short when one of the young teachers decided to ask a question.`@
br
;　恐る恐る。@……だけれども、あまりに素朴に。\
`　Timidly, timidly. `@`...Though, incredibly bluntly.`\

bg black,22

fede 0,1000
E_A

;「あの……、うちって、こんなにたくさん、うさぎ飼ってましたっけ……？」@
`"Um... did we, really, even keep this many rabbits in the pens...?"`@

me1v 17,70

br
;　生きているうさぎと、うさぎの死骸。@
`　The live rabbits and rabbit corpses.`@
br
;　その合計数が、彼らが飼っていると認識していたそれを、上回っていたのだ。\
`　Their total numbers far exceeded the number of rabbits they had all thought were in the cages.`\

bg black,22

fede 0,2000
E_A








bg rouka_02,2

bgm1 8

;　午前９時２０分。@
`　9:20AM.`@
br
;　２組の担任である井俣は教室に向かいながら、@うさぎ小屋の件を生徒たちにどう説明すべきか考えていた。\
`　Imata, the person in charge of the 2nd group, was heading for the classroom, `@`and was thinking about how he should explain the rabbit pen incident to the students.`\

;　不意に先日聞いたあるニュースを思い出す。@
`　Suddenly he recalls news he heard the other day.`@
br
;　隣町の小中学校で、@予算カットのため動物の飼育小屋を全てなくすことが決まったという内容だった。\
`　At the elementary school in the neighboring town, `@`it was talking about how they had to get rid of their animal pens due to budget cuts.`\

;　餌代やら維持費を節約するために、@子供たちが動物と触れ合う機会を取りやめるなんて随分とケチくさいな、とその時は思った。@
`　It was in order to save on maitainance and food costs, `@`and he remembered how cheap they seemed to rob those children of the chance to pet and play with those animals.`@
br
;　しかし今になって思う。@予算カットと言うのは建前だったのではないだろうか。@あれはこういう事態に備えてのことだったのではないだろうか、と。\
`　But now that he thinks about it. `@`Perhaps that talk about budget cuts was just to save face. `@`Perhaps it might have been to dress up an incident like this one.`\

bg black,22

;　物騒な時代だ。子供たちの心も荒んでる。@
`　It's a dangerous age. The hearts of children are going wild.`@
;　動物を飼うことが、情操教育の一環になると信じられた時代は、@すでに遠い過去の話なのかもしれない……。\
`　The idea that taking care of pets was part of a good education,`@` might already be a thing of the past...`\



textoff

lsp bgsp,":a;bmp\background\efe\red_waku.bmp",0,0
bg usagi_01,22
bgcopy
csp -1

;　あのうさぎ小屋はどうなるのだろう。@
`　What will happen with those rabbit pens?`@
br
;　何匹か生き残っていたとは言え、@あの小屋であのまま飼育を続けるのは難しいだろうな、と思う。\
`　Although many were left alive, `@`it would probably be hard to keep raising aniamls in those pens as they are now, so he thought.`\

;　うさぎの死骸を全部拾い集めても、夥しい血を洗い流しても。@あの腐った肉のような臭いや、むせ返るような鉄の匂いは、多分なかなか落ちない。\
`　Even if all the bodies of the rabbits were gathered, and all the vast amounts of blood washed away,`@` that smell like rotten meat, and that choking odor of iron, probably won't really go away.`\

;　……まあ、そもそもあのうさぎ小屋に近づく生徒は少なかったしな。@
`　...Well, there have been few students going near the rabbit pens since the beginning.`@
br
;　うさぎなんて珍しいものでもないし、@わざわざ職員室に鍵を借りに来てまで触れ合おうとする生徒はほとんどゼロに近かった。\
`　It wasn't uncommon for the rabbits and the like, `@`there was almost zero students who would go as far as to expressly ask to borrow the key to the pens in the staff room to pet them.`\

;　それは井俣や他の教師たちも同じで、小屋の中を覗き込むことすら滅多になかった。@
`　It was the same for Imata and the other teachers -- they rarely even checked inside those pens.`@
br
;　鍵を借りに来たのはうちのクラスの飼育委員の生徒だけだ。\
`　Just a student, one of our class's animal rearing committee members, came to borrow a key.`\

bg black,22
;ld c,HIK_Def1,22


;　いつも無表情なあの子。@学年でもトップクラスの成績を持つあの男子生徒。@
`　That ever expressionless kid. `@`That boy with the top grades in his age bracket.`@
br
;　さっきうさぎ小屋を囲んでいた集団の中にあの子はいたのだろうか。@
`　I wonder if he was among that group of kids circling the rabbit pens just now?`@
;　いたとしたら、……さぞショックを受けたことだろう。\
`　If he was there, ...it must have given him quite a shock.`\

bg kyou_04,22

me1v 24,50

;　教室の前まで辿り着き、井俣は立ち止まった。@教室内からがやがやと騒がしい話声が聞こえる。\
`　Finally arriving at the classroom, Imata came to a stop. `@`From inside the classroom he could hear a crowd of students making loud conversation.`\

;『マジで、すごかったんだぜ。』@『血がさ。』@『ドバーってさ。』@
`(?) "Seriosly, it was awesome!"`@` "The blood, see."`@` "It was gushing"`@
br
;　興奮して語る生徒たちの声を聞きながら、井俣は溜め息をついた。\
`　As he listened to the excited voices of the students talking, Imata let out a sigh.`\

;　間もなく警察も来るだろう。@どの程度の扱いになるかは分からないがテレビでニュースも流れるかもしれない。@地方紙には大きく取り上げられるだろうし、ＰＴＡとの緊急集会も開かれるはずだ。\
`　Before long the police should come. `@`He doesn't know what level of assistance he can provide, but the news might leak onto the television. `@`The local newspaper will likely pick up on it, and the PTA should open up an emergency meeting.`\

;　まったく……、何だって昨日からこんなに問題ばかり続くんだ……。@
`　Geez... we've had nothing but problems like these since yesterday...`@
br
;　昨日、井俣のクラスの生徒が行方不明になった。@しかも同時に４人。@
`　Yesterday, some studens in Imata's class were unaccounted for. `@`Furthermore, 4 people at the same time.`@
;　夜遅くになってそれぞれの親から、まだ学校から帰ってこない、と連絡が入ったのだ。\
`　He had gotten word that from several parents after it had gotten late at night that their students hadn't come home yet from school.`\

;　普段から学校をサボることが多く、@何かと素行の悪い生徒たちだったので、井俣は正直そこまで心配はしていなかった。@
`　Normally it wasn't uncommon for students to skip school, `@`and for some reason those students were a particularly ill-mannered bunch, so Imata wasn't honestly that worried about them.`@
br
;　……しかし一晩あけてもまだ見つかっていないとなると、さすがに楽観視はできなかった。\
`　...However, when they still weren't found a day later, he obviously couldn't remain optimistic.`\

se1v 82,100

E_MA

bg white,64
bg kyou_01,22

;　ふぅっ、ともう一度重い溜息を吐いて、井俣は教室の扉を開けた。@
`　*Phew*, Imata let out another heavy sigh and opened the classroom door.`@
br
;　生徒たちがおしゃべりをやめて一斉にこちらを向く。\
`　The students stopped chatting and all at once turned to face his way.`\

;　最前列に座っていた生徒と目が合った。@
`　He met eyes with a student sitting in the front row.`@
;　毎日うさぎ小屋に通っていた飼育委員、@二瓶ひかる（にへい　ひかる）は、相変わらず無表情だった。\
`　An animal raising committee member who went to the rabbit pens every day, `@`Hikaru Nihei (二瓶ひかる), was as expressionless as always.`\

textoff

ld r,HIK_Def1,22

wait 1000

ld r,HIK_Def2,22

cl r,22

;　井俣は改めて教室を見渡す。@
`　Once again Imata looks over the classroom.`@
br
;　一つ、二つ、三つ、四つ。@
`　One, two, three, four.`@
;　うさぎの事件の影に隠れてしまったが、@……昨日から行方不明になっている生徒の席は、依然、空席のまま点在していた……。\
`　It might have been hidden under the shadow of the rabbit incident, `@`...but since yesterday the missing students seats still dotted the classroom, empty...`\

bg black,0
ld c,HIK_Def2,22

;　二瓶ひかるはその無表情っぷりに相応しく、とてもおとなしい生徒だった。@
`　Hikaru Nihei was appropriately expressionless, a very quiet student.`@
br
;　しかし、クラスでの彼の様子を見ていれば、性格的におとなしい、と言うわけではなく、@誰も口を利くクラスメートがいない、ということに気付くはずだ。\
`　However, looking him in this class, it wasn't that his personality was quiet, `@`but he didn't have classmates to talk to -- so it seemed.`\

;　ひかるには話し相手がいない。@
`　Hikaru didn't have anyone to talk to.`@
br
;　……つまり友達がいない。\
`　...In other words, he had no friends.`\

bg black,2
bg kyou_03,22

me1v 24,50

;「……で、旧校舎の女子トイレから聞こえてくるんだってさ。@“めそめそ……めそめそ……そこの人、@どうか哀れな私の話を聞いてください”って女の子の声が……。」\
`"...So, they say you can hear it from the former school building girl's bathroom. `A girl's voice would say...`@` "Mesomeso...mesomeso...you there, `@`please listen to my pitiful story~"`\

;「え、男じゃないの？@　なんか男の悲鳴や絶叫が聞こえるって。」@
`"Eh, it's not a guy? `@`I heard someone say they heard a guy screaming and shouting."`@
;「だーかーらー。@それは、めそめそさんに祟り殺された先生の声で。」\
`"As - I - was - saying. `@`That's the voice of the teacher that was killed by Mesomeso-san's curse."`\

;　帰りのホームルームが終わった後、教室の隅でクラスメートたちが話をしていた。@
`　After returning to their home room, his classmates were talking in the corner of the room.`@
br
;　すぐ近くにひかるが座っているのに、会話に混ぜようとする気配は全くない。\
`　Even though they were sitting right next to him, there was no sign at all of him getting into the conversation.`\

;　それどころか視線にすら入れようとせず、ひかるの存在を完全に無視していた。@
`　They wouldn't even let him enter their gaze, and they completely ignored Hikaru's existence.`@
;　こんなやつは最初からいない。@そんな態度だった。\
`　That kind of guy wasn't there from the beginning. `@`It was that kind of attitude.`\

;　ひかるはさっさと教室を出たかった。@
`　Hikaru wanted to quickly leave the classroom.`@
br
;　学校はもう終わったのだ。@自分をまるでいない者として扱う連中と一緒にいるのは苦痛でしかなかった。\
`　School was already over. `@`Staying around people who acted like he didn't exist was only agonizing.`\

bg black,22

;　だが、帰ろうとしたひかるは、自分の鞄が余りにも軽いことに気付く。@
`　However, when Hikaru decided to go home, he noticed his bag was extremely light.`\
br
;　……教科書やノートはホームルームが始まる前に全部しまったはずなのに。\
`　...Even though he should have had his notebook and textbook since the beginning of homeroom period.`\

;　机の中やロッカーを探していると、@ついさっきまで徹底してひかるを無視していたクラスメートたちが、@いつの間にか話すのをやめてニヤニヤとこちらを見ているのが目に入った。\
`　Looking through inside his desk and locker, `@`his classmates who had been completely ignoring Hikaru until moments ago, `@`suddenly stopped talking and he caught sight of them grinning his way.`\

bg kyou_02,22
ld r,HIK_def2,22

;　……またかよ。@
`　...Not again.`@
br
;　そう思ってゴミ箱を見に行くと、案の定ひかるの教材道具は全部そこに投げ込まれていた。@
`　Thinking so, he went to look in the garbage can, and as he thought, Hikaru's class materials had all been thrown inside.`@
;　……ご丁寧に給食の飲み残しの牛乳がまんべんなくかけられて。\
`　...He carefully moved the leftover milks that covered them.`\

;　ぐっしょり、べったりと汚されたそれに、@自分の名前が書かれていることを認めるのは、それだけで苦痛だった。@
`　They were soaking wet and thickly soiled `@`and recognizing these were his things with his name written on them -- that alone was painful.`@
br
;　教科書はともかく、ノートは捨てるしかないだろう。@先週同じことをされて買い替えたばかりなのに。\
`　He could make use of the textbook, but he probably had to throw away the notebook. `@`Even though he had just gotten it exchanged last week for the same reason...`\

;　何とも言えない悔しさと情けなさがこみ上げてきて、一瞬視界がふるっと揺れる。@
`　A feeling of frustration and shame that could not be put into words welled his heart, and for an instant his vision blurred.`@
br
;　ひかるは俯いたまま、しばらく顔を上げなかった。@クラスメートたちが自分のことをじっと見ているのを感じたからだ。\
`　As Hikaru held his head in shame, he didn't raise his face for some time. `@`Because he felt his classmates starting at him.`\

ld r,HIK_Def3,22

;　そのままの姿勢で深呼吸をし、唇を噛んでいつもの無表情を作る。@そうしてゴミ箱から教科書を拾うと、牛乳にまみれた教科書をそのまま鞄の中に突っこんだ。@
`　Keeping his posture, he took a deep breath, bit his upper lip, and made his usual expressionless face. `@`With that, he took up his textbook from the garbage can, and stuffed that milk-stained textbook in his bag.`@
br
;　家に帰るまでこの鞄を開けることはないだろう。@学校の中で教科書を洗って乾かしている惨めな姿なんて、誰にも見せたくはなかった。\
`　He probably wouldn't open that bag until he got home.`@` He didn't want anyone to see him pathetically cleaning and drying out his textbook at school.`\

ld r,HIK_Def2,80

cl r,23

E_MA

se1v 82,85

bg white,63
bg kyou_04,22
quakex 1,100

;　その場から逃げるように教室を出る。@扉を閉めると同時に、大袈裟なほど下品な笑い声が聞こえてきた。\
`　He left the classroom as if he were running away from that scenario. `@`As he shut the door, he heard a grandoise vulgar laughter.`\


;「…………………………。」@
`"........."`@
br
;　ひかるはもう一度唇を噛み締める。@そして教室に背を向けて歩き出す。\
`　Hikaru once again bit his lower lip.`@` Then he turns away from the classroom and walks off.`\

bg black,24

me1v 16,50

bg rouka_03,24

;　一刻も早くうさぎ小屋に行きたかった。@
`　He wanted to quickly head to the rabbit pens.`@
br
;　……この学校で唯一自分を慰めてくれる、あのうさぎたちのところへ。\
`　...In this school, Hikaru's unique place to go forget her worries, was to the rabbits.`\
bg black,2

fede 1,2000
E_B

bg usagi_01,22
wait 2000

bg black,22
bg usagi_02,22

;ld c,HIK_Def2,23
;ld c,HIK_Def1,80

fede 0,1000
E_A

bgm1 8

;「お待たせ。@みんな元気だった…？」@
`"Thanks for waiting.`@` How have all of you been...?"`@`
br
;　うさぎ小屋の扉を開けながら、ひかるは話し掛ける。@
`　While opening the door to their cage, Hikaru spoke to them.`@`
;　その顔はさっきまでの無表情が嘘のように生気に満ちていた。@声も随分と上機嫌な様子だ。\
`　That face which had been expressionless until now, was filled with such spirit it was hard to believe.`@` His voice also seemed to become extremely good-humored.`\

;ld c,HIK_Def1,80
;quakey 1,200

;　背負っていた鞄を小屋の隅の方に放り投げる。@ドサッという音と共に、乾いた土が舞い上がる。@
`　He tossed the bag he'd been burdened with towards the corner of the cage.`@` Along with a thud, the dried earth whirled up.`@`
br
;　その音に反応したのか、穴に隠れていたうさぎたちが顔を出した。\
`　Whether they'd reacted to the sound or not, the rabbits that had hidden in holes poked their faces out.`\

;　赤くて大きな目。@ぴんと立てた耳。@愛らしい仕草。@
`　Large, red eyes.`@` Ears that stood up straight.`@` Those adorable gestures.`@`
br
;　身体はあちこち土で汚れているが、そんなものは少し払ってやれば真っ白になる。\
`　Their bodies had been dirtied here and there, but if one wiped it away a little, they'd become snow white.`\

ld r,HIK_def1,22

;　ひかるは飼育委員だ。@
`　Hikaru was a member of the animal raising committee.`@`
br
;　２組の飼育委員はうさぎ小屋の世話が割り振られており、@毎日餌をあげなければならないし、週に２回は小屋の掃除もしなければならない。\
`　Class 2's committee had been assigned to taking care of the rabbits' cage. `@`They had to feed them each day, and twice a week they'd have to clean the cage.`\  

;　他の委員や係と比べてもかなり大変なため、みんなから敬遠されてきた役職だった。@
`　Compared to the other members and those involved, it was quite a difficult task, so it had been a position everyone distanced themselves from.`@`
br
;　今学期が始まった時、ひかるは他のクラスメートたちにこの役職を半ば強制的に押し付けられたのだ。\
`　From the start of this semester, Hikaru had been forced into this role by the rest of his classmates.`\
;　しかし、結果的には良かったと思っている。@
`　But, in the end he thought it was good.`@`
br
;　このうさぎたちに会えていなければ、ひかるの学校生活は本当にどん底だったのだから。\
`　Had he not met these rabbits, Hikaru's school life would truly have been the lowest of the low.`\

ld r,HIK_Def4,80

;「また駄目にされちゃったよ、……ノート。」@
`"It was ruined again, ...my notebook."`@`

br

;　うさぎに手を伸ばし、そっと触れる。@
`　She held her hand out to the rabbit, softly petting it.`@`
;　短くて柔らかい毛の感触が指に心地良い。\
`　The texture of its short, soft fur was pleasant to the touch.`\

ld r,HIK_Def3,80

;「そんな高いものじゃないけどさ、@こんなにしょっちゅう捨てられるんなら、もう授業のノートなんかとらないでやろうかなって思うよ。」\
`"It's not all that expensive, but,`@` if it's constantly getting thrown away, I wonder if it'd be better to just not take notes in class anymore."`\
;　そうだ。@ノートなんかとらなくたって、テストでいい点くらい取れる。@
`　That's right.`@` Even if he doesn't bring her notebook, he could still get a good score on his tests.`@`
br
;　ひかるは頭が良い。@クラスの誰よりも頭がいい。@
`　Hikaru was smart.`@` He was smarter than any in his class.`@`
;　クラスメートたちもそれを知っている。\
`　His classmates also knew this.`\

;　二瓶ひかるはおとなしくて頭が良い。@
`　Hikaru Nihei was quiet and smart.`@`
;　だから腹が立つ。@だから、虐められる。\
`　So that made them jealous.`@` So he was bullied.`\

ld r,HIK_Def2,80

;「……理不尽だろ、そんなの。」\
`"...Outrageous, isn't it?"`\
bg black,22
mono 1
bg kyou_03,22

;　ひかるの持ち物が捨てられはじめたのはいつからだったろう。@
`　How long had it been since Hikaru's posessions had started being thrown away?`@`
br
;　全教科で百点をとって先生に褒められてから？@　厚意からみんなにノートをまとめるコツを教えてあげてから？\
`　Was it because he receieved 100% in all of his classes and was praised by her teachers?`@` Was it because he kindly taught everyone his trick to taking notes?`\

;　何が原因だったのかは分からない。@もしくはそれら全部の積み重ねだったのか。@
`　He did not know what the cause was.`@` Or if it was an accumulation of everything.`@`
br
;　とにかくある日を境にひかるは「調子に乗ってる」と陰口を叩かれるようになり、@やがてそれは無視に変わり、持ち物がゴミ箱に投げ込まれるようになった……。\
`　In any case, one day it seemed that Hikaru had been badmouthed as being 'full of himself.'`@` and finally when he had moved on to ignoring it, it turned into having his personal items thrown into the garbage bin...`\
bg black,22
mono 0
bg usagi_02,22
ld c,HIK_Def2,22
ld c,HIK_Def3,80

;「………なんで僕が。」@
`"...Why me?"`@`

br
;　口の中だけでそう呟くと、ひかるは近くにいたうさぎに手を伸ばし、そっと抱きしめた。\
`　He muttered this to himself, and Hikaru reached out her hand to a nearby rabbit -- softly hugging it.`\

;　柔らかくて、温かい。@
`　It was soft, and warm.`@`

br
;　その体温をもっと感じたくて、抱きしめる腕に力を込める。@
`　He wanted to feel that body warmth more, so he put more strength into the arm that was holding it.`@`
;　……心を溶かすような温度が腕を通して伝わってくる。\
`　...The warmth transmitted through his arms was enough to melt his heart.`\

textoff

fede 0,1000
E_A

ld c,HIK_i1,80
quakey 1,200

;「…………なんで、僕がこんな目に…。」\
`"...Why, does this happen to me..."\

me1v 16,50

bg black,22

;　更に力を込める。@更に力を。@更に。@
`　He used even more strength.`@` And more strength.`@` And more.`@`
br
;　……グエッ、とうさぎの口から奇妙な音が漏れた。\
`　...Gwehh, a strange sound escaped the rabbit's mouth.`\

me2v 17,50

;　今やうさぎはひかるの腕の中で苦しそうに暴れている。@
`　By now, the rabbit in Hikaru's arms looked to be in agonizing pain as it struggled.`@`
br
;　だが、ひかるは離そうとしない。@
`　But, Hikaru did not make to let go.`@`
;　うさぎがもがく様子をじっと見つめ、更に力を入れて身体全体を締めあげる……。\
`　He stared at the rabbit's squirming state, putting more power from his entire body into strangling...`\

;　うさぎが首をブンブンとすごい勢いで振り、@ぴんと立った耳がひかるの顔にぺちぺちと当たった。@
`　The rabbit's neck droned and shook with great vigor,`@` and the ears that stood up straight hit Hikaru's face.`@`
br
;　ひかるはうさぎを睨みつける。\
`　Hikaru glared at the rabbit.`\

bg black,26
bg usagi_03,26

E_A
se1v 13,50

quakey 2,200

bgm1 6

;　そして、片手でうさぎを掴んだまま高々と持ち上げると、@隅で固まっていた他のうさぎたちの上に思い切り投げつけた。\
`　Then, raising the rabbit with one hand as high as she could, `@`he threw it towards the other rabbits that had huddled together in the corner.`\
;　投げられたうさぎはぐったりと仰向けになり、@他のうさぎたちはパニックになって小屋の中を駆け回った。\
`　The thrown rabbit went face up -- limp,`@` and the other rabbits became panicked and fled around the cage.`\
ld l,HIK_w1,6
ld l,HIK_w2,22

;「おいおい死んだ振りなんかするなよー。@このくらいもう慣れっこだろ？」\
`"Oh, come on, don't act like you're dead now.`@` You should be used to this much, right?"`\

;　大丈夫。@動物はこのくらいで死んだりはしない。@
`　It's okay.`@` Animals won't die with just that.`@`
;　なにしろ毎日やってるのだ。@どこまでなら大丈夫かちゃんと加減は心得てる…。\
`　He has been doing it every day.`@` He understood perfectly to what extent they're able to withstand.

se1v 10,50
quakex 2,200

;　つま先で倒れているうさぎを蹴りあげながら、ひかるは感謝する。@
`　As he kicked up the fallen rabbit with the tip of his shoe, Hikaru felt grateful.`@`
br
;　このうさぎたちがいてくれて本当に良かった。@飼育委員になって本当に良かった。@
`　Thank goodness these rabbits are here.`@` Thank goodness I became a member of the animal raising committee.`@`
;　こいつらとの遊ぶ時間がなかったら、いじめの日々に、自分はどうにかなっていたかもしれない。\
`　If you I didn't have the time to play with you guys, I don't know what would happen to me during these days of being bullied.`\

;　かろうじて起き上がったうさぎは、穴の中に隠れようとした。@
`　The rabbit who could barely even stand, went to go hide in a hole.`@`
br

quakex 2,200

;　だが、ひかるはその後ろ足を鷲のように掴み、無造作に引きずり戻す。\
`　However, like an eagle, Hikaru caught its back leg, and casually dragged it back.`\

quakex 1,100

;　遠ざけられたうさぎは、また這うようにして穴に向かうが、@穴に辿り着く直前で再び引きずり戻す。@それを何度も繰り返す。\
`　The rabbit mannaged to get away and tried to crawl back into the hole again, `@`but just as it was about to reach the hole, it was pulled back again.`@` This repeated many times.`\ 

bg black,23
bg usagi_02,23
ld c,HIK_Def2,22


;「……あいつら、手は出さないんだ。」@
`"...Those guys, just don't hit me."`@`
br
;　後ろ足をひねるようにして引きずりながら、ひかるは無表情のままで呟く…。\
`　Twisting its back leg back and pulling it towards him again, Hikaru murmured with his expressionless face...`\

ld c,HIK_w2a,80

;「教材は捨てるし、靴は隠すし、体操着は破くし。@掃除当番も班の仕事も全部僕に押し付ける。@……そういうことするのは全然平気なくせに、絶対に殴ったり蹴ったりはしてこないんだ。」\
`"They throw away my school supplies, hide my shoes, tear up my gym uniform.`@` They force me to do all of the work during classroom cleaning duty.`@` ...I'm totally fine with that, but they still haven't punched me or kicked me."`\

;　殴らない。@蹴らない。@身体に痕を残さない。@ひかるはそれを心底軽蔑する。@
`　They don't hit him.`@` They don't kick him.`@` They don't leave any marks.`@` Hikaru hated this from the bottom of his heart.`@`
br
;　もし、ひかるが自殺をしたらきっと彼らはこう言うだろう。\
`　If Hikaru were to commit suicide, surely they all would say this.`\

;　自分たちはイジメなんかしてません。@あいつに手を出したことなんて一度もありません。@一度も。@……一度も……。\
`　Well, we didn't bully him or anything!`@` We've never once laid a finger on him.`@` Not once...`@`...not even once...`\
cl c,0
ld r,HIK_i1,23
se1v 10,50
quakex 2,200

;「……ふざけるなよ。」@
`"...Don't fuck with me."`@`
br
;　彼らには、本当にひかるを虐めているという実感がないのかもしれない。@
`　To them, they might not have really felt they were bullying Hikaru.`@
;　だとしたら許せなかった。\
`　If that was the case, he couldn't forgive them.`\

bg black,22
;bg aka3,28

;　殴ってみろよ。@蹴り飛ばしてみろよ。@
`　Try hitting me!`@` Try kicking me in the air!`@
br
;　なぁ、知っているか？@　何度も持ち物がなくなるあの絶望感を。@親に靴をなくした言い訳をする時の情けなさを。\
`　Heeyy, do you know?`@` Do you know that feeling of having your things gone over and over?`@` That feeling of making excuses to your parents when your shoes disappear?`\

;　あれが暴力じゃないなんて絶対に言わせない。@
`　Since it's not physical violence I can't tell anyone anything.`@
br
;　目に見える傷をつけなきゃ実感できないと言うなら殴ればいい。@歯を折ればいい。@顎を割ればいい。@どれだけ自分が傷ついてるか彼らに分からせるためなら、進んで袋叩きにされたかった。\
`　Because they'll say it didn't happen if I don't have a scratch on me, they should hit me. `@`Knock out my teeth. `@`Break my jaw. `@`I want them to beat me up until I can make someone recognize how much they've hurt me.`\

bg usagi_01,23

se1v 11,50

quakex 2,200

;「殴ってみろってんだッ！！」@
`"I said hit me dammit!!"`@
br
;　吐き捨てるように言って、掴んでいたうさぎを金網に投げつける。@ガシャンと派手な音がするが、彼の心を慰めはしない。\
`　He spat out, and threw the rabbit he held against the wire screen. `@`Although the loud crashing sound did not divert his thoughts.`\ 

;　ひかるは実感している。@
`　Hikaru understood.`@
br
;　自分はこのうさぎたちを虐めている。@抵抗できない、鳴くことすらできない小さな動物を毎日毎日虐待している。\
`　He was bullying these rabbits. `@`He was abusing tiny animals -- that couldn't fight back -- that could only cry each and every day.`\

;　ひどいことをしている。@それをよく分かってる。@
`　He was doing something cruel. `@`He knew that well.`@
;　でも、そのひどいことが堪らなく心地良い。@それをきちんと認め、実感しているのだ。@
`　But, those cruel things felt irresistably soothing.`@` He readily accepted and felt it.`@
br
;　ひかるはもう一度掴み上げようとうさぎに手を伸ばす。\
`　Once again Hikaru put out his hand to take up another rabbit.`\















bg black,1
E_A

;「……こんにちは。」\
`"...Hello."`\

lsp bgsp2,":a;bmp\background\efe\a003.bmp",0,0
print 0
bg usagi_02,1

quakey 2,200

me1v 16,50

;「…………ッ！！」@
`"...!!"`@
br
;　唐突に声を掛けられ、ひかるはビクッと振り返る。\
`　Having suddenly heard a voice, Hikaru looks back with a jump.`\

mld r,MAR_Def1,42

;　見ると、うさぎ小屋の金網の向こうに、小柄な眼鏡姿の少女が立っていた。\
`　When he looked, on the other side of the rabbit pen wire stood a small girl wearing glasses.`\

;　……見られた？@　うさぎたちと戯れる、至福の時間を……？@
`　...Did she see me?`@` My amusements with the rabbits, my moment of bliss...?`@`
;　というか、誰だこいつ、とっとと消えろ……。@
`　Speaking of -- who is this girl? Hurry up and disappear...`@
br
;　そんな感情がそのままひかるの目に浮かんだのだろう。@少女は萎縮してしまう。\
`　Perhaps those emotions welled up into Hikaru's eyes. `@`The girl shriveled.`\

mld r,MAR_def4a,80

;「ご、……ごめんなさい。@いきなり声を掛けて、……驚かせちゃったね。」@
`"I- ...I'm sorry.`@` For suddenly speaking like that ...and scaring you."`\
br
;　そう言って、取り繕うように笑う。\
`　Saying that, she smiled as if to smooth things over.`\

;　いつの間にそこにいたのだろう。@
`　When did she get here?`@
br
;　ひかるはこの小屋でうさぎたちと“遊ぶ”時は、常に誰かがやって来ないか警戒している。\
`　When Hikaru was "playing" with the rabbits in the pen, he was always cautious of whether or not someone was coming.`\

;　うさぎ小屋の中からは、校舎の昇降口も校庭も全て見渡せる。@誰かがうさぎ小屋に近付いてきたら、すぐに気付くはずだ。@
`　The inside of the rabbit pens looks over the school entrance, courtyard, everything. `@`If someone were to near the rabbit pens, he would quickly notice.`@
;　だが、少女の接近には今の今まで気がつかなかった。@
`　However, he hadn't noticed her approach until this very second.`@
br
;　ひかるは立ち上がり、少女の視線からうさぎたちを隠すように間に入った。\
`　Hikaru stood, as if to hide the rabbits from her gaze.`\


ld l,HIK_Def4a,26
;ld l,HIK_Def3,80

;「……何か用？」@
`"...Need something?"`@
br
;　無表情を崩さずにぶっきらぼうに答えたが、内心はかなりドキドキしていた。@
`　He kept his expressionless demenour from dissolving with his question, but his heart was beating fairly rapidly.`@

;　うさぎとの戯れを、見られたかもしれない。\
`　She might have seen him -- having fun with the rabbits.`\

ld l,HIK_Def1,80

;　……ひかるは改めて少女を観察してみる。@
`　...Hikaru tried looking over the girl again.`@
br
;　地味で目立たない顔つき。@同じクラスにいても名前を忘れられてしまいそうな、@ぼんやりとした雰囲気の女の子。\
`　Simple, inconspicuous facial features.`@`Despite being in the same class she seemed like a girl whose name would be forgotten -- `@`a girl with an air of absentmindedness about her.`\

;　彼女と会うのもこれが初めてなのかどうかさえ自信がない。@
`　He didn't even have any confidence that this was the first time he had met her or not.`@
br
;　たとえ以前会話したことがあったとしても、おそらく自分は覚えてないだろう。@そのくらい少女の存在感は希薄だった。\
`　Supposing they had spoken before, he probably wouldn't remember.`@` That's how thin her presence felt.`\

mld r,MAR_w1,80

;「このうさぎ小屋に人がいるなんて、珍しいですね。@……ここにうさぎ小屋があるって、知らない人も多いみたいだし……。」\
`"It's rare for someone to come to these rabbit pens.`@` ...It seems a lot of people don't even know there are rabbit pens here either..."`\

;　動物好きの少女が、たまたまうさぎ小屋に人影を見つけて近寄ってきただけのように見えた。@
`　She seemed like a girl who discovered someone's shadow by the rabbit pens and decided to approach them.`@
br
;　それを察し、ひかるはとりあえずホッと息をつく。@先ほどの自分の行為を見られていた訳ではないようだ。\
`　Guessing as much for now, Hikaru took a breath. `@`It didn't seem as if she saw how he was behaving moments ago.`\

csp -1
print 0
mcl r,0
bg black,24
bg usagi_01,24

;　その安堵を、気を許してくれたようにでも勘違いしたのか。@少女は愛想笑いを浮かべながら、小屋の中に入ってくる…。@
`　That relief might have just been a wrong guess that left him with his guard down `@`Forcing a smile to her face, the girl comes into the pen...`@
br
;　……どこの誰だか知らないけれど、自分だけの聖域に土足で踏み入ってくることが、許せない。\
`　...He didn't know who she was but, stepping foot inside his sanctuary was something he couldn't allow.`\

;　それに、下手をしたら、明日からもひょこひょことここへ通い出すのではないだろうか…？\
`　Furthermore, if I goof up, she'll probably timidly come this way tomorrow too...?`\

bg black,22

;　………ふざけるな。@
`　...Don't fuck with me.`@
br
;　ここは僕だけの聖域なんだ。@お前みたいな、見るからにうさぎ以外に友達がいなさそうなヤツが、のこのこ来ていいところじゃないんだ。\
`　This sanctuary is mine alone. `@`This isn't a place for someone like you, who from the looks of it has no one else but rabbits for friends, to just nonchalantly come in.`\

;　そんなひかるの胸中になど、少女が気付けるわけもない。@
`　There was no way for the girl to tell those were Hikaru's feelings.`@
br
;　しゃがみ込み、ひとり、ほくほくとうさぎを撫でている。\
`　Squatting down, she began petting one of the rabbits happily.`\

;「怯えないで。@……くす、本当に可愛い。」@
`"Don't be afraid.`@` ...*giggle*, you're really cute."`@
br
;　好きなだけ撫でたらいい。@ただし、もう二度とここに来るな……。@
`　It's fine if you pet them as you like. `@`But, don't come here again...`@
;　そう念を送ったところで、届くわけもない。@
`　He had just sent those feelings, but there was no way they would reach.`@
br
;　ひかるは小さな苛立ちを覚えながら、少女の背中を食い入るように睨む…。\
`　As Hikaru began to feel his stomach churn a bit, he glared at her back as if he were about to bite into it...`\

bg black,23
bg usagi_02,0
ld l,MAR_w2,23
ld l,MAR_Def4a,80

E_A

;「……あれ。@この子、怪我をしてるの…？」\
`"...Huh. `@`Is this one hurt...?"`\

se1v 20,50

ld r,HIK_i2,26

cl l,23

se2v 13,50
quakex 2,200


;「そのうさぎに触るなッ！！！」@
`"Don't touch that rabbit!!!"`@

bgm1 7

br
;　少女が、うさぎの怪我に気付いた瞬間。@ひかるは少女の後ろ襟を掴み、引きずり倒した。\
`　The moment the girl noticed the rabbit was injured, `@`Hikaru grabbed the back of her collar and pulled her down.`\

;　突然の乱暴に怯える少女の顔が、@……いつもうさぎたちが見せる表情に似ていて、一層、彼の感情を弾けさせた。\
`　With the sudden violence, `@`...the face of the scared girl matched the expression of the rabbits, adding to his explosion of emotion.`\ 

cl r,0
ld c,HIK_i2,24

;「出て行けッ！！@　ここは２組の飼育委員以外、立入禁止だッ！！@　二度と来るなッ、出て行けッ！！」\
`"Get out!! `@`No one is allowed in her aside from Class 2's animal raising committee!! `@`Don't come back again! Get out!!"`\

ld l,MAR_n2,26
ld l,MAR_n1,80

;「……え、……え………っ。」\
`"...Eh ...Eh..."`\

;　少女は目を白黒させて怯える。@
`　The girl's eyes darted about in fear.`@
;　自分がどんな過ちを犯したのか、理解できないとでも言う風な顔だ。\
`　Did she make some kind of mistake? Her face seemed to ask as she couldn't understand.`\

;ld r,HIK_Def1,80

bg black,22

;　何も犯してないさ、別に何もッ。@
`　You didn't do anything wrong, not a thing..`@
br
;　許してやるから出て失せろッ、二度と僕の聖域に近付くなッ！！\
`　I'll forgive you, so leave -- and don't come near my sanctuary again!!`\

;ld l,MAR_Def3n,80

;「ご、……ごめんなさい……、ごめんなさい……。@私……、何かした……？@　何か悪いことをしたなら謝るから……、ごめんなさい……！」@
`"I- ...I'm sorry... I'm sorry... `@`Did... did I do something..? `@`If I did something wrong, I apologize... I'm sorry...!"`@
br
;　少女が見せる、おろおろとした怯えた瞳。@僕の手から逃れようと呻く、うさぎたちのそれと重なって……、@無性に腹立たしくなる。\
`　The girl shows me -- her nervous, frightened pupils. `@`She moans to escape my hand, and with that she seemed like one of the rabbits, ...`@` She became extremely annoying.`\

cl a,0
bg usagi_03,0
ld c,HIK_i2,22

me1v 17,70

;「何なんだよ、お前ッ！@　こんなところに一人で来て！！@　友達いないのかよ？！@　どうせクラスでいじめられててひとりぼっちなんだろッ！！」@
`"What the hell is it with you! `@`Coming to a place like this by yourself!! `@`Do you have no friends?! `@`You're probably some loner who gets bullied in class!!"`@
br
;　感情のままに怒鳴りながら、何て自虐的な言葉だろうと耳も痛くなる。\
`　As he shouted full of emotion, his self-wounding words hurt even his ears.`\

ld r,MAR_n1,22

;　しかし、その少女にその言葉は、あまりに的を射ていたらしい。@
`　However, to the girl those words cut right to the point.`@
br
;　表情が悲しみと驚愕でぐにゃりと歪む。@
`　Her expression limply twisted from shock to sorrow.`@
;　……どうして自分がひたすらに隠していた、いじめられっこだという秘密が見破られたのか。@自問しているに違いない。\
`　...'How did he know the secret that I've been hiding about being bullied?' `@`She had to have been asking herself.`\

;　生憎だな。@僕にはよくわかるんだよ。@そしてこの感情は同族嫌悪だ。@あぁ、その歪めた表情、……いらいらするッ！！\
`　It's unfortunate. `@`I understand it well. `@`So we both hate this feeling. `@`Aahh, that twisted expression... it pissed me off!!`\

;bg black,26
bg usagi_01,26
se1v 11,50
quakey 2,200

;「さっさと出て行けッ、このブス！！@　人間に相手にされないからって、動物なら相手にしてもらえると思ったか？！@　お前の浅ましい考えなんて見え見えなんだよ！！」\
`"Hurry up and get out of here, ugly!! `@`Knowing that humans can't be your companions, you thought animals could be your companions instead?! `@`Your miserable thoughts are all too obvious!!"`\ 

ld r,HIK_i2,26

;「わかってんだよッ、いじめられっこなんだろ？！@　悔しいんだろ？@　でも何も出来ないんだろ？！@　だから動物なら相手にしてもらえるって思ったんだろ？！@　お前みたいなヤツ、うさぎも誰も相手になんかするもんかッ！！@　出て失せろッ、二度とここには近寄るな！！@　…………このッ！！」\
`"I know it, you're a bullied kid right?! `@`Frustrating isn't it? `@`But you can't do anything about it can you?! `@`So you think you could make friends with animals? `@`As if rabbits, or anyone, would be friends with some bitch like you~!! `@`Fuck off, and don't come back!! `@`......You!!"`\

bg black,22

;bg usagi_03,24
;ld r,HIK_i1,24
;quakex 1,100

;　足元の土くれを拾い上げ、乱暴に投げつける。@
`　He takes up a dirt rock and throws it violently.`@
br

;ld r,HIK_Def4a,80

bg usagi_03,22

E_A

;　…………………………………。@
`　............`@
me1v 17,50
;　…………え……？\
`　...Huh...?`\

;　そこには、誰もいなかった。@
`　There was no one there.`@
br
;　少女から目を離したのは、足元の土くれを拾うために屈んだ一瞬だけだ。@
`　When he was grabbing the clump of dirt from the ground, he had only taken his eyes off her for an instant.`@
;　なのに、……その一瞬を境に、少女の姿は消えていた。\
`　Even so... from the edge of that single instant, the girl had disappeared.`\

;cl r,24
ld c,HIK_Def4a,2

;　辺りを見渡すが、どこにも姿がない。@隠れる場所などあるわけもない。@
`　He looked around, but she wasn't anywhere to be seen. `@`There was no where she could have hid either.`@
br
;　……文字通り、……霞のように、少女は消え去ってしまった……。\
`　...Literally, ...she had vanished like mist...`\

bg black,22
bg usagi_01,22

;　何だよ、これ……。@
`　What is this...`@
br
;　……まるで、……幽霊……。@…………まさか、妖怪……？\
`　...Almost like... a ghost... `@`...It couldn't be... a youkai...?`\

;　どこの学校だってそうだろうけど、この学校にも七不思議、……いや、最近、八不思議になったらしいが、@……というものがある。@
`　It's like that for every school, but this school also has its Seven Mysteries... no, lately it seems it has become Eight Mysteries, `@`...or so they say.`@
br
;　その中の怪談には、ひとりで遊んでいる生徒に話し掛けて、神隠しにしてしまう…、@みたいなのが混じっていたりしなかったっけ……。\
`(?)　Among those stories, a student playing by himself started talking to one, and was demoned away... `@`Wasn't there a story like that mixed up in there...?`\

;　目の前にいたはずの少女が、瞬時に消える。@
`　The girl who should have been in front of me, disappeared in an instant.`@
br
;　ただそれだけのことなのに、……ひかるの背中は、冷たい汗でびっしょりだった。\
`　Although that was all it was, ...Hikaru's back was drenched in cold sweat.`\

ld l,HIK_w2a,22

;「まさかな。@……はっ。@いるわけないよな、妖怪なんて。」@
`"No way. `@`...Heh. `@`Youkai don't exist"`@
br
;　ひかるは土くれで汚れた手を払う。@
`　Hikaru wipes the dirty hand that held the clump of dirt.`@
;　何だか興醒めしてしまった。@今日は帰ろう。@そう思い、入口の扉に手を掛ける。@
`　Well that ruined the fun. `@`I'll go back today. `@`So he thought, and put his hand on the entry gate.`@
br
;　……その時だった。\
`　...That was the moment.`\










bg black,22

E_A

;「そんな寂しいこと言わないでよ。」@
`"Don't say such lonesome things!"`@
br
;　背後からいきなり声を掛けられ、ひかるは思わず「ひっ」と悲鳴をあげた。\
`　Hearing a voice suddenly behind him, without thinking, Hikaru let loose a scream, "Hii~!"`\

bg black,24
bg usagi_02,24

;　振り返ると……。@……そこには、おかしな服を着た、長身の青年が立っていた。\
`　Turning around... `@`...there was a strangely dressed tall man standing there.`\

bgm1 9

ld r,HAM_Def1,2
ld r,HAM_Def2,80

;「“いるわけないよな、妖怪なんて”。@……そんなの妖怪が聞いたら、きっと傷つくよ。@存在を否定される辛さは、君もよく知ってるだろう……？」\
`"'Youkai don't exist'. `@`...If a youkai heard something like that, it would definitely hurt. `@`You're well aquainted with the pain of having your existence denied, aren't you...?"`\

;　今度は、一瞬の間に、自分の背後に人がいたのだ。@……もう驚愕を超えて、呆然とするしかない。\
`　This time, in an instant, someone was behind me. `@`...I was beyond frightened -- I was dumbfounded.`\

;　その青年は、くっきりとした端正な顔で、肌は透けるように白い。@最近女子たちが騒いでいるアイドルにどことなく似ているかもしれない。@
`　The young man had a distinctly handsome face, and his skin seemed transparently white. `@`He might resemble one of those idols girls are making a fuss over these days.`@
br
;　その容姿は、この汚いうさぎ小屋には余りにも不釣り合いで、@ひかるは現実の風景の中に、急にフィクションの映像が差し込まれたかのように感じた……。\
`　His appearance greatly crashed with this dirty rabbit cage. `@`Hikaru felt that he was transported suddenly from a scene of everyday life into a fictional movie...`\

ld r,HAM_Def1,80

;「何だ。@そういう驚いた顔もできるんじゃないか。@いつもの能面みたいな顔よりずっと素敵だよ。@二瓶ひかるくん。」\
`"What. `@`So you can make that kind of surprised face too?` @`It's much better than your usual Noh mask-like face. `@`Hikaru Nihei-kun."`\

ld l,HIK_Def4a,22
;ld l,HIK_Def1,80

;「ど、……どうして、僕の名前を？」@
`"H- ...How do you know my name?"`@

ld r,HAM_Def2,80

;「ここしばらく、君には注目させてもらってたんだ。@気付かなかった？」@
`"I've taken to watching you here for some time. `@`You didn't notice me?"`@
br
;　ひかるは真っ青になる。@
`　Hikaru flushed bright red.`@
;　それは、ひかるが今までうさぎたちにしてきたことを知っているということだろうか……。\
`　That probably meant that he knew what Hikaru had done to those rabbits...`\

bg black,22
bg usagi_03,22

;ld r,HAM_Def3,80

me1v 16,5

;「もちろん、知ってるよ。@君がこの子たちとどんな風に遊んでたのかもね。」@
`"Of course I know. `@`That is how you play with these little ones."`@
br
;　青年は口元に悪戯っぽい笑みを浮かべて言った。\
`　The young man spoke and then his mouth changed into an impish smile.`\

me2v 17,50

;　み、見られていた……。@
`　I, I was seen...`@`
;　誰にも知られないよう警戒してきたつもりだったのに……！@
`　Even though I had planned cautiously to not be found out...!`@`
br
;　彼はどうする気なのだろうか？@　先生に言いつける？@　親に知らせる？@　それともまさか、警察に………、\
`　What in the world did intend to do?`@` To talk to the teachers?`@` To tell my parents?`@` Or maybe even, to the police...`\

ld l,HAM_Def2,22

;「ははは、安心していいよ。@そんなことしないから。」@
`"Hahaha, don't worry.`@` I wouldn't do something like that."`@`
br
;　青年は屈託なく笑った。@
`　The youth laughed without a care.`@`
br
;　……本当に？@　本当に誰にも言わない？\
`　...Really?`@` He really won't tell anyone?`\
ld l,HAM_Def1,80

;「うん、約束する。」@
`"Yes, I promise."`@`
br
;　果たしてこの言葉を信用していいのだろうか……。@…………あれ？\
`　Is it really, honestly okay to have faith in these words...`@` ...Hmm?`\

mbg black,22

;ld l,HIK_Def1,80

;　ひかるは不意に違和感を感じ、自分の口を押さえる。@
`　Hikaru suddenly felt uncomfortable, and held his tongue.`@`
br
;　僕は今、無意識に自分の考えを声に出していただろうか？\
`　Did I just, unconciously say what I was thinking?`\

;　……いや、そんなことはない。@
`　...No, I didn't.`@`
;　なのに、彼は僕の心の中の言葉に対し、返事をしている……。@
`　Yet, he is replying to the words in my mind...`@`
br
;　ひかるの口は干上がったかのようにカラカラに乾いている。\
`　Hikaru's mouth became dry as though he were parched.`\

cl l,0
mcbg 22
;bg usagi_03,22

;　……では、これはどういうことなのだろうか？@
`　...but, then what does that make this?`@`
;　この人が僕の心を読んだとでも……そんな馬鹿な。@それじゃあまるで本物の……、\
`　This person read my thoughts, but...that's ridiculous.`@` If that were the case, he'd have to be a real...`\

ld l,HAM_Def1,22
;ld l,HAM_Def4,80

fede 10,1000
E_MA
ld l,HAM_Def2,80

「……妖怪じゃないか？」@
`"...Youkai?"`@`
br
;　青年がまるで先回りでもするようにひかるの考えを口にする。\
`　The young man, as though anticipating it, spoke what Hikaru was thinking.`\

ld l,HAM_Def3,80

;「ひかる君は頭が良いんだね。@正解を出すのが早い。」@
`"Hikaru-kun, you're rather smart, aren't you?`@` You're quick to get the right answer."`@`
ld r,HIK_Def4a,24

;「…………じゃ、じゃあ………。」\
`"...Th, then..."`\

;　ひかるは早々に観念する。@
`　Hikaru quickly formed a notion.`@`
br
;　出会ってから本当にわずかな時間しか経っていないにも関わらず、@目の前に立っているこの青年が、ただの人間でないということを受け入れる。\
`　In spite of the fact that only a miniscule amount of time had passed since they'd met,`@` he was able to accept that the young man standing in front of him, was not any ordinary human.`\
;　何者かは分からないが、彼は自分とは違う、何か特別な存在なのだと。@ひかるは全身の感覚でそれを感じ取った。@
`　I don't know what he is, just that he is different from me, some sort of special existence.`@` Hikaru sensed this feeling through his entire body.`@`
br
;　そうだ。@……そもそも彼は、ひかるがうさぎ小屋から出ようとした瞬間、@そのすぐ背後、うさぎ小屋の中にいきなり現れたのだ。\
`　That's right.`@`...In the first place, the moment Hikaru went to leave,`@` he suddenly appeared immediately behind Hikaru inside the rabbit cage.`\
;　普通の人間には、そんなこと絶対に不可能だ。@金網をすり抜けることが出来ない限りは。\
`　As long as one could not slip through the wire mesh. `@`For a normal human, that sort of thing is absolutely impossible.`\
;(Edit) Statements inverted for sensibility.
 
ld l,HAM_Def1,80

;「理解が早くて助かるよ。@最近は、僕らみたいな存在を頭から否定してて、@どんなに証明しても受け入れてくれない子供が多いんだ。」\
`"It helps that you understood so quickly.`@` These days, there are plenty of children out there who start out denying us --`@` and won't accept any proof we give them."`\

ld r,HIK_Def4,80

;「あなたは……その、妖怪なんですか……？」@
`"You're...er, a youkai, right...?"`@~

br
;　上擦った声で尋ねると、青年はニッコリ笑って言った。\
`　He asked in a nervous voice, which made the young man grin broadly as he replied.`\

ld l,HAM_Def2,80

;「ハメルン。@それが僕の名前。@……みんなには“音楽室のハメルン”って呼ばれたいね。」@
`"Hameln.`@` That is my name.`@`...Everyone wants to call me 'Hameln of the Music Room,' though."`@`

ld r,HIK_Def2,80

;「……音楽室？」\
`"...The music room?"`\

;ld l,HAM_Def3,80

bg black,22
bg gakkou_03,22

;「ほら、あそこ。@……このうさぎ小屋の向かいの教室だよ。@僕はいつもあそこにいてね。@あの窓から毎日ここに通う君をこっそり覗いてたってわけさ。」@
`"See, over there.`@`...It's the classroom facing the rabbits' cage.`@` I am always over there.`@` The truth is, from that window, I have secretly spied you come here every day."`@`
br
;　そう言うと、ハメルンと名乗った青年は、自分の手をひかるの目の前に差し出した。\
`　Saying this, the young man called Hameln, presented his hand in front of Hikaru's eyes.`\
bg black,22
;bg usagi_01,26

me1v 16,50

;　その手には何かが握られている。@ハメルンは勿体ぶるようにゆっくりとその指を広げる……。@
`　That hand was grasping something.`@` Hameln seemed to put an air of importance as he slowly spread his fingers...`@`
br
;　……それは、何……？@
`　...What is that...?`@`
;　次第に見えてきたそれは……、カスタネットだった。\
`　The next thing he could see were..., castanets.`\

ld r,HAM_Def1,22

;「……『ハメルンのカスタネット』っていう怪談を聞いたことある？」@
`"...Have you heard the ghost story called, 'The Castanets of Hameln?`"`@`
;「いえ、僕はそういうのはあんまり詳しくないです……。@……でも多分、学校の八不思議の中に入ってるんじゃないかと……。」\
`"No, I'm not all that well-versed in that sort of thing...`@`...But perhaps, it might be one of the school's Eight Mysteries..."`\

;bg black,24
bg usagi_02,0
ld r,HAM_Def1,22
ld r,HAM_Def2,80

;「あぁ、僕のは八不思議にはまだ入ってないんだよ。@この学校に来てから、まだ日が浅いからね。@……う～ん、そうか残念。@まだまだ怪談も僕も無名みたいだ。」\
`"Ah, mine is not one of the Eight Mysteries yet.`@` After all, it hasn't been very long since I came to this school.`@`...Yes, it is unfortunate.`@` It seems I am still but a nameless ghost story."`\

ld l,HIK_Def2,23

;「……ハメルンのカスタネット…。@……聞いたことないです、そんな怪談。」@
`"...The Castanets of Hameln...`@` ...I haven't heard of that ghost story."`@` 
ld r,HAM_Def1,80

;「僕のはね、こんな話なんだ……。」\
;"My story, goes like this..."`\

bg black,22

fede 1,1000
E_B

bg rouka_01,2

wait 2000

bg black,22
bg ongaku_01,2

;　……夜、音楽室にいると、カチ、カチ、カチというカスタネットの音が聞こえてくる。@
`　...At night, if you are in the music room, you can hear the sound of castanets go *click*, *click*, *click*.`@`
br
;　しかし、辺りを見回しても誰もいない……。\
`　But if you look around you, there is nobody there...`\

;　カチ、カチ、カチ……。@
`　*Click*, *click*, *click*...`@`
br
;　音は段々大きくなってくる。\
`　The sound gradually becomes louder.`\

me2v 28,70

;bg black,22
bg ongaku_03,2

;　……そこで気付くんだ。@自分の姿がいつの間にか小さなねずみに変わっていることに……。@
`　...And that's when you notice.`@` Your form has become that of a small rat while you were unaware...`@`
br
;　カチ、カチ、カチ、というその音は、ねずみになった自分が歯を打ち鳴らしている音なんだって。\
`　They say that click, click, clicking sound, was really the sound of your mousey teeth clicking together.`\
ld c,HAM_Def1,22

;　……すると、いつの間にか音楽室の中に、カスタネットを持った男が立っている。@
`　...And then, before you know it a man is standing in the music room holding castanets.`@`
;　彼は自分を“ハメルン”と名乗る。\
`　He calls himself, "Hameln."`\

;　そして、ねずみに姿を変えられた子供達は、@ハメルンの鳴らすカスタネットの音に導かれ、闇の中へと消えていくらしい……。\
`　Then, the children who turned into rats, `@` seem to disappear into the darkness, guided by the sound of Hameln's beating castanets...`\

bg black,2

fede 0,1000
E_A

bg usagi_02,0
ld c,HAM_Def1,22
ld c,HAM_Def2,80

bgm1 14

;「と、こんな怪談なのさ。@ぜひ君にも広めて欲しいね。」@
`"And, that's the kind of story it is.`@` I would love it if you also would spread it around."`@`

br
;　……初めて聞く話だった。@噂好きのクラスメートたちが話しているのも聞いたことがない。\
`　...That's the first time I've heard it.`@` I haven't even heard it from my rumor-loving classmates when they talk.`\
;bg black,23
;bg usagi_03,0
;ld l,HAM_Def2,23

cl c,0

ld l,HAM_Def1,24

;「だから言ったろ？@　まだ日が浅いって。@だけどそのうち、みんな嫌でもこの怪談を噂するようになるよ。@この学校の名物になるくらいね。」\
`"Well, I told you, didn't I?`@` I haven't been here long.`@` But in that time, even if they don't like it, everyone is gossiping about it.`@` It has gotten to the point of becoming this school's local speciality."`\
ld r,HIK_Def4,22
;ld r,HIK_Def4,80

;「その……。@それで、そのハメルンさんが僕に何の用ですか……？」@
`"Er...`@` Then, is there something you want from me, Hameln-san...?"`@`
br

;　犠牲者をねずみに姿を変えてしまうという物騒な妖怪が、……自分に何の用があるというのか。@
`　What could a dangerous Youkai who turns his victims into rats... want with me?`@`
;　まさか、自分をねずみにするつもりじゃ………。\
`　He couldn't be, planning on turning me into a rat...`\

ld l,HAM_Def2,80

;「フフフ、そんなに身構えなくてもいいよ。@僕は君を助けてあげに来たんだから。」@
`"Hu, hu, hu, you don't need to be so on guard.`@` After all, I came here to help you."`@`

ld r,HIK_Def4a,80

;「助ける？@　……僕を？」\
`"Help?`@`...Help me?"`\

ld l,HAM_Def3,80

;「そう。@……ひかる君さ。@いつまで、こうやってうさぎたちに八つ当たり続けるつもり？」@
`"Yes.`@`...Hikaru-kun.`@` How long do you plan on letting out your anger on rabbits like this?"`@`

ld r,HIK_i1,80

;「…………っ。」\
`"....!"`\

bg black,24
bg usagi_02,24
;ld r,HAM_Def1,24

me1v 5,50

;　ハメルンは、金網の隅に怯えるように群がっているうさぎたちを見ながら笑う。\
`　Hameln smiled as he looked at the frightened rabbits, all huddled in the corner of the wire mesh.`\
ld r,HAM_Def1,22

;「これって動物虐待って言うんだろ？@　随分と残酷なことするよね。@罪もないうさぎたちを、いじめるなんて。」@
`"This is called animal abuse, right?`@` It is a particularly cruel sort of thing.`@` To torture these innocent rabbits.`@`
br
;　それを言われると、……何も言い返せない。\
`　Being told that, ...I am unable to retort.`\

;　僕という弱者をいじめることが社会の摂理ならば。@……うさぎという弱者を僕がいじめることだって、同じ摂理のはずなのだ。@
`　If a weak person like me is persecuted as allotted by society,`@`... then a weak creature like a rabbit should have the same courtesy.`@`
br
;　……僕がいじめられるように、より弱者のうさぎたちだって、いじめられる義務がある。@そして僕には権利がある。@……そう思っていた。\
`　...These rabbits that are weaker than I am bear the duty of being tormented the same way I am.`@` And I have that right.`@`...That's what I thought.`\

;　しかし、それはあくまで僕の中だけで成立するルールだ。@
`　But in the end, that was just a rule established only by me.`@`

br
;　うさぎたちには、何の罪もない。@
`　These rabbits are innocent.`@`
;　僕にいじめられる、どんな理由も存在しない……。\
`　There is no reason why they should be tormented by me...`\

ld r,HAM_Def2,80

;「うさぎたちに責任があるならばともかく。@……何の罪もないのに虐めるなんて。@それはおかしいことじゃないかい？」@
`"Regardless of whether these rabbits have any responsibility,`@`...torturing something that is innocent,`@` isn't that just ridiculous?"`@`
ld l,HIK_Def4a,23

;「…………………………。」\
"......."`\

bg black,22
mono 2
bg Different_spiral_1a,22

me2v 17,50

;　そうさ。@僕がいじめられっこだからといって、@……より弱いモノをいじめる理由になどなりはしない。@
`　That's right.`@`Saying it was all because I was abused,`@` ...was no excuse for abusing these weak creatures.`@`

br
;　多分、心のどこかで理解はしていた。@
`　I think, somewhere in my heart I realized that.`@`
br
;　でも、……じゃあ、僕の悲しみや怒りは、どこへ吐き出せばいいんだよ…？！\
`　But, ...then, where am I supposed to let out all of my sadness and anger...?!`\

;bg Different_spiral_1b,22

;　最近は色々と物騒だ。@動物虐待なんかでも、新聞や警察は大騒ぎする。@
`　These days its been all kinds of dangerous.`@` Things like animal abuse would cause a huge stir with the newspaper and the police.`@`
br
;　……僕という人間をいじめても、誰も咎めないのに、@……僕がうさぎをいじめると、……裁かれるというのか………。@
`　...Even if this human I call myself is being tortured, even though I cannot blame anyone,`@` ...I tortured rabbits, ...and I am being judged for it...`@`
br
;　この男は、……うさぎをいじめた僕を咎め、……裁こうというのか……。\
`　Will this man ...charge me for abusing rabbits, ...and sentence me...?`\
bg black,22
mono 0

fede 0,1000
E_A

bg usagi_03,0
ld l,HAM_Def1,22
ld l,HAM_Def2,1
quakey 1,100

;「あははははははははははは！」@
`"Ahahahahahaha!"`@`

bgm1 7

br
;　突然ハメルンが愉快そうに笑いだした。\
`　Suddenly, Hameln let out a pleasant laugh.`\

ld l,HAM_Def3,80

;「ひかる君、人の話聞かないなぁ。@言っただろ？@　僕は君を助けてあげに来たんだって。@何だよ裁くって。@あははははは！」@
`"Hikaru-kun, you don't listen to what people are saying, do you?`@` Remember?`@` I said I came here to help you.`@` What's all this about being judged?`@` Ahahahahaha!"`@`

ld r,HIK_Def4a,22

;「………………。」\
"......."`\

ld l,HAM_Def2,80

;「もしかして君、僕のことを小動物を愛する心やさしい妖怪…、とでも思ってる？」@
`"Could it be that you think I am a kind-hearted youkai...who loves small animals?"`@`

ld r,HIK_Def2,80

;「……違うんですか。」\
`"...Is that wrong?"`\

cl l,0
ld c,HAM_Def1,23

;　ハメルンは、この上なく楽しそうに笑うと、その長い手をひかるの首に回し、@まるで口づけでもするくらいの至近距離でジッと目を覗き込んできた。\
`　Hameln laughed even harder than ever, waving his hand dismissively at Hikaru, `@` and at a range close enough to kiss, he peered into Hikaru's eyes.`\

ld r,HIK_Def4a,80

;「……な……なんですか！？」@
`"...Wh...what?!"`@`
br
;　ハメルンの目は吸い込まれるような赤い色をしていた。@まるでうさぎの瞳のように。\
`　Hameln's eyes were stunningly red.`@` It was exactly like a rabbit's eyes.`\

ld c,HAM_Def3,80

;「……君は傷ついてる。@あのクラスメートたちの仕打ちに、心の底から傷ついてる。@関係ないうさぎに当たり散らしたところで、そんなのは所詮その場しのぎだ。@君の傷は決して癒えることはない。@……違うかい？」\
`"...You are hurting.`@` You are hurting from the bottom of your heart due to poor treatment from your classmates.`@` You made due with a temporary solution of striking these rabbits unrelated to the matter.`@` But your pain could not be healed.`@` Am I wrong?"`\
bg black,23
bg gakkou_02u,23

;　そう言って、ハメルンは視線をひかるから校舎の方に移した。@
`　And saying this, Hameln's gaze shifted from Hikaru to the school building.`@`
;　２階の廊下に、さっき教室にいたひかるのクラスメートたちがいるのが見えた。\
`　On the second floor hallway, he could see Hikaru's classmates, who had earlier been in the classroom.`\
me1v 16,50

;　……またくだらないおしゃべりをしているのだろう。@大袈裟に身振り手振りをつけながら笑い合っているのが見える。@
`　...Probably having another worthless conversation.`@` He could see them laughing with each other, gesturing exaggeratedly.`@`
br
;　それを見た瞬間、ひかるは自分の頭にカッと血がのぼるのが分かった。\
`　The moment he saw that, Hikaru understood what made his blood rise to a boil.`\
bg black,22

;　……そうだ。@自分は傷ついている。@こんなにも傷ついている。@
`　...That's right.`@` I'm in pain.`@` I'm suffering so much.`@`
;　なのにあいつらは……。\
`　But still, those guys are...`\
bg usagi_02,0
ld c,HAM_Def1,0
ld r,HIK_i1,22

ld c,HAM_Def2,80

;「ねぇ、ひかる君……“ハメルンのカスタネット”で変えられるのは、ねずみだけじゃないんだ。@小さな動物になら、どんな姿にも変えることができるんだよ。」@
`"You know, Hikaru-kun...`Hameln's Castanets` can change things into more than just rats.`@` As long as it's a small animal, it can change them into anything."`@`
br
;　ハメルンはひかるの耳元に口を近づけ、この上なくやさしい声で囁いた。\
`　Hameln placed his mouth near Hikaru's ear and whispered this softly.`\

cl c,0
mld c,HAM_Def1,22

;「僕は、うさぎを虐めちゃいけないって言いに来たんじゃない。@……罪もないうさぎを虐めるなら、………罪深いうさぎをいじめる方が、道理に適ってるんじゃないかな、って。@……そう言いたいのさ。」\
`"I didn't come to tell you, that torturing rabbits is wrong.`@` ...If they're innocent, at least...but if they are full of sin, it might be more reasonable.`@` That's what I wanted to tell you."`\
ld r,HIK_Def4a,80

;「……罪深い、うさぎって……。」\
`"...Sinful, rabbits...?"`\
mld c,HAM_Def3,80

me2v 17,50

;「君の傷を癒すことが出来る、……本当の罪を背負ったうさぎだよ。@……そんなうさぎたちを、思いのままに出来たなら。@……ようやく、君の心のぱっくり開いた傷は、@……縫い閉じることが出来るんじゃないかな……。」\
`"Rabbits truly burdened with sins... that can heal all your wounds.`@` ...If you do to these sorts of rabbits as you have before,`@` ...can't these wounds that have opened in your heart,`@` ...finally be sewn shut...?"`\

mcl c,0
bg black,2

fede 0,2000
E_A

bg rouka_01,2

me1v 5,50

;「よーし、次、旧校舎のトイレ行ってみようぜ。」@
`"All right, next let's try heading to the old school's toilets."`@
;「もういいから帰ろうぜー。@八不思議なんて、どうせただの噂だって。」\
`"It's fine, let's go back. `@`They say The Eighth Mystery is just a rumor after all."`\

;　廊下で騒ぐ少年たち。@彼らは学校の八不思議を検証しようと、@噂になっている教室や場所を巡って、校内を練り歩いていた。\
`　Boys were making a ruckus in the hallway. `@`Thinking to inspect the school's Eighth Mystery, `@`they were rounding the rumored classrooms and halls, parading through the inside of the building.`\

;　しかし思った以上に学校の敷地は広い。@
`　However the school grounds were much larger than they thought.`@
　まだ半分も確認していないというのに、@既に夕陽は沈みかけ、校舎の中を格子状の影で覆おうとしていた。\

bg black,23
bg rouka_02,23

「て言うかさ、普通、学校の怪談って七不思議じゃねぇの？@　なんでうちだけ八不思議なんだろ？」@
「そりゃ、この学校がとんでもなくでかいからだろ？@　八不思議でも少ないくらいだって。@普通の学校の何倍もあるんだからさ。」\

　そんな何でもない会話をしながら、少年たちはだらだらと歩いていく。@
br
　すると、廊下の先、階段の踊り場の陰から、不意に人影が現れた。\

ld c,HIK_Def1,2

「ん？」@
「……何だよ、お前かよ。@泣いて帰ったんじゃなかったのかよ？」\

　その人影は二瓶ひかるだった。@

　少年たちはさっき、彼が逃げ出すように教室を出て行ったのを見たばかりだった。@
br
　しかし、今のひかるは何も言わず、無表情のままジッと少年たちを睨みつけている。\

bgm1 9

bg rouka_03,22

「うぇ……。@何かこいつ睨んできてんだけど。」@
「何か用？@　まさか、俺たちと一緒に遊びたいとか？」@
「えー。@ちょっとそれ冗談でもきついって。@俺、こいつと友達とか死んでも無理！」@
br

;quakey 2,200

　少年の一人が大袈裟に顔をしかめ、それを見て他の少年たちも豪快に笑った。\

「ほら、さっさと帰れよ。@じゃないと今度はゴミ箱じゃなくて焼却炉に鞄ごとぶち込むぞ。」@
br
　少年たちは凄むと、ひかるに向かってゆっくりと近付いて行く……。@
　と、次の瞬間……。\

E_MA

mbg white,1
mcbg 22

「……痛っ！」@
br
　少年たちの顔に何かが当たった。@
　ひかるが何かをばらばらと投げつけたのだ。\

bg rouka_04,22

　それは……、うさぎの糞だった。@
br
　少年たちには、それが糞であることは理解できなかったが、挑発的な行為であることは充分に理解できた。\

;cl c,23

　ひかるは呆然とする彼らを尻目に、それこそ脱兎のごとく逃げ出す。@
br
　感情が、呆然から怒りに変わり、少年たちの耳はみるみる真っ赤になる。\

「お前ッ、ふざけるなよ！！！」@「待てコラ！」@「ブッ殺してやる！！」@
br
　一斉にひかるの後を追う。\

bg black,23
bg k_rouka_03,23
wait 500
bg black,23
bg toire_01,23
wait 500
bg black,23
bg kaidan_01,23
bg black,23
bg kaidan_02,23
;wait 500
;bg black,23
;bg rouka_01,23


　廊下を走り抜け、階段を２、３段飛ばして駆け下りる。@すると前を走るひかるが１階の奥の教室に逃げ込むのが見えた。\

se1v 82,100

bg white,64
bg ongaku_03,24
quakex 1,100

　勢い良く扉を開け、少年たちもそこに飛び込む。@
　しかし、教室の中にひかるの姿はなかった。@どこか物陰にでも隠れているのだろうか。\

「おい、出てこいよッ！！」@
br
　少年たちは怒りに任せて叫ぶ。@
br
「あいつ、やっぱり一回本気でシメようぜ。@あれだけやったのに全然反省してねぇじゃん。」\

bg black,23
bg ongaku_01,23

me1v 11,90

　少年たちは教室の中を探し始める。@
br
　ここはどうやら、音楽室のようだった。@日が落ち、明かりがついていないこともあって、とても薄暗かった。@
　音楽室の象徴とも言うべきグランドピアノが、薄暗闇の中で黒い大きな動物のように見える。\

　一体、どこに隠れた？@　ここにいることはわかってるんだ。@
　見つけ出して、ギタギタにしてやる………。\

bg black,22
fede 0,2000
E_A










se1v 85,100

　……その時、音楽室の中に、……カチ、カチ、カチ、という音が響いた。@

se2v 85,100

br
　それが、……懐かしいカスタネットの音であると、すぐに気が付く。\

bg ongaku_02,22

me2v 17,50

se3v 85,100

「おい……何の音だ？」@
「……カスタネット……、……だよな……？」\

se1v 85,70

　少年たちは辺りを見回すが誰もいない。@
br
　壁にかかった肖像画の音楽家たちとは目が合ったが、現実の人間の姿はどこにもない。@しかし音は止まらない。\

se2v 85,70

「おい！@　ふざけてないで出て来いよ！」@
br
　少年たちは叫ぶ。@だがその声には恐れが滲んでいた。\

se3v 85,100

　ひかるがカスタネットを叩いているに違いないと、理屈ではわかっているのだが。@……しかしさっきから、@この音楽室には自分たち以外の気配が感じられないのだ。\

bg black,22

se1v 85,50
　なのに、カスタネットの音がする。@
se2v 85,70
　なのに、カスタネットの音が近付いてくる。@
br
se3v 85,85
　………カチ、カチ、カチ……。@
se1v 85,100
　カチ、カチ、カチ、カチ、カチ、カチ………。\

me3v 16,50

　少年たちは狼狽し、互いの顔を見合わせる。@もはや誰も自分の恐怖を隠そうともしない。@
br
　……絶対おかしいだろ？@　……何なんだよこの音！@
　一体どこから聞こえてくるんだよ！？@　だって、これじゃ、まるですぐ後ろから……。\

se1v 85,100
wait 300
se2v 85,100

　少年たちは、姿なく近付いてくるその音が、今、自分たちのすぐ後ろまで来ていることを悟る。@
br
　そして、恐る恐る、だけれども一斉に振り返る。\

bg black,24
bg ongaku_01,24

E_A

「……え。」@

me1v 11,90

「……………………。」@
「は、……はは。@……誰もいねぇじゃん。」\

　そこには……、誰もいなかった。@
br

E_A

　しかし、少年たちを不思議な感覚が襲う。@
　……何だか、視界がおかしい。\

bgm1 11

bg black,0
print 99,2000,"trvswave.dll/l"
print 26

bg ongaku_03,0
print 99,2000,"trvswave.dll/l"

　ぐにゃりと歪み、……眩暈を覚える。@
br
　何だか、急に部屋が広くなったような気がした。@
　見上げる天井が異様に高い。@
　このピアノはこんなに大きかっただろうか？@　鍵盤が手の届かないほど高い位置にある。\

me1v 28,70

　少年たちは気付く。@部屋が大きくなったんじゃない。@自分たちが小さくなったんだと。\

bg black,22
bg aka3,1
quake 5,300

　パニックになった少年たちは悲鳴を上げようとした。@だが声が出ない。\

　どうして？@　それにさっきから周りの音がやたらと大きく聞こえるような……。@あれ、俺の手足ってこんなに短かったか？！@
br
　その時、すぐ近くから誰かの囁くような声が聞こえてきた。\

bg black,22

se1 85

bg ongaku_02,0
ld c,HAM_Def1,22
ld c,HAM_Def3,80

「“夜、音楽室にいると、カチ、カチ、カチ、というカスタネットの音が聞こえてくる。@しかし、辺りを見回しても誰もいない。@カチ、カチ、カチ…。@音は段々大きくなってくる。@そこで気付く。@自分たちの姿が小さなうさぎに変わっていることに……。”」\

　そこにはおかしな衣装を纏った長髪の青年が立っていた。@そして、その手にはカスタネットが。\

　しかし、今の彼らにとって、……その青年は見上げるほどの巨人のような背丈があった。@
br
　彼らは理解する。@自分たちがどれほど小さくなってしまったかを理解する。@
br
　青年は、整ったその顔で笑顔をつくると、ぶるぶると震える少年たち…、@いや、うさぎたちに笑いかけた。\

ld c,HAM_Def6,80

me2v 17,70

「おめでとう！@　君たちが僕の怪談、『ハメルンのカスタネット』の初めての犠牲者だよ。」@
se1 85
br
　青年はなおもリズミカルにカスタネットを鳴らす。@するとうさぎたちはまるでその音に操られるかのように一列に並んだ。\

ld c,HAM_Def3,80

「ふふふ、それじゃあ、いよいよ怪談のラストだ。」\

“……動物に姿を変えられた子供達は、ハメルンの鳴らすカスタネットの音に導かれ、闇の中へと消えていったのでした……。”\

ld c,HAM_Def4,80

「さぁ、君たちをとっておきの“闇”へとお連れするよ。」@
br
se1 85
　夜の音楽室の中に、ハメルンのカスタネットが鳴り響く……。\

bg black,2

fede 0,2000
E_A
bg usagi_01,2

me1v 16,50

　気がつくとうさぎたちは校舎裏のうさぎ小屋の中にいた。@
br
　ハメルンがカスタネットを鳴らすのをやめると同時に、うさぎたちは自分の意志で動けるようになる。@
　しかし、うさぎの手足は人間のそれとは感覚が違うのか、うまく歩くことすらままならない。\

ld r,HAM_Def2,2

「……さあ、ひかる君。@後はどうぞご自由に。」@
br
　軽やかなハメルンの声を合図に、うさぎ小屋の扉がギィーという錆びた金属の音と共に開いた。\

mld c,HIK_Def2,2
bg black,2

bg usagi_02,2
;ld c,HIK_Def1,2

　うさぎたちは赤い目を見開く。@そこには、………ひかるが立っていた。@
br
　もちろん、見上げるような巨人の背丈がある。\

　そして、……彼が両手に握り締めるものが、不気味な銀の輝きを放つ。@
br
E_A
　ひかるの両手には、無数の文房具が。@
bgm1 16
　ハサミ、コンパス、カッターナイフ……。@……それらは月の光に反射し、冷たい輝きを放っている。\

bg black,22
mono 2
bg usagi_01,22
quake 5,500

me1v 28,70

　うさぎたちはこれから起こることを直感し、必死になって逃げ出そうとする。@
br
　しかし、金網を引き千切れるわけもなく、そのわずかな隙間から外へ逃れ出ることも出来はしない。\

quake 5,500

　出来るのは、ただがむしゃらに走り回って、壁や金網に突進して頭をぶつけることだけ。@
　見ているのが哀れなくらい愚かで無駄な抵抗だった。\

　金網に負けて爪が剥がれ、あちこちに頭をぶつけ血を滲ませると、@……とうとう彼らも諦めたのか、身を寄せ合って、懇願するようにひかるを見上げる。\
mcl c,0
bg black,22
mono 0
　お願いします。@許して下さい。@助けてください。@どうか、どうか、頼むから。\

mono 2
bg usagi_03,0
ld c,HIK_w1,2

wait 2000

ld c,HIK_w2,2

　ひかるはそんなうさぎたち、いやクラスメートたちの瞳をジッと覗き込むと、@冴え冴えとした笑みを浮かべる。@
br
　両手に握り締める無情の文房具の数々が、ただぎらぎらと酷薄な煌きを浮かべるだけだった………\









E_A

mono 0
bg white,1
;mcbg 22
bg black,2

wait 2000

bg kyou_03,22

bgm1 9

;「……ほんと、酷過ぎるよね。」@
`"...Really, it's too cruel."`@`
;「うさぎとか殺して、何が面白いのかしらね……。」@
`"I wonder what the hell is so fun about killing rabbits..."`@`
;「こういうのって、猟奇殺人の前兆なんだろ。@……怖ぇよなぁ…！」\
`"I wonder if this could be the warning signs of some psycho killer.`@`...That's freaky as hell...!"

;「例の、４人が行方不明になったってのも未解決なんだろ？」@
`"And those 4 missing people still haven't been found, right?"`@`
;「やだぁ、学校、怖ぁい…！！」\
"Noooo, school is creepy...!!!"`\

bg black,22
bg rouka_02,0
ld r,HIK_Def2,22

;　学校は今、先日起きた二つの事件の話題で持ち切りだった。\
`　At school, all anybody talked about now were the two incidents that occured the other day.`\

;「うさぎ小屋の虐殺」。@そして、「行方不明になった４人の生徒」。\
`"The Mass Killing in the Rabbit Cage."`@` And, "The Missing 4 Students."`\


;　うさぎ小屋の周りには立ち入り禁止のテープが引かれ、誰も入れなくなっている。@
`　The area around the rabbit cage was closed off by No Trespassing tape, and nobody was allowed in.`@`
;　いなくなった生徒たちは警察に失踪届けが出され、今も捜索は続いている。@
`　The police released a missing persons' report for the missing students, and the search was still continuing.`@`
br
;　しかし、絶対に４人が見つかることはないだろう。\
`　But, the 4 people would never be found.`\

ld r,HIK_w1,22

;　ひかるだけが“彼らは絶対に見つからない”ということを知っている。@
`　The only one who knew 'they would not be found,' was Hikaru.`@`
br
;　いや、正確には“見つかっているのに気付いてもらえない”ということになるのだが……。\
`　No, to say, "Even though they were found, nobody realized it," would be more accurate, but...\

cl r,22

;　二つの怪事件に繋がりがあるのではと訝しがる者は多い。@
`　There were many who doubted the two incidents were connected.`@`
br
;　また、特に勘のいい者は、@うさぎ小屋の死骸の数と行方不明の生徒の数が合致することに気付いてもいるようだった。\
`　There were also more perceptive people,`@` who seemed to realize that the number of corpses in the rabbit cage were the same as the number of students missing.`\

;　これは、４人を殺すというメッセージなのでは、犯行予告なのでは……。@
`　'Do you think this was an advanced notice of the crime, that they would kill 4 people...?'`@`
br
;　何人かの先生たちがそう囁いているのを聞いた。\
`　The teachers heard countless people whispering like that.`\

;ld l,HIK_Def1,80
bg rouka_04,22

;　……的外れな話だ。@
`　...What a muddled up tale.`@`
;　その死骸が、まさに行方不明の彼らだなどと、誰も気付けはしまい。\
`　Nobody can realize that those corpses, all really were the four missing people.`\

;　死骸の数を含めると、うさぎ小屋のうさぎの数が、本来よりも多いことには、@誰も違和感を覚えなかった。@
`　Nobody picked up that if one added the number of corpses to the number of rabbits in the cage,`@` that the number was higher than before.`@`
br
;　うさぎは生殖本能が強いから、気付かない間に勝手に繁殖して増えていたのだろう。@……そのくらいにしか考えていないらしい。\
`　Rabbits have a strong instinct to reproduce, and bred on their own while nobody was paying attention.`@`...It seems that's as far as anybody was thinking.`\

bg black,22

;　今はそれでいい。@噂が膨れ上がるのはこれからだ。@
`　And for now, that was fine.`@` That was as far as the rumors swelled.`@`
;　昨日、ハメルンはうさぎ小屋で言った。@
`　Yesterday, Hameln said in the rabbit cage,`@`
br
;「怪談になるのはゆっくりでなくちゃいけない。」、と。\
`That, "You must work slowly to become a ghost story."`\

bg black,29
lsp bgsp,":a;bmp\background\efe\red_waku.bmp",0,0
bg usagi_02,0
ld c,HAM_Def1,22
ld c,HAM_Def2,80
bgcopy
csp -1


;「何しろ、簡単に知れ渡ってしまったら、@誰も怖がって音楽室には近づかなくなっちゃうじゃないか。@……ひかる君が仕返ししたい奴らは、この子たち以外にもまだまだたくさんいるんだろ？@　噂になるのは、君が殺したい連中をみーんなうさぎに変えてからさ。」\
`"At any rate, if I were to be well-known too easily,`@` everybody would get scared, and nobody would go near the music room.`@` ...There are still plenty of those that you want to get even with other than these kids, right Hikaru-kun?`@` To become common talk, I'll turn all of your colleagues you wish to kill into rabbits."`\

bg black,22

;　ひかるは頷いた。@
`　Hikaru nodded.`@`
br
;　そうだ。@こいつらだけじゃない。@
`　That's right.`@` It's not just them.`@`
;　僕を無視した奴ら。@虐めを見て見ぬ振りした奴ら。@クラスメート全員がひかるの標的なのだ。\
`　Those bastards who ignored me.`@` The ones who pretended not to see my persecution.`@` Every one of Hikaru's classmates were his targets.`\

;bg gakkou_01,22

;　これからも、学校のあちこちでうさぎの死骸が見つかるだろう。@
`　From here on out, rabbit corpses will be found all throughout the school.`@`
br
;　行方不明になった生徒の数だけ。\
`　Only the same amount as missing students.`\

;bg black,23
bg ongaku_01,22

;　そうして、……音楽室から聞こえる不思議なカスタネットのことが次第に知られるようになり、@…………『ハメルンのカスタネット』は、定番の怪談となる。\
`　In doing that, ...once word get out about the mysterious sound of castanets coming from the music room,`@` ..."The Castanets of Hameln" will become a standard ghost story.`\

;　僕をいじめたクラスメートたちは、その怪談の犠牲者であり、……僕がその立会人になるんだ。@
`　The classmates who tortured me will be the victims of that tale, ...and I will be the sole witness.`@`

br
;　そうさ。@彼らは怪談に飲み込まれて消えたんだ。\
`　That's right.`@` They all will be swallowed up by this sordid story and disappear.`\

;bg black,23
;bg rouka_02,0
;ld c,HIK_Def1,23
bg blood_1a,22

me1v 16,50

;　僕を殺人者と罵るかい？@　悪いけれど、それは的外れだ。@
`　Would you say I am a murderer?`@` Apologies, but that's off the mark.`@`
br
;　……僕は誰も殺しちゃいない。@僕が殺したのは、罪深いうさぎだけさ。\
`　...I haven't killed anybody.`@` I only kill immoral rabbits.`\

;ld c,HIK_Def1,80

;　万が一、僕がうさぎを殺しているところを誰かに見られたとしても。@
`　Even in the worst case that I were caught by someone while killing them.`@`
br
;　僕を逮捕できるのかい？@　うさぎ殺人罪という罪でもあるのかい？\
`　Could anyone arrest me?`@` Is there a crime out there, like a rabbit assassin?`\

;　動物虐待で児童相談所に連絡、とやらがせいぜいさ。@僕のプライバシーも人権もばっちり保護されるし、@健全な社会生活を送るためのバックアップだって完璧さ。@……何も恐れることなんてない。\
`　Even as animal cruelty, the worse they'd do is contact a child consultation center.`@` My privacy and human right would be perfectly protected,`@` and they'd even provide backup to seamlessly bring me back to a healthy social life.`@` ...That's nothing to be afraid of.`\
bg Aka2,0
ld c,HIK_w2,22

;　……そうして、やがて『ハメルンのカスタネット』は、誰もが震え上がる、本物の怪談になる。@
`　...And before long, "The Castanets of Hameln," will become a true ghost story, one that anybody would shiver to think about.`@`

br
;　その怪談の犠牲者を決めるのは、……僕なんだ。@
`　The one who chooses the victims to this tale, ...is me.`@`
;　僕をいじめるヤツや、……気に入らないヤツは、……ハメルンの力でみんなうさぎにしてやる。\
`　Those who abused me, ...guys I just plain don't like, ...all of them will become rabbits by Hameln's power.`\
ld c,HIK_w3,80
quakey 1,100

;　ふふ、っふふふふっふっふっふっふ、あっははははははははは…！！\
`　Huhu, huhuhuhuh, Ahahahahahahahaha...!!!`\
bg black,22

E_A















;「くすくす。@……随分、機嫌が良さそうね。」\
`"Teehee.`@` ...You seem to be in considerably good spirits."`\
me1v 5,50

bg rouka_03,24

;　背後からいきなり声がした。@反射的に声の方向を振り返る。@
`　He suddenly heard a voice from behind him.`@` He reflexively turned towards the voice.`@` 
;　そして、……驚いた。@
`　And, ...was astonished.`@`

br
;　そこには、まるで舞台からそのまま抜け出してきたような豪奢な服を着た少女が立っていた。\
`　A girl clad so extravagently that it looked as though she'd just slipped away from a play was there.`\
ld c,HIG_Def2,22
fede 0,1000
E_A
ld c,HIG_w3,80

bgm1 5

;　ぞっとするほど色の白い肌と、それと対照的な漆黒の長い髪。@思わずたじろいでしまうほど美しい少女だった。\
`　Skin so pale it would make one shudder, and long, jet black hair in contrast.`@` A girl so beautiful it made him hesitate without thinking.`\

;　上級生だろうか。@いくら生徒数が多いと言っても、@同じ学年に彼女のような人間がいたらさすがに覚えているはずだ……。\
`　Was she an upperclassman?`@` Even knowing that the number of students in the school was high,`@` he knew that if a human like her were at the same school as him, he would certainly remember her...`\
ld c,HIG_Def4,80

;「あなた。@すごい邪悪に笑うのね。@……まるで、学校の妖怪みたいな笑い方だったわよ。@……くすくすくすくすくすくす。」@
`"You.`@` You have an incredibly wicked laugh.`@` ...It's exactly the same kind of laugh as one of the school's youkai.`@` ...Teehee, heehee hee."`@`
br
;　妖怪、という言葉にひかるは一瞬ビクッとする。\
`　Hearing the word 'youkai' startled Hikaru for a moment.`\

;　……ハメルンのことを、ニンゲン風情に理解できるわけがない。@……怪談は、まだまだこれからなのだから。\
`　...H u m a n s should not be able to even appear to grasp anything about Hameln.`@`...The story, is still not finished.`\

bg black,22
bg k_rouka_03,22
ld l,HIG_def3,22

;「何がそんなにもご機嫌なのかしら…？@　良かったら、私にも教えてくれないかしら。」@
`"What has you in such high spirits...?`@` If you'd like, perhaps you could tell me?"`@`

ld r,HIK_Def4a,22

;「あ、いえ、何でもないんです……。@ちょっとその……、思い出し笑いをしちゃっただけで……。」\
`"Ah, n-no, it's nothing...`@`It's just...I remembered something and it made me laugh, that's all..."`\

ld l,HIG_w4,80

;「くすくす。@……児童失踪事件に、今日は動物の虐殺事件なのに。@こんな状況で思い出し笑いなんて、随分と不謹慎なのね。」@
`"Ehehe.`@` Even though there's been the missing children's case and the animal slaying case today.`@` It's rather imprudent of one to suddenly remember something and laugh in these circumstances."`@`
br
;　そう言いながらも、彼女も笑う。\
`　While saying this, she laughed too.`\

;　……それは、ぞっとするほどの冷たさを感じる笑い。@
`　...It was a laugh so cold it made him shudder.`@`
br

;　思わず目を逸らしたくなるほどに、冷え切った眼光の笑いだった。\
`　A smile with such an icy gleam in her eye it made him avert his eyes inadvertantly.`\

ld r,HIK_Def3,80

;「そ、……そうですよね。@こんな酷い事件が起きてるってのに……。」\
`"Th, ...that's right.`@` Even though such terrible events are happening..."`\

ld l,HIG_Def4,80

;「くすくす、冗談よ。@どんな悲劇が起きたからって、笑っちゃいけないなんてことはないわ。@自分にとっては悲劇でも他人にとっては娯楽なんてこと、よくあることだもの……。」\
`"Ehehe, it's a joke.`@` No matter what kind of tragedies occur, there's none that are impossible to laugh at.`@` One man's pain is another man's pleasure -- that sort of thing happens frequently..."`\

;　彼女は長い髪に自分の指を通すと、弄ぶようにくるくると絡めた。@
`　She passed her finger through her long hair, idly spinning it around the digit.`@`

br
;　その一つ一つの仕草が余りにも優雅で、なんだかよく出来た人形のように見えた…。\
`　Those detailed movements were excessively elegant, and made it look as though she were a very well made doll...`\

bg black,22

;　自分にとっては悲劇でも、他人にとっては娯楽。@
`　One man's pain, is another man's pleasure.`@`
br
;　それは学校で、ひかるが常々感じていることだった。\
`　In this school, this was something Hikaru usually felt.`\

;　無視され、持ち物を捨てられ、どこまでも沈んでいく毎日。@しかし、ひかるが傷つけば傷つくほどクラスメートたちの笑い声は大きくなっていく……。\
`　Being ignored, having his things thrown away, feeling awful every day.`@` And yet, the more pain Hikaru was in, the louder his classmates' laughter would get...`\

bg k_rouka_03,0
ld c,HIG_w3,22

;「……もちろん、娯楽だと思っていたことが悲劇に変わってしまうこともよくあることだけどね。@……くすくすくすくすくす。」\
`"...Of course, there are times when pleasure turns to disaster as well.`@` Heehehehehe."`\

;bg black,22

;　……そうだ。@今や、クラスメートたちにとって娯楽は悲劇へと変わったのだ。@
`　...That's right.`@` Right now, those classmates' pleasure has turned to misery.`@`
br
;　自分たちのした行為が、因果応報。@
`　The retribution for their deeds.`@`
;　僕を傷つけて楽しんだヤツらが、今度は僕に傷つけられて楽しませるのだ。\
`　The assholes who enjoyed my suffering, now I can enjoy theirs.`\

;ld_p HIK_Def1
;lsp2 2,$ld_pass,320,240,100,100,0
;lsp2 3,$ld_pass2,320,240,100,100,0
;print 22

bg black,22
ld r,HIK_w2,22

;　いや、僕は彼らを傷つけなどしない。@
`　No, I am not hurting them.`@`
br
;　僕はうさぎを殺すだけ。\
`　I'm just killing a couple of rabbits.`\

;ld_p HAM_Def2
;lsp2 4,$ld_pass,420,240,100,100,0
;lsp2 5,$ld_pass2,420,240,100,100,0
;print 0
bg aka3,0
ld c,HAM_def3,0
ld r,HIK_w2,22

;　彼らはハメルンの怪談に飲み込まれるだけ。@
`　They're simply being swallowed up by Hameln's legacy.`@`

br
;　僕の手は、誰の血にも汚れないのだ。\
`　My hands are not stained with anyone's blood.`\

se1 84

bg black,42

bg rouka_02,0
ld r,HIG_w3,22
ld r,HIG_Def5,80

;「……ふぅん。@そういう考えなのね。」@
`"...Hmm.`@` Is that how you're thinking?"`@`
ld l,HIK_Def4a,23

;「………何ですか、突然…。」\
`"...What are you talking about all of a sudden..."`\

;　何も口にしていないはずなのに、……彼女は唐突に、「そういう考えなのね」と、相槌を打つ。@
`　Even though I don't believe I said anything, ...she abruptly threw in an appropriate word with, "That's how you're thinking."`@`
br
;　……この、口にしていないはずなのに、会話になってしまう感覚は……、まさか……。\
`　...This feeling, creating a conversation when I hadn't said anything...it can't be...`\

ld r,HIG_Def2,80

;「時に非力な妖怪は、残酷なニンゲンを手駒にすることがあるわ。@……自分の力だけでは狩りが出来ないものだから、@ニンゲンを唆し、その手を借りようとする。@……情けない狩りよね。@くすくすくすくす……。」\
`"Sometimes a powerless youkai will make a pawn out of a pitiless human.`@` ...They can't hunt by their own power.`@` So they tempt HUMANS and use them.`@` ...Truly a deplorable hunt.`@` Teeheehee..."`\

ld l,HIK_Def3,80

;「……そ、それが何ですか。@……何を言ってるのか、わかりません。」\
`"...A, and what of it?`@` ...I don't understand what you're saying."`\

ld r,HIG_w4,80

;「同じことが、駒にされるニンゲンにも言えるわ。@……自ら手を下す勇気のない子が、妖怪と怪談を免罪符に、@自分の手は汚れていないんだ…、などと言い出したりね？」\
`"That's the sort of thing a HUMAN pawn would say.`@`...Someone without the bravery to do things by their own hands can indulge in a ghost story, `@`that way their own hands don't get dirty, ...is also the sort of thing they might say."`\

;　それは、……紛れもなく、ひかるのことだ。@
`　That's, ...without any doubt, about Hikaru.`@`
br
;　やはり、この少女はハメルンと同じ。@……ニンゲンではない。@心を、読んでいる……。\
`　Just like he thought, this girl was the same as Hameln.`@` ...She was not h u m a n.`@` She's reading his thoughts...`\

ld r,HIG_Def5,80

bg black,22









;「あなたは、殺す、ということを理解していないんだわ。」@
`"You don't seem to understand that you are killing."`@`

;ld l,HIK_Def1,80

;「………それはどういう意味ですか？」\
`"...What do you mean by that?"`\

bg k_rouka_03,0
ld c,HIG_Def3,22
ld c,HIG_Def4,80

;「缶詰の中の牛肉はどうやって作るか知っているの？@　まさか、小麦粉を混ぜて練り上げると牛肉になるなんて、@信じてるわけじゃないわよね…？」\
`"Do you know how ground meat is made?`@` Don't tell me you think they mixed up some wheat flour and made beef.`@` There's no way you'd believe that, right...?"`\

;　……最近の子供は、食肉が動物の死の上に生み出していることを、理解していないとよく言われる。@
`　...Many kids these days say that they didn't understand that animals were born for more than just to die for meat.`@`
br
;　肉に限らない。@僕たちの食卓には、“死”が積み上げられている。\
`　They're not restricted to meat.`@` D E A T H  is piled up on our dining tables.`\

;mbg black,22

;　だが、僕たちはそれに目を逸らし、暴食の限りを尽くす。@
`　But, we avert our eyes, relying on our surfeit.`@`
br
;　自分たちの食卓を生み出す、“死”そのものについては、知らぬ存ぜぬ見たくもない、とくる。\
`　We don't want to look at, or even know that the very thing brought forth to our dining tables is D E A T H.`\

;　フライドチキンを頬張る子供たちの内、@一体、何人が、自らの手で鶏を絞め殺せるというのだろう？@
`　I wonder how many of those children stuffing their faces with fried chicken,`@` have it in them to strangle a chicken with their own hands?`@`
br
;　そういう光景に目を逸らし、忌避するくせに。@僕たちは暴食と飽食を繰り返している……。\
`　Even though we look away from such a spectacle, though we avoid it.`@` We still repeat our cycle of gluttony and overindulgence...`\

;mcbg 22

cl c,0
ld r,HIG_w4,23

;「………その通りよ。@肉を食うとは即ち、殺して肉を剥ぐということ。@その罪を理解せぬ者には、肉を食らう資格なんて、ありはしない。」\
`"...That's right.`@` To eat meat is namely, to tear off the flesh of the dead.`@` Those who do not understand that sin, don't have any right to eat meat."`\
ld l,HIK_Def2,80

;「僕に、………肉を食らう資格がないと、……言いたいんですか…？」\
`"Are you, ...trying to tell me, ...that I have no right to eat meat...?"`\
ld r,HIG_Def5,80

;「“僕の手は、誰の血にも汚れないのだ”、なんて、得意気に言ってしまうあなたに。@……一体、誰の肉を食らう資格があるというのかしら……？」@
`"I ask this you, who proudly said, 'I have not stained my hands with anyone's blood.'`@`...Whose meat do you have the right to partake of...?"`@`

ld l,HIK_Def4a,80

;「…………………………………。」\
`"......"`\

ld r,HIG_Def2,80

;「ニンゲンがニンゲンを殺す、というのは、重いことよ？」@
`"HUMANS killing HUMANS, is awfully heavy to say."`@`

ld l,HIK_Def3,80

;「……僕はニンゲンなんて、殺しませんよ。」\
`"...I have not killed any human."`\
ld r,HIG_w4,80

;「くすくすくす。@……フライドチキンを食べながら、鶏なんて殺しませんって言うわけよね。」@
`"Teeheehee.`@` ...So you're saying that you haven't killed a chicken while you eat fried chicken?"`@`
br
;　……何も言い返せない。@
`　...He couldn't respond.`@`
;　誰なんだ、この少女は……。@……やっぱり、ニンゲンじゃ、ない………。\
`　Who the hell, is this girl...?`@` ...Just as he thought, she's not, h u m a n...`\














bg black,29
bg rouka_04,29

me1v 5,50

fede 1,1000
E_B

;　その時、廊下に設置されたスピーカーから放送が流れ出した。\
`　Just then, the speaker installed in the hallway began broadcasting.`\

;『……＊年２組の二瓶ひかるくん。@井俣先生がお呼びです。@職員室まで来てください。@繰り返します。@＊年２組の二瓶ひかるくん……、』\
`"...Hikaru Nihei of Class 2, Year ***.`@` You have a call from Inomata-sensei. `@` Please come to the staff room.`@` I repeat.`@` Hikaru Nihei of Class 2, Year  ***....."`\
bg black,24
bg rouka_03,0
ld r,HIK_Def3,24

「……あ、すみません。@僕、行かないと。」\

　先生が僕に何の用だろうという気持ちより、@……この不気味な少女から逃げ出す口実に出来る……という気持ちの方がはるかに勝っていた。\

ld l,HIG_w3,22

「ええ、またね。@………くすくすくす。」\

cl r,23

　ひかるは、彼女に背を向けると、そこから逃げ出すように職員室に向かう。\

bg black,23
bg rouka_02,23

　その背中に、少女は言葉を投げ掛けた。\

「もしも。@あなたに再び、人の命を奪う機会が訪れたなら。@……殺す、ということの重みを、今一度噛み締めてみることよ。@……もし、何の覚悟もなく、何も背負うことなく、@……人の命を、手を汚さずに奪おうなんて再び考えたなら。」@
br
　………考えたなら………。\

「あなたにとっての娯楽が、……再び悲劇になってしまう、なんてことも、……あるかもね……？@　……くす、………くすくすくすくすくすくすくす……。」\

bg black,22

　ひかるは逃げ出すように足を速める。@
br
　……あいつは何を言ってるんだ…？@
br
　ちょっとおかしい、イカれた上級生の電波話に付き合わされただけさ……。\

　忘れろ忘れろ、忘れてしまえ。@僕が、……殺してること、……知られてるわけがない……。@
br
　しかし、殺すことの重みを噛み締めろという、少女の言葉は、@……抜けない棘のように、ひかるの胸を苛むのだった…。\

fede 0,2000
E_A





;bg white,64

se1v 82,100

bg shokuin_01,24

bgm1 8

　職員室の扉を開ける。@
br
　井俣先生以外にも数人の教師がいたが、みんな一様に覇気のない疲れた顔をしていた。\

　そのうちの何人かは電話応対で忙しそうだった。@
br
　安否を気にする行方不明の生徒の親だけでなく、他の保護者たちからの苦情や心配の声も絶えず、@地方紙やマスコミからの問い合わせなども殺到しているらしい。\

bg black,22

　ふと目をやると、職員室の隅に生き残ったうさぎたち、@というか元々小屋にいた本物のうさぎたちがいた。@
br
　いくつかのダンボールで組み上げた簡易的な柵。@そこに新聞紙が敷かれて、とりあえずの彼らの住処が出来上がっていた。\

　そう言えば、事件の後、一時的に職員室に移されることになった、@と誰かが言っていた気がする。@
br
　ひかるはうさぎたちを一瞥すると、それ以上は気にせずに井俣先生の席に向かった。\

bg shokuin_02,22
ld c,HIK_Def1,22

「何ですか、先生。」\

　先生は顔をあげた。@やはり疲れた顔をしている。@あまり寝ていないのかもしれない。\

「あぁ。@あのうさぎ小屋のことなんだけどな……。」@
br
　心臓が大きく跳ねる。@
　……知られているはずはない。@うさぎ小屋のことが、……知られているわけ………。\

「ショックだったろうな……。@あんなに可愛がっていたんだからな……。@あまり、気に病みすぎないようにな？」\

ld c,HIK_Def4a,80

　ひかるは一瞬身構えた緊張を解く。@
　そうさ、当然だ。@自分の仕業だと、気付かれているわけもない。\

ld c,HIK_Def2,80

「……はい。@本当にひどいです。@なんであんなことが出来るんだろうって思います。」@
br
　ひかるは特に表情は作らずに言った。\

　こういう時は無表情のままでいい。@後は相手の方で勝手に想像してくれる。@傷ついてるだろう、とか、本当は泣きたいのだろう、とか。@
　先生は、まったく想定どおりの言葉をひかるに掛ける。@
br
　ひかるは、失笑したくなるのを抑えるので精一杯だった。\

「それでな二瓶、これはまだ決まったわけじゃないんだが……。@多分、近い内にあのうさぎ小屋はなくなると思う。」\

ld c,HIK_Def3,80

「……そうですか。」@
br
　それはひかるも予測していたことだ。@別に構わない。\

　散々気晴らしに使わせてもらってきた場所だったが、@自分にはもうあのうさぎ小屋も、本物のうさぎたちも必要ない。@
br
　今や、僕にとって、@……いや、僕たちにとって、この学校自体が巨大なうさぎ小屋なのだから。\

「二瓶には気の毒と思うが、……早く、うさぎ小屋がなくなってくれた方が、@ショックを受けた児童が、忘れてくれるのも早くていいだろうと思う。」\

ld c,HIK_Def4,80

「………あんな無残に殺されてたんですからね。」@

「まぁ、それもあるんだが。@…………………何て言うのかなぁ。@……先生たちも、うまく説明が出来ないんだよ。」\

ld c,HIK_Def1,80

「説明って、何の話ですか…？」@
br
　先生は頭の後ろで両腕を組み、う～んと唸りながら天井を見上げる。\

bg shokuin_04,22

me1v 11,90

「………低学年の子たちにさ。@各担任が質問攻めにされてるらしいんだよ。」\
;ld l,HIK_Def1,80
「犯人は誰かって…？」@

「いや違う。@……どうして、うさぎをあんな無残に殺したのか。@……まだ幼い子たちには、それがまったく理解できないんだ。@……つまるところ、“人間の悪意”ってヤツを説明できないんだ。」\

;ld l,HIK_Def1,80

bg black,22

「人間の、……悪意？」\

「俺たち教師は、人間には生まれついてのやさしい心があり、お互い助け合って生きてるんだって、@ずっと繰り返し説いてきたんだ。@それを信じてきた幼い子たちにとって、@………うさぎを惨たらしく殺す“悪意”というものが、まったく理解できないんだ。」\

;ld l,HIK_Def1,80

「………………………。」@
「誰が、どうしてこんな酷いことをしたんですか。@どうしてこんな惨たらしいことが出来るんですか。@……そう聞かれると、先生たちは何も答えることが出来ない。」\

bg shokuin_03,22

　先生にすら答えられない、……悪意という不条理。@
br
　家族の愛情と、友達との友情に囲まれて、健やかに日々を過ごしてきた幼い子たちにとって。@………不条理なる“悪意”という毒は、あまりに早過ぎるのだ。\

「……世の中、良い人間ばかりじゃない。@悪い人間だっているし、……まったく理解も説明もできない、不条理な悪意だってたくさんある。@………大人になったって理解できないんだ。@それを、唐突に突きつけられた。@……子供たちは、理解不能な恐怖に直面し、大勢が酷いショック状態に陥ってるんだよ。@………俺たちは無力だ。@“人間の悪意”というものすら、……子供たちに説明できない。」\

;bg black,22
;mono 2
;bg Different_spiral_1b,22

ld r,HIK_Def1,22

　ひかるはなんだか呆れてしまった。@
br
　この世が善と悪で出来ているなら、悪意は世界の半分を構成する要素だ。@
　それを説明できないと公言することは即ち、@世の中の半分すらも理解していないと言うも同然ではないか。\

;bg Different_spiral_1a,22
ld r,HIK_Def2,80

　教室には、理不尽な悪意なんて、いくらでも渦巻いている。@
　損得勘定などで説明できない、純粋かつ単純で、そして理不尽な、悪意。@
br
　そんなものも理解できないで、よくも教壇で担任面が出来たものだ。\

bg black,23
bg shokuin_02,23

「……まぁ、うさぎ小屋の話はこれくらいで、話を変えるが。@………二瓶、お前、もう少し何とかならないのか？」\

fede 1,1000
E_B

ld r,HIK_Def1,22

「……はい？」\

　唐突に話題が変わり、ついていけない。@……何の話だ？\

　先生は言い辛そうに頭を掻きながら、曖昧に笑っている。@
　その仕草を見る限り、……どうもこっちの話題が本題と見える。\

E_A
bgm1 14

「……その、もう少し、クラスのみんなとうまくやれないか？」\

ld r,HIK_Def4,80

　……は？@
　………うまく、やれ？@
　それって僕に言うことなのか？@　僕を虐めるクラスメートたちじゃなくて？\

「お前、木下のノートを捨てたそうじゃないか。」@

ld r,HIK_Def3,80

「…………。」\

bg note1,22

「“頭の悪いヤツにこんなの必要ないだろ”って言って、@みんなの前でゴミ箱に捨てたんだって？@　……木下のやつ、泣きながら先生のところに来たんだぞ。」@
br
　………………。\

「しかもその後で、自分のノートのコピーをクラス全員に配ったそうじゃないか。@『ノートって言うのはこうやってまとめるんだ。@良かったら参考にしろよ』って言って。」\

bg black,22

　……先生は何を言ってるのだろうか。@
br
　それじゃまるで、僕が悪い奴みたいな言い方じゃないか。\

mono 1
bg kyou_01,22

　確かにひかるは木下裕子のノートを捨てた。@
br
　でもそれは、裕子が本当に勉強ができない馬鹿女で、@効率の良いノートの取り方を全く分かっていなかったからだ。\

　黒板に書かれたことの断片、教科書に太字で記された単語をただ書き連ねただけの、らくがき帳のようなお粗末さ。@あんなもの捨ててしまった方がよっぽど良い。@
br
　そう判断して、厚意からひかるは裕子のノートを捨てたのだ。\

　もちろん、いくら厚意からとは言え、@ノートを捨てただけなら見ようによってはひかるが責められても仕方ないかもしれない。\

　だから、その後できちんと裕子のことを考え、@自分のノートのコピーを、模範的資料として提供したのだ。@
br
　しかも、良い機会だからと裕子だけではなくクラスメート全員分をコピーして。\

bg black,22
bg kyou_03,22

　うちは他のクラスの連中から駄目クラスと言われている。@他のクラスに比べて成績が極端に悪いからだ。@
br
　学年でもトップクラスのひかるがいるにも関わらず、クラス平均点は低迷している。\

　ひかるはいつもそれを腹立たしいと思っていた。@だからクラスのために、みんなのために良かれと思って奮起してやったことなのだ。\

　それなのにひかるは糾弾された。@“調子に乗ってる”と。@
br
　ひかるの脳裏に、先日殺害したクラスメートの一人が言っていたことが思い出される。\

bg black,22
;bg kyou_02,24

『あいつ、やっぱり一回本気でシメようぜ。@あれだけやったのに全然反省してねぇじゃん。』@
br
　反省って何だ？\

　僕が木下裕子のノートを捨てたのは厚意だ。@
br
　でも、お前たちが僕のノートを捨てたのはただの嫌がらせ、虐めだ。@そんな理不尽なことをされて一体何を反省しろって言うんだ？\

bg black,22
mono 0

fede 0,2000
E_A

bg shokuin_03,22

me1v 11,90

　先生は諭すような口調で尚も続ける。\

「確かにお前は成績がいい。@だけどな、本当に頭がいいやつってのは、それを他の子にひけらかしたりしないもんだ。@……先生はそう思うぞ。」\

　ひかるの頭は急速に冷めていった。@
br
　本当に先生は……、こいつは何を言ってるんだろうか？\

E_A

bg black,22

bg aka3,0
ld c,HIK_i1,22

bgm1 11

　お前がどう思うとか、そんなのどうでもいいんだよ。@そもそもお前が無能だからあんな馬鹿ばっかりのクラスになったんだろうが。@
br
　それにお前、あれから僕がどんな目に遭ってきたか知ってるのか？@　クラスの中で行われているいじめに何一つ気付きもしなかったくせに。@見ようともしなかったくせに。\

　なのに、泣きつかれた木下裕子の言い分だけを聞いて、状況を把握した気になっている。@何て浅はかなんだこいつは。@
br
　さっきこいつは“子供に悪意を説明できない”と言った。@その発言こそがこいつの無能を証明している。\

cl c,0
mld c,HIK_w2a,22

　あのうさぎたちを殺したのは誰だと思う？@　町の変質者？@　ストレスを抱えたキレやすい大学生？@
br
　違う！@　僕だ！@　目の前にいる子供だっ！！@　そして僕をそこまで追いつめたのもみんな子供だっ！！！\

　子供は悪意なんてとっくに知ってる。@
br
　大人のあんたたちよりも遥かに鮮烈な悪意の中で毎日生きてるんだ。@そんなことも分からないのかこの無能教師はッ。\

bg black,22

mcl c,0
ld c,HIK_def2,0

bg shokuin_02,22

「………先生は、ほとんど毎日お前がうさぎ小屋に通ってたのを知ってる。@飼育委員だからってそうそうできることじゃない。@ずっと偉いなって思ってたんだ。@……俺は、お前が本当はやさしい子だってことを知ってる。@だからな……？」\

　ひかるは思わず笑いそうになる。@
br
　確かにうさぎ小屋に通ってたのは知ってるだろう。@うさぎ小屋の鍵はあんたに言わなきゃ借りられないんだから。\

ld c,HIK_w1,22

　でも、それだけだ。@借りに来た僕に、事務的にただ渡していただけ。@僕のことを、ましてうさぎのことを気にかけていたわけじゃない。@
br
　なのに、今になってよくそんな取って付けたようなことが言えたものだ。@
br
　うさぎ小屋で僕が本当は何をしてたのかあんたは知らないだろ？@　あそこにだって悪意はあった。@あんたが気付いてなかっただけだ。\

「だから……。@もっとみんなに歩み寄って、……仲良くやれるよな？」@
br
　探るような目つきでひかるの顔を覗き込む。@今すぐこの目を潰してやりたかった。\

;ld c,HIK_Def3,22
ld c,HIK_Def2,80

「…………はい。@がんばってみます。@色々すみませんでした。」@
br
　ひかるの全く心のこもってない返事に、それでも無能教師は満面の笑みを浮かべた。\

quakey 1,100

「そうか、良かった。@二瓶なら分かってくれると思ったんだよ。」@
br
　嬉しそうに背中をバンバンと叩く。@
　この手を力任せにもぎ取ってやりたい。\

「あ、そうだ。@今日は先生、宿直当番で遅くまで学校にいるんだ。@だから、放課後になってあのうさぎたちに会いたくなったら、@いつでもここに来ていいからな。@あと何日も会えないかもしれないしな。」\

ld c,HIK_Def3,80

「……ありがとうございます。@井俣先生。」\

cl c,22

E_A
se1v 82,100

bg black,63
bg shokuin_01,22

　ひかるは早足で職員室を出た。\

　これ以上この茶番に付き合うのは耐えられなかった。@
　扉を閉めると同時に廊下にしゃがみこみ、歯を食いしばる。@軋む音が聞こえるほどに。@
br
　そうやって口の中から漏れだしそうになる声を必死に抑え込む。\

bgm1 10

quakey 1,100

　無能教師ッ、無能教師ッ、無能教師ッ、無能教師！！！\

　あんな無能が担任だから、……うちのクラスは落ち零れ扱い！@　僕が理不尽ないじめを受けてるのに気付きもせずッ。@なのに、泣き言をいう女子にだけは耳を貸して僕に説教までするッ！！\

bg black,24
bg rouka_02,24

「……次のうさぎが、決まったようだね。」\

ld r,HAM_Def1,2
ld r,HAM_Def3,80

　誰もいない廊下に、さも当然のように、涼しげな顔のハメルンが立っていた。@
　ひかるは、掴み掛かるかのようにハメルンに詰め寄る。\

ld l,HIK_i1,23
quakex 1,100
ld l,HIK_i2,80

「今すぐ！@　今すぐあいつをうさぎに変えてくれッ、あの職員室の無能教師を！！」\

ld r,HAM_Def2,80

「君の頼みなら、誰だって何人だって、うさぎに変えてあげるよ。@だけれども、君の今の頼みは聞けないね。」\

ld l,HIK_i1,80
quakey 2,200

「どうしてっ。」\

ld r,HAM_Def3,80

「忘れたのかい？@　だって、僕は“音楽室のハメルン”じゃないか。」@

ld l,HIK_w1,80

「………あ、……あぁ、そうだったっけ。」\

cl r,0
ld c,HAM_Def3,24

「音楽室の中でなら。@誰だってうさぎにしてあげるよ。@でも、それ以外の場所では、僕のカスタネットを聞かせたくないね。@夜の音楽室に拘るのが、僕のポリシーなんだ。」\

bg black,22

　なら幸いだ。@あいつは今日、当直だとか言ってた。@夜遅くまでいるだろう。\

lsp bgsp,":a;bmp\background\efe\red_waku.bmp",0,0
bg ongaku_01,22
bgcopy
csp -1

「それで、あいつを、……音楽室へ連れ込めば……。」@
「『ハメルンのカスタネット』の怪談、再びというわけさ。@……君の望む相手を、何人でも何十人でも、うさぎに変えてあげるよ。」\

bg black,22

　……ひかるは考えを巡らせる。@
br
　夕陽が沈むまではまだしばらく時間がある。@夜まで待つのはいいとして、はたして井俣をうまく音楽室に誘い込むことができるだろうか。\



lsp bgsp,":a;bmp\background\efe\red_waku.bmp",0,0
bg shokuin_02,22
bgcopy
csp -1
　この職員室からあそこまではかなり離れているし、@夜に音楽室に呼び出すと言うのも何とも不自然だ。@
br
　真っ暗な時間になっても校内にいれば、早く帰りなさいと言われるのがせいぜいだ。\

　ハメルンは、夜の音楽室でしか仕事をするつもりはない。@
br
　どうやって犠牲者を音楽室に……。@
　恐らく、職員室に篭り切りで日誌でも書いてるだろうあの無能教師を、どうやって音楽室に……。\

bg white,1
bg black,22

　しかし、僕は賢い。@
br
　……職員室に居るだろう無能教師を、@……ハメルンのポリシーとやらを破らずに、……如何にうさぎに変えてやるか。@それを閃く。\

bg shokuin_01,0
ld l,HIK_w1,0
ld r,HAM_Def2,22
ld r,HAM_Def5,80
quakey 2,200

　ハメルンにそれを話すと、彼は愉快そうに笑い声をあげた。\

ld r,HAM_Def4,80

「ははははは。@君は実に面白いことを思い付くね。@……なるほど、それならば、僕も力を貸さないわけには行かないようだ。@……やっぱり僕のパートナーに君を選んで正解だったよ。@ひかる君は本当に頭が良い。」\

ld l,HIK_w2,80

　それを聞いてひかるも満足そうに笑う。@
　そうだよ、僕は本当に頭が良いんだ。\

bg black,2

fede 0,2000
E_A







wait 2000

bg gakkou_01u,22

me1v 5,50

　放課後になった。@間もなく夕陽が沈む。@
br
　図書室が閉まるギリギリまで時間を潰したひかるは、まっすぐ職員室に向かった。\

bg rouka_01,22

　夜の学校は、昼とはまったく違って見える。@
br
　明るさとか雰囲気とかそんな程度の違いではなく、まるで建物ごと別の次元に迷い込んでしまったかのようだ。\

　そんな薄暗い廊下を、早足で歩いていく。@気持ちが急くのを抑えきれない…。@
　カツカツ、と反響する自分の足音を聞きながら、ひかるは思い出していた。@
br
　……命を奪うに相応しい、覚悟が自分にあるのかどうかを。\

bg black,22

『あなたは、殺す、ということを理解していないんだわ。』@
br
　それは、あの謎の、黒髪の少女の言葉だ。\

　僕は今夜、うさぎをまた一匹、殺す。@
br
　そして教師が一人、ハメルンの怪談に飲み込まれて、消える。\

　……僕が、ハメルンにあいつをうさぎに変えろと頼んだ。@
br
　それは、…………限りなく、あいつを殺せと言ったのと同じことだ。\

ld r,HIG_w4,22

『……自ら手を下す勇気のない子が、妖怪と怪談を免罪符に、@自分の手は汚れていないんだ…、などと言い出したりね？』\

　………………………。@
br
　僕が、臆病者だと言うのか。@
　殺すことの重みを、理解していないとでも言うのか。\

　あんたはこう言いたいのか。@
br
　ニンゲンがニンゲンの命を奪うなら。@……相応の覚悟や、背負うべきものが必要だと。\

bg black,0
mld l,HIK_W1,22

　僕は臆病者じゃない。@
br
　僕があいつらを、うさぎをいたぶるように殺すのは、@……あいつらが僕をニンゲン扱いしないのと同じにしたいからだ。@
　ニンゲンを殺しているという事実から逃げたくて、うさぎにして殺してるんじゃない。\

　ニンゲン扱いすらせずに、殺す。@
br
　それが僕なりの、……殺人すらも超えた、究極の復讐なんだ。\

mld l,HIK_W2a,22

　そう。@これは僕にとって、大きな意味のある行為なんだ。@
br
　……なるほど。@なら、その大きな意味に相応しい何かを、僕は心に留めるべきだろう。\

;bg black,22
;mono 2
bg Different_spiral_1a,22

me2v 17,70

　殺すということを、僕が理解していない、……だって？@
br
　じゃあ、理解してやるよ。@
　殺すということを、五感の全てで、実感して理解してやるよ。\

;bg Different_spiral_1b,22
mcl l,0
mld c,HIK_W3,23

　泣き声をあげることすら出来ないうさぎに変え、@……顔を踏みつける感触、耳を切り裂くハサミの震え、目玉を突き破る時のコンパスのあの手応え。@
br
　それら全てを実感して、理解してやる。@
br
　それが、僕が本気で“理不尽な悪意”を憎んでいることの、証。\

mcl c,0
bg black,22
;mono 0

se1v 82,100

bg white,64
bg shokuin_01,24

　………あるとも。@
br
　僕には、食らう資格がある。@
br
　僕は憎み、復讐するために、……殺す覚悟がある。\

bg black,22

E_A

「……くすくすくすくす。@本当にそうかしら？」@

bgm1 6

br
　不意に笑い声が聞こえた。@
　……あいつだ。@あの、……上級生の女の姿をした、……妖怪だ。\

bg shokuin_04,0
ld c,HIG_w3,2
ld c,HIG_def4,22

　彼女は、……職員室で僕を待ち構えていた。@
br
　肝心の井俣はいない。@どこかの見回りにでも行っているのだろうか。\

ld c,HIG_def2,80

「邪魔だからしばらく見回りに行ってもらったわ。@当分は戻って来ないわよ。@くすくすくす……。」@
br
　まるで心を読んだかのように言う。\

bg black,22
bg shokuin_02,0

ld r,HIK_Def4a,22

「君は、……一体何者なんだ。」@
br
　ようやく出た言葉は自分でも情けないほど震えていた。\

ld l,HIG_w4,22

「うふふふふ。@……そう言えばまだ名乗ってなかったわね。@でも、きっとあなたも聞いたことのある名前よ。@………くすくすくす。」\

bg black,24
bg shokuin_03,0
ld r,HAM_Def1,24
ld r,HAM_Def2,80

「これは、どういうつもりですか。@学校妖怪序列第３位の、踊る彼岸花先輩。」\

　背後からの声に振り返ると、そこにはいつの間にかハメルンが立っていた。\

ld r,HAM_Def1,80

「……これは私たちの狩り。@井俣先生は彼岸花さんの獲物ではないはずですが……？」@

ld l,HIG_Def2,23

「えぇ、そうね。@私の獲物じゃないわ。」\

ld r,HAM_Def2,80

「なら、何の御用でしょう？@　何しろ私は非力な妖怪。@学校妖怪八席はおろか、生徒たちにさえ未だ覚えられていない怪談の身ですから。@彼岸花先輩が、じきじきにお出でになられるような心当たりが何もありません。」\

ld l,HIG_Def5,80

「えぇ、まったく。@……あなた如き低級妖怪の狩りなんて、微塵も関心はないのだけれど。@………でも、少し派手にやり過ぎたわね。」\

ld r,HAM_Def3,80

「これは驚きましたよ。@……夜の闇をさらに濃く深く染め上げるのが、@学校の妖怪の務めだとばかり思っていましたのに。@派手にやり過ぎたと咎められるとは。」\

bg black,22

;ld l,HIG_w3,80

「そうよ。@それこそが私たちの唯一の務め。@………でも、私たちには私たちの不文律がある。@そして私にも私の不文律がある。@……新参者の妖怪の分際で、少しそれを蔑ろにし過ぎたわね…？」\

ld r,HAM_Def1,80

「……おやおや。@私たちの何があなたの逆鱗に触れたやら。@……新参者の分際で、派手にやり過ぎた、ということでしょうか。@ふっふふふふふ。」\

bg shokuin_02,22
ld r,HIG_Def4,22

「それよ。@………新参者の分際で、学校妖怪八席に対し、少し敬意が欠けたみたいね。」\

ld l,HAM_Def5,22

「はっ、……はっはっははははははははははは！！@　これは失礼しました、先輩っ。@……ですが、このハメルン。@こう見えても、ずいぶんと長いこと、敬意を示し大人しくさせていただいたつもりですよ。」\

ld r,HIG_Def2,80

「あら、そう……？」\

ld l,HAM_Def1,80

「身分も弁えずに申し上げて恐縮ですが。@……学校妖怪八席の皆様は、少々、お甘いのではないですか？」@

ld r,HIG_Def5,80

「甘い？@　私が？」\

ld l,HAM_Def2,80

「八席の皆様方がです。@私はずっとこの学校の夕闇に隠れ、皆さんの狩りを拝見させていただきました。@……その狩りの、何と慎ましやかで奥ゆかしくて情けないものかッ。」\

ld r,HIG_w4,80

「くすくす。@……なかなか言うわね、後輩さん…？」\

bg black,22
bg shokuin_04,22
quakey 2,200

「なぜに、学校を闇と恐怖で覆い尽さないのか？！@　皆様方にはそれだけの力が充分におありのはずだ！@　なのに、事故のふりをしたり病気のふりをしたり。@……皆様方の狩りの、あぁ何と慎ましやかなことか！！@　学校妖怪への畏怖と敬意はどこへ？！@　八つもの怪談がありながら、まったく子供たちに恐れられているとは思えない！！」\

;bg black,24
;bg shokuin_02,0
ld r,HIG_w3,22
ld r,HIG_w4,80

「…………………くす。」\

ld l,HAM_Def4,22
ld l,HAM_Def2,80


「ですから。@このハメルンが、学校妖怪と学校の夜の闇に再び畏怖を取り戻すため、立ち上がったのです。@……如何ですか？！@　たった一度の狩りで、もう学校中が恐怖に支配されている！@　そして今夜にも新たな犠牲者が増えるでしょう！@　いえいえ、まだまだ犠牲者は増えていく！@　ひかる君は憎しみの限りを尽くし、僕の音楽室に次々犠牲者を連れ込んでくれる！！」\

cl r,0
ld c,HIG_def5,24

「楽しい？@　妖怪ごっこは。」\
;＜彼岸花

bg black,24
bg shokuin_02,0
ld r,HIK_Def4a,24

me1v 16,50

「…………………っ。」\
;＜ひかる

ld c,HAM_Def5,22
;ld c,HAM_Def1,80

「数日を経ずに、この怪異は学校に止まらず、町全体を恐怖のどん底に叩き込むでしょう！@　そしてやがて、音楽室より聞こえるカスタネットの音が、@その恐怖に彩りを加え、『ハメルンのカスタネット』という新たな怪談を生み出すのです！」\

ld c,HAM_Def3,80

「如何です？@　教師がたった一人だけ犠牲になったような、トイレのめそめそさんなどという、ぱっとしない怪談より、@ずっとずっと素晴らしくて恐ろしい怪談でしょう？！」\

bg black,23
bg shokuin_03,0
ld r,HIG_Def5,23
ld r,HIG_w3,80

「………誰が唆したやら。@……毬枝を蹴落として、序列第８位を奪い取れる気でいるのね。」\

;ld l,HAM_Def4,23
ld l,HAM_Def5,26
quakey 1,100

me2v 17,70

「イエス、オフコースッ！！@　森谷毬枝を序列第８位に推薦しなかった妖怪たちが３人もいたことをお忘れなくっ。」\

ld r,HIG_Def2,80

「私たちのクラスで、@……毬枝より恐ろしい怪談が生まれたら、@毬枝と入れ替えて新しい第８位にしようという論調にしたがってる連中がいるわ。@……あなたは、その連中の中の誰かに招待されたわけね。この学校に。」\

bg black,23
bg shokuin_02,23
ld c,HAM_Def3,23
ld c,HAM_Def5,80

「森谷毬枝は学校妖怪に相応しくありませんッ。@だから私が、新しい第八の怪談となりましょう！！@　『音楽室のハメルン』！@　『ハメルンのカスタネット』！！@　ふっははははっはっはっは！！@　この新しき怪談が、八つの怪談の頂点に躍り出るのですッ！@　充分な狩りによって私は力を増し、やがて実力でめそめそさんを駆逐する！@　その時こそ、私は本当の第八の怪談となるのです！」\

ld r,HIK_Def4a,24
ld r,HIK_w3a,80

「……ハメルンは、……いや、……僕たちは、学校の新しい怪談になるんだ。@………僕たちの邪魔をするなら、@……例え、相手が妖怪だって、容赦はしない。@お前がどんな恐ろしい妖怪だったとしても、僕たちには敵わないんだ。@……ハメルンのカスタネットには、敵わない…！！」@
br
　ひかるは精一杯の強がりを吐き出す。\

bg black,23
bg shokuin_04,0
ld c,HIG_Def5,23
ld c,HIG_w4,80

「くす。」@
br
　それに、彼岸花は堪え切れなくなる。\

E_A

ld c,HIG_w6,80

se1v 84,70

quakey 1,100

「……くす、……くすくすくすくすくすくす…！！@/
bgm1 12
　うっふふふふふふっはっはははっはっはっはっはっはっは！！！」@
br
　上品な笑いは最初だけ。@最後の方には、職員室全体を振るわせるような、地獄の底からの笑いとなっていた。\

bg black,23
bg shokuin_03,0
ld l,HIK_n1,23
quakey 2,200

　初めてそれを聞くひかるは、今さらのように震え上がった。@
br
　それに打ち勝ちたくて、叫ぶ。\

cl l,0
ld c,HIK_i2,23
quakex 2,200

「……ハ、ハメルンッ…！！@　こいつをうさぎにしてしまえぇッ！！」\

ld r,HAM_Def4,23
ld r,HAM_Def6,80

se1v 2,100

quakey 1,100

「イエェーースッ！！！@　『ハメルンのッ、カスタネット』ォオオォッ！！！」\

se1v 85,70

mbg white,1
mcbg 22
wait 200

se2v 85,85

mbg white,1
mcbg 22
wait 200

se3v 85,100
se1v 66,100

bg white,28
bg black,22
bg shokuin_04,0
ld c,HIG_Def5,22
ld c,HIG_Def4,80

「ここは音楽室じゃなくってよ？@　くっすくすくすくすくすくすくす！！」\

me1v 28,70
me2v 3,70

bg e020,28
quakey 1,100
quakex 2,200

　彼岸花の笑いにその長い髪が暴れ散る。@
br
　彼女を中心に竜巻が湧き起こり、書類などを撒き散らして、まるで地獄の吹雪のような光景を見せた。\

bg black,24
bg shokuin_03,0
mld c,HAM_Def4,0
ld r,HIK_n1,24
ld r,HIK_i2,80

「ハメルンッ、何をやってる？！@　早くあいつをうさぎに……！@　………あッ…！！」\

se1 66

mcl c,0
bg white,24
bg black,22

　職員室中に螺旋を描いて舞い散る書類の吹雪が、@うねる真っ白な大蛇のように、ハメルンに襲い掛かり、……ぐるぐる巻きに拘束してしまう。\

　ハメルンはまるで、大量の書類で作られた、巨大な張子の虎のような姿にされていた……。@
br
　辛うじて首だけは覗かせているが、……首から下は完全に、大量の書類に拘束されてしまっている。\

bg black,23

「……う、ぐ、ぐ……。」@

;bg shokuin_02,0
;ld l,HIG_Def1,23
;ld l,HIG_Def1,80

「“音楽室のハメルン”を名乗る分際で、職員室でこの踊る彼岸花に喧嘩を…？@　くすくすくす、笑わせるわ。」\


bg black,24
bg shokuin_02,0
ld r,HIK_n1,24
;ld r,HIK_Def1,80
quakey 1,100

「ハ、ハメルン……！！」\

;bg black,23
;bg shokuin_04,0
ld l,HIG_def5,22
;ld c,HIG_Def5,80

「他人の心配より自分の心配をしたら…？@　二瓶ひかる君……？」@
br
　彼岸花の冷酷な瞳が、ひかるを射抜く。\

cl l,0
mld c,HIG_Def3,23

「……ハメルンをけしかけておいて、自分は蚊帳の外のつもりだったの？@　……ハメルンに私をうさぎに変えさせようとしたということは。@……あなたが、私を殺そうとしたのと同じことよ。@人を殺そうとするなら、……自分も殺される覚悟を持つことね。」\

;bg black,24
;bg shokuin_03,0
;ld r,HIK_i2,24
ld r,HIK_n1,80

「う、………わ、……………。@た、……助けて…………、」\

;bg black,23
;bg shokuin_02,0
mld c,HIG_Def5,80
;ld l,HIG_Def1,80

「そんな様じゃ、殺すということの意味を、まだ理解できていないようね。@………私の話を、ちゃんと聞いていた？@　殺すということの意味を。@……覚悟や、背負うものを。@あなたは考えることが出来た……？」\

mcl c,0
bg black,0
ld r,HIK_n1,22

;bg shokuin_03,0
;ld r,HIK_n1,22

me3v 17,70

　ゆっくりと、……ゆっくりと彼岸花が近付いてくる。@
br
　ひかるの足は、凍り付いて床に貼り付いてしまったかのよう。@
　真っ白な紙吹雪の旋風を纏いながら、一歩一歩近付いてくる妖怪を前に、尻餅すらつけない。\

;mbg white,28
;mcbg 22
;ld r,HIK_Def1,80
;ld l,HIG_Def3,2
ld l,HIG_w3,2

「……………………………。@そう。@……理解したつもりで、いるのね。」@
br
　彼岸花は、ひかるの心の声を完全に読み取っている。@
　ひかるが至った、彼なりの殺人の覚悟を読み取り、……せせら笑っている。\

bg Aka2,22
;ld r,HIK_Def1,80

me4v 16,70

　僕には、食らう資格がある。@

;ld r,HIK_Def1,80

　僕は憎み、復讐するために、……殺す覚悟がある。@
br
　その為に、殺すということを、五感の全てで、実感して理解してやるよ。\

;ld r,HIK_Def1,80

　……顔を踏みつける感触、耳を切り裂くハサミの震え、目玉に突き破る時のコンパスのあの手応え。@
br
　それら全てを実感して、理解してやる。\

ld c,HIG_w4,22


「それがあなたの覚悟？@　殺すということの理解？@　……………くすくす、うふふ、うっふふふふふふふふふふふふふふ！！@　何を実感したというの？@　……うさぎの皮を裂いた実感しか記憶に留めていないくせに。@……そんなあなたが、何を実感して、何を覚悟しているって言うの？@　くすくす、……くっすくすくすくすくすくすくすくすくすくすくすッ！！！」\

se1v 66,100

me5v 5,90

bg white,23
bg black,23

　彼女の笑いと旋風が、共に激しくなる。@
　そして、その旋風が爆ぜて、ひかるを飲み込んだ。@
br
　その瞬間、彼の世界は静寂の暗闇に包まれた。\

;ld c,HIG_Def1,2
;ld c,HIG_Def1,80

fede 0,1000
E_A

wait 2000

se1 38

bg e015,2

bgm1 13

　……あなたは人間を殺したのよ？@　本当にそれを理解できているのかしら？\

　目の前でしゃべっているはずなのに、彼岸花の声は、どこか、ものすごく遠くから聞こえてくるようだ。@
br
　そしてそれは恐ろしく静かで透明感に満ちた、電子音のような声に変わっていた。\

bg white,1
bg black,22

me1v 16,50

　肌が粟立ち、気持ちが戦慄する……。@
br
　不意にひかるは、自分の右手が何かを握っている気がした。\

bg aka3,1
quakey 2,200

　それは……、文房具。@
me2v 17,50
　ハサミ、コンパス、カッターナイフ。@
br
　それはうさぎたちを虐殺した、処刑道具。\

　ここにあるはずがない。@だって捨てたはずだ。@
　あの日、彼らを殺した後、血を洗い流し、コンビニのゴミ箱の中へ放り込んだ。@それなのに何故……。\

bg white,1
bg black,22


　その時、土の匂いを嗅いだ気がした。@それに混じる獣の臭い……。@
br
　え……ここって……。@
　ゆっくりと、……真っ暗だった世界が薄れていく……。\

fede 0,2000
E_A

bg white,8
lsp bgsp,":a;bmp\background\efe\red_waku.bmp",0,0
print 0
bg usagi_02,8
bgcopy
csp -1

me1v 5,50

　頬に感じる風。@外気。@……むわっとする獣の臭い。@
br
　辺りを見回して驚く。@そこはさっきまでいた職員室じゃなかった。@
　錆び付いた金網に取り囲まれたその場所は……、うさぎ小屋だった。\

　そんな…………、馬鹿な。@
br
　うさぎ小屋は立ち入り禁止のはずだ。@しかし、小屋の周りには貼られているはずのテープもない。\

　すると……、うさぎ小屋の隅に、何かの影が見えた。@
br
　一瞬うさぎかと思ったが、そうじゃない。@もっとずっとずっと大きな影。\

　…………え……？@　………ぅ、………うわ…………。\

E_A
quakey 1,100

bgm1 10

　薄闇に目を凝らしたひかるは、その正体に気付いて叫びそうになった。@
　それは、あの夜ひかるが殺したはずのクラスメートたちだった。\

ld r,HIG_Def3,2
ld r,HIG_w4,22

「くすくす。@あらあら、クラスメートたち、なんて括り方はいけないわ。@実感して、理解して殺すのが、あなたの決めた、殺人の覚悟なんでしょう？@　なら、一人ずつちゃんと思い出してあげなくちゃ。」@
br
　……ひかるはようやく気付きはじめる。@これから彼岸花が何をしようとしているのかを。\

ld r,HIG_w6,80

「……くすくすくすくす。@そうよ、これは過去の光景。@あなたが彼らを殺したあの夜の光景。@……だけど一つだけ違っているところがあるわ。@それは、これからあなたが虐殺する彼らが、うさぎじゃなくて、本当の姿をしているということよ。」\

bg black,29
lsp bgsp,":a;bmp\background\efe\red_waku.bmp",0,0
print 0
bg usagi_01,29
bgcopy
csp -1

me1v 5,50

　唐突にクラスメートたちの名前を思い出す。\

　田渕修、@槙島新一、@西藤庸介、@良島俊輔。\

　彼らは土の上に這いつくばり、許しを請うような目でジッとひかるを見上げていた。@
br
　その瞳は黒かった。@あの夜見たうさぎの赤い瞳ではなく、ひかると同じ黒い瞳をしていた。\

「さあ、実感なさい。@あなたが言ったんだわ。@くすくす。@五感で、実感するってね。」\













bg black,29
lsp bgsp,":a;bmp\background\efe\red_waku.bmp",0,0
print 0
bg usagi_02,29
bgcopy
csp -1

mbg white,1
mcbg 22

fede 1,2000
E_B

　ひかるの手が、自分の意思と無関係に、……コンパスを握り締める。@
br
　まるで、操り人形になったような気分。@自分の体なのに、何も抗えない。\

　当然だ。@何故ならこれは過去の光景だから。@既に起こってしまった光景だから。@ひかるの身体はそれを忠実に再現するだけ……。\

E_A

quakex 1,100

bgm1 16

　ひかるは、田渕修の顔を押さえつけた。@
br
　彼は教室では、タブチンというあだ名で呼ばれていた。@
　その彼の、懇願する眼差しの、ど真ん中に。@……眼球に深々とコンパスの針を突き立てる。\

bg white,25
bg "BMP\background\efe\red1.bmp",1
bg blood_2a,1
quakey 2,200

　凄まじい悲鳴が田渕修の喉から放たれる。@聞くもおぞましい、絶叫。@
br

quake 5,600

　しかしひかるには、耳を塞ぐことも許されない。@
　それが、殺人を実感するということ。\

　みんなが、タブチン、タブチンと呼び掛けるが、……当の本人は目を押さえて転げ回るだけだ。\

bg black,8
lsp bgsp,":a;bmp\background\efe\red_waku.bmp",0,0
print 0
bg usagi_02,22
bgcopy
csp -1



　次にひかるは、カッターナイフで西藤庸介の右手の指を切り落とそうとする。@
br
　あだ名はニシヤン。@女子にも友達の多いタイプだった。\


　……指をカッターナイフで切断しようとするのは、かなり骨の折れることだ。\

mbg black,25
mono 2
mcbg 25
quakey 1,100


　刃がぬめり、欠ける度にカチカチと刃を繰り出して、ようやく……、ぞりりと……切り落とす。@
br
　その、ぞりりという感触がそのまま、ひかるの背中を這い上がる……。\

　もちろん、あの晩のひかるは、指一本程度では満足しない。@……そのまま、他の指も……。@…………ぞり、………ぞりり………。\

quakex 2,200

　そして、良島俊輔を蹴り上げる。@踏みつける。@腹を、背中を、顔面を。@
br
　同じ名前のサッカー選手がいるとかで、サッカーが好きなヤツだった。\

quakey 2,200

　だから、サッカーボールのように扱ってやった。@
br
　全身が紫に変色しても、尚も踏みつける。\

quakex 2,200

　もはや虫の息になった良島俊輔の腹を何度も蹴り、踏む。@それを何度も何度も繰り返す。@やがて何かが潰れるような感触が足を通して伝わってきた。\

bg black,22
mono 0
bg blood_1aR,22
quakey 1,100

　腹を蹴飛ばす度に、……ごぷり、ごぷりと、口からどろりとしたものが溢れ出す…。\

bg black,28
lsp bgsp,":a;bmp\background\efe\red_waku.bmp",0,0
mono 2
bg usagi_01,22
bgcopy
csp -1

　槙島新一のあだ名は、シンイッちゃんだった。@
br
　そのシンイッちゃんの耳に、ハサミを当てる。\

quakey 1,100

　ぞぎ、………ぞぎぎ…り……。@
br
　もう一息というところまで切断したが、刃がこぼれてハサミは駄目になる。@だから、切れ掛かってぷらぷらしている耳をむんずと掴み、@/

quakex 1,100

……びりびりびちびちと引き千切ってやった。\

textoff
bg black,29
mono 0
lsp bgsp,":a;bmp\background\efe\red_waku.bmp",0,0
bg usagi_02,0
ld c,HIK_w2,22
ld c,HIK_w3,80
bgcopy
csp -1

me1v 5,70

　そして、……あの夜の僕は、笑うのだ。@
br
　血に染まったうさぎ小屋を見渡し、@……処刑はまだまだこれからだと、邪悪な笑みで、笑い転げるのだ………。\

bg black,2

　出来た？@　殺人の実感。\

bg white,23
bg shokuin_03,23

E_B

se1v 13,50

quakey 2,200

　その途端、ひかるは職員室の冷たい床に投げ出される。@紙吹雪の乱れ飛ぶ、ついさっきまでの職員室の床に。\

bg black,26
bg shokuin_04,26
quakex 2,200

bgm1 12

「ぎ、ゃあああぁああああああああぁああぁあああああああぁああぁぁぁッ！！！」\

　ひかるは床をのたうち回りながら、声の限りに叫んだ。\

quakey 1,100

　自分でもおかしくなるんじゃないかと思うくらい腹の底から絶叫した。@
br
　もはやひかるの精神はめちゃくちゃになりそうだった。@自分自身のしている行いの残虐さを悔い、獣のように声をあげ続けた。@やがてその声は謝罪へと変わる。\

bg black,24
bg shokuin_02,24
ld c,HIK_n2,26
ld c,HIK_n1,80


「ごめんなさいッ！！」@
br
　それが、殺したクラスメートたちに対してなのか、これから殺そうとしていた先生に対してなのか、@それとも虐待を続けてきたうさぎたちに対しての言葉なのか。@……ひかるは自分でも分からなかった。\

　それを言って何かが許されるとも思っていなかった。@だけど言いたかった。\

ld c,HIK_n2,80
quakey 1,100

「ごめんなさい！@　ごめんなさい！@　ごめんなさいぃッ！！！@　うぐぉ、……うげぇ、……うげええぇええええぇえええッ！！」\

cl c,25
quakey 1,100

　嗚咽はとうとう嘔吐にまでなる。@
br
　内臓を吐き出すかと思うほどに、……ひかるはビチビチと嘔吐を続ける。\

ld l,HIG_w3,22
ld l,HIG_w4,80


「くすくすくすくす。@随分と可愛らしくなっちゃって。@……でも悪いけれど、謝る相手が少し違うみたいね。@その程度じゃ、あなたの罪には、見合わない。」\

　彼岸花の形相は、なおも邪悪な笑みに歪む。@
　ひかるは、殺すという本当の覚悟がなかったことを、今こそ本当に思い知るのだ……。\

ld r,HAM_Def2,22
ld r,HAM_Def4,80

「……さすがは彼岸花先輩です。@僕の、可愛いパートナーを、こんなにもあっさり、壊してくれるなんて。」@

ld l,HIG_Def5,80

「くすくす。@こんな華奢で愚かな子が手駒だなんて笑えるわ。」\

ld r,HAM_Def3,80

「ひかる君は僕の妖力と波長の合う、僕の手足に相応しい子だったのに……。@彼ほどの駒になってくれる子を探すには、ずいぶんと骨を折りそうです。」\

ld l,HIG_w6,80

「それがお望み？@　なら、私があんたをこのまま、ぼきぼきに折って砕いてあげるわ。」@
br
　彼岸花は妖艶に笑い、拘束されたままのハメルンを睨む。\

se1v 11,50

mbg white,1
mcbg 22
quakex 1,100
cl r,0

se2v 12,50
se3v 20,50

mbg white,23
mcbg 23

　その時。@バリリと音がして、……ハメルンを拘束する書類の一部が千切れ飛ぶ。@
br
　彼の右腕が、拘束を破ったのだ。\

ld l,HIG_Def5,80

「あら、驚いたわ。@まさか腕一本とはいえ、私の拘束を逃れるなんて。」\

bg black,23
bg shokuin_04,23
ld c,HAM_Def2,26
ld c,HAM_Def4,80

「余裕ぶり過ぎましたね、先輩。@ぼきぼきと骨を折られるのは、あなたのようです。」@
br
　その手には、カスタネットが。\

se1 85

mbg white,1
mcbg 22
wait 100

se2v 85,85

mbg white,1
mcbg 22

　カチ。@/
se3v 85,100
……カチ、カチ、カチ、カチ！\

bg shokuin_04,22

ld r,HIG_Def2,24
;ld r,HIG_Def2,80

「…………何の真似？@　ここは職員室よ。@あんたのカスタネットは、音楽室じゃないと力を発揮しないんじゃないの？」\

ld l,HAM_Def4,26

「えぇ、そうです。@ですが今、私たちがいるこの部屋は、どこだと思います？！」@

ld r,HIG_Def5,80

「職員室でしょ。」\

ld l,HAM_Def6,80
quakey 2,200

「ふ、ふははははははははははは！！@　そう思うなら、表札をご覧になられてはどうです？！」\

bg black,23
bg shokuin_01,23

「………………………。@……くす。@くすくす、そんな冗談みたいなことで、あなたは力を発揮できるわけ？@　本当にいい加減な妖怪だわ。」@
br
　彼岸花は、職員室の引き戸の隙間から見える、表札を見て苦笑する。\

bg black,22

　そこには本来、「職員室」と書かれた表札が下がっているはずだ。@
br
　なのにそれが、どういうわけか、「音楽室」と書かれた表札に変わっているのだ。\

bg shokuin_04,0
mld c,HAM_Def2,26
mld c,HAM_Def4,80

「これはひかる君のアイデアでしてね。@……井俣先生を音楽室に誘き寄せるのが難しいなら、@職員室を音楽室にしてしまえばいいとね…！」@
br
　ひかるは職員室を訪れる時、音楽室より取り外した表札と入れ替えていたのだ。\

mld c,HAM_Def5,80

「よってッ、ここは音楽室です！@　僕のテリトリーです！！@　おなりなさいッ、僕の可愛いうさぎにねッ！！@　『ハメルンのッ、カスタネット』ォオォッ！！！」\

se1v 85,100

quakey 1,00

se2 66

mbg white,1
mcbg 22

se3v 66,100

mbg white,1
mcbg 22
mcl c,0

se1v 85,100

bg "BMP\background\efe\red1.bmp",28

bg black,23
bg shokuin_02,0
ld c,HIG_Def5,23
bg "BMP\background\efe\red1.bmp",28
bg black,28
bg shokuin_02,0
ld c,HIG_w5,22

se2v 85,100
se3v 56,50

cl c,5

　カチカチ、カチカチ、カチカチカチカチッ！！@
br
　呪いのカスタネットの魔力が、彼岸花を凝縮する。\

;cl c,45

se1v 56,50

mbg white,25
mbg black,25

　まるで背丈が縮む薬を飲んだアリスのように、……彼岸花の体がみるみる縮んでいく。@
br
　やがて、その姿は、彼女と同じ赤い目をしたうさぎに変わり果ててしまう……。\

mbg white,22
mcbg 22
quakey 1,100

　それと同時にハメルンの拘束は解け、書類の束がバサバサと崩れ落ちる。\

ld c,HAM_Def3,22
;ld c,HAM_Def1,80

　ハメルンは自由になった両腕をぶらぶらと振ると、@うさぎになった彼岸花を軽々と片手で掴み上げる。\

ld c,HAM_Def4,80

「こうなってしまっては、序列第３位の踊る彼岸花先輩も形無しですね。@……いつの間にかここが、音楽室になってしまっていたことに気付かなかったことが、@あなたの敗因です。」\

;ld c,HAM_Def1,80

　掴み上げるその耳を、ぎゅうっと、さらに強く握り締める。@
br
　そして、未だに這いつくばって、嘔吐物に塗れているひかるを見て、小さく舌打ちする。\

ld c,HAM_Def3,80

「やれやれ。@……せっかく扱いやすい人間を見つけたってのに。@……あそこまで完璧に壊されたら捨てるしかないよなぁ。@……ごめんねー、ひかるくーん。@くっくくくくくくくくく…！」\

　その言葉はひかるの耳には届かない。@
br
　ひかるは頭の中まで嘔吐物でいっぱいになったかのような吐き気の中で、@……誰でもいいから自分を殺してくれと願っていた…。\

ld c,HAM_Def2,80

「いいとも。@君の要望には極力応えてあげることにするよ。@……結果的には感謝してるしね。@君の働きがなければ、踊る彼岸花先輩を倒すことは出来なかったのだから。@……お陰でこうして、序列第３位の座を手に入れることが出来たんだ。」@
br
　ハメルンは、ますますに邪悪な笑いを浮かべながら、うさぎの彼岸花を高く掲げる。\

bg black,26
bg shokuin_04,22

「このままうさぎ小屋に放ってしまおうかとも思ったけれど、何しろ彼岸花先輩のこと。@いつ妖力を取り戻して、元の姿を取り戻されるかわかったものじゃありませんからね。@……手も足も出ない、このみすぼらしい姿の内に、@しっかりトドメを刺させていただきましょう。」\

ld r,HAM_Def5,26

「……僕はひかる君のように残酷ではありませんよ。@ただ一口に。@べろりとあなたを飲み込んで胃袋に放り込んでしまうだけです。」\

　……高く掲げたうさぎの彼岸花を見上げ、@……ハメルンの口が、ぎょぷりと裂けて、頭でさえ易々と飲み込んでしまうような大口となる。\

bg black,22

『…………手も足も出せない？@　この踊る彼岸花が…？』\

;bg shokuin_03,0
ld c,HAM_Def2,22
ld c,HAM_Def4,80

「おや。@うさぎに変えられてもしゃべることが出来るとは。@ふっふふふふふふ、驚きです。@ですが、それ以上の何も、あなたには出来ませんがね。」\

『そうね。@動かせるのはせいぜい、この口だけ。』\

ld c,HAM_Def2,80

「ならばせめて。@その口で断末魔くらい聞かせて下さい。@……それではご機嫌よう、彼岸花先輩。」\

bg black,22

『ご機嫌よう？@　……もう勝ったつもりでいるの？@　あなた程度、口だけ動かせれば充分よ。』\


　ハメルンは、その手を開く。@
br
　うさぎは、……眼下に開くハメルンの大口へ真っ逆さま……。\

se3 66

bg white,25

fede 0,2000
E_A

se1v 38,100

bg "BMP\background\efe\red1.bmp",1
quakey 2,200
bg shokuin_04,22

bgm1 21

「ひぎゃッ、…ああぁああああぁあああッああああッあああぁあああッ！！！」\

　その悲鳴が一体誰のものなのか、一瞬分からなかった。@
　彼岸花の断末魔でないことだけは、確かだった。\

;bg black,24
bg blood_1aR,24
se1 38
quakex 2,100

　一条の鮮血が、職員室の壁を走る。@
br
　それは異様な光景だった。@
　大口を開けて、うさぎの彼岸花を飲み込もうとするハメルンが、@………両目を見開いて、呻き声をあげながら、痙攣しているのだ。\

quakey 2,200
quakex 3,300
quakey 2,200

bg black,22

mono 2

bg white,1
bg shokuin_02,22

se1v 38,100

quakey 1,100

me1v 16,50

　その口から、うさぎが飛び出す。@……何かを咥えて、引きずり出して。@
br
　それは、………ハメルンの舌だった。@
br
　鮮血に塗れたうさぎの彼岸花が、……ハメルンの舌に噛み付き、……引きずり出したのだ。\

　もっとも、舌と呼ぶべきは、彼岸花が噛み付いている上端部分のわずかだけ。@……それより先は、……不気味にのたうつ、ハメルンの内臓なのだ。@
br
　ハメルンは彼岸花に、……舌ごと、……内臓ごと、ずるりと引きずり出されたのだ。\

mbg "BMP\background\efe\aka1.bmp",1
mcbg 22
se1 38
quakey 2,200

me2v 17,70

「ぉごおぉおおおおっぉおおぉ…ぉおお……ぉぉぉ……！！！！」@
br
　ハメルンは白目を剥きながら、びくびくと全身を震わせる。\

bg black,23

mono 0

『……毬枝を追い落として第８位になると言ってみたり、私を倒して第３位になると言ってみたり。@くすくす、うふふふふふ、それだけの大口を叩くだけあって、実に立派な舌だわ。@くすくすくすくすくすくす…！！』\

bg shokuin_04,22
se1 38
quakey 1,100


「ご……くく……ごごご……ごっ、……ぉお………！！！」\

『最後に教えてご覧なさい。@あんたをこの学校に呼び寄せたのは誰……？@　毬枝は私の大切なオトモダチなのよ…？@　それを追い払おうとするなんて、許せないヤツだわ。@……そいつの名を教えてご覧なさい…？@　……………………。@……あぁ、無理よね。@こんなにも舌も内臓も引きずり出されちゃ、返事も満足に出来ないわね。』\

se2 38

quakey 2,200

「んごごごッ、………こ…ぉおぉ……ッッッ……！！！」\

bg black,22

『さようなら、ハメルン。@あんたの怪談なんて、……この学校に残させてやらない。@くす、くすくすくすくすくすくす、あっははははははははははははははははははははは！！！』\

se3v 84,100

bg white,1
bg aka3,22
quakex 2,200
quakey 2,200

　ごきゅり、ぶちぶちぶちぶちッ…、………ブチィッ！！\

se1 36

bg blood_1aR,1
quakey 3,300

bg black,2
bg shokuin_03,22

wait 2000

ld l,HIG_w4,46

　机の影で、……不気味な音と共に鮮血が飛び散る。@
br
　……そこから、彼岸花がゆっくりと立ち上がり、姿を見せる。@
　それは元の西洋人形のような姿。@……そして、ハメルンの姿はもう、どこにもなかった。\

ld l,HIG_Def2,80

「お生憎様。@……うさぎって、食欲もすごく旺盛なの。@……知らなかった？」@
br
　悠然と笑う彼岸花は、未だに床を這いつくばるひかるを見る。\

「……ぁ、………ぅ……………。」\

ld l,HIG_w3,80

「あなたの顔。@悪夢に怯えて目を覚ました寝ぼすけみたいだわ。@………でもね。@本当の悪夢は、これからじゃないかしら。@……私は踊る彼岸花。@学校妖怪八席の中でも、……特に残酷な妖怪なのよ…？@　あなたをそのまま見逃して、私が立ち去るとでも思ったかしら……？」\

ld r,HIK_n1,26
ld r,HIK_n2,80
quakex 1,100

「ひ、……ひぃ………！！@　こ、……これ以上、………ぼ、……僕に……、な、何を………！」\

ld l,HIG_Def5,80

「人を殺すということを、まさか、あれっぽっちで全て実感できたと思っているの…？@　あなたが実感したのは、ニンゲン側だけじゃない。」\

ld r,HIK_n1,80

「それって、……どういう…………。@……………ッ？！@　そ、……それ…は…………、」\

se1v 85,100

mbg white,1
mcbg 22

　カチ。@
br
　それは、ハメルンが持っていた、カスタネット。@今は彼岸花の手に……。\

cl l,0
ld c,HIG_Def3,23

「どうしたの？@　何を怯えているの？@　これは、音楽室で鳴らさないと意味がないんでしょう…？@　あぁ、でも今はこの職員室、音楽室なんだったっけね。@くすくすくすくす……！」@
br

se2 85

mbg white,1
mcbg 22

se3v 85,100

mbg white,1
mcbg 22

　カチ。@カチ、カチ、カチ、カチ…！\

se1v 56,50

mbg "BMP\background\efe\red1.bmp",28
mcbg 28

ld r,HIK_n2,80

　彼岸花が何を企んでいるのかを理解し、@ひかるは、先ほどの悪夢など、まだまだ序の口であったことを理解する。\

　ひかるは、ニンゲンとして殺すことしか、まだ実感していない。@
br
　うさぎとして、……殺されることを、まだ実感していない…！\

ld c,HIG_Def4,80

「安心なさい。@あんたの魂は私の好みじゃないの。@だから命は奪わない。@だから、殺されることを実感はさせないわ。@……あなたに実感させるのは、いじめられる、ということよ。」\

se1v 56,50
se2 66

cl r,5
bg black,26
bg shokuin_04,6


　そう語る彼岸花の姿が、見上げるほどの大きなものになっていく。\

　机はみるみる巨大になり、……まるで巨大な建物のようだ。\
bg black,26
bg shokuin_02,0
ld c,HIG_Def3,26

　彼岸花は、うさぎのひかるを、ひょいと掴み上げる。@
　そして、職員室の隅へと連れて行く。@
br
　そこには、うさぎ小屋から移された、生き残りのうさぎたちのダンボールでできた住処があった。\

ld c,HIG_Def5,80

「あなたはうさぎをいじめることを、たくさん実感したわ。@……なら今度は、その逆を実感するのはどうかしら。」\

『………や、……やめて……、ゆ、許して…………！！』\

ld c,HIG_Def3,80

「それを許さないから、私は飛びきり残酷な妖怪なのよ。@…………でも、いいわ。@……特別に、一度だけチャンスをあげる。」@
br
　掴み上げたうさぎのひかるを、本物のうさぎたちの群の上に高々と掲げる。\

『チャ、……チャンス………。』@

ld c,HIG_w3,80

「そうよ。@チャンス。」\

『そ、それは何です…？！』@

cl c,0
ld r,HIG_Def2,23

「謝りなさい。」@

『……ご、ごめんなさいッ、ごめんなさいッ！！』\

ld r,HIG_Def5,80

「それは、誰に向かって何を謝ったの？」@

『そ、それは、……彼岸花さんに、その……ッ、……あッ！！』\

E_MA

mbg white,1
mcbg 22

se1v 13,50

quakey 1,100

　彼岸花は掴んでいた手を放し、……うさぎのひかるを、うさぎたちの群に落とした。\

cl r,0
ld c,HIG_w4,24
;ld c,HIG_w4,80

「ハズレ。@………じゃあね、さようなら。@二瓶ひかる君。@これであなたは大好きなうさぎ小屋で、死ぬまで過ごせるわね。@……どこの動物園に送られるか知らないけど、@意地悪な飼育係に当たらないといいわね。@くすくすくすくすくすくすくすくす…！」\

se1v 84,100

bg black,22
bg shokuin_04,22
quakey 2,200

『ま、……待って………、待って………！！』@
br
　ひかるはダンボールの柵を出ようと足掻くが、今のうさぎの身体では、それは到底、叶わない。\

　待って、………待って……ッ！！@　………………！！！@
br
　次第にひかるの言葉も失われていく。\

　うさぎは、鳴けない。@人の言葉など、しゃべれるわけもない。@
br
　それでも必死に彼岸花に、待って待ってと叫び続ける。\

bg black,22
;wait 1000
bg e006,2

me1v 28,70

　……するとその時、自分を見つめる、いくつもの視線に気が付いた…。@
br
　視線の主は、…………………うさぎたちだった。\

　ひかるが虐待し続けてきたうさぎたち。@
br
　彼らは身動き一つせず、その無数の赤い瞳を、ひかるに向けていた。\

me2v 16,70

　…………な、何なんだよ、こいつら……？！@
br
　やがて、うさぎたちはゆっくりとひかるに歩み寄ってくる。@
　取り囲むように、ゆっくりと、ゆっくりと……。\

　ひかるは後ずさろうとするが、ダンボールの隅に追い詰められている。@
br
　………こ、…こいつら一体何をする気だ……？！@
　その問いに、彼岸花は答えてくれた。\

bg black,23
bg shokuin_03,0
ld c,HIG_Def5,6
ld c,HIG_w3,80

「くすくすくすくす。@………みんな歓迎しているのよ。@……あなたみたいな可愛い子が入ってきて、興奮してるみたい。」\

　……こ、……興奮って………？\

ld c,HIG_Def3,80

「知ってる？@　うさぎってね。@………同性同士でも、交尾をするんですって。」\

bg black,22

　……そ、…………そん…な…………。@
br
　ひかるの大きくなった耳に、うさぎたちの荒く熱っぽい息が吹きかかる。@
　ひかるは、真っ赤な目を見開いて凍りつく……。\

ld c,HIG_w6,22

「くすくすくすくすくす。@……うさぎって、性欲がすごく強いって聞くんだけれど。@……本当かしらね…。@……くす、………くすくすくすくすくすくすくすくすくすくす！！」\

cl c,2

　軽やかな笑い声と共に、彼岸花は廊下の闇の中へと消えていった……。\

se1v 82,100

bg white,63
bg black,23

　開け放たれていた職員室の扉がひとりでに閉まる。@
br
　その音と同時に、うさぎたちが一斉にひかるに飛びかかった……。\

bg e006,22
bg e007,22

se1v 66,100

bg "BMP\background\efe\red1.bmp",8
quakey 3,300

me3v 3,70

　…………！@　………………ッ！！！\

　うさぎは鳴けない。@
　悲鳴をあげることさえできない。@
br
　だから、ひかるは好んでいじめてたんじゃないか。\

bg black,2
fede 0,2000
E_A













bg rouka_01,2

me1v 16,50

wait 2000

bg black,22
bg okujou_01y,22


　すっかり夜の闇に包まれた学校は、@まるで生きてる者は誰もいないかのような沈黙に支配されているのだった………。\

;ld c,HIG_w3,2

　彼岸花の姿は、大きな月を眺めることの出来る屋上にあった。\

ld c,HIG_Def5,2

「誰に謝れば許してあげたかって…？」@
br
　誰に問われたわけでもないのに、彼岸花はそう呟く。\

ld c,HIG_Def4,80

「………さぁね。@地獄で考えてみたら？@　あなたのせいで、私は服を涙と鼻水でぐしゃぐしゃにされたんだから。」\

cl c,2

　彼岸花は笑う。@
br
　月は酷薄なまでに白い。@
　温かみなどなく、ただただ寒々しいだけだった……。\


;bg black,42

bg e022,42
wait 1000
bg black,42
bgcopy ;背景をリセット

fede 0,2000
E_A
wait 2000


;＜おしまい＞




if %UMINEKOEND < 5 mov %UMINEKOEND,5 : mov %END_FLG,5 ;クリアフラグの変更
	saveoff            ;セーブオフで、処理を高速化する。
	erasetextwindow 0  ;テキストエフェクトを切る事で処理を高速化
	rmode 0            ;右クリックのメニュー表示の無効化
	textoff


goto *b_title
;reset

*higan7_opning
texton
csp -1

bg black,2
bgcopy ;背景をリセット

setwindow 31,16,22,16,26,26,0,2,20,1,1,#999999,0,0,639,479

!sd

mono 0
E_A

;スミレ衣装フラグ
mov %smi_Isyou,1

me1v 16,50

wait 2000
