;Chapter 3
;　扉を開けると、いつもの様にクラスメート全員が私を振り返った。\
`　As I opened the door, everyone in the class turned around to look at me as usual.`\

mld c,MID_def1,22

;「おはよう、みんな。」@
`"Good morning everyone."`@
br
;　私が挨拶すると、みんなも一番の笑顔の挨拶で返してくれる。\
`　And with my greeting I was met with everyone's wide smiles.`\

;　私を迎える感情は、敬愛、尊敬。@そして、憧れ。@
`　They showed feelings of affection, respect, `@`and desire.`@
br
;　毎朝、教室に入るこの瞬間、@自覚してはいけないのだけれど、私は優越感に包まれるのだ。\
`　From the moment I step through that classroom door, `@`although I might not be aware of it, every morning I'm enveloped with a sense of superiority.`\

;「おはよう、みどり。」@
`"Good morning Midori."`@

mld c,MID_def3,80

;「おはよう。」\
`"Good morning."`\

;「おはよう、みどり姫っ。」@
`"Good morning, Princess Midori~"`@

mld c,MID_def1,80

;「おはよう。@くす、姫はやめてね。」@
`"Good morning. `@`Hehe, stop with the 'princess' alright?"`@
br
;　でも、みんなは私のことを敬愛を込めて“姫”と呼ぶ。\
`　Everyone lovingly refers to me as 'Princess.'`\

;　そう呼ばれると、みんなとは身分が違うみたいな気持ちになって、@ちょっぴりの疎外感を覚えてしまう。@
`　When they call me that, it makes me feel different than the rest, `@`and just a tad alienated.`@
br
;　でも、みんなが温かにそう呼んでくれるのは、決して悪い気持ちのするものではない。@だから、恥ずかしがりながらも、その呼び名を受け入れている。\
`　But it's not like anyone has any ill will in warmly referring to me as that. `@`So even though it's a bit embarassing to admit it, I'm starting to accept being called that.`\

bg black,22

;　彼女の名は楠木みどり（くすのき　みどり）。@
`　This girl's name is Kusunoki Midori　（楠木みどり）.`@
br
;　クラスメートたちが姫の愛称で呼んで敬愛する、このクラスのお姫様だった。\
`　Her classmates have lovingly given her the pet name princess. She was the princess of this class.`\

mcl c,0
bg black,22
bg kyou_02,22

;「おはよう、姫。」@
`"Good morning princess."`@
br
;　隣の席のサキエが挨拶をしてくる。@何気なく声を掛けたつもりだろうが、その声は少し緊張しているようだ。\
`　Sakie from the seat next to me was greeting me. `@`She might have intended to express a calm voice, but her voice seemed a bit nervous.`\

ld r,MID_Def1,24

;「あぁ、おはよう。サキエ。」@
`"Oh, good morning Sakie."`@
br
;　名前を呼ばれ、サキエの顔がパッと明るくなる。@
`　After I called her name, Sakie's face suddenly brightened up.`@
;　私は気さくに接しているつもりだけれど、友人たちは少し畏まり過ぎているのだ。\
`　I intended to be really casual, but my friends were being far too humble.`\

;「今朝も素敵なお洋服ね。@みどりって本当にセンスいいっ。」@
`"I see you have a lovely dress this morning as well. `@`Midori, you have some real fashion sense."`@

ld r,MID_Def5,80

;「くす、ありがとう。@ママにおねだりして、やっと買ってもらったお気に入りなの。@……良かったら、今度、譲ってあげるね。」\
`"Hehe, thank you. `@`I begged mom for it. When she bought it for me it became my favorite. `@`...If you want, I'll let you have it next time."`\

;「ほ、本当っ？@　う、嬉しいけど、わ、悪いよっ。」@
`"R- Really~? `@`I- I'd be happy but... I- I can't do that."`@

ld r,MID_Def3,80

;「うぅん。@素敵って褒めてくれたサキエに着てもらったら、この服もきっと喜ぶと思うよ。」\
`"No no. `@`I think even this dress that you complimented as 'lovely' would be happy if I let you wear it, Sakie."`\

;「ち、違うのっ。@それは姫が着てるからこそ素敵なんだよっ。@私なんかが着ても、ダメダメダメ…！！」\
`"T- That's not it~. `@`It's lovely because a princess is wearing it~! `@`For someone like me to wear something like that... I can't do it, I can't~!!"`\

bg black,22

;　サキエは慌てて固辞する。@
`　Sakie politely and nervously declines.`@ 
br
;　みどりは裕福な家の子だった。@だから、綺麗なお洋服などたくさん持っているのだ。@
`　Midori was a child from a wealthy household. `@`So she had lots of beautiful Western-style dresses.`@
br
;　しかし、姫のお召し物をもらえるなんて、とても嬉しいことだけれど、逆に畏れ多くて。@サキエにはとてももらえない。\
`　Although receiving the princess' clothes and the like might have made Sakie really happy, but it also filled her with anxiety. `@`Sakie really couldn't take her clothes.`\

bg kyou_01,22
ld c,MID_Def1,24

;「長袖だと今の季節にはもう暑いかな。@……私は肌がすぐ焼けちゃうから、夏でも長袖じゃないと駄目なんだけどね。」\
`"Maybe these long sleeves are a bit too long for this season. `@`...But even in the summer I have to wear long sleeves or else my skin will get sunburned real quick."`\

;「みどり姫の白磁の肌は、袖で大切に守らなくちゃねっ。」@
`"With your procelein white skin, you have to be keep those sleeves in mind Princess Midori."`@

ld c,MID_Def5,80

;「ありがとう。@でも、サキエの肌だって綺麗だよ。」\
`"Thank you. `@`But Sakie, your skin is also fair."`\

;「そ、そんなっ。@ご謙遜をご謙遜をッ。@……あ、あーそのッ、こ、国語の宿題、やって来た？！」@
`"N- No way. `@`You're too nice, too nice~ `@`...Um, Ohh. Did you do your Japanese homework?!"`@
br
;　みどりに肌を綺麗だと褒められてよほど浮かれたのか、サキエは真っ赤になって慌てる。@そして何の脈絡もなく、国語の宿題の話を切り出してしまった。\
`　It might have been because Midori had complimented how fair her skin was, and so Sakie turned bright red. `@`And so without any rhyme or reason, she changed the topic to Japanese homework.`\

bg black,22
bg kyou_03,22

;ld c,MID_Def1,24

;「……国語の宿題？@　……いけない。@あれって今日までだったのね…。@昨夜は遅くまで台詞を覚えていたから、すっかり忘れてしまってて……。」\
`"...Japanese homework? `@`...Oh no. `@`That was due today...? `@`I was memorizing my lines late last night, so I completely forgot about the homework..."`\

;「あ！@　じゃあ、良かったら私の写して！」@
`"Ah! `@`Then if you'd like, you can copy mine!"`@

;ld c,MID_Def1,80

;「いいの？」\
`"Can I?"`\

;「姫は演劇の台詞覚えたりで大変なんだしっ。@お隣なんだからこれくらいさせてよっ。」@
`"It must be hard for you to memorize those stage lines. `@`I'll let you copy it 'cause it's the neighborly thing to do ."`@
br
;　サキエは自分のノートを開いて、まるで賞状授与みたいに畏まって差し出す。\
`　Sakie opened her own notebook, and then she respectfully handed it over as if it was a diploma.`\ 

bg kyou_02,0
ld l,MID_Def5,22
ld l,MID_Def3,80

;「ありがとう。@……私、サキエが友達でいてくれて本当に嬉しいよ。」@
`"Thank you. `@`...I'm really happy we're friends, Sakie."`@
;「……そっ、そんな！@　お、ぉ、大袈裟だよっ、このくらいで…！！」\
`"...O- Oh no! `@`T- This is all t- too much~!!"`\

;　サキエは耳まで真っ赤にして照れ笑いする。@
`　Even Sakie's ears turned bright red as she grinned in embarassment.`@
br
;　みどり姫に“友達”と呼んでもらえるほどの名誉は、このクラスには存在しないのだから。\
`　After all, no one in this class had the honor of being called Princess Midori's 'friend.'

se1v 82,100

bg white,24
bg kyou_01,24

;「おはよ、みどり！」@
`"Good morning Midori!"`@
br
;　遅刻ぎりぎりでやって来たのはフミエだった。@
`　Fumie finally showed up just before class was about to start.`@
;　彼女もサキエと同じ、みどり姫の取り巻きの一人だ。\
`　Just like Sakie, Fumie was also one of Princess Midori's followers.`\

;「ねぇねぇ、今月号の『シーキャット』見た？」@
`"Hey, did you see this month's issue of 'Sea Cats'?"`@
;「うん。すごかったね。@急展開って感じで。」\
`"Yep. It was awesome, right? `@`I felt it was a dramatic development."`\

;　『シーキャット』は今、このクラスで人気のある連載漫画だ。@かなりダークな描写があるので、親達や学校には問題視されているが、@クラスの子の大半は隠れて読んでいる。@
`　`Sea cats` is a popular serial manga in this class. `@`It's pretty dark themes are seen as a bit of a problem by the parents and the school, `@`however the majority of students in this class are secretly reading it.`@
br
;　もちろんみどりもファンの一人で、毎月号欠かさず雑誌を買っている。\
`　Of course, as one of those fans, Midori doesn't miss an issue and buys it every month.`\

;「来月からアニメもスタートだしねっ。@すっごい楽しみ！」@
`"It seems like there's gonna be an anime starting next month too. `@`I'm soo excited!"`@

ld c,MID_Def1,22

;「へぇ、本当なの？@　知らなかった。」\
`"Ohh, is that true? `@`I didn't know."`\

;「えーッ、みどり、知らなかったのー？！」@
`"Whaaat? Midori, you didn't know~?!"`@
br
;　フミエは素っ頓狂な声をあげて、驚き喜ぶ。\
`　Fumie shouted hysterically in astonishment and delight.`\

;　喜ぶ、とは、みどり姫に初耳の情報を提供できたことを喜んでいるのだ。@
`　That delight was in regards that she had new gossip to offer Princess Midori.`@
br
;　でも、これは実はみどりのサービス。@
`　But this was a service from Midori.`@
;　本当はアニメ化されることはもう、本で読んで知ってる。@初耳を装ってあげたら、フミエが喜んでくれるかなと思って、そう言ったのだ。\
`　Truthfully she had already read that an anime version was being made. `@`By pretending that she hadn't heard about it before, she was letting Fumie feel happy.`\

;　彼女も、ただちやほやされてるわけではない。@自分に好意を寄せてくれる人たちに、少しでも喜んでもらおうと、@ささやかな気遣いを忘れないようにしている。\
`　(?) It wasn't as if she was just be favored by them. `@`By spreading a bit of good will to those around her, `@`she was being modestly considerate of others.`\

;　フミエは嬉しそうに、聞いてもないアニメ化情報を次々に説明し出す。@
`　Fumie was happily giving explaination after explaination about the anime version they hadn't heard about.`@
br
;　主要キャラクターの声優から、制作会社がどこだの、監督は誰だの。@……みどりにそれを話せるのが、よほど嬉しいか光栄なのだろう。\
`　From who the main character voice actors were, to what studio was in charge of it, and who was directing it. `@`...Fumie might have been happy - perhaps even honored to talk to Midori like that.`\

ld c,MID_Def5,80

;「ふうん、すごいね。@……でも、演劇部のお稽古が始まっちゃったら、@毎週見るのは難しいかもしれないな…。」\
`"Hmmm, that's neat. `@`...But since it starts after drama club practice, `@`watching it every week would be hard to do...`"\

;「放送されるの結構遅い時間みたいだよ？@　あ、でも、もし見れない時は言ってね！@　私、録画しといてあげるから！」@
`"It's on pretty late at night isn't it? `@`Oh, but just say if you can't watch it okay?! `@`I'll... record it for you!"`@

ld c,MID_Def3,80

;「ありがとう、フミエ。@あなたがお友達で、本当に嬉しいよ。」\
`"Thank you Fumie. `@`I'm truly happy you're my friend."`\

;「とッ、当然でしょ！！@　と、友達だもんね、あはははははは！！」@
`"O- Of course!! `@`W- We're friends after all, right? Ahahahahaha!!"`@
br
;　フミエもまた、サキエと同じように真っ赤になって舞い上がる。@
`　Fumie blushed just like Sakie.`@
;　みどりに感謝の言葉をもらえて舞い上がらない子など、このクラスには存在しないのだから。\
`　Because no other blushing girl in this class had ever received words of gratitude from Midori.`\

;　楠木みどり。@クラス中の女子の誰もが憧れる、姫と呼ばれる少女。@
`　Kusunoki Midori. `@`The girl called princess who every girl in the class yearned after.`@
br
;　彼女は何の不足もなく、満ち足りた学校生活を送っていた……。\
`　Without any insecurities, she lived a completely satisfying school life...`\

bg black,22

me1v 24,50
fede 1,2000
E_B













bg kyou_03,22

;「…………ねえ、姫。@あいつ、またこっち見てるよ…。」@
`"......Hey, Princess. `@`That girl, she's looking over here again..."`@
br
;　ノートを写させてもらっている私に、サキエが囁く。\
`　Sakie, who was letting me copy her paper, whispered to me.`\

;　あいつって？@　私は、サキエが不愉快に睨む教室後方に目を向ける。\
`　That girl? `@`I followed Sakie's uncomfortably glare towards the back of the classroom.`\




bg black,24

fede 0,1000
E_A

bg kyou_02,24

bgm1 8

;　すると、サキエの言う通り、@川田のぞみがこちらの様子をじっとうかがっているのがわかった。\
`　Just as Sakie had said, `@`I noticed Kawada Nozomi was staring over this way.`\

;「……マジであの子、嫌な感じだよね。@いっつもジーッと姫のこと見ててさー。」@
`"...Seriously, I have a bad feeling about that girl. `@`She's allllways staring at the princess."`@
;「みどりのこと妬んでんだよ。@前のクラスではあいつも、お姫様気取りだったらしいし。」@
`"She's just jealous of Midori. `@`In her last class, it seems she was treated like a princess."`@
br
;　サキエとフミエは顔をしかめて囁きあう。\
`　Sakie and Fumie scowled and whispered.`\

mbg black,22

;　川田のぞみも、裕福な家の子らしい。@
`　It seemed Kawada Nozomi was also a child of a wealthy household.
br
;　しかし、みどりとはまったく正反対の扱いを受けていた。\
`　However she was receiving the exact opposite treatment that Midori was.`\

;　のぞみは家が裕福であることを鼻にかけ、威張っていた。@
`　Nozomi took pride in her family's wealth and flaunted it.`@
br
;　しかしみどりは、威張ったりなどせず、誰にでもやさしかった。\
`　But Midori wasn't boastful, and she was kind to everyone.`\

;　当然の結果として、みどりは姫と呼ばれて誰からも慕われた。@
`　As a natural result, Midori was called princess and adored by everyone.`@
br
;　そして逆にのぞみは、@今ではクラスの女子のほとんどから無視され、あるいはいじめられている……。\
`　Conversely, `@`now Nozomi was almost completely ignored by the girls in class, or rather was being bullied...`\

mcbg 22

;　去年のクラスでは、金持ち自慢で姫と祭り上げられて、ちやほやされていたらしい。@
`　In last year's class, it seems she was pampered and set up as the pridefully rich princess.`@
br
;　それが今年は正反対の扱いで、かつて自分が座っていた姫の座にはみどりが座っていて。\
`　This year with the complete opposite treatment, the seat she once occupied as princess now belonged to Midori.`\

;　きっと、妬ましくて妬ましくて仕方がないのだ。@
`　Undoubtedly, she felt jealous and being jealous was all she could do.`@
br
;　それがありありとわかるから、サキエもフミエも不快そうに睨み返している。\
`　Since it was clear to them, Sakie and Fumie returned that sharply unpleasant glare.`\

;「自分が姫と呼ばれるかと思ったら、それがみどりだったから面白くないんだよ。」@
`"If I thought I was called princess, I wouldn't like it if Midori was called that."`@
;「ふんっ。@みどりとテメーじゃ姫の器が違うってんだよっ。」\
`"Yeah~. `@`Midori is a different princess of a different caliber than her though~!"`\

;「あいつ、いつまでガンつけてるつもりなわけ？」@
`"Just how long does she intend to keep staring at her?"`@
;「本当だよねー。@……みどりも不愉快でしょ。@私、ちょっと言ってこようか？」@
`"I know right~. `@`...Midori is probably uncomfortable too. `@`Perhaps I should go talk to her?"`@
br
;　フミエが物騒な強面で席をがたりと立ち上がる。@サキエも忠臣ぶりでは負けないとでも言わんばかりに、荒々しく立ち上がる。\
`　With a scary look on her face, Fumie stood out of her chair with a crack. `@`As if wordlessly implying she wouldn't lose to her as Midori's loyal retainer, Sakie stood up hurriedly as well.`\

ld r,MID_Def2,22

;「やめてよ、二人とも……。」@
`"Stop it, the both of you..."`@
br
;　のぞみは毎日、クラスの誰かから、酷い言葉を掛けられたり、あるいは酷い悪戯をされたりしている。\
`　Every day someone in class said terrible things about Nozomi or played terrible pranks on her.`\

;　今日だって、誰からどんないじめを受けるか、わかったものではない。@
`　Who knows what kind of abuse she's suffered today alone.`@
;　みどりは、こんな朝から、さっそくいじめられるところを見たくはなかった……。\
`　On this kind of morning, Midori didn't want to immediately look at the bullying taking place...`\


;　サキエとフミエは、一触即発の緊張感でのぞみを睨みつけている。\
`　Sakie and Fumie were staring at Nozomi with an explosive tension.`\

quakey 2,200

mbg black,22

;「………あんた、さっきから誰にガンつけてんのよ。」@
`"...Hey you, just who do you think you're staring at anyway?"`@
;「文句あんなら言いなさいよっ。@聞いてんのッ？！」@
`"If you've got a problem, then say it~! `@`I'm listening?!"`@
br
;「…………………………。」\
`"............"`\

;　一言でものぞみが言い返したら、それをきっかけに“キレる”つもりなのだろう。@
`　If Nozomi replied back with a single word, they might use that as an excuse to 'end it.'`@
;　それがわかってるから、のぞみも一言も言い返さない。@……いや、言い返せない。\
`　Even though Nozomi understood that, she didn't reply with a single word. `@`...No, she didn't reply at all.`\

mcbg 22

ld r,MID_K2,80

;「やめてっ、二人とも…！！」@
`"Stop it, the both of you!!"`@
br
;　みどりは、少しだけ大きい声で言った。@
`　Midori shouted a bit when she spoke.`@
;　敬愛する姫の大声に、忠臣たちは飛び上がって驚く。\
`　Her loyal subjects jumped with surprise at the loud voice of their beloved princess.`\

ld r,MID_Def2,80

;「……朝からいじめなんて、見たくないの。@……だからやめて。@……ね？」\
`"...I don't want to see bullying this morning. `@`...So stop it. `@`...Alright?"`\

;「姫………。」@
`"Princess..."`@
;「……ちっ。@川田ぁ、次、ガンつけたら容赦しねーからなっ。」@
`"...Tch. `@`Kawada, next time if you stare at her there'll be no mercy alright."`@
br
;　とりあえず、この場は収まってくれた。@
`　At least for now they've settled down.`@
;　しかし、川田のぞみがクラス中から嫌われているいじめられっこであることに、代わりはない。\
`　But it doesn't change the fact that Kawada Nozomi is still hated and bullied during class.`\

bg black,22
bg kyou_03,22

;　みどりが、いじめを見たくないと言ったから、@クラスメートたちは少なくとも、みどりの前だけでは、いじめをしないだろう。@
`　After hearing Midori say she didn't want to see any bullying, `@`for a little while, her classmates didn't do any bullying, at least not in front of her.`@
br
;　もちろんそれは、いじめがなくなるという意味ではない。\
`　Of course that doesn't mean the bullying stopped.`\

bg black,22

;　みどりは、のぞみを救ってやれないことを、気の毒にも思う。@……庇ってあげるべきなのではと思うこともある。@
`　Midori thought it was pitiful that she couldn't save Nozomi. `@`...She also thought she should stand up for her.`@
br
;　しかし実際、川田のぞみは高慢で、自分の家の方が裕福であることを威張っている。@今でも、口を開くことを許されるなら、それを自慢して、みどりを見下したいのだ。\
`　But in reality, Kawada Nozomi was arrogant and took pride in her family's wealth. `@`Even now if they let her speak up, in her pride she wanted to look down on Midori.`\

bg kyou_01,0
ld r,MID_K1,22

;　……みどりも、世の中の不条理は理解している。@
`　...Even Midori realized the irrationality of this world.`@
br
;　どんなに親しく接しようとしても、世の中には仲良くなれない人間もいる。@……それが、川田のぞみなのだ。\
`　That no matter how friendly you are to them, there are people in this world you cannot get along with. `@`...And one of them was Kawada Nozomi.`\

;　だから、彼女へのいじめは、……辛いけれど、見て見ぬふりをするしかない。@
`　Because the bullying against her ...might have been cruel, but all she could do was see it or pretend not to see it.`@
br
;　彼女だって、みどりにだけは庇われたくないと思っているのだから……。\
`　Because after all, Midori thought that if Nozomi wanted protection, she didn't want to be protected by her...`\

bg black,22

;　ごめんね……。@みどりは心の中で謝る。@
`　I'm sorry... `@`Midori apologized from her heart.`@
br
;　でも、………こんなこと言ったら気の毒だけれど。@
`　But, ...If I were to say that, it would be pitiful and yet...`@
;　私だって、みんなに好かれたくて、色々とがんばったり、気遣ったりしてることがあるんだよ。\
`　After all, everyone likes me, supports me with a lot, and is concerned for me.`\

;　川田さんだってそれをすればいいのに、……どうしてしないの？@
`　Kawada-san would be fine if only she would too ...but why doesn't she?`@
;　家が裕福だって自慢したって、誰もいい顔をしないのに……。@
`　She brags about her family's wealth, even though no one would be sympathetic...`@
br
;　去年のクラスでは、それをちやほやしてもらえたかもしれないけれど、@……誰もがお金持ち自慢を持て囃してくれるわけじゃない。\
`　Last years class might have spoiler her by letting her get away with that, `@`...however, it's not like anyone will praise someone for having pride in being a rich person.`\

bg kyou_03,22

me1v 24,50

;　……いじめられてるのは気の毒に思う。@
`　...I think being picked on is unfortunate.`@
br
;　でも、……どうして自分がいじめられているのか、@……早くそれを受け入れて、……自分を直せるといいね。\
`　But, ...the sooner she realizes why she's being picked on, `@`...the sooner she can fix that problem herself.`\

;　ここまで彼女がクラス中に目の仇にされてしまっている以上、それは簡単なことではないだろう。@
`　Aside from staring at me in class until now, this isn't really a simple matter.`@
br
;　でも、……お金持ち自慢の傲慢をやめて、……少しずつ、みんなへの接し方を変えて。@……心を少しずつ入れ替えていけば、……友達も、作れるんじゃないかな。\
`　However, ...if she stopped bragging about being rich, ...then over time, everyone's attitude towards her would change. `@`...And if they slowly change their minds, ...she might even be able to make some friends.`\

bg black,22

;　そうしたらきっといつか、……いじめられっこじゃなくなると思う。@
`　If she did that, then someday ...I think she might stop being bullied.`@
br
;　そしたらその時。@……私とも、友達になろうね。\
`　If she did that, `@`...then she might even become my friend.`\

bg kyou_01,0
ld c,MID_Def2,22

;　その思いが、……のぞみに届いたと信じて。@みどりは再びノートに目線を戻し、宿題の写しに勤しんだ。\
`　I believed... that thought reached Nozomi. `@`Once again I turned my gaze back to Midori's paper, and worked to copy her homework.`\









E_A

mbg "BMP\background\efe\red1.bmp",1
mcbg 0
ld c,MID_K2,22

;「……………痛ッ！@　……………。」\
`"......Ow~! `@`........."`\

me1v 24,50

;　みどりは唐突な腕の痛みに顔をしかめる。@
`　Midori grimaced as she felt a sudden pain on her arm.`@
br
;　骨が痛んだとか、古傷が疼いたとか、そんな痛みではない。@
`　It wasn't a pain from a bone or the throbbing of an old wound or anything like that.`@
;　もっとはっきりとした、……例えるなら、透明人間に腕を叩かれでもしたかのような痛みだった。\
`　It was more direct, ...it was a pain as if an invisible man had struck her across the arm.`\

bg black,24
bg kyou_02,24

;　何事と思い、周りを見回すのだが、何事もない教室の光景が広がっているだけだ。@
`　Wondering what happened, I looked around the room, but all that spread out before me was the scenery of an uneventful classroom.`@
br
;　サキエもフミエも談笑している。@……誰かが私を叩きに来て、それに二人が気付かないわけはない。\
`　Sakie and Fumie were both having a friendly conversation. `@`...It's not possible for someone to just come by and hit me without those two noticing it.`\

bg black,23
bg kyou_01,0
ld c,MID_K1,23

;　……それ以前に。@私はここでこうしてノートを取っているのだ。@その私に気取られずに、誰が私の腕を叩けると言うのだろう。@
`　...Before that, `@`I was just finishing up my homework here like this. `@`Does that mean without them noticing me someone was able to hit my arm?`@
br
;　何か物が飛んできてぶつかったのかとも考えたが、そういう感触ではなかったし、@第一、飛んできたらしき物体はどこにも転がっていなかった。\
`　I thought maybe something had flown and hit me, but it didn't really feel like that. `@`First of all, if something did, there was nothing rolling around to indicate that.`\

;「……どうしたの？」@
`"...What's wrong?"`@
;「………大丈夫、みどり？」@
`"...Are you alright, Midori?"`@
br
;　私の様子に気付き、フミエとサキエが心配そうに覗き込んでいる。\
`　When they took notice of me, Fumie and Sakie were looking at me with concern.`\

ld c,MID_Def2,80

;「……うん、大丈夫。@何でもないよ……。」@
`"...Yeah, I'm fine. `@`It's nothing..."`@

se1 69

br
;　チャイムが鳴って、サキエとフミエがそれぞれ授業の準備にとりかかると、@私はもう一度自分の腕を見てみた。@やはり何もない。\
`　The bell sounded. Sakie and Fumie each started getting ready for class, `@`and I tried looked at my arm again. `@`It must have been nothing.`\

bg black,22

fede 10,2000
E_MA











bg kyou_03,22

bgm1 14

;　実は、……これが初めてではない。@最近たまにこういうことが起こる。@
`　The truth is ...this isn't the first time. `@`Lately every once in a while something like this has been happening.`@
br
;　突然、身体のどこかに痛みを感じるのだ。\
`　Suddenly, I'll feel a pain somewhere in my body.`\

;　それは、何かが触った程度にしか感じない時もあれば、@その場にうずくまってしまう程の激痛であることもある。@
`　There are times when I feel that something had to have touched me, `@`and during those times I've also felt a pain that sends me cowering.`@
br
;　そしてその箇所も、今のように腕であったりお腹であったり背中であったり、一定ではない。\
`　And like at that point too, like now I'd feel it in my arm, in my stomach, in my back -- it's not a specific place.`\

;　……最初の頃は、気のせいか何かだろうと考えていた。@
`　...From the beginning, I've thought about whether it's my imagination or something.`@
br
;　しかし、最近、この不思議な痛みを感じる機会が増えた気がする。\
`　But lately I feel those chance moments when I feel those mysterious pains are on the rise.`\

mbg black,22

;　ひょっとするとこれは、……何か、とても悪い病気なのではないだろうか…？@
`　Perhaps this could be ...I don't know... some kind of really bad illness...?`@
br
;　あまりに酷いようなら、両親に打ち明けて、ちゃんと病院で見てもらった方がいいのかもしれない。\
`　If it's so severe, I'll be honest with my parents, and if they think I should, they'll certainly take me to get looked at in the hospital.`\

;　……紅茶紳士さん。@……これって、何かの病気なの…？\
`　...Oh Tea Gentleman. `@`...Just... what kind of sickness is this...?`\

fede 0,1000
E_B
E_MA

se1v 56,50

mbg white,8
mcbg 22

;　私が心の中でそう呟くと、@/
`　When I muttered that in my own mind, `@/
me1v 28,70
;……………宙に浮くティーカップが現れる。@
`......a teacup appeared flying through the air.`@
br
;　そして、宙に浮くティーポットも現れ、@………ティーカップになみなみと紅茶を注ぎ入れた。\
`　And then a teapot appeared floating in the air, `@`...and it poured ordinary black tea into the teacup.`\

;　そして、カップを持ち優雅に口にする男の姿が、ゆっくりと現れる……。\
`　And then a figure of an elegent man taking a cup elgently to his lips slowly appeared...`\

bg black,22
fede 10,1000
E_MA
bg kyou_01,22
ld c,SIN_Def1,22

bgm1 18

;　この不思議な男の人を、私は紅茶紳士さんと呼んでいる。@……いつも現れる時、紅茶を飲んでいるからだ。\
`　I call this mysterious man the Tea Gentleman. `@`...Because whenever he appears, he's always drinking black tea.`\

;　みんなが談笑する教室の中で、@おかしなアレンジをしたタキシード風の格好で、立ったまま紅茶を嗜む謎の紳士。@
`　In the middle of the classroom filled with idle chatter, `@`in a strangely arranged tuxedo outfit, he was a strange gentleman standing and tasting his tea.`@
br
;　無論、その姿は私以外の誰にも見えていない。\
`　Of course, I was the only one who could see him.`\

cl c,0
ld r,SIN_Def3,23

;「今朝もアッサムがとても良い香りですねぇ。@………おや。@どうなさいましたかな？」@
`"This Assam tea smells wonderful this morning wouldn't you say? `@`...Oh my. `@`Whatever is the matter?"`@

ld l,MID_K1,22

;「……最近、突然、体が痛むことがあるの。」\
`"...Lately I've been getting these sudden pains."`\

ld r,SIN_Def1,80

;「おや。@それはお稽古に差し支えるほどのものですかな？」@
`"Oh my. `@`Do you think it's bad enough that it's going to interfere with your practice?"`@

ld l,MID_Def2a,80

;「……それほどではないけれど…。@……でも、いつも突然でびっくりするし…。@何だか薄気味悪いし……。」\
`"...It's not that bad but... `@`...It always suddenly frightens me and... `@`There's something weird about it..."`\

ld r,SIN_Def2,80

;「ならば、気にしないことです。」@
`"Well, then it's nothing to worry about."`@
br
;　紅茶紳士は、あっけらかんとそう言う。\
`　The Tea Gentleman said indifferently.`\

ld l,MID_K1,80

;「……気にしなくて、いいの…？」\
`"...Is it alright... not to worry about it...?"`\

ld r,SIN_Def1,80

;「はい。@……それに、そんなことを気にしている場合ではないのではありませんか？@　今度のお芝居は、とても重要な役ではありませんか。」\
`"Yes. `@`...Anyway, now isn't really the time to be worrying about that is it? `@`Don't you have an extremely important role in this upcoming play?"`\

ld l,MID_Def2,80

;「はい…。@……台詞も、すごく多くて覚えるのも大変です。」\
`"Yes... `@`...And I have so many lines to remember, it's quite difficult."`\

ld r,SIN_Def4,80

;「今はそれに集中すべき時期ではありませんか？@　他のことに気を取られるのは、集中力を削がれている証拠だと思いますがねぇ。」@
`"Then shouldn't you focus your time on that? `@`I think worrying about other things just shows you're losing your focus, wouldn't you say~?"`@
br
;　それを言われると、言い返せない。\
`　When he said that, I didn't respond.`\

bg black,22

;　今度、演劇部で演じたい役は、とてもとても重要で大切な役。@
`　This upcoming role I want to play in the theater club is an extremely important role.`@
br
;　自分が失敗すれば、お芝居の全てが駄目になるとさえ言っても過言ではないほどの、重要な役。\
`　This role was so important that if I were to mess it up the entire play would be ruined.`\

;　そんな私の緊張が、ありもしない痛みを感じさせるのかもしれない。@
`　Maybe that kind of pressure caused me to feel some kind of imaginary pain.`@
br
;　時に緊張が腹痛を引き起こすように、……これも、そういうものなのかもしれない。\
`　Perhaps... I'm just feeling occasional pains in my chest from the stress.`\

bg kyou_02,0
ld r,MID_Def2a,22
;ld r,MID_Def1,80

;「……そうですね。@気にしても、仕方ないかもしれませんね。」@
`"...You're right. `@`It bothers me but I suppose I have no choice, right?"`@

ld l,SIN_Def2,22

;「そういうことですよ。@気になどしないことです。」@
`"That's how it is, you see. `@`Don't worry about it."`@
br
;　気にするなと、重ねて言われる。@
`　He kept saying not to worry about it.`@
;　……もう、腕の痛みも消えている。\
`　...And the pain in my arm was already fading away.`\

ld l,SIN_Def1,80
cl l,2

;　私が納得すると、紅茶紳士さんは姿を消す。\
`　When I agreed with him, the Tea Gentleman disappeared.`\

ld r,MID_k1,80

;　彼は当然、人間ではないだろう。@
`　He's probably not human`@

;　なら、何？@　……オバケとか、……妖怪？@
`　Then what is he? `@`...A monster? ...a youkai?`@
br
;　その正体について、深く考えても意味はない。\
`　There's no reason to think too much about his real identity.`\

;　彼は紅茶紳士さん。@私の前に現れた、不思議な人。@
`　He is the Tea Gentleman. `@`A mysterious figure who revealed himself to me.`@
br
;　彼が、かつての私を、生まれ変わらせてくれたのだ。\
`　And he brought me a new life from who I once was.

bg black,2

fede 0,2000
E_A












bg engeki_01,22

bgm1 2

;　放課後、演劇部の部室に行くと、既に部活は始まっていた。@
`　When I went to the drama clubroom after school, things were already underway.`@
br
;　皆、部長の指示のもと、熱心にストレッチをしている。\
`　Under the direction of the club president, everyone was performing stretching exercises with enthusiasm.`\

ld l,MID_Def1,23

;「ごめんなさい。@遅くなりました。」@
`"I'm sorry. `@`I'm late."`@
br
;　部室に入ると、誰もが一瞬手を止めて、私を見る。@
`　As I enter the room, everyone stops what they're doing and looks at me.`@
;　敬愛だったり、憧れだったり。@遅刻してきた身には、勿体無い眼差しだ。\
`　Adoration. Admiration. `@`They were improper glances to give to someone who was late.`\

;mbg white,1
;mcbg 22

;「………ほら、ストレッチの続き！」@
`"...Hey, keep stretching!"`@
br
;　部長が手を打ち鳴らす。@彼も、みどりの姿に一瞬、見惚れていたくせに。\
`　The club president clapped his hands. `@`Even he had been enchanted by Midori for an instant.`\

;「楠木ー、お前、最近遅刻が多いぞー。」@
`"Kusunoki~, you've been late a lot lately~"`@

ld l,MID_Def5,80

;「すみません。@ちょっと着替えるのに手間取ってしまって……。@以後、気をつけますね。」@
`"Sorry. `@`I had some trouble getting changed... `@`I'll be more careful in the future."`@
br
;　そう言って微笑みかけると、部長は分かり易いほど頬を赤くして俯いた。\
`　I said with a smile, and as the club president realized what that meant he turned red and looked away in embarassment.`\

;「……まあ、気をつけてくれればいいんだけどさ……。」@
`"...Well~. I'm sure you'll be fine as long as you're more careful..."`@
br
;　上級生である部長は、先生たちからの信頼も厚く、女生徒達からもとても人気がある。@
`　Our upperclassman club president got along well with the teachers and was very popular among the girls at school.`@

;　だが、そんな彼でもみどりの笑顔一つでこの通りだ。\
`　But even someone like him would show Midori a smile like that.`\

cl l,22

;　クラスのお姫様は、演劇部においてもお姫様だった。@
`　The princess of the classroom was also a princess even in the drama club.`@
br
;　いや、厳密には逆か。@
`　No, perhaps it makes more sense the other way around?`@
;　演劇部でお姫様だからこそ、クラスでもお姫様なのだ。\
`　Because I was the princess in the drama club, I was a princess in the classroom.`\

;　舞台上の彼女が美しく輝くからこそ、彼女は姫と呼ばれ、@他のクラスどころか、他の学年の子にまで大勢慕われているのだ。\
`　She is called Princess because she shines beautifully on stage, `@`and she is loved by students from other classes and even different grades.`\

bg black,23
bg engeki_02,23


;　みどりがストレッチをする場所を探して歩くと、@それに合わせて、まるで花道でもつくるかのように他の部員達がスペースをあけてくれた。\
`　As Midori went looking for a place to stretch, `@`in response, the other club members made way as if she were passing through the audience to the stage.`\

ld c,MID_Def1,23

;「ありがとう。」@
`"Thank you."`@
br
;　彼女が微笑んでお礼を言うと、みんな照れて俯いてしまう。@
`　As she smiled and thanked them, everyone shyly looked away.`@
;　みどり姫が微笑むだけで、花も恥らうというのは言葉通りの意味に違いなかった。\
`　It was exactly as if even flowers would blush with just a smile from Princess Midori.`\

;　我が校の演劇部は、部員も多く、文化部なのにノリは完全に体育会系だった。\
`　Our school drama club had a lot of members, and although it was a cultural club it was completely sport-oriented.`\

;　部活の時は全員体操着に着替える。@そして体力作りと称して学校の周りを走り込んだり、@近くの河原に行って大声で発声練習も行ったりもする。@ほとんど『ガラスの仮面』の世界だ。\
;　(Translator's Note) Reference made to Gurasu no Kamen, "Glass Mask." A manga from the 1960s.
`　(?) During club hours everyone changes into gym outfits. `@`And in the name of improving our endurance we do things like running around the school `@`as well as heading down to the river bed and practicing our shouts for vocal exercises. `@`It's almost like the world in "Glass Mask."`\ 

;　そして、毎学期末には発表会があり、全校生徒の前で芝居を上演することになっている。@
`　And now it's become a tradition to have a recital at the end of every semester where we perform in front of all the students in school on stage.`@
br
;　今日はその発表会の配役決めを行う重要な日だ。@部員達はいつもにも増して気合いが入っているようだった。\
`　Today is a very important day where the roles of the recital will be decided. `@`It was as if all the club members were overflowing with excitement.`\

mbg black,22

;　基本的に芝居の配役は、部員がやりたい役に立候補し、@顧問の先生と部長が問題ないと判断すればそれで決まる。@
`　Basically, when it came to casting the play, members would start calling out the part they wanted to play, `@`and if the adivising teacher and club president saw no problems, then it was decided then and there.`\
;　一つの役に二人以上立候補者がいた場合は、みんなの前でオーディションとなる。\
`　When two or more people wanted the same role they would audition in front of everyone.`\


;　今回の発表会での演目は、『六軒島』という古典作品。@
`　This time the play we're doing at the recital will be "Rokkenjima," a classic work.`@
br
;　ファンタジーのようでもあり、ミステリーのようでもある不思議な作品だ。\
`　It's a mysterious play that is like a fantasy but also like a mystery.`\

;　かなり難解な内容で、役者が心情を充分に理解して演じなければ、@到底、メッセージを伝えることなど出来ない。@
`　With some very difficult contents to work with, if the actors don't understand the emotions they have to portray, `@`then they cannot transmit the message of the story.`@
br
;　かなり難易度の高い演目だが、顧問の先生は敢えてこれを選んだのだ。\
`　It's a really difficult play, but our advising teacher has chosen this as a challenge for us.`\

;ld c,MID_Def1,80

mcbg 22

;　主演の魔女役に求められる演技力は、並大抵のものではない。@
`　The leading role of the witch is no ordinary role and requires real acting ability.`@
br
;　でも、それを見事射止めたい。@この演目を、そしてこの役を、@……私になら出来ると信じてくれた先生の期待に応えたいのだ。\
`　But I want to make that role mine. `@`This play, and this role, `@`...If I can do it, I want to realize the expectations of the teacher who believed in me.`\

bg black,23
bg engeki_01,23

;「……主役はみどりさんで決まりよね。」@
`"...The leading actress has to be Midori-san."`@
;「当然よ……。@魔女の役が出来るのは、彼女以外に誰もいないわ。」@
`"Obviously... `@`she's the only one who can play the role of the witch."`@
br
;　その魔女こそが、このお芝居の主人公。\
`　That witch was also the protagonist of this play.`\

;　他にも登場人物が出てくるけれど。@……もはや一人芝居と言ってもいいほど、魔女役の演技力がそのまま、お芝居の完成度を左右する大役なのだ。\
`　There are other characters that are introduced. `@`...But pretty soon it turns into a one woman show, and the perfection of the play is controlled by the acting ability of the one playing the witch.`\

;　部員たちが、みどり以外の誰にも務まらないと囁き合っている。@
`　The club members whispered amongst themselves that no one else except Midori could fit the role.`@
br
;　恐らく、みどり以外の誰も、魔女役には立候補しないだろう。\
`　And it was most likely that no one else would announce their candidacy for the role of the witch.`\

;　彼女と演技力で張り合おうなんて、おこがましいにも程がある。@
`　To suggest that someone would compete with her on acting ability was beyond absurd.`@
br
;　楠木みどりは、演劇部においては姫というより、女王の貫禄を持っていたのだ。\
`　Kusunoki Midori was more than a princess in the drama club. She resembled a queen.`\

ld r,MID_Def1,26

;　もちろん彼女も、自動的に魔女役をもらおうなどと甘えるつもりはない。@
`　Of course, she wasn't so naiive as to think she would be given the part of the witch automatically.`@
;　そして自分の演技力を試す意味で、先生がこの演目を選んだことも理解している。@
`　She also knew that her teacher had chosen this play specifically to test her acting abilities.`@
br
;　だから、今日に備えて、ずっと魔女役をレッスンしてきたのだ。\
`　After all, he had been giving her lessons on the witch's role for ages now in preperation for today.`\

bg black,24
bg engeki_02,24

;　先生が厳しい眼差しでみどりを見ている。@
`　The teacher was staring intensely at Midori.`@
br
;　……見事、魔女役を射止めてみなさいという、挑戦的な眼差し。\
`　...It was a look as if to say, magnificent, now make the role of the witch your own.`\

;　もしもみどりが、魔女役に不適ならば、この演目すらも撤回するつもりかもしれない。@
`　If for some reason Midori didn't prove to be a very good which, he might have even intended on cancelling the play altogether.`@
br
;　それは即ち、……この『六軒島』という演目が、@みどりのためだけに選ばれたも同然であることを意味していた。\
`　In other words, ...this play on "Rokkenjima" `@`might as well have been chosen just for Midori's sake.`\

;　………先生、私を見て下さい。@絶対に、魔女役に相応しい演技をお見せします。@
`　...Sensei, please look at me. `@`No matter what, I'll show you a fitting performance for the role of the witch.`@
br
;　みどりもまた、決意を眼差しに込めて、先生にそれを返すのだった。\
`　And then Midori's eyes filled with determination in response to her teacher.`\

;　ほぼ魔女役が内定しているみどりと違い、@その他の部員たちにとっては、無事に役を射止められるかどうか、まだまだ不安だった。\
`　Unlike Midori who was almost guaranteed to get the role, `@`the other club members were still worried whether or not they would so easily get their own parts.`\

;「あーあ、私、どの役にも就けなかったらどうしよう。」@
`"Ah~ah, what should I do if I don't get any of the parts?"`@
;「雑用係になったら大変だよね。@今回、小道具とかも多そうだし……。」@
`"I would hate getting stuck doing the odd jobs. `@`This play seems to have a lot of props and what not too..."`@
;「くす。@それは心配しなくても大丈夫でしょ。@ほら、全部一人でやってくれそうな子がいるじゃない。」\
`"Heh. `@`You shouldn't worry about that. `@`I mean look, there's a kid who'll do it all for us."`\

bg black,24
fede 0,1000
E_A
bg engeki_03,24










bgm1 8

;　彼女たちの目が部室の隅に向けられる。@
`　Their eyes shifted to the corner of the clubroom.`@
;　そこには、みんなから孤立して一人でストレッチを行っている子がいた。@
`　There was a single girl isolated from everyone doing her stretches.`@
br
;　………川田のぞみだった。\
`　...It was Kawada Nozomi.`\

;　そう言えば彼女も演劇部だった。@誰とも目を合わせない様に俯いたまま身体を伸ばしている。@
`　On that note, she was also a member of the drama club. `@`She was stretching herself out with her head down while everyone avoided making eye contact with her.`@
br
;　そんな彼女を見ながら、@他の部員たちは「ほんとブス」とか「キモい」などと口々に囁いている。\
`　Looking at her like that, `@`all at once the other club members started whispering: 'Uuugly.' 'Disgusting.'`\

;　みどりのところにまで声が届いているのだから、当ののぞみに聞こえていないはずがない。@
`　Their voices extended out to Nozomi. There was no doubt that she heard what they were saying.`@
;　しかし、彼女は全く気にしない様子で黙々とストレッチを続けていた。@おそらく必死に心を殺し、聞こえない振りをしているのだろう。\
`　And yet, silently she continued to stretch as if it didn't bother her one bit. `@`Perhaps she was silencing her heart and pretending not to hear.`\

;　クラスだけでなく、ここでもいじめられてるなんて。@みどりは気の毒に思う。@
`　She wasn't just bullied in the classroom, but here as well. `@`Midori felt sorry for her.`@
br
;　のぞみは、みんなに陰口で言われるほどブスではない。@……むしろ、顔立ちは美人の部類に入るだろう。\
`　It wasn't as if Naomi was as ugly as everyone was slandering her out to be. `@`...On the contrary, her face made her seem like a beautiful person.`\

;　金持ち自慢の傲慢な笑みでなく、……心の底からの朗らかな笑いを浮かべることが出来たなら、@もっともっと明るく輝くだろうに。\
`　Rather than a smile prideful of her wealth ...if she could smile from the bottom of her heart, `@`then her face would surely shine even brighter.`\

bg black,22

;　……私もかつて、家の裕福さを無自覚に自慢していたことがある。@
`　...I too was once ignorantly took pride in my family's wealth.`@
br
;　でも、幸いなことに、それが傲慢であると気付き、直すことが出来た。\
`　Thankfully, I realized my arrogance and I fixed myself.`\

;　それが出来なければ、……川田のぞみは、私だっただろう。@
`　If I hadn't done that... I would be Kawada Nozomi.`@
br
;　彼女が時折、私をじっと見ているように。@
`　Just as sometimes she's staring at me.`@
;　私もまた、……時折、じっと彼女を見てしまうのだ……。\
`　Sometimes... I'm also staring at her...`\

bg engeki_01,22
ld l,SIN_Def1,22

;「何をぼうっとされているのですか…？@　貴方の番ですよ。」@
`"What are you daydreaming about...? `@`It's your turn."`@

ld r,MID_K1,26

;「え？@　……あ、ありがとう。」@
`"Eh? `@`...Oh, thank you."`@
br
;　紅茶紳士が現れ、みどりに、番が来たことを教えてくれる。\
`　The Tea Gentleman appears and tells Midori that her time has come.`\

cl r,23
bg black,23
bg engeki_01,23
ld l,MID_Def1,23

;　先生の前に歩み出て、何役に立候補したいかを宣言し、その演技を見せなくてはならない。@
`　Walking towards the teacher, I would announce what role I want to play, and I would demonstrate that performance.`@
br
;　私は、部員たちが床に座って静まり返る中、立ち上がり、一人、前へ出る。\
`　As silence fell on the other club members sitting on the floor, I stood up, alone, and stepped forward.`\

;「楠木さん。@希望する役は？」@
`"Kusunoki-san. `@`What part do you want?"`@
br
;　先生が問う。@
`　The teacher asked.`@
;　私はその強い眼差しに負けないよう、力強く頷きながら答える。\
`　Without losing that self-confidence, with a strong nod I replied.`\

cl l,0
ld c,MID_Def5,23

;「楠木みどり。@魔女役を希望します。」@
`"Kusunoki Midori. `@`I want the role of the witch."`@
br
;　誰もが予想していた通りではあっても、みんなはおぉと低い声でどよめく。\
`　Even though it was what everyone expected, they all let out low gasps.`\

;「……結構。@それでは、演技をいくつか見せてもらいましょう。」@
`"...Splendid. `@`Then how about you show us a performance."`@
br
;　複雑な台詞、複雑な言い回し。@そして細やかな感情表現。@
`　Complicated lines, complicated delivery, `@`and a tender expression.`@
;　今日までずっと頑張ってきた成果が問われる。\
`　He was asking to see the fruits of all my labors from so long ago until this day.

ld c,MID_Def1,80

;　先生に演技を促され、……私は静かに精神を統一する。\
`　After being urged to perform by my teacher ...I quietly began to focus.`\











E_A

mbg "BMP\background\efe\red1.bmp",1
ld c,MID_K2,0
mcbg 22

;　その時、………また痛みが走った。@
`　At that moment, ...that pain ran through me once again.`@

me1v 17,50

br
;　……こんな時にまで、……また……。\
`　...Even now at a time like this ... again...`\

;　今度は肩だった。@
`　This time it was my shoulder.`@
;　もちろん、誰かが叩いたわけでもないし、何かが飛んできたわけでもない。@
`　Of course it wasn't like anyone hit my shoulder or like anything flew and hit it.`@
br
;　でも、何かにどんとぶつかられたような突然の痛み。\
`　But it was a pain as if I had suddenly been hit by something.`\

;「楠木、どうかしたか？」@
`"Kusunoki, what's wrong?"`@
br
;　部長が声を掛けてくる。\
`　The club president called out.`\

ld c,MID_Def2,80

;「…………いいえ、何でもありません。」@
`"...No. It's nothing."`@
br
;　一回、リラックスさせるように腕を回す。@……もう、何ともない。\
`　Hoping it would help ease my mind I circled my arm around once. `@`...There wasn't any pain anymore.`\

ld l,SIN_Def1,22

;「どうしました？@　いよいよ、今日までの成果を見せる時ですよ。」@
`"What's the matter? `@`It's finally time to show them what you've been working for until today, you know."`@
br
;　紅茶紳士さんも励ましてくれる。\
`　Even the Tea Gentleman was cheering me on.`\

ld c,MID_Def1,80

;　……やっぱり私、緊張してるのかな。@
`　...Perhaps I'm just nervous`@
br
;　それとも、川田のぞみを意識し過ぎてしまったせいだろうか。\
`　Or perhaps it's because I was too worried about Kawada Nozomi.`\

;　蘇るのだ。@……彼女を見ていると、……生まれ変わる前の自分を見ているようで。@
`　She stirs my memory. `@`...When I look at her ...it's as if I'm looking at myself before I was born again.`@
br
　みどりは、魔女役の演技を見せながら、@……かつての、一学期の頃の自分を思い出していた………。\

bg black,2
fede 0,2000
E_A









bgm1 14

　生まれ変わる以前のこと。\

　それは私にとっては前世のように遠くて。@……そして時間的には、ほんの２ヶ月前の、一学期のことを指す。@
br
　私にとってはもう、思い返すのもおぼろげな、遠い記憶だ……。\

mono 1
bg kyou_02,22

「みどりちゃんてさ、何か高慢ちきだよね。@お金持ち自慢が過ぎるって言うかさ。」@
br
　クラスメートの少女の一人が、みどりを指して唐突にそう言ったのだ。\


　彼女は容姿もよくて成績優秀ということもあって、クラスでも人気のある、@当時の私よりヒエラルキーのはるかに高い子だった。\

　………そう。@私が姫などと呼ばれてちやほやされているのは、遠い過去からのことではない。@今学期になってからなのだ。\

　私にとっては、前世のことのように遠いけれど、……それはつい、前の学期のことなのだ。\

　その子のその指摘は、……瞬く間にクラスメートたちに共有された。\

bg black,22
mono 0
bg e010,2
;quakey 1,100

me1v 5,50

　楠木みどりは、お金持ち自慢の高慢ちき。@
br
　そうレッテルが貼られ、三日と開けずに、クラス全員によるみどりへのいじめが始まったのだ。\

　それは、思い返すだけでも辛い日々だった。@
br
　心が押し潰され、死んでしまいたいと思ったことも、一度や二度ではない。@
　そしてそのいじめは、クラスだけでなく、演劇部にも伝染した。\

bg black,22
mono 1
bg engeki_01,22

　それまでは発表会の時には何かしらの役には付けていたのに、@雑用ばかりをやらされるようになった。@
br
　仲の良かった部員たちも次第にみどりと口をきかなくなり、@みどりはクラスでも演劇部でも孤立した。\

bg black,22
mono 0

　まさに、……今の川田のぞみのように。\

　あぁ、わかった。@だから、……彼女を見ていると、…………疼くんだ。@
br
　心の古傷が。@……前世の古傷が。\

fede 10,1000
E_MA

　そんな、ある日。@
br
　私は出会ったのだ。@
　紅茶紳士と名乗る、人ならざる存在に。\

fede 0,1000
E_A












mono 1
bg engeki_03,22

bgm1 5

　その日、みどりは演劇部の雑用を全て押し付けられ、@日が落ちてからも部室に残って小道具作りを行っていた。@
br
　段ボールに銀紙を貼った剣を作りながら、これが本物だったら、と思った。\

　部内でみどりを虐めるリーダー格の子は、今回の演目で主役を演じる。@ラストシーンで、彼女はこの剣で胸をついて自害するのだ。\

;mono 0
;print 0
;bg white,1
;bg blood_1aR,22
;quakey 1,100

　体育館のステージが彼女の血で真っ赤に染まることを、根暗に想像する。@だが、すぐにそれが、下らない妄想だと思い直した。\

;bg black,23
;mono 1
;bg engeki_03,23
;bgcopy
;csp -1
;mono 0

bg black,22
mono 0

　演劇部に入ったのは、……舞台の上での輝かしい瞬間を求めてだった。@
br
　なのに、今の自分は何の役にも就けず舞台にも上がれない。@……許されているのは、こんな時間までの、たった一人での小道具作り……。\

　悲しくて悔しくて。@
　でも、思い返してみれば、事の発端は全て、自業自得のような気もして。@
br
　……お金持ち自慢の高慢ちき、というレッテルを貼られる前に戻ることが出来たらと、@ひとり悲しく夢想していた…。\

　涙を零したって、仕事は終わらない。@
br
　みどりは大きく深呼吸をした。@……薄暗い部室のカビと塗料の臭いが、鼻を通り抜けていった。\

　……しかし、もう一度、深呼吸をした時。@みどりは不意に、香ばしい素敵な香りを嗅いだ気がした。@
br
　それはあまりにこの場には不似合いな、………紅茶の香りだった。\

fede 0,1000
E_A

;bg white,23
mono 1
bg engeki_01,23













me1v 11,90

　思わず部室を見回したみどりの目は、ある一点に注がれた。@
br
　………閉じられた窓の前に、湯気のたつティーカップが浮いていた。@……そう、浮いていたのだ。@何もない空中にふわふわと。\

　小道具作りに疲れ切っていたせいもあっただろう。@……みどりはただ呆然と、その不思議な光景を凝視していた。\

　…………自分が見ているのは幻に違いない。@
br
　毎日のいじめと小道具作りの作業で、心身共に疲れきっていたみどりは、そう思い込もうとした。@
E_A
　だからそのティーカップがいきなりしゃべりだした時にも、大して驚きはしなかった……。\

bgm1 18

「……このような時間まで部活動とは。@……熱心なお嬢さんですねぇ。」@
br
　成人男性の声だった。@若いのかお年寄りなのかすら分からない、@まるでエコーでもかかったのかの様な不思議な響きのある声だった。\

mono 0
print 2

「失礼。@驚かせてしまいましたか……？」@

ld l,MID_Def2a,22

「い、………いいえ。」\

「ふむ。@……どうやら、お嬢さんの心のチャンネルと、@私の波長が偶然にも合ってしまったようですね。」@
br
　ティーカップが動きながら、そうしゃべる。\


　次第に、それが透明人間が手にティーカップを持っているのだと理解できるようになる。@
br
　すると、まるでカメラのピントが合うみたいに、@………ティーカップを持つ、男の姿が見えてくるようになる……。\

se1v 56,50

bg white,8
bg engeki_01,0
ld l,MID_Def2a,0
ld r,SIN_Def1,22

　それは、タキシード…？　をアレンジしたような、不思議な服を着た大人の男性だった。\

　……先生には見えない。@もちろん生徒にも見えない。@
br
　しかしその奇抜な服装は、むしろ演劇部にぴったりのようにも思えた。\

ld r,SIN_Def3,80

「おや。@すっかり私の姿が見えるようになったみたいですねぇ。」@
br
　不思議な男は、にっこりと微笑みながらもう一度、紅茶をすする。\

ld r,SIN_Def2,80

「こんばんは、お嬢さん。@……部活動に熱心なのは良いことですが、@女の子には少々、遅過ぎる時間ですよ。」@
br
　それが、みどりと紅茶紳士の、初めての出会いだった。\

bg black,22

　紅茶紳士は、小道具作りを手伝ってくれたわけではない。@
br
　しかし、窓辺でティーカップを傾けながら、みどりの身の上話に静かに相槌を打ってくれた。\

bg engeki_03,0
ld r,MID_K1,0
ld l,SIN_Def1,2

ld l,SIN_Def3,80

「……可哀想に。@クラスにも部活にも居場所がないとは、実に気の毒な限りです。」@

ld r,MID_Def2,80

「クラスは、……別にいいんです。@元々、学校なんて、好きじゃなかったし。」\

ld l,SIN_Def1,80

「では、貴方が悲しんでいるのは、……演劇部のことなのですね。」\

ld r,MID_Def2a,80

「私、……本当に演劇が好きなんです。@………舞台の上では、色んな自分になれる。@別の世界や、別の人生が体験できる。@それが好きで、演劇部に入ったんです。」\

ld l,SIN_Def2,80

「……なのに、貴方は理不尽に扱われ、今や小道具作りを押し付けられるこの扱い。@……お気の毒なことです。」\

ld r,MID_K2,80

「………………………………。」@
br
　みどりは手を止め、……しくしくと涙を零す。@
br
　小道具作りがしたくて、演劇部に入ったわけではないのだ。\

;bg white,28
bg black,22

　輝きたかった。@声援を浴びたかった。@
br
　クラスでいじめられようとも、@……せめて舞台の上でだけでも輝けたなら、まだ堪えることは出来たのだ。\

bg engeki_03,0
;ld r,MID_Def1,0
ld c,SIN_Def1,22

ld c,SIN_Def3,80

「………可哀想に。@……しかし、これも何かの縁です。」@

ld l,MID_K1,80

「縁、って……？」\

cl c,0
ld r,SIN_Def2,23

「私たちが望まずして姿を見ることが出来るニンゲンは、なかなか存在しませんよ。@私と貴方のこの出会いは、とても奇跡的なのです。」@
br
　確かに奇跡だろう。@
　人の人生において、人ならざる者と出会う機会など、普通、あるわけもないのだ。\

ld r,SIN_Def1,80

「せっかくの機会です。@……私の力で、貴方のささやかな夢を一つ、叶えてあげましょう。」@

ld l,MID_K2,80

「私の、……夢………。」\

cl r,0
ld c,SIN_Def4,24

「貴方は、クラスでどんなにいじめられようとも、@舞台の上で輝けたならそれで満足とまで仰いました。@……演劇部員として、実に見上げた根性です。@それに敬意を表し、……そんな貴方の夢を一つだけ、一度だけ叶えてあげましょう。」@
br
　男はそう言うと、左手をツイと上げる。\

se1v 56,50

　すると、部室の隅に詰まれた、舞台脚本を詰めたダンボール箱がいくつも、ふわりと浮き上がる。@
br
　そこから何冊もの舞台脚本が飛び出し、……私の周りを、ゆっくりと漂いながら回り始める。\

me1v 17,70

se1v 56,50

bg white,28
bg black,28

se2v 22,50

bg white,23

se3v 1010,50

bg engeki_01,0
ld r,SIN_Def2,23
ld r,SIN_Def1,80

「お好きな役を選んで下さい。@貴方にその役を与えてあげましょう。」@

ld l,MID_Def2a,22

「ほ、本当に……？@　ど、どんな役でも……？！」\

ld r,SIN_Def3,80

「えぇ、どんな役でもですよ。@悪を倒すヒーローにも愛を囁かれるヒロインにも。@望むなら犬にも猫にも、背景の木の役にだってして差し上げますよ……。」\

;ld l,MID_Def1,80

me2v 16,50

　いくつもの素敵な舞台脚本がみどりの前を過ぎる。@
br
　どの脚本も、どの役も、……憧れて止まなかったものばかり。\

ld r,SIN_Def1,80

「一つだけ、選んで下さい。@それを以って、私たちの契約と致しましょう。」@

ld l,MID_K1,80

「……契約って……？」\

ld r,SIN_Def4,80

「すでにご想像されていると思いますが。@私はニンゲンではありません。@……むしろ、ニンゲンの皆さんの魂のカケラを少々。@お裾分けしてもらって糊口を凌ぐ身です。」\

bg black,22

　みどりもすぐに察する。@
br
　どんな役でも。@一つ願いを叶える代わりに、……魂を渡すという契約をせよと言っているのだ。\

;bg white,1
bg engeki_02,0
ld c,SIN_Def1,22
;ld l,MID_Def1,22

ld c,SIN_Def2,80

「おっと。@誤解させてしまいましたね。@……私は決して、死神ではありません。@私と契約したからと言って、貴方のお命を頂戴するような物騒は致しません。@魂のカケラをほんの少々。@かじらせてもらう程度です。@貴方には自覚できない程度のわずかですので、どうぞご心配をなさいませんように……。」\

　男はそう言ってにこやかに笑う。@
br
　……その笑いは確かに、命と引き換えに…、という物騒さは感じさせないものだった。\

fede 10,1000
E_MA

ld l,MID_K5,80

　みどりは、逡巡せず決断する。@
br
　このままの日々を繰り返したって、……自分の心は日々、殺されていくだけなのだ。\

　なら、彼と契約しよう。@
br
　日々、緩慢に殺されていくくらいなら。@………自らの意思で魂のカケラを支払い、何かを切り開く方がずっとマシだ。\

cl c,0
ld r,SIN_Def4,23

「素晴らしい。@……貴方の心の強さに敬意を表します。@……貴方は必ずや得るでしょう。@この貴重な機会を活かし、それを切っ掛けに、まったく別の人生を切り開けると。@……貴方は必ずや今夜の奇跡を活かし、生まれ変われるに違いありません。」\

bg black,22

　時に、舞台の上での神秘体験が、……実生活にも影響を及ぼすことはある。@
br
　そう。@これは私にとって、一度だけお芝居で抜擢してもらえるというだけの奇跡ではない。@
br
　これを機会に、……自分を、人生を、運命を、変えるのだ。\

　彼はそのチャンスを与えてくれた。@……でも、掴むのは私なんだ。@
br
　絶対に掴む。@……そして、変えるんだ……。@
br
　そして私は、………役を、選んだ。\

bg engeki_01,22
;ld r,SIN_Def1,0
ld c,MID_Def2,22

;ld l,MID_Def1,80

「……あなたのことは、何て呼べば……。」@

ld l,SIN_Def1,22

「そうですね。@……では、私の大好きな紅茶にちなみ。@紅茶紳士とでも名乗るとしましょう。」\
















bg black,2

fede 0,2000
E_A

bg engeki_02,2

bgm1 5

　そして、紅茶紳士さんは約束を守った。@
br
　次の演目で、私は大抜擢を受けたのだ。\

　その役の子が本番の直前に部長と大喧嘩をして、部を飛び出してしまったのだ。@
br
　私は偶然にも、彼女の不在の折に代役を務めるため、その台本を熟読していた。@だから、本当の代役が見つかるまで、@仮ではあるが大抜擢を受けることとなったのだ……。\

;se1 01
;bg white,28
;bg engeki_02,2

bg black,22

　………それは私が願って止まなかった、可憐な可憐な、……お姫様の役だった。\

　私など、突然の穴に抜擢された、あくまでも急場凌ぎ。@……先生も部長も、誰も期待などしていなかった。\

　でも、私はその役に、全ての魂をぶつけた。@
br
　紅茶紳士さんが与えてくれた、たった一度のチャンスに、@……いや、一度と知るからこそ、全てをぶつけたのだ。\

;se1 77
bg white,22
bg engeki_05,2

　お稽古も舞台の上も、……頭の中は真っ白だった。@
br
　それは緊張していて真っ白だった、という意味じゃない。@
　私の全てを、内側が空っぽになるくらいに、全て全て出し切ったという意味。\

　全てが無我夢中。@……舞台が幕を下ろすまで、何も記憶に残ってはいなかった。\

se1v 54,70
wait 100
se2v 54,70

　……だから、全てが終わり、我に返った時。@
br
　私は割れんばかりの歓声と拍手の中にいた。\

　何が何やら、わからない。@眩いスポットライトに照らし出され、目が眩んでしまい、何もわからない。@
br
　主演の部長が私の手を取って、………アンコールに応えてあげる。\

se1v 54,100
wait 100
se2v 54,100
wait 100
se3v 54,100

　その時、私はようやく理解し、実感した。@
br
　舞台は、……私のお姫様の役は、……大成功に終わったのだ……。\

bg black,23
bg engeki_06,0
ld r,SIN_Def1,23
;ld r,SIN_Def1,80

me1v 24,50

wait 500

ld l,MID_Def2,22

「紅茶……紳士さん…………。」@

ld r,SIN_Def2,80

「お見事でしたね。@ここでずっと見ていましたよ。」@
br
　舞台袖のカーテンの陰で。@紅茶紳士さんもずっと手を叩いていてくれた。\

ld l,MID_Def5,80

「あなたの……お陰です……。@……私は、………最高の役を得ました……。」\

ld r,SIN_Def3,80

「えぇ。@私は貴方の望む最高の役を与えました。@しかし、それを演じ切ったのは貴方の力ですよ。@……この大歓声に讃えられるに相応しい、素晴らしい才能でしたよ。」\

cl l,5
;ld l,MID_Def1,80

「………嬉しい……。@……嬉しいです……。@……私、……眩し過ぎて、……何も見えない……。」\

ld r,SIN_Def1,80

「もう、貴方は生まれ変わったのです。@チャンスを得て、貴方が掴んだ。@……その力を忘れずに。@貴方の人生を切り開き、ますますに豊かなものにしてくれるでしょう。」\

ld l,MID_Def4a,26

「忘れませんっ。@私、……今のこの気持ちを、絶対に……。」\

ld l,MID_Def3,80
cl l,2

wait 1000

ld r,SIN_Def4,80

「それと、私との約束も、お忘れなく。」\

cl r,2

　紅茶紳士はにやりと笑い、それだけを言い残すと姿を消す。\

bg white,1
bg engeki_05,22
se1v 54,70
wait 100
se2v 54,70


　でも、今この場で魂を抜き取られて殺されたとしても。@……構わないくらいに、彼女は絶頂の中にいた。\

fede 0,2000
E_A











bg black,2

bgm1 1

　奇跡の大抜擢。@奇跡のお姫様。@
br
　彼女はその日より、みどり姫と呼ばれ、@学校中の女子から憧れられ、一目を置かれるようになったのだ……。\

bg kyou_01,2

　そして夏休みが終わって、新学期になると。@
br
　一学期の頃が嘘だったかのように、みどりに対するいじめは、綺麗さっぱりなくなっていた。\

　かつて自分をいじめていた子たちは、皆、それがまるでなかったかのように振舞った。@
br
　みどりにちやほやし、姫と呼んで持て囃してくれた。\

　最初はちょっぴり、何て調子のいい人たちとも思った。@
br
　でも、手の平返しではあっても、………尊敬し、敬愛してもらえるのは悪い気持ちではない。\

　……そこで浮かれたくなる気持ちを、彼女はぐっと堪える。@
br
　もう、お金持ち自慢の高慢ちきなんて、絶対に言われないようにしよう。@
　あのお姫様のように、……可憐でやさしくて、誰からも愛される心の美しいお姫様になるんだ……。\

bg black,22
bg kyou_03,22

　あの舞台を機に、私は生まれ変わったのだ。@
br
　今ではもう、一学期のことなんて、誰も覚えていない。\

　男子なら、私が側を通り過ぎるだけで、見惚れて顔を赤くし。@
br
　女子なら、私に憧れ、友達と呼んでもらいたがる。\

　私のわずかの振る舞いに、みんなは一喜一憂する。@
br
　私の何気ない仕草が、まるで偉人のように扱われ、学校の伝説になっていく。\

bg black,23
bg rouka_03,0
ld r,MID_Def1,23

cl r,2

『みどりちゃんって凄いよね、かっこいいよね！@　私もあんな風になりたいっ。』@
『みどり姫、マジ可憐……。@一度でいいから、名前呼んで微笑んでくれねぇかなぁ……。』@
『みどり姫、主演の演劇、またやらないのかな！@　演劇部、目が離せな～い！』\

bg black,23
bg engeki_01,23

『さぁっ、レッスンレッスン！@　浮かれないで！@　基礎を忘れずに！』@
『……楠木の実力を見誤ってたよ。@これまでを申し訳なく思う…。』\

ld r,MID_Def3,22

『いいんですよ、部長。@私、これからもお稽古をがんばって、もっともっと素敵な演技が出来るように努力しますね。』\

『さすがみどり姫～……。@何であんな素敵な子が同じ部にいるのに、私たちはずっと気付かなかったの？』@
br
　教室でも部室でも、みどりを賞賛する声が溢れる。\

bg black,22

　それらはみどりに自信と勇気を与えた。@
br
　そしてみどりも慢心することなく、稽古に励み。@何より、誰からも愛される自分になろうと、心を入れ替えた。\

　心が変われば、それは身体も変わる。\

;bg white,28
bg black,0
ld r,MID_Def1,22

　いつも俯いて猫背だった背筋はピンと伸び、美しい姿勢に変わった。\

bg rouka_02,0
ld r,MID_Def5,22

　声にも凛とした響きが宿り、その声を聞いた人は思わず振り返らずにはいられなくなった。@
br
　顔も、誰もが溜め息を漏らしたくなるほどに美しく変わっていった。\

ld r,MID_Def3,22
cl r,22

　もう、一学期の彼女とはまるで別人。@
br
　まさに、彼女は生まれ変わったのだ。\

bg black,22
bg white,29
bg air_02,2

　今日もみどりは部活動に勤しんでいる。@
br
　校庭を走り込んでの体力作り。@
　他の部活の子たちが、みどりの姿が見える度に、手を振ったり声援を送ったりする。\

　………私、本当に幸せだ………。@
br
　みどりはこうして、……誰からも愛される“姫”になったのだ……。\

















bg black,22
bg gakkou_03,22

me1v 17,50

「…………たった一つの小さな切っ掛けで、ニンゲンはここまで変われるものなのですねぇ。」@
br
　校舎の物陰で、誰にも見えないティーカップが、ツイっと傾く。\

ld r,SIN_def2,22

fede 1,1000
E_B

wait 1000

ld r,SIN_def4,80

「ですが、みどりさん？@　一応、これ。@……ギブアンドテイクですので、@その辺りだけは、お忘れないようお願いしますよ。@……っくっくっく。」@
br
　もう一度、ティーカップが、ツイっと傾いた。\

cl r,22










bg black,2

E_A

bg white,1
bg engeki_01,22

「結構ですっ。」@
br
　先生がパンと手を打つ。\

　……私は魔女役の演技を止めた。@
br
　しばしの沈黙の後、先生と部長が無言で頷き合う。\

bgm1 5

「合格です。@楠木さん、あなたを『六軒島』の主役に決定します。」@

ld c,MID_Def3,22
;ld c,MID_Def1,80

「あ、ありがとうございますっ。」\

「みんなも楠木の演技をよく見て、各自、自己研鑽に励めよ…！！」@

;quake 2,200

「「「はいッ！！！」」」\

bg black,24
bg engeki_03,24
se1v 54,70

「みどりっ、魔女役おめでとう！！」@
br
　温かな拍手が広がっていく。\

　そんなに思い切り叩いたら、手が痛くなるんじゃないのと、@こっちが心配してしまうほどの大きな拍手だった。\

「あの可憐なみどり姫が、今度はミステリアスな魔女役に挑戦なんて…。@すっごい反響がありそうだね！」@
「もちろんっ。@みどり姫が主演の大作だもん。@すごい話題になるよ！」\

「発表会、ものすごい盛り上がりそう！@　うわぁ、今から緊張するー！」@
「……わ、私たちも、足を引っ張らないようにしないとねー。」\

ld r,MID_Def1,24

　拍手の中、花道を歩くかのような気持ちで、……私は自分の座る場所に戻る。\

　………前回は、突然の降板による穴埋めの抜擢だった。@
br
　しかし今回は違う。@実力で役を掴み取った。@
　たった一段だけれども、確実に踏み越えた。@そんな達成感があった。\

　………みんなの拍手に包まれながら、座る時。@
br
　また、………川田のぞみと目が合った。\

bg black,22
;ld r,MID_Def1,80

　みんなは満面の笑みで祝福してくれているのに、………彼女だけは違った。@
br
　ただ、ジッと私を見ていた。\

　その瞳からは何の感情も読み取れない。@わかるのは、祝福の気持ちがないということだけ。@
br
　……そんな彼女の姿に、まるで一学期の頃の自分を見ているような、@……不安と焦燥を覚えてしまう。\

;bg black,22
mono 2
bg Different_spiral_1a,22

　何で、そんな嫌な目でずっと私を見ているの…？@
br
　………わかってる。@……私が、妬ましいんだよね……？\

;bg Different_spiral_1b,22

　かつては自分がお姫様だとちやほやされてたのに、@……今ではお金持ち自慢の高慢ちきだと嫌われ、いじめられ。@
br
　……それがかつての自分そのものだから、……痛いくらいに彼女の胸中がわかるのだ。\

bg black,22
mono 0
;bg white,28

　でもね、川田さん。@
br
　変われるよ、人間は。@
br
　あなたは、かつての私。\

　その私も、たった一度のチャンスで、自分が生まれ変わるほどの変化を得た。@
br
　ならあなたにだってきっと。@そんなチャンスがやがてあるよ……。\











E_A

bg "BMP\background\efe\red1.bmp",1
bg engeki_03,22

wait 2000

ld r,MID_K2,6

me1v 28,70

「…………痛ッ、…………………。」\

　その時、何の前触れもなく、また、………痛みが走る。@
br
　足に、思わず身をよじってしまうような激痛が。\

bg black,23
bg engeki_01,23

「……ちょっと、みどり。@……大丈夫…？」@
「顔色悪いよ？」@

ld c,MID_Def2a,22

「………ん、……大…、丈夫…………。」\

「保健室行った方がいいよっ。@私、付き添うよっ。」@
br
　みんながみどりの身を案じる。\

bg black,22

　もう何度目になるかもわからない、突然の謎の痛み。@
br
　……良い機会かもしれない。@一度、保健室で見てもらおう。\

　きっと、緊張のし過ぎなんだ。@普通の人は腹痛に出る。@……私はきっと、それが体の痛みに出るタイプに違いない。\

　リラックスしてれば大丈夫と、保健の先生に太鼓判を押されれば、またがんばれる…。@
br
　みどりは部員の肩を借りて、保健室へ向かうのだった……。\

fede 0,1000
E_A
wait 1000






bg gakkou_02,22

me1v 31,50

wait 2000

bg hoken_01,22
ld r,HOK_Def1,22

me2v 11,90

「特に異常はないみたいね。」@
br
　保健室の先生はあっさりとした口調でそう言った。@
　足に感じていた痛みは、保健室にくるまでに完全に消えていた。\

ld r,HOK_Def4,80

「何もないのに、突然、痛くなるなんて。@………もし、頻繁に繰り返すようなら、大きな病院で見てもらった方がいいわね。」\

ld l,MID_Def2,22

「い、いいえ、大丈夫です。@私、緊張したり疲れたりすると、痛みを感じるタイプなんだと思うので……。」@
br
　それを友達が大袈裟がっちゃって。@……大騒ぎしちゃってすみませんでしたと、みどりは謝る。\

bg black,22

　病院には行きたくなかった。@
br
　もしも本当に何か悪い病気だとしたら、発表会に出られなくなるかもしれない。@
　せっかく主役を演じることが決まったのに、それだけは絶対にごめんだった。\

bg hoken_04,22
;ld r,HOK_Def1,80

　もう平気だと言われては、保健の先生に何も出来ることはない。@不思議なこともあるものだと、鉛筆を鼻の下に挟んで小首を傾げる。\

　特に異常はない。@……その言葉にみどりは少し安堵するが、@ならばこの痛みの正体は何なのかと、かえってもやもやした気持ちになるのだった。\

fede 11,1000
E_M1






bg black,22

　かつては十日くらいに一度、唐突に痛む程度だった。@
br
　しかし、少しずつその頻度が増えてきた気がする。\

　痛みも、かつては触る程度や、あるいは鈍痛程度だったのに、@最近は顔をしかめてしまうような激痛も多い。\

　これからは、発表会に向けて、ますますにお稽古に集中していかなければならない。@
br
　なのに、このおかしな痛みがどんどん酷くなっていったら、きっと差し支えるに違いない……。\

bg hoken_02,22
;ld l,SIN_Def1,24

E_A

「…………気にしないことですよ。@/
bgm1 18
痛みなどに、かまけているほど貴方はお暇ではないでしょう。」@

ld r,MID_K1,22

「紅茶紳士さん……。」\

ld l,SIN_Def2,22

「あの、舞台の上での集中力を忘れてしまいましたか？@　貴方は発表会に向けて、役作りに励まねばなりません。@それが疎かだから、痛みなどというものが気になってしまうのではありませんか？」@

ld r,MID_Def2a,80

「……………………。」\

　痛みのことなど気にするな。@
　紅茶紳士さんは、いつもそう言う。\

;ld r,MID_Def1,80

　確かに、気にしても仕方がないのなら、彼の言う通りだ。@
br
　結局は、自分の集中力が足りないから。@
　舞台のことだけを考え、お稽古に専念したなら、こんな痛み、気にもならないはず……。\

bg black,23
bg hoken_01,23
;ld r,HOK_Def1,23
;ld l,MID_Def1,23
;ld l,MID_Def1,80
;cl l,4

　みどりはそう納得し、先生に頭を下げてから保健室を出る。\

;bg black,24
;bg hoken_02,0
;ld c,SIN_Def1,24

　……紅茶紳士はそれを背中で見送りながら、紅茶のティーカップを傾ける。\

ld c,SIN_Def2,22

「そうですか。@……痛みの頻度が、増しているのですか。@……っくっくっく、それは困りましたねぇ……。@っくっくっくっく……。」\

ld c,SIN_Def4,22

cl c,2

　人ならざる者にしか聞こえない笑い声を残し、紅茶紳士の姿は消える。\

fede 0,1000
E_A

　………人ならざる者にしか、聞こえない。@
br
　だから、それを人ならざる者が聞いていた。\

bg black,22
bg hoken_04,22
ld_p MAR_Def4
lsp2 2,$ld_pass,10,400,-100,100,0
lsp2 3,$ld_pass2,10,400,-100,100,0
print 22

ld_p MAR_Def4a
lsp2 2,$ld_pass,90,400,-100,100,0
lsp2 3,$ld_pass2,90,400,-100,100,0
print 3

bgm1 14

「……………………。」@
br
　薬品棚の物陰から、恐る恐る毬枝が顔を覗かせる……。\

　その手には、職員室かどこかからちょろまかしてきた、栗饅頭が握られている。@
br
　……美味しそうなお茶菓子を見つけたので、彼岸花にお裾分けを持ってきたのだ。\

　ちなみに、毬枝にはどういうわけか、お茶菓子を発見するという奇妙な才能が、……死後に発現したのだった。\

　彼岸花は留守だった。@
br
　代わりに、………見慣れない男の姿を見てしまった。\

csp2 -1

ld c,MAR_def4a,22

;ld_p MAR_Def1
;lsp2 2,$ld_pass,90,400,-100,100,0
;lsp2 3,$ld_pass2,90,400,-100,100,0
;print 80

「……誰、……だろう。@……今の人は……。」@
br
　人ならざる者の直感が、紅茶紳士もまた同類であることを毬枝にも報せる。\

　……妖怪だろうか。@
br
　先に出て行った女の子に、取り憑いてるように見えた。\

;ld_p MAR_Def1
;lsp2 2,$ld_pass,90,400,-100,100,0
;lsp2 3,$ld_pass2,90,400,-100,100,0
;print 80

ld c,MAR_def1,80

「…………………………。」\

bg black,2

fede 0,1000
E_A












bg engeki_01,22

bgm1 5

　翌週から始まった『六軒島』の稽古は想像以上に大変だった。@
br
　まず、何よりも台詞が多い。@一人芝居と言っても過言ではないほどに、主役の台詞量が膨大なのだ。\

　覚えるだけでも大変だし、@その一つ一つの言葉の意味をきちんと理解した上で、感情を込めねばならない。@
br
　１シーンだけでも相当な集中力を必要とする。\

　相手役との呼吸が一つ合わなかったりするだけで、@途端に台詞が出てこなくなったり、小道具の扱いを間違えてしまったりする。\

se1v 19,50

mbg white,1
mcbg 22

「ほら、楠木さんッ。@体だけで演技しては駄目！@　心から演技しなさいッ！@　もう一度やり直し！！」\

「……みどり、すごいよね。@よく、あんな長い台詞、覚えられるよ…。」@
「大変な役だよね…。@あんなのみどり姫以外には不可能だよ……。」\

　部員たちはみどりの演技を素晴らしいと褒めるが、先生は容赦ない。@
br
　無論、みどりも、その期待に応えるため、全力で稽古に臨んでいた。\

　……かつては、好きな演劇のためとは言っても、体力作りや柔軟などは苦手だった。@
br
　でも、今は全然、苦にならない。\

　あの日の、舞台での感動が、眩しく記憶に焼きついている。@
　あの感動をもう一度得られるなら、どんな苦しい稽古にだって耐えられる。@
br
　そんなみどりが流す汗は、透き通っていて輝いていた。\

bg black,24
bg engeki_03,0
ld r,MID_Def1,24

me1v 11,90

「…………ふぅっ……。」@
br
　一息入れて汗を拭っていると。@………部室の片隅で衣装の綻びを直す、川田のぞみの姿が目に入った。\

mbg black,22

　……彼女は今回も、何の役も得られなかった。@
br
　誰もが予想した通り、今回も雑用係を押し付けられた。\

　発声練習も柔軟体操も、何の役にも立たない。@
br
　相変わらず、ひとり暗く孤立して、……時折、私に妬みの眼差しを向ける。\

ld r,MID_K1,0
mcbg 22

　……川田さん。@妬んだって、何も変わらないんだよ。@
br
　そうやって、押し付けられた仕事だけを、渋々とやっている内は、何も変われない。\

　……私だって、かつては雑用係だった。@夜の遅くまで小道具作りをさせられた。@
br
　でも、夢は諦めなかった。\

　こっそり台本を読み、お姫様役の台詞を全て頭に叩き込んだ。@
br
　誰もいない薄暗い部室の鏡に向かって、たったひとりでずっとずっと稽古をしてきたのだ。\

;bg white,28

bg black,22

　だからこそ、……突然の抜擢にも応えることが出来たのだ。\

　……私だって、みんなを妬んだことはある。@でも、努力をしたんだよ。@
　努力をしなきゃ、チャンスだって掴めないんだよ。@
br
　私は掴んだ。@だから手放さない。@全力で、……自分とその役を、全うするからね。\

;bg black,28
bg engeki_03,22
;ld r,MID_Def1,22

　のぞみが顔を上げる。@……目が合った。@
br
　その目は、無気力で、相変わらず何を考えているかわからない。\

;ld r,MID_Def1,80

　……でも、今日は何か違う。@
br
　少し、ぞっとするものを感じさせた。\

bg black,22

fede 0,1000
E_A

me1v 16,50







　彼女が訴えるのだ。@……彼女の、目が。@
br
　………私だって、……ただ妬んでるだけじゃ、ないんだよ、……と。\

　のぞみの傍らに、開いたままの『六軒島』の台本が、そのまま伏せて置かれている。@
br
　衣装の綻びを直す仕事に、台本が必要とは思えない。\

bgm1 6

bg engeki_03,2









　彼女は、ただ妬んでいるわけではない。@
br
　……うかがっているのだ。@……虎視、眈々と。@
　誰もが私以外に適任はいないと言って、“諦める”魔女の役。\

　もし、……私が、発表会の直前に、……体調不良か何かで、突然、降板するようなことになったなら。@……誰にも代役を務めることは出来ない。@
br
　……私が、……落ちることを見越して、……耽々と台本を読んでいる彼女を除いて……。\

bg black,22

me2v 17,70

mono 2
bg Different_spiral_1a,22

　そうか……、そういうことか………。@
br
　みどりは根拠なく、理解する。\

　日ごとに増していく謎の痛み。@
br
　……きっとこれは、川田のぞみの呪いか何かなのだ。\

;bg Different_spiral_1b,22

ld r,MID_K2,22

　私が突然のお姫様役の降板によって、大抜擢を受けたように。@……彼女も私が、突然降板することを願っているのだ。\

　楠木みどりに出来たことなら、自分に出来ないはずはないとでも言うつもりだろうか。@
br
　……無感情な、……見ているだけで不快になる、その眼差し。@
　きっとそれが、……私に、おかしな痛みを送っているに違いないのだ……。\














bg black,22
mono 0

fede 1,2000
E_B

me5v 24,50

fedexx 0,0,0,0,0,50,2000

E_M1
E_M2

「みどり？@　どしたの？」@

bg white,1
bg engeki_03,0
ld r,MID_Def2a,22

「………っ。」@
br
　友達に呼ばれ、我に返る。\

　……川田さんが、私に呪いを送って、それで体が痛むなんて、@……私もおかしなことを考えてしまう。@……疲れてるのかな。\

　でも。@
br
　私に、紅茶紳士さんという不思議な存在が現れて力を貸してくれたのだ。@
　彼女にも、不思議な何かがあったとしても、おかしくはないのかもしれない。\

bg black,22

;ld r,MID_Def1,80

　……うん。@紅茶紳士さんの言う通りなんだ。@
br
　気にしたら負けだ。@彼女が私の代役を狙っているかどうかなんて、関係ない。@
br
　私が完璧な魔女役で、発表会に臨むだけのこと。@全ては、私個人の問題なのだ。\

;ld r,MID_Def1,80

　……気にしたら負けだ。@……負けて、堪るか……。@
br
　そうとも、川田のぞみの不気味な眼差しに怯えている時間など、私にはないのだ。\

;bg black,2

fede 0,2000
E_A














bg engeki_01,22

bgm1 8

　発表会に向けた、猛稽古の日々が続いた。@
br
　一分たりとも無駄にできる稽古などなく、時間が経つのが本当にあっという間に感じられた。\

bg black,22
bg Air_01,22

　部活を終えて家に帰る頃にはいつも夜。@夕食もそこそこに済ませると、ベッドに倒れ込み泥の様に眠ってしまう。@それの繰り返しだった。@
br
　体力的には辛いけれど、……最高に充実した日々だった。\

bg black,22

　………痛み。@……それさえなければ。@
br
　あの不思議な痛みの間隔が日に日に短くなっていた。\

bg "BMP\background\efe\red1.bmp",1
bg engeki_02,0
ld c,MID_K2,2

「……みどり？@　どうしたの？」@

ld c,MID_Def2a,80

「…………何でもないの…。@ごめんね……。」\

　あまりに頻繁が過ぎると、周りに不審に思われてしまう。@
br
　すでに一度、保健室沙汰になっているのだ。@……騒がれたら、降板させられてしまうかもしれない。\

bg black,23
bg rouka_02,23

me1v 16,50

　お手洗いに行って来るからと誤魔化し、ひとりになる。\


　さっきの激痛も、……いつもと同じ。@
br
　相変わらず傷らしい傷はどこにもない。\

　……もう、嫌になる。@
br
　一度は振り払った考えだけれど、……やはりこれは、川田のぞみの呪いなのだろうか。\

　だって、痛みはいつも、学校にいる時に限られる。@
　さらに言えば、川田のぞみが近くにいる時に感じることが、多い気もする。@
br
　この痛みの時も、振り返ったら彼女の眼差しがあったから。\

bg black,22
mono 2
bg Different_spiral_1a,22

me2v 17,50

　……やっぱり。@
br
　負けて堪るものか、……堪るものか……。\

　私は絶対に発表会に出る。@降板など絶対にしない。@
br
　一度掴んだチャンスは、絶対に手放さない。\

;bg Different_spiral_1b,22

bg black,22
mono 0

　……悪いけれど、……川田さんに、絶対に譲るものか………。@
br
　発表会までもう何日もない。\

;bg black,22
;bg rouka_02,0
ld r,SIN_Def4,22

「気にしないことです。@そのようなことに、心を割く余裕など貴方にはないではありませんか。」@
br
　紅茶紳士さんは繰り返す。@気にしないことですと。\

bg black,22

　……気にしない、気にしない。@
br
　おかしな痛みなどに……、負けるものか………。\

fede 1,1000
E_B

　しかし。@
br
　私を蝕む謎の呪いは、……“痛み”だけではなかった。\

fede 0,2000
E_A












bg kyou_01,22

me1v 24,50

　それはある日の給食の時間だった。\


　給食係によそってもらったカレーを持って席に戻ると、@サキエやフミエら、他の取り巻きたちが一斉に集まってくる。@
br
　囲まれながらの楽しい昼食。@……いつもの光景だった。\

「姫、大丈夫？@　最近、顔色良くないみたいだけど……。」@

ld r,MID_Def2,22

「そ、そう…？@　気のせいよ。@気にしないでね。」\

「稽古、ほとんど毎日なんでしょ？@　無理しないでね。」@
「だけど、みどりが主役の舞台が見れるなんてすっごい楽しみ。@今週末だよね？@　頑張ってね、みどり！」\

ld r,MID_K1,22

　痛みの呪いは、やはり私を疲弊させているようだった。@
br
　素振りを見せているつもりはないのだが、@いつも身近にいるサキエたちにはわかるようだった。\

　……お姫様が病気、なんてことになったらきっと、みんな大仰に大騒ぎする。@
br
　そうしたら演劇部にも話が届いて、………先生や部長の耳にも入って……。\

bg black,22

　………冗談じゃない。@
br
　絶対に降りない。@……発表会で、舞台の中央でスポットライトを浴びるのは私なんだから。@
br
　こんな呪いに、………川田のぞみに、………負けるものか……。\

bg kyou_01,22

「ねーねー、昨日の『シーキャット』のアニメ見たぁ？」@
「見た見た！@　欠かさず見てるよ～！@　声が素敵だよねっ、斧さん最高～！」@
「ってゆうか、声優みんなすごいよね！」@
「ねぇねぇ、みどりは誰が好き？！」\

ld r,MID_Def2a,22
;ld r,MID_Def1,80

「……え？@　………あ、……うん。@私、帰るの遅いから、ほとんど見てないの。」@
br
　毎日、遅くまで稽古なので、帰る頃にはとっくに放送が終わっているのだ。\

　好きな作品だけれど、今はまったく興味ない。@……発表会に、集中しなきゃ。@
br
　サキエたちは、私が連日の稽古で疲れているのだろうと察し、自分たちだけで勝手に盛り上がってくれた。\

　私はそれをぼんやりと聞きながら、作業の様に給食を口に運んだ。@
br
　安っぽいカレーの味が口の中に広がる。\

ld r,MID_K1,22

　食欲は全然なく、一口食べるのにもかなりの時間がかかった。@
br
　でも、無理矢理でも食べなければならない。\

　今週に入ってからは毎日のように本番用の衣装を着けて通し稽古をしている。@食べなければ身体が持たないのだ。\










E_A

mbg "BMP\background\efe\red1.bmp",1
quakex 1,100
mcbg 22
ld r,MID_K2,80

bgm1 11

　その時、……またあの、呪いの痛み。@
br
　今度は後頭部だった。@誰かに激しく叩かれたかのような痛み。\

　どうせ振り返っても誰もいないので、もはや私は振り返りさえしない。@
br
　代わりに、川田のぞみの背中を憎々しげに睨むのだ。\


mbg black,22

　……悔しい。@
br
　何の証拠もない。@でも、絶対に川田さんのせいだって、わかってる。\

　でも、気にしたら負けだ。@
br
　こんな呪いで、私を妨害することが彼女には関の山なのだ。\

ld r,MID_K3,0
mcbg 22

　あんたなんかに、私の役は譲らない。@……負けるものか、絶対、絶対。@
br
　下唇を噛み締めながら、……目を給食に戻す。\

mbg white,0
print 99,2000,"trvswave.dll/l"
print 1

me1v 17,50

　すると。@……ゆらりと、……給食のカレーが、歪んだ気がした。@
br
　湯気とか、そういう感じじゃない。@……疲れ目？@　……そんな感じだった。\

cl r,0
mcbg 22

　私は霞んだ目を擦り、違和感を感じるそれを凝視する。@
br
　……たった今、自分が食べている、給食のカレー。@
　そこに、……ゆらりと、………黒い物が混じるのだ。\

;ld r,MID_Def1,80

bg black,22

fede 0,1000
E_A

　中から浮いてきた？@　……そんなはずない。@
br
　でも……、……そのカレーには、……無数の、……/
se1 34
虫の死骸があった……。\

bg aka2,1
quakey 3,200

「ッ？！@/
bgm1 12
　……………………ッ！！！」@
br
　あまりの驚愕に、窒息しそうになる。@
br
　カレーの上には、……紛れもなく、それらがぶちまけられていた。\

　私が川田さんを睨んでいる間に誰かが悪戯したとか、カレーの下から浮いてきたとか、@そんなことは断じてありえない。@
br
　私の目の前で。@それはゆらりと、現れたのだ……。\

me1v 28,90

　てらてらと黒光りする虫の背中。@節の様な足、髪の毛の様な触覚。@
br
　それらが茶色いカレーのルーと白いライスに混じっている壮絶な光景。\

　私の手はスプーンを握り、そこにずっと突き立てたままだった。@
br
　さっきまでそれは、カレーの中に突き立てられていたのだ。@
br
　しかし今は、カレーだけじゃない。\

me2v 3,90

　……先割れスプーンは、……深々と、……黒い昆虫に、……突き刺さっていて。@
br
　そこから、何色とも形容し難い、体液と内臓を溢れ出させているのだ……。\

;bg black,22
bg kyou_03,1
quakey 3,300

me3v 16,90

　私は食べていた物を全て吐き出しそうになり、慌てて口を押さえる。@
br
　目の前にあるそれのせいだけで、嘔吐を覚えたわけじゃない。\

　……さっきまで食べていた物の中にも、……それが混じっていたのではないかと感じて、@……ぅ、……うぅううぅぅ……。\

bg black,22

「ちょっと、大丈夫？！」@
「どうしたの、みどり？！@　気分悪いの？！」@
br
　みどりの様子にサキエたちが気付き、不安そうに声を掛ける。\

　……やっぱり。@彼女らには、このカレーの異常が見えていない。@
br
　痛みと同じ。@……私だけに感じられる、“呪い”なのだ。\


bg kyou_01,22
ld l,SIN_Def1,22

「どうなさいましたか？」@

ld r,MID_K2,22

「……紅茶紳士さんにはこれ、……見えていますか。」\

ld l,SIN_Def2,80

「…………………。@私から貴方に申し上げることはただ一つ。」@

ld r,MID_Def4a,80

「気にしないことです…？」\

ld l,SIN_Def4,80

「っくっくっくっく。@その通りです。」@
br
　紅茶紳士さんは他人事のようにくすくすと笑う。\

　……見えている。@
　彼にも、このカレーの惨状が見えているのだ。@
br
　その時、……私の頭の中で、……嫌なピースが合わさり、一つの想像を形作る。\

ld r,MID_K5,80

「……紅茶紳士さん、ですね……。」@

ld l,SIN_Def1,80

「おや。@何の話ですかな？」\

bg black,22
bg kyou_02,22

;ld r,MID_Def1,80

「………惚けないで下さい。@……あのおかしな痛みも、このカレーも。@……紅茶紳士さんの力じゃないんですか。」@

;ld l,SIN_Def1,80

「これはこれは。@心外ですねぇ。@どうして私がそのような真似をするのですか…？@　私は貴方の味方ではありませんか。」\

;ld r,MID_Def1,80

mbg black,22

「…………確かに、私の味方だと思います。@……でも、ひょっとして。@……他にも味方している子が、……いるんじゃありませんか？」@

;ld l,SIN_Def1,80

「おや。@それはどういう意味ですかな…？」\

mcbg 22

ld c,MID_K5,22

「演劇部で。@……私に出会い、力を貸してくれたように。@………川田さんにも出会って。@……何かの力を貸したんじゃないですか。」\

ld r,SIN_Def4,22

「なるほど。@……川田さんが主役の座に就けるよう、貴方を降板させようと私が企んでいると。@なるほどなるほど……、っくっくっく。」@
br
　紅茶紳士さんは意味深に笑う。\

cl c,0
ld l,MID_K5,24

　……今まで、彼を恩人と思ってきたけれど。@彼は正体不明の、人ならざる者なのだ。@
br
　私に気紛れに力を貸してくれただけで、……味方のつもりなんて、初めからないのだ。\

ld r,SIN_Def1,80

「みどりさん。@それはとても心外な想像です。」@

ld l,MID_U1,80

「……だって、そうじゃなきゃ説明がつかないッ！」\

ld r,SIN_Def3,80

「みどりさん。@……私は貴方の味方です。@だからこそ、こうしていつも、貴方の側にいるのではありませんか。」\

ld l,MID_K3,80

「…………川田さんの呪いのために、……私に取り憑いてるのかもしれないです。」\

ld r,SIN_Def2,80

「………………………。@私は、貴方の味方です。@そして、貴方が耳を貸さないとしても、同じことを言いましょう。」@

ld l,MID_K5,80

「“気にしないことです”？」\

bg black,22

;ld l,SIN_Def1,80

「その通りです。@そして、それ以上の何も申し上げるつもりはありません。」@

;ld r,MID_Def1,80

「……おかしなことが起こっても、何も気にせず、発表会へのお稽古に励めと…？@　……こんなおかしなことが繰り返し起こるんじゃ、集中なんて出来ない！！」\

ld c,SIN_Def2,22

「ならばお稽古を止め、主役を川田さんに譲るのですか？」@

;ld r,MID_Def1,80

「そ、そんなことはさせない…！@　主役は私…！@　私が掴んだ役！@　絶対に私が演じてみせる…！」\

bg Aka1,0
ld c,SIN_Def2,22

ld c,SIN_Def4,80

「っくっくくくくく……。@……良いことを仰います。@その通りです。@主役は貴方。@誰にも譲ってはなりません。」@

;ld r,MID_Def1,80

「あなたが、……何を考えているのか、私にはわからない…！」\

bg black,22

fede 0,2000
E_A










;bg black,26

se1v 13,50

bg kyou_03,1
quakey 2,200

　みどりは勢い良く立ち上がる。@

me1v 24,50

br
　その荒々しさにみんなが驚くが、みどりは何も気にしない。\

　食べ掛けの給食を乱暴に持つと、残飯入れの中に食器ごと突っ込む。@
br
　そしてそのまま、教室を飛び出していった。\

bg black,22

fede 0,1000
E_A

bg kyou_01,0
ld c,SIN_Def2,22

bgm1 13

「……っくっくくくくくくくく。@……やれやれ。@若々しいですねぇ。」@
br
　紅茶紳士は肩を竦めて笑う。\

se1v 22,50

mbg white,9
mcbg 22

　……彼の目には、不思議なものが見えていた。@
br
　荒々しく席を立ち、教室から出て行ったみどりは、@全身からうっすらと、湯気かお線香の煙のようなものを棚引かせていた。\
　それは人ならざる者の目にしか見えない。@
br
　紅茶紳士は空のティーカップをふわりと持つと、@……その煙のようなものが、すぅっと集まり、カップに満たされていく。\

　そしてそれは渦を巻きながら茶色く透き通り、@……彼好みの、鮮烈な香りを放つ、良い紅茶となった。@
br
　一口すすり、にんまりと笑う………。\

ld c,SIN_Def4,80

「……実に初々しい味わいです。@……みどりさん。@貴方の魂は、……実に良い香りの紅茶になりますよ。@っくっくくくくくくくく………！」\

bg black,2

fede 0,2000
E_A

wait 2000










bg rouka_02,22

me1v 16,50

　みどりは小走りで部室に向かった。@
br
　まだ昼休みではあるけれど。@
　稽古がしたかった。@演劇がしたかった。@誰か他の人間を演じたかった。\

se1 82

bg white,63
bg engeki_01,22
;quakex 1,100

　部室へ飛び込む。@
br
　教室の並びから離れているため、昼休みの喧騒が遠くて、それだけでも心地良かった。\

　みどりは部室の奥にある衣装置き場にまっすぐ向かう。@
br
　そして主役の衣装である、ドレスを手に取り、@まだ昼休みであるにも関わらず、着替え始める……。\

bg black,24
bg engeki_04,0
ld c,MID_Def2a,24

「………私が主役、……私が主役……。@……誰にも譲らない、……誰にも譲らないッ……。」@
br
　お気に入りのワンピースを脱ぐ。\

;bg white,28

bg black,1

　その時、……鏡に映る自分の姿を見て、……みどりは息を呑んだ。\

E_A






se1 24

bg aka2,1
quake 3,300

「な、………何よ、………これ………。」@
br
　露になった二の腕に、シミの様なものがついていた。@鮮やかな色の何かが。\

　絵の具だろうか……？@　そう思って顔を近づける。\

bgm1 16

「……………何よ、……これ……。」\

　痣だった。@
br
　一つや二つではない。@
　赤、青、紫…………………鮮やかな痣が腕一面に浮かんでいた。@
br
　腕がガタガタと震えだした。\

me1v 17,70

「……なんなのよ、これ。」@
br
　服に覆われて隠れていた部分に、……背中にも、お腹にも。@いくつもの、いくつもの痣が。@内出血の痕が。\

;bg black,22
bg engeki_04,0
ld c,MID_U1,22

me2v 3,70

「何よ、………これ………、…………これ……ッ…！！！」@
br
　静寂の部室に、……みどりの悲鳴が木霊した……。\

bg black,22
bg engeki_01,22

　部室の片隅に浮かぶティーカップが、くいっと傾く。@
br
　衝撃を受けて放心しているみどりには、紅茶紳士の姿は見えていないようだった。\

ld l,SIN_Def1,2
ld l,SIN_Def4,22

「気にしないことですよ、みどりさん。@………もっとも、それを口にしたところで、もう耳には届かないようですがねぇ。@……っくっくっくっくっくっく！」\

;ld r,MAR_Def1,42

mbg black,22

E_A

「……その子を、そっとしてあげて下さい。」\

mcbg 22
ld l,SIN_Def1,80

me1v 17,50

「………おや。」@
br
　紅茶紳士の前に、……毬枝が、ゆっくりと姿を現す。@
　鋭い目線で、紅茶紳士を睨んでいた。\

ld l,SIN_Def4,80

「学校妖怪、序列第８位の。@……めそめその毬枝さんではありませんか。」\

E_A

bgm1 15

ld r,MAR_i4,2
ld r,MAR_i3,22

「……妖怪ですね。@あなたも。」@

ld l,SIN_Def2,80

「えぇ。@ご同業ですよ。@……ニンゲンから魂のささやかなカケラをお譲りいただき、糊口を凌ぐささやかな存在です。」\

ld r,MAR_i1,80

「楠木みどりさんは、がんばり屋さんで、とても心の綺麗な女の子です。@……今も、発表会に向けて一生懸命、努力しています。」@

ld l,SIN_Def3,80

「えぇ。@それは誰よりもよく承知しておりますよ……。」\

bg black,22

;ld l,MAR_Def1,80

「そんな彼女をいじめて、……楽しいですか。」@

;ld r,SIN_Def1,80

「それは誤解ですねぇ。@どうして私がみどりさんをいじめるのでしょうか。」\

bg engeki_03,22
ld l,MAR_i3a,22

「……彼女の魂を、あなたは食べています。@……これは、あなたの狩りです。」@

ld r,SIN_Def2,22

「ささやかなものでしょう？@　強欲な学校妖怪たちと違い、私は命を奪うようなことは好みませんので。」\

ld l,MAR_i4,80

「………はい。@だから、もうこれで。@……彼女を見逃してあげて下さい。」@

ld r,SIN_Def3,80

「見逃す、とは……？」\

bg black,23
bg engeki_01,0
ld c,MID_K2,23

wait 1000

;ld l,MAR_Def1,80

「彼女をずっと見てきました。@……おかしな呪いは日増しに酷くなり、彼女を追い詰めています。@……彼女は発表会で最高の演技をしたいだけ。@あなたの呪いが、それを妨げようとしています。」\

;ld r,SIN_Def1,80

「痛みとやらが気になるのは。@彼女の集中力が足らないからに他なりません。@……彼女が演技について本当に集中してくれたなら、気になるようなものではないのですが。」\

mld r,MAR_i3,22

「………もう一度言います。@みどりさんを、見逃してあげて下さい。」@

mld l,SIN_Def3,22

「出来ませんね。@彼女は、私の獲物です。」\

;bg black,24
;bg engeki_02,0
mld r,MAR_i2a,80

「………なら。@……学校妖怪のルールに、従わせてもらいます。」@

mld l,SIN_Def2,80

「ルール？@　はて。@如何なる束縛も嫌う私たちが、何のルールを？」\

mld r,MAR_i3a,80

「誰を獲物とするも自由。@……そして、誰の獲物を奪うも、自由。」\

mld l,SIN_Def4,80

「くっくくく。@っくっくくくくくくくくくくく！@　なるほどッ、確かに妖怪が従う、唯一のルールですねぇ。」@
br
　紅茶紳士は、一本取られたとでも言うように肩を揺すって笑う。\

mcl a,0
bg black,23
bg engeki_02,23
ld c,MAR_i4a,22

「妖怪にも、生きるために魂を食らわねばならない都合があることはわかっています。@……だから、ここで引き下がってくれれば、私も事を荒立てません。」@
br
　毬枝は強い意思の宿る眼差しで、紅茶紳士を射抜く。\

ld l,SIN_Def2,22

「これは困りました。@学校妖怪八席のめそめそさんに凄まれては。@序列を持たぬ弱小妖怪の私など、塵にされてしまいますねぇ。」\

ld c,MAR_i3,80

「私だってしたくないし。@あなただって、されたくないはずです。」\

ld l,SIN_Def3,80

「……しかし、みどりさんという素晴らしき茶葉をここで譲るには余りに惜しい。」@

cl c,0
ld r,MAR_i4,23

「………………わかってます。@妖怪同士が、話し合いで決着するわけもないと。」\

ld l,SIN_Def4,80

「………………………たくましい。@元いじめられっことは思えませんね。」\

ld r,MAR_i2,80

「元いじめられっこだからこそ。@………私には人の心が、誰よりもわかるんです。@……あなたはがんばり屋の少女を蝕んでいる。@……そんな努力を蔑ろにしようとするあなたを、私は見過ごすわけには行きません。」\

cl l,0
mld l,SIN_Def1,80

「めそめそさんは、扉を挟んでこそ、真価を発揮する妖怪と聞きましたが…？」@

ld r,MAR_i3a,80

「……仮にも学校妖怪八席。@……あなたを、……この腕で、……駆逐しますッ。」\

se1v 22,50
bg white,8

　いつの間にか、紅茶紳士のティーカップの湯気が、部室中に充満していた。@
br
　それは霧のようというより、@……まるでティーカップから、霧の腕が何本も生え出したかのよう。\

se2v 22,50

mcl l,0
mbg white,0
print 99,2000,"trvswave.dll/l"
print 1

;mbg "BMP\background\efe\red1.bmp",1
;quakex 1,100
;mcbg 22
;;bg black,22
;bg aka2,1
;quakey 1,100
;bg aka3,1
;quakex 1,100


　それらが揺らめき、……爬虫類のように毬枝を睨みつけ、…………襲う。@
br
　何本もの霧の腕が毬枝に飛び掛る。@ぐるぐる巻きにして締め上げる。\

mcbg 0

se1v 20,50
bg black,23

se2v 20,60
bg white,24

se3v 20,70
bg black,23

se1v 20,90
bg white,24

se2v 55,70
quakex 3,300

quakey 3,200


ld l,SIN_Def1,22

「……………………………。」@
br
　紅茶紳士は、ふっと笑う。\

　あっさりと決着がついたから？@　違う。@
br
　わかっているのだ。@仮にも、学校妖怪八席。@……この程度で、仕留められるわけもない。\


mbg "BMP\background\efe\red1.bmp",1
mcbg 22

　毬枝をぐるぐる巻きにしている霧の腕が、……ぶるぶると震える。@
br
　そして、……内側から引き剥がすかのように、……一本一本、……千切られていく。\

ld l,SIN_Def3,80

「……めそめそさんは豪腕怪力の妖怪だそうですね。@……なるほど、恐ろしい力です。」@
br
　繭を内側から破るように。@……激しい音がして、霧の腕が霧散する。\

se1v 55,70

bg white,28

se2v 12,50

bg black,28
bg engeki_02,22

mld c,MAR_i4,25

se3v 13,50
quakey 2,200

　再び姿を見せた毬枝は、@……学校を代表する妖怪たちの末席を務める者に相応しい貫禄を見せていた。\

mld c,MAR_i2,80

「…………私は、まだ自分の力をよくわかっていません。@………私に抱き締められタラ、……手加減は、無理……デス……。」\

me1v 16,70

bg black,2
bg aka1,0
mld c,MAR_o1,2

me2v 28,90

　毬枝の体から、重い冷気が噴出し、床を満たす……。@
br
　鉛のような質量を伴った両腕は、@まるで丸太を思わせるほどの太ささえ感じさせる威圧感を放っていた。\
mcl c,0
bg engeki_01,0
mld l,SIN_Def1,22
;ld l,SIN_Def1,80

「やはり、……敵いませんか。@……では、最後に一花とさせていただきましょう。」@
br
　紅茶紳士が手をかざすと、そこに霧の蛇が巻きつき、……槍のような鋭さを見せる。\

se1v 22,50

bg white,8

ld r,MAR_o1,2

「…………………………………。」@

mld l,SIN_Def2,80

「……おや。@足音が近付いてきますね。@……これ以上、ニンゲンが増えると居心地が良くありません。@この一撃で、決着とさせていただきましょう。」\

　確かに、誰かの足音が近付いてくる。@
　まっすぐ、この部室に近付いてくる。@
br
　それが、二人の決闘の、秒読みとなる………。\

E_A

se1v 82,100

mcl l,0
bg white,64


　がらりと部室の引き戸が開け放たれた瞬間。@/
me1v 28,70
……毬枝と紅茶紳士は、電光のような閃きで交差した。\



ld_p MAR_i2
lsp2 4,$ld_pass,130,550,200,200,0
lsp2 5,$ld_pass2,130,550,200,200,0
print 24

「…………………………。」@

ld_p SIN_Def3
lsp2 2,$ld_pass,480,480,-200,200,0
lsp2 3,$ld_pass2,480,480,-200,200,0
print 23

「………ですよねぇ…………。」\

ld_p MAR_i3
lsp2 4,$ld_pass,130,550,200,200,0
lsp2 5,$ld_pass2,130,550,200,200,0
print 80

「……負けを認めて下さい。@……手加減は、本当に難しいんです。」@

ld_p SIN_Def1
lsp2 2,$ld_pass,480,480,-200,200,0
lsp2 3,$ld_pass2,480,480,-200,200,0
print 80

「恐ろしい。@……これで、………手加減と、……は………。」\

textoff

E_A

csp2 -1
print 0

se3v 20,70

bg white,24
bg black,24
bg engeki_03,24

wait 500

se1v 1006,70
se2v 12,70

quakex 3,300

se3v 13,50

quakey 2,300

me1v 5,50

　雷鳴のような音が轟き、……紅茶紳士の体は、豪腕によって殴り飛ばされたことを、思い出す。@
　一番奥の壁まで吹き飛ばされ、大の字に叩き付けられた。@
br
　紅茶紳士は、見事な一撃です…、と言いながら、親指を立てる仕草をしてみせる…。\

se1v 1100,30
mbg white,1
mcbg 22

　それと同時に、小さな割れる音。@
　みどりに及んでいた紅茶紳士の力が砕け、彼女が解放されたことを示すものだった。@
br
　毬枝は安堵の溜め息を漏らしながら、ゆっくりと両拳の力を抜いていく………。\

bg black,2

fede 0,1000
E_A
wait 1000

bg engeki_04,22

me1v 11,90

「………何やってんの、あんた。」\

　部室に入ってきたのは、……川田のぞみだった。@
br
　そして、ドレスを着て鏡の前に立つみどりを睨み付けた。\

ld c,MID_K2,22

「………川田……さん……………？」@
「………何、勝手に、………人の衣装、着てんのよ。」\

ld c,MID_K1,80

E_A

「え……………………。」@

bgm1 7

br
　川田のぞみが、ぞっとするほど冷たい目でみどりを見下ろしていた。\

「ほら。@………さっさと脱ぎなさいよ。」@
br
　みどりは困惑した。@のぞみがいきなり現れたこともそうだが、@彼女が何を言っているのか、心の底から理解できなかった。\

　……人の衣装？@　人の衣装って何？@　だってこれは私のドレスじゃない。@主役である、私の衣装。\

bg black,22

「何ボーッとしてんのよ。@叩かれ過ぎて頭おかしくなった？」@
br
　川田さんは厳しい口調できびきびと私にそう言い放つ。\

me1v 17,50

　……彼女って、こんなにもはっきりとしゃべる子だったっけ…？@
br
　妬ましそうに、無言でじっと睨むくらいしか出来ない子だと思ってたのに……。\

「とっとと脱げって言ってんのよ。@あんたの臭いニオイが染み付くでしょ。@あんたが私の衣装に触れていいのは、雑用係として手入れをする時だけよ。」\

ld c,MID_Def4a,22

　雑用係……？@
br
　それは、……川田さんのことじゃないの？@　……私は、……主役……。\

bg engeki_01,1
quakex 2,200

「脱げって言ってんのよ…！@　あんたみたいな根暗な子が主役の衣装を着ようなんて、千年早いのよッ！」@

ld c,MID_Def2a,22

「な、………何を言ってるの、……あなた………。」\

「わけわかんねーこと言ってんのはテメーだろーが！@　脱げっツってんだよッ！！」@
br

se1v 8,50
quakex 2,200
cl c,23
se1 13

quakey 2,200

　川田さんは私をどんと突き飛ばす。@
　私はふらりとよろめいて転び、……道具入れの木箱の角に激しく頭をぶつける。\

;se1 1100

E_B

mbg aka1,1
mcbg 22

　その時、……何かが、割れた。@

me2v 16,50

br
　頭蓋骨がじゃない。@……もっと胸の奥の、深いところにある頑丈な何かが、びしりと割れた。\

bg black,22
mono 1

ld l,SIN_def4,22

　紅茶紳士は、一つだけ願いを叶えようと言った。@
br
　どんな役でも一つ、与えてあげようと言った。\

　みどりが選んだ役は、“お姫様”ではなかった。@
br
　彼女が望んだ役は…………。\











bg black,28

mono 0

E_A

se1 1100
bg white,1
bg engeki_01,0
ld r,MID_U1,22

se1 1100
bg white,1
bg engeki_02,0
ld l,MID_K4,22

se1 1100
bg white,1
bg engeki_03,0
ld c,MID_U2,22

se1v 1100,90
bg black,1
bg white,22

bgm1 6

　心の中の亀裂から、次々に、……“真実”が、溢れ出して来る。@
br
　彼女が演じた虚偽ではなく、“本当”が、溢れ出す。\

bg black,28
bg white,28
se1 1100
bg white,1
bg kyou_04,22
se1 1100
bg white,1
bg kyou_01,22
se1 1100
bg black,1
bg white,22


　それはまるで、録画した映像が巻き戻されるかのよう。@
br
　過去の記憶が鮮明に蘇る。@嘘で上書きされる前の、正しい“本当”の姿で。\

bg kyou_02,2

me1v 24,50

　朝、教室に入る私を、クラスメート全員が見る。@そして笑いながら近寄ってくる。@
br
　私を敬愛して、挨拶するためではない。\

　私を、叩くために。@
　笑いながら集まってきて、私を叩いて、叩いて、嘲笑う。\

　宿題やってきたよね？@　サキエが言う。@
br
　そして彼女が差し出すノートを受け取る。@
　私のやってきた宿題を、彼女のノートに写すために。\

mbg "BMP\background\efe\red1.bmp",1
se1 12
mcbg 22

me2v 17,70

　写している間。@サキエが定規を取り出し、私の腕を叩く。@フミエが私の顔面に上履きを投げつけてくる。@
br
　彼女らの宿題をしてあげてるのに、彼女たちは私に酷い仕打ちをするのだ。\

bg black,22

fede 11,1000
E_M1

bg engeki_01,22

　放課後、部室に入る私に部長が言う。\

「楠木、お前も最近遅刻が多いぞ。」@
br
　着替えるのに手間取ってしまって。@私はそう言い訳した。\

　……その私の着ている体操着はシミだらけ。@ついさっきまでゴミ箱にでも突っ込まれていたかのような悪臭がする。\

bg black,22
bg engeki_03,22

　私がストレッチをする場所を探していると、みんなが「臭い」といって一斉によける。@
br
　ぽっかりとあけられた広すぎるスペース。\

mbg "BMP\background\efe\red1.bmp",1
se1 12
mcbg 22

　そこで身体を伸ばし始める私の肩を、部員たちが次々に踏みつけていく。\

　女子の部員たちのひそひそ話が聞こえてくる。\

「雑用係になったら大変だよね。@今回、小道具とかも多そうだし……。」@
「くす。@それは心配しなくても大丈夫でしょ。@ほら、全部一人でやってくれそうな子がいるじゃない。」\

　彼女たちが私を見る。@いくつもの醜い笑いが並んでいる。@
br
　私に役が与えられることなんてない。@……いつだって、万年雑用係なのだ。\

E_MA

se1 1100
bg white,1
bg engeki_01,22

「次。@川田のぞみさん。」@



「はい。@川田のぞみ。@魔女役を希望します。」@
br
　『六軒島』の主役を堂々と立候補する。@みんな拍手でそれを祝福した。\

「のぞみ姫しかありえないよね！」@
「のぞみーっ、がんばってねー！」\

ld r,MID_def4a,22

「………………………。」@
br
　私はひとり、……その背中を、祝福でない眼差しで見つめていた…。\

　次々と配役が決まっていく。@
br
　私も勇気を出していくつかの役に立候補するのだが、@演技が硬い、感情表現がダメとさんざん言われ、どの役ももらえない。\

bg black,22

　結局、当然のように、……雑用係だった。\

bg engeki_03,22
mbg "BMP\background\efe\red1.bmp",1
se1 12
mcbg 22

「あんたが余計な立候補したから、余計な時間を食ったじゃない。」@
「あんたに一番お似合いの役が雑用係なのよ。@それくらいわかれよなー。」\

「がんばってね、万年雑用係～。」@
「二度と立候補なんかしないでよね、ウザイから。」@
br
　みんなが私の背中を蹴りながら言う。@体操着の背中に無数の足跡がついていく。\

bg black,22

　部活の後、私は部室に残ってたった一人で小道具を作り、衣装を縫った。@
br
　その合間に、こっそり『六軒島』の台本を読み、主役の魔女の台詞を口に出して言う。@
　最初は小さく、徐々に大きく。\

se1v 13,30

　やがて私は、………こっそりと、主役のドレスを纏い、たった一人の通し稽古を始める。@

me1v 5,50

br
　相手はいない。@でも、私には見えていたし、聞こえていた。\

bg Different_spiral_1a,22

　……だから毎日、家に帰る頃にはすっかり夜になっている。@
br
　『シーキャット』のアニメなんて、とっくに終わっている。@
　そしてベッドに倒れ込むように横になり、……頭を空っぽにして、泥のように眠った。\

bg black,22

fede 10,2000
E_MA

bg kyou_01,2

me1v 24,50

　給食の時間。@……意地悪な誰かが、虫の死骸を私のカレーに入れた。@
br
　先生に見られないよう、意地悪な女子たちが私を囲むように座り、@……ちゃんと食べるかどうか、見張っていた。\

mbg "BMP\background\efe\red1.bmp",1
se1 12
mcbg 22

me2v 28,70

　いつまでも口にしない私の後頭部を、フミエがトレイで叩く。@痛かった。\

「さっさと喰えよ、金持ち自慢のお嬢様。」@
「良かったじゃん、みどりだけ特別カレーじゃん！」@
「お金持ちなんだから、特別メニューじゃないとねー。」@
「喰えよほら。@健康にいいと思うよー、マジで。」\

　私へのいじめは、１学期と何も変わっていなかったのだ。@
br
　何も、何も。\


bg black,24
bg kyou_02,24

me3v 16,70

　そんな中、……川田のぞみは、お姫様だった。\

　“お姫様”役で、学校中で大人気でちやほやされてて。@
　羨ましかった。@妬ましかった。@
br
　舞台の中央はいつも彼女のものだった！\

bg black,22

me4v 3,70

　だから、紅茶紳士に何の役を演じたいのかと問われて、私は答えたんだ。@
br
　私は、川田のぞみになりたいって……！\

fede 10,2000
E_MA

bg engeki_04,6
;ld c,MID_def1,6

　後頭部から血を滴らせ、……魔女のドレスを血に染めながら。@みどりはゆっくりと立ち上がる。@
br
　そして、壁に寄り掛かり、苦しそうにしている紅茶紳士の姿を見つけた。\

bg black,24
bg engeki_03,24
;ld l,SIN_Def1,24
ld r,MID_K5,22

wait 1000

ld r,MID_def4a,22

「私は、……川田のぞみさんに、なりたい。」@

ld l,SIN_Def1,22

「……えぇ。@知っていますよ。」\

ld r,MID_def2a,80

「姫と呼ばれて、……ちやほやされたい。@演劇部でも、素敵な役を与えられて、舞台の中央でスポットライトを浴びたい…。@私を、彼女にして。@……川田のぞみにして……。」\

ld l,SIN_Def3,80

「えぇ。@なれます。@……貴方が演じさえするならば、いつだって、これからだって、@……貴方は川田のぞみとなれるのですよ……。」\

mbg black,22

me1v 16,70

;ld r,MID_def1,80

「でも、……おかしいの……、おかしいの……。@……みんなが、みんなが……私をいじめるの……。@……川田さんもおかしいの……。@このドレス、私のじゃないって……、私のこと、……雑用係だって……！！」\

;ld l,SIN_Def1,80

「みどりさん。@気にしないことです。」@

;ld r,MID_def1,80

「気に、……しない…………。」\

cl a,0
mcbg 22

ld c,SIN_Def1,22

「貴方は、川田のぞみさんのように演じて下さい。@何も気にせず、耳を傾けず。@演技に集中するのです。」\

bg black,0
ld c,SIN_Def1,22

「……貴方は川田さんがのぞみ姫と呼ばれているように、貴方もみどり姫と呼ばれている。@クラスメートたちの憧れを一心に浴び、サキエさんやフミエさんにも親しく接し。@演劇部では常に主役を与えられて祝福されるのです。」\

mld r,MID_def2a,22

「………それが、……私……。@……私は、……姫……。@……みどり姫………。」\

bg black,2

　みどりの世界が、少しずつ薄暗くなっていく。@
br
　まだ昼間だというのに、みどりの世界は暗くなっていく。\

　当然だ。@舞台の上は薄暗い。@……そして、目立つべき人物に対し、鋭くスポットライトが浴びせられ、その姿を浮き立たせるのだ。\


se1 77

mcl r,0
bg white,1
bg engeki_05,22

　それは、主役のドレスを纏った、みどりの姿。@
br
　『六軒島』の舞台を最高の演技で締めくくり、盛大な拍手と歓声を独り占めにするところ。\

　ほら、聞こえてきた……。@聞こえてきた……。@拍手、歓声……。@私を姫と呼んで讃えるみんなの声…………。\

bg black,22
bg engeki_03,0
ld c,MID_U2,22

　何なのこいつ……。@川田のぞみは、呆然とする他ない。@
br
　みどりは鏡に向かって一人、深々とお辞儀をしている。@
　……誰かに手を取られるかのようにしながら。\

bg black,0
ld c,MID_U2,0
ld l,SIN_Def2,2

　その手を、紅茶紳士が握っている。@
br
　毬枝もまた、その光景を呆然と見ている他なかった。\

ld l,SIN_Def1,80

「………こういうことです。@めそめその毬枝さん。@………私はそれでも、……みどりさんにお邪魔な存在ですかな…？\

ld r,MAR_i3a,22

「…………………………。」@
br
　毬枝は絶句する。@何も言い返せない。\

cl l,0
mld l,SIN_Def2,22

「私は嘘を信じさせる妖怪です。@………嘘と聞けば、良からぬものにも思えるでしょう。@しかし。@痛み止めや麻酔薬のように。@人には生きていくために、忘れねばならぬ痛みもあるのではないでしょうか。@私はこの少女の痛みを、こうして和らげているのです。」\

ld r,MAR_i2a,22

fede 1,1000
E_B

mcl a,0
bg black,22
;bg engeki_01,0
;ld r,HIG_Def1,23

E_A

「……毬枝。@相手が悪いわ。@そのくらいになさい。」\

bg engeki_01,22
ld l,MAR_i1,22

bgm1 14

「彼岸花さんっ。」@
br
　いつの間にか彼岸花の姿もあった。\

ld r,HIG_Def2,22

「元々。@………楠木みどりは私の獲物だった。」@

ld l,MAR_i1a,80

「え…？」\

ld r,HIG_W3,80

「お金持ち自慢が過ぎて、クラス中に嫌われていじめられて。@……私好みの美味しい魂になりそうだった。@……それを、そいつに掻っ攫われたの。」\


bg black,24
bg engeki_03,0
ld c,MID_U2,0
ld l,SIN_Def2,24

ld l,SIN_Def1,80

「私がみどりさんを獲物としなければ。@……今頃は彼岸花さんの甘言に耳を貸し。@……ひょっとしたら、自らの命を軽んじていたかもしれませんねぇ。」\

ld r,MAR_i1a,22

「………………………………。」\

ld l,SIN_Def4,80

「ニンゲンには、辛い現実から逃避する権利もあります。@そしてそれが当人にとって、幸せな夢を叶えるものに思えるならば。@……それは素敵なことではありませんか？」\

bg black,24
bg engeki_01,0
ld c,HIG_W3,24
ld c,HIG_Def5,80

「詭弁だわ。@ニンゲンは現実に生きる。@……それから逃げたツケを、いつかは支払うことになるわ。」\
;＜彼岸花

ld l,SIN_Def1,22

「そうですね。@現実に戻る時、支払うことになるでしょう。@……しかし、戻らないならば、永遠に支払わなくても良い。」\

ld r,MAR_i3a,22

「……そんなのが、……彼女にとって、……幸せなんですか……。」@

ld l,SIN_Def4,80

「元いじめられっこの貴方なら。@……彼女の今の気持ちも、察してあげて欲しいものですがねぇ。」\

ld r,MAR_i2a,80

「……………………………。」\

cl c,22

bg black,23
bg engeki_02,23
ld r,HIG_w3,22

「もう毬枝に文句がないならば。@その子はそいつの獲物よ。@……行きましょう、毬枝。@どうせ、あんたには太刀打ち出来ない相手なのだから。」\

ld l,MAR_i4a,22

「彼は紅茶紳士と名乗りましたが、……一体、何者なんですか。」@

ld r,HIG_Def3,80

「学校妖怪八席に序列は持たないわ。@……でも、実力はある。@そうね。@影の序列第２位ってところかしら。@………校長先生の右腕よ。@私たちは、“教頭先生”と呼んでる。」\

bg black,0
ld c,SIN_Def1,22

　学校妖怪序列第１位の校長先生の右腕、教頭先生。@
br
　嘘を叶える力を持つ、恐ろしい妖怪。\

　ただし、嘘は嘘。@いくら叶えても、それは気付けば虚ろな嘘に過ぎない。@
　しかしそれはあまりに甘美で、……抗えるニンゲンなど、きっと誰もいない。@
br
　校長先生の手下という扱いなので、序列は持たないが、@その実力は影の序列第２位と囁かれている……。\

bg engeki_01,0
ld c,SIN_Def1,22

「ご謙遜を。@私など、名も無い一妖怪に過ぎません。」\

bg black,22
bg engeki_02,0
;ld l,MAR_Def1,0
ld r,HIG_w3,22

ld r,HIG_Def2,80

「行きましょう、毬枝。@楠木みどりが、自ら望んだ顛末よ。@……現実を直視せず、嘘の世界を望み、ツケを払うことさえ拒んだ。@………あの子はもう、素敵な世界のお姫様。@……毎日が幸せでしょうから、自殺なんて金輪際、考えないでしょうし。@……残念ね、もう私好みの魂じゃないわ。」\


cl r,2

　彼岸花はくるりと姿を翻して姿を消す。@
br
　毬枝は呆然と、……紅茶紳士とみどりのアンコールを見ていた……。\

bg black,22
;bg engeki_03,0
;ld c,MID_Def1,24

　川田のぞみも呆然としている。@……もう、みどりには誰の姿も目に入らない。@
　彼女の瞳に浮かぶのは、……満場の観客席だけだ。\

se1v 77,70

bg white,1
bg engeki_05,22

wait 1000


se1v 54,100
wait 100
se2v 54,85
wait 100
se3v 54,70

ld c,MID_U2,22
ld c,MID_def3,2

「ありがとう、みんな。@ありがとう、みんな…。@この舞台を、私を愛してくれる皆さんに捧げます。@……ありがとう、……本当にありがとう……。」@
br
　いつまでもいつまでも。@割れんばかりの大歓声が、彼女を祝福し続けるのだった……。\


se1v 54,85

cl c,2

se2v 54,70
se3v 55,50

bg white,2

;＜おしまい＞

fede 1,2000
E_B
wait 2000

se1v 77,70

bg e022,1

wait 2000

bg black,42
bgcopy ;背景をリセット

if %UMINEKOEND < 3 mov %UMINEKOEND,3 : mov %END_FLG,3 ;クリアフラグの変更
	saveoff            ;セーブオフで、処理を高速化する。
	erasetextwindow 0  ;テキストエフェクトを切る事で処理を高速化
	rmode 0            ;右クリックのメニュー表示の無効化
	textoff


goto *b_title
;reset

*higan4_opning
texton
csp -1

bg black,2
bgcopy ;背景をリセット

setwindow 31,16,22,16,26,26,0,2,20,1,1,#999999,0,0,639,479

!sd

mono 0
E_A

;■鎮守神さまの祠

me1v 5,50

wait 2000

bg gakkou_03,2
