;Chapter 3
;　扉を開けると、いつもの様にクラスメート全員が私を振り返った。\
`　As I opened the door, everyone in the class turned around to look at me as usual.`\

mld c,MID_def1,22

;「おはよう、みんな。」@
`"Good morning everyone."`@
br
;　私が挨拶すると、みんなも一番の笑顔の挨拶で返してくれる。\
`　And with my greeting, I was met with everyone's wide smiles.`\

;　私を迎える感情は、敬愛、尊敬。@そして、憧れ。@
`　They showed feelings of affection, respect, `@`and desire.`@
br
;　毎朝、教室に入るこの瞬間、@自覚してはいけないのだけれど、私は優越感に包まれるのだ。\
`　Although I might not be aware of it, `@`I'm enveloped with a sense of superiority from the moment I step through that classroom door every morning.`\

;「おはよう、みどり。」@
`"Good morning Midori."`@

mld c,MID_def3,80

;「おはよう。」\
`"Good morning."`\

;「おはよう、みどり姫っ。」@
`"Good morning, Princess Midori~"`@

mld c,MID_def1,80

;「おはよう。@くす、姫はやめてね。」@
`"Good morning. `@`Hehe, stop with the 'Princess' alright?"`@
br
;　でも、みんなは私のことを敬愛を込めて“姫”と呼ぶ。\
`　Everyone lovingly refers to me as 'Princess.'`\

;　そう呼ばれると、みんなとは身分が違うみたいな気持ちになって、@ちょっぴりの疎外感を覚えてしまう。@
`　When they call me that, it makes me feel different than the rest `@`and just a tad alienated.`@
br
;　でも、みんなが温かにそう呼んでくれるのは、決して悪い気持ちのするものではない。@だから、恥ずかしがりながらも、その呼び名を受け入れている。\
`　But it's not like anyone has any ill will in warmly referring to me like that. `@`So even though it's a bit embarrassing to admit it, I'm starting to accept that nickname.`\

bg black,22

;　彼女の名は楠木みどり（くすのき　みどり）。@
`　This girl's name is Midori Kusunoki 　（楠木みどり）.`@
br
;　クラスメートたちが姫の愛称で呼んで敬愛する、このクラスのお姫様だった。\
`　Her classmates have lovingly given her the pet name 'Princess.' She was the princess of this class.`\

mcl c,0
bg black,22
bg kyou_02,22

;「おはよう、姫。」@
`"Good morning princess."`@
br
;　隣の席のサキエが挨拶をしてくる。@何気なく声を掛けたつもりだろうが、その声は少し緊張しているようだ。\
`　Sakie from the seat next to me was greeting me. `@`She might have intended to express a calm voice, but her voice seemed a bit nervous.`\

ld r,MID_Def1,24

;「あぁ、おはよう。サキエ。」@
`"Oh, good morning Sakie."`@
br
;　名前を呼ばれ、サキエの顔がパッと明るくなる。@
`　Sakie's face suddenly brightened up when I called her name.`@
;　私は気さくに接しているつもりだけれど、友人たちは少し畏まり過ぎているのだ。\
`　I intended to be really casual, but my friends were being far too humble.`\

;「今朝も素敵なお洋服ね。@みどりって本当にセンスいいっ。」@
`"I see you have a lovely dress this morning as well. `@`You have some real fashion sense, Midori."`@

ld r,MID_Def5,80

;「くす、ありがとう。@ママにおねだりして、やっと買ってもらったお気に入りなの。@……良かったら、今度、譲ってあげるね。」\
`"Hehe, thank you. `@`I begged mom for this. It became my favorite when she bought it for me. `@`...If you want, I'll let you have it next time."`\

;「ほ、本当っ？@　う、嬉しいけど、わ、悪いよっ。」@
`"R- Really~? `@`I- I'd be happy, but... I- I can't do that."`@

ld r,MID_Def3,80

;「うぅん。@素敵って褒めてくれたサキエに着てもらったら、この服もきっと喜ぶと思うよ。」\
`"No no. `@`I think even this dress that you complimented as 'lovely' would be happy if I let you wear it, Sakie."`\

;「ち、違うのっ。@それは姫が着てるからこそ素敵なんだよっ。@私なんかが着ても、ダメダメダメ…！！」\
`"T- That's not it~. `@`It's lovely because a princess is wearing it~! `@`For someone like me to wear something like that... I can't do it, I can't~!!"`\

bg black,22

;　サキエは慌てて固辞する。@
`　Sakie politely and nervously declines.`@ 
br
;　みどりは裕福な家の子だった。@だから、綺麗なお洋服などたくさん持っているのだ。@
`　Midori was a child from a wealthy household. `@`So she had lots of beautiful Western-style dresses.`@
br
;　しかし、姫のお召し物をもらえるなんて、とても嬉しいことだけれど、逆に畏れ多くて。@サキエにはとてももらえない。\
`　Although receiving the princess' clothes and the like might have made Sakie really happy, it also filled her with anxiety. `@`Sakie really couldn't take her clothes.`\

bg kyou_01,22
ld c,MID_Def1,24

;「長袖だと今の季節にはもう暑いかな。@……私は肌がすぐ焼けちゃうから、夏でも長袖じゃないと駄目なんだけどね。」\
`"Maybe these long sleeves are a bit too long for this season. `@`...But even in the summer, I have to wear long sleeves or else my skin will get sunburned real quick."`\

;「みどり姫の白磁の肌は、袖で大切に守らなくちゃねっ。」@
`"With your porcelain white skin, you have to be sure to keep those sleeves in mind, Princess Midori."`@

ld c,MID_Def5,80

;「ありがとう。@でも、サキエの肌だって綺麗だよ。」\
`"Thank you. `@`But Sakie, your skin is also fair."`\

;「そ、そんなっ。@ご謙遜をご謙遜をッ。@……あ、あーそのッ、こ、国語の宿題、やって来た？！」@
`"N- No way. `@`You're too nice, too nice~ `@`...Um, Ohh. Did you do your Japanese homework?!"`@
br
;　みどりに肌を綺麗だと褒められてよほど浮かれたのか、サキエは真っ赤になって慌てる。@そして何の脈絡もなく、国語の宿題の話を切り出してしまった。\
`　Maybe it was because Midori complimented how fair her skin was, but Sakie had turned bright red. `@`And so, without any rhyme or reason, she changed the topic to Japanese homework.`\

bg black,22
bg kyou_03,22

;ld c,MID_Def1,24

;「……国語の宿題？@　……いけない。@あれって今日までだったのね…。@昨夜は遅くまで台詞を覚えていたから、すっかり忘れてしまってて……。」\
`"...Japanese homework? `@`...Oh no. `@`That was due today...? `@`I was up late last night memorizing my lines, so I completely forgot about the homework..."`\

;「あ！@　じゃあ、良かったら私の写して！」@
`"Ah! `@`Then if you'd like, you can copy mine!"`@

;ld c,MID_Def1,80

;「いいの？」\
`"Can I?"`\

;「姫は演劇の台詞覚えたりで大変なんだしっ。@お隣なんだからこれくらいさせてよっ。」@
`"It must be hard for you to memorize those stage lines. `@`I'll let you copy it 'cause it's the neighborly thing to do."`@
br
;　サキエは自分のノートを開いて、まるで賞状授与みたいに畏まって差し出す。\
`　Sakie opened her own notebook and respectfully handed it over as if it was a diploma.`\ 

bg kyou_02,0
ld l,MID_Def5,22
ld l,MID_Def3,80

;「ありがとう。@……私、サキエが友達でいてくれて本当に嬉しいよ。」@
`"Thank you. `@`...I'm really happy that we're friends, Sakie."`@
;「……そっ、そんな！@　お、ぉ、大袈裟だよっ、このくらいで…！！」\
`"...O- Oh no! `@`T- This is all t- too much~!!"`\

;　サキエは耳まで真っ赤にして照れ笑いする。@
`　Even Sakie's ears turned bright red as she grinned in embarrassment.`@
br
;　みどり姫に“友達”と呼んでもらえるほどの名誉は、このクラスには存在しないのだから。\
`　After all, no one in this class had the honor of being called Princess Midori's 'friend'.\

se1v 82,100

bg white,24
bg kyou_01,24

;「おはよ、みどり！」@
`"Good morning Midori!"`@
br
;　遅刻ぎりぎりでやって来たのはフミエだった。@
`　Fumie finally showed up just before class was about to start.`@
;　彼女もサキエと同じ、みどり姫の取り巻きの一人だ。\
`　Just like Sakie, Fumie was one of Princess Midori's followers.`\

;「ねぇねぇ、今月号の『シーキャット』見た？」@
`"Hey, did you see this month's chapter of 'Sea Cats'?"`@
;「うん。すごかったね。@急展開って感じで。」\
`"Yep. It was awesome, right? `@`I felt it was a dramatic development."`\

;　『シーキャット』は今、このクラスで人気のある連載漫画だ。@かなりダークな描写があるので、親達や学校には問題視されているが、@クラスの子の大半は隠れて読んでいる。@
`　'Sea Cats' is a popular serialized manga in this class. `@`Its rather dark themes are seen as a bit of a problem by the parents and the school, `@`however the majority of students in this class are reading it behind closed doors.`@
br
;　もちろんみどりもファンの一人で、毎月号欠かさず雑誌を買っている。\
`　Of course, as one of those fans, Midori doesn't miss a chapter and buys one every month.`\

;「来月からアニメもスタートだしねっ。@すっごい楽しみ！」@
`"It seems like there's gonna be an anime starting next month too. `@`I'm soo excited!"`@

ld c,MID_Def1,22

;「へぇ、本当なの？@　知らなかった。」\
`"Ohh, is that true? `@`I didn't know."`\

;「えーッ、みどり、知らなかったのー？！」@
`"Whaaat? Midori, you didn't know~?!"`@
br
;　フミエは素っ頓狂な声をあげて、驚き喜ぶ。\
`　Fumie shouted hysterically in astonishment and delight.`\

;　喜ぶ、とは、みどり姫に初耳の情報を提供できたことを喜んでいるのだ。@
`　Her delight was because of the new gossip she had to share with Princess Midori.`@
br
;　でも、これは実はみどりのサービス。@
`　But this was a service from Midori.`@
;　本当はアニメ化されることはもう、本で読んで知ってる。@初耳を装ってあげたら、フミエが喜んでくれるかなと思って、そう言ったのだ。\
`　Truthfully, she had already read that an anime adaptation was being made. `@`By pretending that she hadn't heard about it before, she was letting Fumie feel happy.`\

;　彼女も、ただちやほやされてるわけではない。@自分に好意を寄せてくれる人たちに、少しでも喜んでもらおうと、@ささやかな気遣いを忘れないようにしている。\
`　It wasn't as if she was just being doted on. `@`By spreading a bit of good will to those around her, `@`she was being modestly considerate of others.`\

;　フミエは嬉しそうに、聞いてもないアニメ化情報を次々に説明し出す。@
`　Fumie was happily giving explanation after explanation about the anime version they hadn't heard about.`@
br
;　主要キャラクターの声優から、制作会社がどこだの、監督は誰だの。@……みどりにそれを話せるのが、よほど嬉しいか光栄なのだろう。\
`　From who the main character's voice actors were, to what studio was in charge of it and who was directing it `@`...Fumie might have been happy - perhaps even honored to talk to Midori like that.`\

ld c,MID_Def5,80

;「ふうん、すごいね。@……でも、演劇部のお稽古が始まっちゃったら、@毎週見るのは難しいかもしれないな…。」\
`"Hmmm, that's neat. `@`...But since it starts after drama club practice, `@`watching it every week would be hard to do...`"\

;「放送されるの結構遅い時間みたいだよ？@　あ、でも、もし見れない時は言ってね！@　私、録画しといてあげるから！」@
`"It's on pretty late at night isn't it? `@`Oh, but just tell me if you can't watch it okay?! `@`I'll... record it for you!"`@

ld c,MID_Def3,80

;「ありがとう、フミエ。@あなたがお友達で、本当に嬉しいよ。」\
`"Thank you Fumie. `@`I'm truly happy you're my friend."`\

;「とッ、当然でしょ！！@　と、友達だもんね、あはははははは！！」@
`"O- Of course!! `@`W- We're friends after all, right? Ahahahahaha!!"`@
br
;　フミエもまた、サキエと同じように真っ赤になって舞い上がる。@
`　Fumie blushed, just like Sakie.`@
;　みどりに感謝の言葉をもらえて舞い上がらない子など、このクラスには存在しないのだから。\
`　Because no other blushing girl in this class had ever received words of gratitude from Midori.`\

;　楠木みどり。@クラス中の女子の誰もが憧れる、姫と呼ばれる少女。@
`　Midori Kusunoki . `@`The girl called 'Princess' who every girl in the class swooned over.`@
br
;　彼女は何の不足もなく、満ち足りた学校生活を送っていた……。\
`　She lived a completely satisfying school life without any insecurities...`\

bg black,22

me1v 24,50
fede 1,2000
E_B













bg kyou_03,22

;「…………ねえ、姫。@あいつ、またこっち見てるよ…。」@
`"......Hey, Princess. `@`That girl is looking over here again..."`@
br
;　ノートを写させてもらっている私に、サキエが囁く。\
`　Sakie, who was letting me copy her paper, whispered to me.`\

;　あいつって？@　私は、サキエが不愉快に睨む教室後方に目を向ける。\
`　That girl? `@`I followed Sakie's uncomfortable glare towards the back of the classroom.`\




bg black,24

fede 0,1000
E_A

bg kyou_02,24

bgm1 8

;　すると、サキエの言う通り、@川田のぞみがこちらの様子をじっとうかがっているのがわかった。\
`　Just as Sakie had said, `@`I noticed Nozomi Kawada was staring over this way.`\

;「……マジであの子、嫌な感じだよね。@いっつもジーッと姫のこと見ててさー。」@
`"...Seriously, I have a bad feeling about that girl. `@`She's aaaalways staring at the princess."`@
;「みどりのこと妬んでんだよ。@前のクラスではあいつも、お姫様気取りだったらしいし。」@
`"She's just jealous of Midori. `@`In her last class, it seems she was treated like a princess."`@
br
;　サキエとフミエは顔をしかめて囁きあう。\
`　Sakie and Fumie scowled and whispered.`\

mbg black,22

;　川田のぞみも、裕福な家の子らしい。@
`　Evidently, Nozomi Kawada was also a child of a wealthy household.
br
;　しかし、みどりとはまったく正反対の扱いを受けていた。\
`　However she was receiving the exact opposite treatment that Midori had.`\

;　のぞみは家が裕福であることを鼻にかけ、威張っていた。@
`　Nozomi took pride in her family's wealth and flaunted it.`@
br
;　しかしみどりは、威張ったりなどせず、誰にでもやさしかった。\
`　But Midori wasn't boastful, and she was kind to everyone.`\

;　当然の結果として、みどりは姫と呼ばれて誰からも慕われた。@
`　Naturally, Midori was called princess and adored by everyone.`@
br
;　そして逆にのぞみは、@今ではクラスの女子のほとんどから無視され、あるいはいじめられている……。\
`　On the other hand, `@`now Nozomi was almost completely ignored by the girls in class, or rather, she was being bullied...`\

mcbg 22

;　去年のクラスでは、金持ち自慢で姫と祭り上げられて、ちやほやされていたらしい。@
`　In last year's class, it seems she was pampered and portrayed as the pridefully rich princess.`@
br
;　それが今年は正反対の扱いで、かつて自分が座っていた姫の座にはみどりが座っていて。\
`　She has the complete opposite treatment this year, and the seat she once occupied as princess now belonged to Midori.`\

;　きっと、妬ましくて妬ましくて仕方がないのだ。@
`　Undoubtedly, she felt jealous, and being jealous was all she could do.`@
br
;　それがありありとわかるから、サキエもフミエも不快そうに睨み返している。\
`　Since that was clear to Sakie and Fumie, they returned her sharply unpleasant glare.`\

;「自分が姫と呼ばれるかと思ったら、それがみどりだったから面白くないんだよ。」@
`"If I thought I was called princess, I wouldn't like it if Midori was called that."`@
;「ふんっ。@みどりとテメーじゃ姫の器が違うってんだよっ。」\
`"Yeah~. `@`Midori is a different princess of a different caliber than her though~!"`\

;「あいつ、いつまでガンつけてるつもりなわけ？」@
`"Just how long does she intend to keep staring at her?"`@
;「本当だよねー。@……みどりも不愉快でしょ。@私、ちょっと言ってこようか？」@
`"I know, right~. `@`...Midori is probably uncomfortable too. `@`Perhaps I should go talk to her?"`@
br
;　フミエが物騒な強面で席をがたりと立ち上がる。@サキエも忠臣ぶりでは負けないとでも言わんばかりに、荒々しく立ち上がる。\
`　With a scary look on her face, Fumie stood up from her chair with a crack. `@`As if wordlessly implying she wouldn't lose to her as Midori's loyal retainer, Sakie quickly stood up as well.`\

ld r,MID_Def2,22

;「やめてよ、二人とも……。」@
`"Stop it, the both of you..."`@
br
;　のぞみは毎日、クラスの誰かから、酷い言葉を掛けられたり、あるいは酷い悪戯をされたりしている。\
`　Every day, someone in class said terrible things about Nozomi or played terrible pranks on her.`\

;　今日だって、誰からどんないじめを受けるか、わかったものではない。@
`　Who knows what kind of abuse she has suffered today alone.`@
;　みどりは、こんな朝から、さっそくいじめられるところを見たくはなかった……。\
`　On a morning like this, Midori didn't want to see the bullying start so soon...`\


;　サキエとフミエは、一触即発の緊張感でのぞみを睨みつけている。\
`　Sakie and Fumie were staring at Nozomi with an explosive tension.`\

quakey 2,200

mbg black,22

;「………あんた、さっきから誰にガンつけてんのよ。」@
`"...Hey, you. Just who do you think you're staring at anyway?"`@
;「文句あんなら言いなさいよっ。@聞いてんのッ？！」@
`"If you've got a problem, then say it~! `@`I'm listening?!"`@
br
;「…………………………。」\
`"............"`\

;　一言でものぞみが言い返したら、それをきっかけに“キレる”つもりなのだろう。@
`　If Nozomi replied back with a single word, they might use that as an excuse to 'end it.'`@
;　それがわかってるから、のぞみも一言も言い返さない。@……いや、言い返せない。\
`　Since Nozomi understood that, she didn't say a single word. `@`...No, she didn't reply at all.`\

mcbg 22

ld r,MID_K2,80

;「やめてっ、二人とも…！！」@
`"Stop it, the both of you!!"`@
br
;　みどりは、少しだけ大きい声で言った。@
`　Midori shouted a bit when she spoke.`@
;　敬愛する姫の大声に、忠臣たちは飛び上がって驚く。\
`　Her loyal subjects jumped with surprise at the loud voice of their beloved princess.`\

ld r,MID_Def2,80

;「……朝からいじめなんて、見たくないの。@……だからやめて。@……ね？」\
`"...I don't want to see any bullying this morning. `@`...So stop it. `@`...Alright?"`\

;「姫………。」@
`"Princess..."`@
;「……ちっ。@川田ぁ、次、ガンつけたら容赦しねーからなっ。」@
`"...Tch. `@`Kawada, next time you stare at her, there'll be no mercy. Alright?"`@
br
;　とりあえず、この場は収まってくれた。@
`　At least for now, they've settled down.`@
;　しかし、川田のぞみがクラス中から嫌われているいじめられっこであることに、代わりはない。\
`　But it doesn't change the fact that Nozomi Kawada is still hated and bullied during class.`\

bg black,22
bg kyou_03,22

;　みどりが、いじめを見たくないと言ったから、@クラスメートたちは少なくとも、みどりの前だけでは、いじめをしないだろう。@
`　After hearing Midori say she didn't want to see any bullying, `@`her classmates didn't do any bullying for a while, at least not in front of her.`@
br
;　もちろんそれは、いじめがなくなるという意味ではない。\
`　Of course that doesn't mean the bullying stopped.`\

bg black,22

;　みどりは、のぞみを救ってやれないことを、気の毒にも思う。@……庇ってあげるべきなのではと思うこともある。@
`　Midori thought it was unfortunate that she couldn't save Nozomi. `@`...She also believed she should stand up for her.`@
br
;　しかし実際、川田のぞみは高慢で、自分の家の方が裕福であることを威張っている。@今でも、口を開くことを許されるなら、それを自慢して、みどりを見下したいのだ。\
`　But in reality, Nozomi Kawada was arrogant and took pride in her family's wealth. `@`Even now if they let her speak up, Nozomi's pride made her want to look down on Midori.`\

bg kyou_01,0
ld r,MID_K1,22

;　……みどりも、世の中の不条理は理解している。@
`　...Even Midori realized the irrationality of this world.`@
br
;　どんなに親しく接しようとしても、世の中には仲良くなれない人間もいる。@……それが、川田のぞみなのだ。\
`　No matter how friendly you are to them there are people you cannot get along with in this world. `@`...Nozomi Kawada was one of them.`\

;　だから、彼女へのいじめは、……辛いけれど、見て見ぬふりをするしかない。@
`　It's because the bullying against her ...which might have been cruel, but all she could do was see it or pretend not to see it.`@
br
;　彼女だって、みどりにだけは庇われたくないと思っているのだから……。\
`　After all, Midori thought that if Nozomi wanted protection, she didn't want to be protected by her...`\

bg black,22

;　ごめんね……。@みどりは心の中で謝る。@
`　I'm sorry... `@`Midori apologized from her heart.`@
br
;　でも、………こんなこと言ったら気の毒だけれど。@
`　But, ...If I were to say that, it would be pitiful and yet...`@
;　私だって、みんなに好かれたくて、色々とがんばったり、気遣ったりしてることがあるんだよ。\
`　After all, everyone likes me, tries hard to support me, and is concerned for me.`\

;　川田さんだってそれをすればいいのに、……どうしてしないの？@
`　Kawada-san would be fine if only she would too ...but why doesn't she?`@
;　家が裕福だって自慢したって、誰もいい顔をしないのに……。@
`　She brags about her family's wealth, even though no one can sympathize...`@
br
;　去年のクラスでは、それをちやほやしてもらえたかもしれないけれど、@……誰もがお金持ち自慢を持て囃してくれるわけじゃない。\
`　Last year's class might have spoiled her by letting her get away with that,`@` ...however, it's not like anyone will praise someone for having pride in being a rich person.`\

bg kyou_03,22

me1v 24,50

;　……いじめられてるのは気の毒に思う。@
`　...I think being picked on is unfortunate.`@
br
;　でも、……どうして自分がいじめられているのか、@……早くそれを受け入れて、……自分を直せるといいね。\
`　But, ...the sooner she realizes why she's being picked on, `@`...the sooner she can fix that problem herself.`\

;　ここまで彼女がクラス中に目の仇にされてしまっている以上、それは簡単なことではないだろう。@
`　Aside from staring at me in class until now, this isn't really a simple matter.`@
br
;　でも、……お金持ち自慢の傲慢をやめて、……少しずつ、みんなへの接し方を変えて。@……心を少しずつ入れ替えていけば、……友達も、作れるんじゃないかな。\
`　However, ...if she stopped bragging about being rich, ...then over time, everyone's attitude towards her would change. `@`...And if they slowly change their minds, ...she might even be able to make some friends.`\

bg black,22

;　そうしたらきっといつか、……いじめられっこじゃなくなると思う。@
`　If she did that, then someday ...I think she might stop being bullied.`@
br
;　そしたらその時。@……私とも、友達になろうね。\
`　If she did that, `@`...then she might even become my friend.`\

bg kyou_01,0
ld c,MID_Def2,22

;　その思いが、……のぞみに届いたと信じて。@みどりは再びノートに目線を戻し、宿題の写しに勤しんだ。\
`　I believed... that thought reached Nozomi. `@`Once again, I turned my gaze back to Sakie's paper, and proceeded to copy her homework.`\









E_A

mbg "BMP\background\efe\red1.bmp",1
mcbg 0
ld c,MID_K2,22

;「……………痛ッ！@　……………。」\
`"......Ow~! `@`........."`\

me1v 24,50

;　みどりは唐突な腕の痛みに顔をしかめる。@
`　Midori grimaced as she felt a sudden pain on her arm.`@
br
;　骨が痛んだとか、古傷が疼いたとか、そんな痛みではない。@
`　It wasn't a pain from a bone, the throbbing of an old wound, or anything like that.`@
;　もっとはっきりとした、……例えるなら、透明人間に腕を叩かれでもしたかのような痛みだった。\
`　It was more direct, ...it was as if an invisible man had struck her across the arm.`\

bg black,24
bg kyou_02,24

;　何事と思い、周りを見回すのだが、何事もない教室の光景が広がっているだけだ。@
`　Wondering what happened, I looked around the room, but all that spread out before me was the scenery of an uneventful classroom.`@
br
;　サキエもフミエも談笑している。@……誰かが私を叩きに来て、それに二人が気付かないわけはない。\
`　Sakie and Fumie were both having a friendly conversation. `@`...It's impossible for someone to just come by and hit me without those two noticing it.`\

bg black,23
bg kyou_01,0
ld c,MID_K1,23

;　……それ以前に。@私はここでこうしてノートを取っているのだ。@その私に気取られずに、誰が私の腕を叩けると言うのだろう。@
`　...Before that, `@`I was just finishing up my homework here like this. `@`Does that mean someone was able to hit my arm without them noticing?`@
br
;　何か物が飛んできてぶつかったのかとも考えたが、そういう感触ではなかったし、@第一、飛んできたらしき物体はどこにも転がっていなかった。\
`　I thought something might have flown and hit me, but it didn't really feel like that. `@`First of all, even if something did, there was nothing rolling around to indicate that.`\

;「……どうしたの？」@
`"...What's wrong?"`@
;「………大丈夫、みどり？」@
`"...Are you alright, Midori?"`@
br
;　私の様子に気付き、フミエとサキエが心配そうに覗き込んでいる。\
`　When they took notice of me, Fumie and Sakie were looking at me with concern.`\

ld c,MID_Def2,80

;「……うん、大丈夫。@何でもないよ……。」@
`"...Yeah, I'm fine. `@`It's nothing..."`@

se1 69

br
;　チャイムが鳴って、サキエとフミエがそれぞれ授業の準備にとりかかると、@私はもう一度自分の腕を見てみた。@やはり何もない。\
`　The bell sounded. Sakie and Fumie started getting ready for class, `@`and I looked at my arm again. `@`It must have been nothing.`\

bg black,22

fede 10,2000
E_MA











bg kyou_03,22

bgm1 14

;　実は、……これが初めてではない。@最近たまにこういうことが起こる。@
`　The truth is ...this isn't the first time. `@`Lately, something like this has been happening from time to time.`@
br
;　突然、身体のどこかに痛みを感じるのだ。\
`　Suddenly, I'll feel a pain somewhere on my body.`\

;　それは、何かが触った程度にしか感じない時もあれば、@その場にうずくまってしまう程の激痛であることもある。@
`　There are times when I feel that something had to have touched me, `@`and during those times, I've also felt a pain that sends me cowering.`@
br
;　そしてその箇所も、今のように腕であったりお腹であったり背中であったり、一定ではない。\
`　And like at that point too, like now I'd feel it in my arm, in my stomach, in my back ― it's not a specific place.`\

;　……最初の頃は、気のせいか何かだろうと考えていた。@
`　...From the beginning, I've thought about whether it's my imagination or something.`@
br
;　しかし、最近、この不思議な痛みを感じる機会が増えた気がする。\
`　But lately, I feel like those chance moments when I feel those mysterious pains are on the rise.`\

mbg black,22

;　ひょっとするとこれは、……何か、とても悪い病気なのではないだろうか…？@
`　Perhaps this could be ...I don't know... some kind of really bad illness...?`@
br
;　あまりに酷いようなら、両親に打ち明けて、ちゃんと病院で見てもらった方がいいのかもしれない。\
`　If it's so severe, I'll be honest with my parents, and if they think I should, they'll certainly take me to get looked at in the hospital.`\

;　……紅茶紳士さん。@……これって、何かの病気なの…？\
`　...Oh, Black Tea Gentleman. `@`...Just... what kind of sickness is this...?`\

fede 0,1000
E_B
E_MA

se1v 56,50

mbg white,8
mcbg 22

;　私が心の中でそう呟くと、@/
`　When I muttered that in my own mind, `@/
me1v 28,70
;……………宙に浮くティーカップが現れる。@
`......a teacup appeared flying through the air.`@
br
;　そして、宙に浮くティーポットも現れ、@………ティーカップになみなみと紅茶を注ぎ入れた。\
`　And then a teapot appeared floating in the air, `@`...and it poured ordinary black tea into the teacup.`\

;　そして、カップを持ち優雅に口にする男の姿が、ゆっくりと現れる……。\
`　And then the figure of an elegant man taking a cup elegantly up to his lips slowly appeared...`\

bg black,22
fede 10,1000
E_MA
bg kyou_01,22
ld c,SIN_Def1,22

bgm1 18

;　この不思議な男の人を、私は紅茶紳士さんと呼んでいる。@……いつも現れる時、紅茶を飲んでいるからだ。\
`　I call this mysterious man the Black Tea Gentleman. `@`...Because whenever he appears, he's always drinking black tea.`\

;　みんなが談笑する教室の中で、@おかしなアレンジをしたタキシード風の格好で、立ったまま紅茶を嗜む謎の紳士。@
`　In the middle of the classroom filled with idle chatter, `@`in a strangely arranged tuxedo outfit, was a strange gentleman standing and tasting his tea.`@
br
;　無論、その姿は私以外の誰にも見えていない。\
`　Of course, I was the only one who could see him.`\

cl c,0
ld r,SIN_Def3,23

;「今朝もアッサムがとても良い香りですねぇ。@………おや。@どうなさいましたかな？」@
`"This Assam tea smells wonderful this morning, wouldn't you say? `@`...Oh my. `@`Whatever is the matter?"`@

ld l,MID_K1,22

;「……最近、突然、体が痛むことがあるの。」\
`"...Lately, I've been getting these sudden pains."`\

ld r,SIN_Def1,80

;「おや。@それはお稽古に差し支えるほどのものですかな？」@
`"Oh my. `@`Do you think it's bad enough that it will interfere with your practice?"`@

ld l,MID_Def2a,80

;「……それほどではないけれど…。@……でも、いつも突然でびっくりするし…。@何だか薄気味悪いし……。」\
`"...It's not that bad but... `@`...It always suddenly frightens me and... `@`There's something weird about it..."`\

ld r,SIN_Def2,80

;「ならば、気にしないことです。」@
`"Well, then it's nothing to worry about."`@
br
;　紅茶紳士は、あっけらかんとそう言う。\
`　The Black Tea Gentleman said this indifferently.`\

ld l,MID_K1,80

;「……気にしなくて、いいの…？」\
`"...Is it alright... not to worry about it...?"`\

ld r,SIN_Def1,80

;「はい。@……それに、そんなことを気にしている場合ではないのではありませんか？@　今度のお芝居は、とても重要な役ではありませんか。」\
`"Yes. `@`...Anyway, now isn't really the time to be worrying about that, is it? `@`Don't you have an extremely important role in the upcoming play?"`\

ld l,MID_Def2,80

;「はい…。@……台詞も、すごく多くて覚えるのも大変です。」\
`"Yes... `@`...And I have so many lines to remember. It's quite difficult."`\

ld r,SIN_Def4,80

;「今はそれに集中すべき時期ではありませんか？@　他のことに気を取られるのは、集中力を削がれている証拠だと思いますがねぇ。」@
`"Then shouldn't you focus your time on that? `@`I think worrying about other things just shows you're losing your focus, wouldn't you say~?"`@
br
;　それを言われると、言い返せない。\
`　When he said that, I didn't respond.`\

bg black,22

;　今度、演劇部で演じたい役は、とてもとても重要で大切な役。@
`　This upcoming role I want to play in the drama club is an extremely important role.`@
br
;　自分が失敗すれば、お芝居の全てが駄目になるとさえ言っても過言ではないほどの、重要な役。\
`　This role was so important that if I were to mess it up, the entire play would be ruined.`\

;　そんな私の緊張が、ありもしない痛みを感じさせるのかもしれない。@
`　Maybe that kind of pressure caused me to feel some kind of imaginary pain.`@
br
;　時に緊張が腹痛を引き起こすように、……これも、そういうものなのかもしれない。\
`　Perhaps... I'm just feeling occasional pains in my chest from the stress.`\

bg kyou_02,0
ld r,MID_Def2a,22
;ld r,MID_Def1,80

;「……そうですね。@気にしても、仕方ないかもしれませんね。」@
`"...You're right. `@`It bothers me, but I suppose I have no choice, right?"`@

ld l,SIN_Def2,22

;「そういうことですよ。@気になどしないことです。」@
`"That's how it is, you see. `@`Don't worry about it."`@
br
;　気にするなと、重ねて言われる。@
`　He kept saying not to worry about it.`@
;　……もう、腕の痛みも消えている。\
`　...And the pain in my arm was already fading away.`\

ld l,SIN_Def1,80
cl l,2

;　私が納得すると、紅茶紳士さんは姿を消す。\
`　When I agreed with him, the Black Tea Gentleman disappeared.`\

ld r,MID_k1,80

;　彼は当然、人間ではないだろう。@
`　He's probably not human.`@

;　なら、何？@　……オバケとか、……妖怪？@
`　Then what is he? `@`...A monster? ...a youkai?`@
br
;　その正体について、深く考えても意味はない。\
`　There's no reason to think too much about his real identity.`\

;　彼は紅茶紳士さん。@私の前に現れた、不思議な人。@
`　He is the Black Tea Gentleman. `@`A mysterious figure who revealed himself to me.`@
br
;　彼が、かつての私を、生まれ変わらせてくれたのだ。\
`　And he brought me a new life from who I once was.\

bg black,2

fede 0,2000
E_A












bg engeki_01,22

bgm1 2

;　放課後、演劇部の部室に行くと、既に部活は始まっていた。@
`　When I went to the drama clubroom after school, things were already underway.`@
br
;　皆、部長の指示のもと、熱心にストレッチをしている。\
`　Under the direction of the club president, everyone was performing stretching exercises with enthusiasm.`\

ld l,MID_Def1,23

;「ごめんなさい。@遅くなりました。」@
`"I'm sorry. `@`I'm late."`@
br
;　部室に入ると、誰もが一瞬手を止めて、私を見る。@
`　As I enter the room, everyone stops what they're doing and looks at me.`@
;　敬愛だったり、憧れだったり。@遅刻してきた身には、勿体無い眼差しだ。\
`　Adoration. Admiration. `@`They were improper glances to give to someone who was late.`\

;mbg white,1
;mcbg 22

;「………ほら、ストレッチの続き！」@
`"...Hey, keep stretching!"`@
br
;　部長が手を打ち鳴らす。@彼も、みどりの姿に一瞬、見惚れていたくせに。\
`　The club president clapped his hands. `@`Even he had been enchanted by Midori for an instant.`\

;「楠木ー、お前、最近遅刻が多いぞー。」@
`"Kusunoki~, you've been late a lot lately~"`@

ld l,MID_Def5,80

;「すみません。@ちょっと着替えるのに手間取ってしまって……。@以後、気をつけますね。」@
`"Sorry. `@`I had some trouble getting changed... `@`I'll be more careful in the future."`@
br
;　そう言って微笑みかけると、部長は分かり易いほど頬を赤くして俯いた。\
`　I said with a smile, and as the club president realized what that meant, he turned red and looked away in embarrassment.`\

;「……まあ、気をつけてくれればいいんだけどさ……。」@
`"...Well~. I'm sure you'll be fine as long as you're more careful..."`@
br
;　上級生である部長は、先生たちからの信頼も厚く、女生徒達からもとても人気がある。@
`　Our upperclassman club president got along well with the teachers, and was very popular among the girls at school.`@

;　だが、そんな彼でもみどりの笑顔一つでこの通りだ。\
`　But even someone like him would show Midori a smile like that.`\

cl l,22

;　クラスのお姫様は、演劇部においてもお姫様だった。@
`　The princess of the classroom was even a princess in the drama club.`@
br
;　いや、厳密には逆か。@
`　No, perhaps it makes more sense the other way around?`@
;　演劇部でお姫様だからこそ、クラスでもお姫様なのだ。\
`　Because she was the princess in the drama club, she was a princess in the classroom.`\

;　舞台上の彼女が美しく輝くからこそ、彼女は姫と呼ばれ、@他のクラスどころか、他の学年の子にまで大勢慕われているのだ。\
`　She is called Princess because she shines beautifully on stage, `@`and she is loved by students from other classes and even different grades.`\

bg black,23
bg engeki_02,23


;　みどりがストレッチをする場所を探して歩くと、@それに合わせて、まるで花道でもつくるかのように他の部員達がスペースをあけてくれた。\
`　As Midori went looking for a place to stretch, `@`the other club members made way in response, as if she were passing through the audience to the stage.`\

ld c,MID_Def1,23

;「ありがとう。」@
`"Thank you."`@
br
;　彼女が微笑んでお礼を言うと、みんな照れて俯いてしまう。@
`　As she smiled and thanked them, everyone shyly looked away.`@
;　みどり姫が微笑むだけで、花も恥らうというのは言葉通りの意味に違いなかった。\
`　It was exactly as if even flowers would blush with just a smile from Princess Midori.`\

;　我が校の演劇部は、部員も多く、文化部なのにノリは完全に体育会系だった。\
`　Our school drama club had a lot of members, and although it was a cultural club, it was completely sport-oriented.`\

;　部活の時は全員体操着に着替える。@そして体力作りと称して学校の周りを走り込んだり、@近くの河原に行って大声で発声練習も行ったりもする。@ほとんど『ガラスの仮面』の世界だ。\
;　(Translator's Note) Reference made to Gurasu no Kamen, "Glass Mask." A manga from the 1960s.
`　Everyone changes into gym outfits during club hours. `@`To improve our endurance, `@`we run around the school or we head down to the river bed and practice shouting to exercise our vocal cords. `@`It's almost like the world in #ECD672Glass Mask#FFFFFF.`\ 

;(Glossary Entry #5: Glass Mask)
if %EN_glossary_progress > 5 jumpf
	mov %EN_glossary_progress,5
	se1v 1011,50
~

;　そして、毎学期末には発表会があり、全校生徒の前で芝居を上演することになっている。@
`　And now, it has become a tradition to have a performance at the end of every semester where we act in front of all the students in school on stage.`@
br
;　今日はその発表会の配役決めを行う重要な日だ。@部員達はいつもにも増して気合いが入っているようだった。\
`　Today is that very important day where the roles of the performance will be decided. `@`It was as if all the club members were overflowing with excitement.`\

mbg black,22

;　基本的に芝居の配役は、部員がやりたい役に立候補し、@顧問の先生と部長が問題ないと判断すればそれで決まる。@
`　Basically, when it came to casting the play, members would start calling out the part they wanted to play, `@`and if the advising teacher and club president saw no problems, then it was decided on the spot.`\
;　一つの役に二人以上立候補者がいた場合は、みんなの前でオーディションとなる。\
`　When two or more people wanted the same role, they would audition in front of everyone.`\


;　今回の発表会での演目は、『六軒島』という古典作品。@
`　This time the play we are performing will be the classic 'Rokkenjima'.`@
br
;　ファンタジーのようでもあり、ミステリーのようでもある不思議な作品だ。\
`　It's a mysterious play that is like a fantasy but also like a mystery.`\

;　かなり難解な内容で、役者が心情を充分に理解して演じなければ、@到底、メッセージを伝えることなど出来ない。@
`　Since there is some very difficult content to work with, if the actors don't understand the emotions they have to portray, `@`then they cannot transmit the message of the story.`@
br
;　かなり難易度の高い演目だが、顧問の先生は敢えてこれを選んだのだ。\
`　It's a really difficult play, but our advising teacher has chosen this as a challenge for us.`\

;ld c,MID_Def1,80

mcbg 22

;　主演の魔女役に求められる演技力は、並大抵のものではない。@
`　The leading role of the witch is no ordinary role, and it requires real acting ability.`@
br
;　でも、それを見事射止めたい。@この演目を、そしてこの役を、@……私になら出来ると信じてくれた先生の期待に応えたいのだ。\
`　But I want to make that role mine. `@`This play, and this role, `@`...If I can do it, I want to realize the expectations of the teacher who believed in me.`\

bg black,23
bg engeki_01,23

;「……主役はみどりさんで決まりよね。」@
`"...The leading actress has to be Midori-san."`@
;「当然よ……。@魔女の役が出来るのは、彼女以外に誰もいないわ。」@
`"Obviously... `@`she's the only one who can play the role of the witch."`@
br
;　その魔女こそが、このお芝居の主人公。\
`　That witch was also the protagonist of this play.`\

;　他にも登場人物が出てくるけれど。@……もはや一人芝居と言ってもいいほど、魔女役の演技力がそのまま、お芝居の完成度を左右する大役なのだ。\
`　There are other characters that are introduced. `@`...But it quickly turns into a one woman show, and the perfection of the play hinges upon the acting ability of the one playing the witch.`\

;　部員たちが、みどり以外の誰にも務まらないと囁き合っている。@
`　The club members whispered amongst themselves that no one else except Midori could fit the role.`@
br
;　恐らく、みどり以外の誰も、魔女役には立候補しないだろう。\
`　And it was most likely that no one else would announce their candidacy for the role of the witch.`\

;　彼女と演技力で張り合おうなんて、おこがましいにも程がある。@
`　To suggest that someone would compete with her on acting ability was beyond absurd.`@
br
;　楠木みどりは、演劇部においては姫というより、女王の貫禄を持っていたのだ。\
`　Midori Kusunoki was more than a princess in the drama club. She resembled a queen.`\

ld r,MID_Def1,26

;　もちろん彼女も、自動的に魔女役をもらおうなどと甘えるつもりはない。@
`　Of course, she wasn't so naive as to think she would automatically be given the part of the witch.`@
;　そして自分の演技力を試す意味で、先生がこの演目を選んだことも理解している。@
`　She also knew that her teacher had chosen this play specifically to test her acting abilities.`@
br
;　だから、今日に備えて、ずっと魔女役をレッスンしてきたのだ。\
`　After all, he had been giving her lessons on the role of the witch for ages now in preparation for today.`\

bg black,24
bg engeki_02,24

;　先生が厳しい眼差しでみどりを見ている。@
`　The teacher was staring intensely at Midori.`@
br
;　……見事、魔女役を射止めてみなさいという、挑戦的な眼差し。\
`　...It was a look as if to say "Magnificent. Now make the role of the witch your own."`\

;　もしもみどりが、魔女役に不適ならば、この演目すらも撤回するつもりかもしれない。@
`　If for some reason Midori didn't prove to be a very good witch, he might have even intended on canceling the play altogether.`@
br
;　それは即ち、……この『六軒島』という演目が、@みどりのためだけに選ばれたも同然であることを意味していた。\
`　In other words, ...the play 'Rokkenjima' `@`might as well have been chosen just for Midori's sake.`\

;　………先生、私を見て下さい。@絶対に、魔女役に相応しい演技をお見せします。@
`　...Watch me Sensei. `@`No matter what, I'll show you a fitting performance for the role of the witch.`@
br
;　みどりもまた、決意を眼差しに込めて、先生にそれを返すのだった。\
`　And then Midori's eyes filled with determination in response to her teacher.`\

;　ほぼ魔女役が内定しているみどりと違い、@その他の部員たちにとっては、無事に役を射止められるかどうか、まだまだ不安だった。\
`　Unlike Midori, who was almost guaranteed to get the role, `@`the other club members were still worried whether or not they would get their own parts so easily.`\

;「あーあ、私、どの役にも就けなかったらどうしよう。」@
`"Ah~ah, what should I do if I don't get any of the parts?"`@
;「雑用係になったら大変だよね。@今回、小道具とかも多そうだし……。」@
`"I would hate getting stuck doing the odd jobs. `@`This play seems to have a lot of props and what not too..."`@
;「くす。@それは心配しなくても大丈夫でしょ。@ほら、全部一人でやってくれそうな子がいるじゃない。」\
`"Heh. `@`You shouldn't worry about that. `@`I mean look, there's a kid who'll do it all for us."`\

bg black,24
fede 0,1000
E_A
bg engeki_03,24










bgm1 8

;　彼女たちの目が部室の隅に向けられる。@
`　Their eyes shifted to the corner of the clubroom.`@
;　そこには、みんなから孤立して一人でストレッチを行っている子がいた。@
`　There was a single girl, isolated from everyone and doing her stretches.`@
br
;　………川田のぞみだった。\
`　...It was Nozomi Kawada.`\

;　そう言えば彼女も演劇部だった。@誰とも目を合わせない様に俯いたまま身体を伸ばしている。@
`　Incidentally, she was also a member of the drama club. `@`She was stretching out with her head down while everyone avoided making eye contact with her.`@
br
;　そんな彼女を見ながら、@他の部員たちは「ほんとブス」とか「キモい」などと口々に囁いている。\
`　Looking at her like that, `@`all at once, the other club members started whispering: 'Uuugly.' 'Disgusting.'`\

;　みどりのところにまで声が届いているのだから、当ののぞみに聞こえていないはずがない。@
`　Their voices extended out to Nozomi. There was no doubt that she heard what they were saying.`@
;　しかし、彼女は全く気にしない様子で黙々とストレッチを続けていた。@おそらく必死に心を殺し、聞こえない振りをしているのだろう。\
`　And yet, she silently continued to stretch as if it didn't bother her at all. `@`Perhaps she was silencing her thoughts and pretending not to hear.`\

;　クラスだけでなく、ここでもいじめられてるなんて。@みどりは気の毒に思う。@
`　She wasn't just bullied in the classroom, but here as well. `@`Midori felt sorry for her.`@
br
;　のぞみは、みんなに陰口で言われるほどブスではない。@……むしろ、顔立ちは美人の部類に入るだろう。\
`　It wasn't as if Nozomi was as ugly as everyone was slandering her out to be. `@`...On the contrary, her face made her seem beautiful.`\

;　金持ち自慢の傲慢な笑みでなく、……心の底からの朗らかな笑いを浮かべることが出来たなら、@もっともっと明るく輝くだろうに。\
`　Rather than a smile prideful of her wealth ...if she could smile from the bottom of her heart, `@`then her face would surely shine even brighter.`\

bg black,22

;　……私もかつて、家の裕福さを無自覚に自慢していたことがある。@
`　...I, too, was once ignorantly prideful of my family's wealth.`@
br
;　でも、幸いなことに、それが傲慢であると気付き、直すことが出来た。\
`　Thankfully, I realized my arrogance and I changed my ways.`\

;　それが出来なければ、……川田のぞみは、私だっただろう。@
`　If I hadn't done that... I would be Nozomi Kawada.`@
br
;　彼女が時折、私をじっと見ているように。@
`　Just as sometimes she's staring at me.`@
;　私もまた、……時折、じっと彼女を見てしまうのだ……。\
`　Sometimes... I'm also staring at her...`\

bg engeki_01,22
ld l,SIN_Def1,22

;「何をぼうっとされているのですか…？@　貴方の番ですよ。」@
`"What are you daydreaming about...? `@`It's your turn."`@

ld r,MID_K1,26

;「え？@　……あ、ありがとう。」@
`"Eh? `@`...Oh, thank you."`@
br
;　紅茶紳士が現れ、みどりに、番が来たことを教えてくれる。\
`　The Black Tea Gentleman appears and tells Midori that her time has come.`\

cl r,23
bg black,23
bg engeki_01,23
ld l,MID_Def1,23

;　先生の前に歩み出て、何役に立候補したいかを宣言し、その演技を見せなくてはならない。@
`　Walking towards the teacher, I would announce what role I want to play, and I would demonstrate that performance.`@
br
;　私は、部員たちが床に座って静まり返る中、立ち上がり、一人、前へ出る。\
`　As silence fell over the other club members sitting on the floor, I stood up, alone, and stepped forward.`\

;「楠木さん。@希望する役は？」@
`"Kusunoki-san. `@`What part do you want?"`@
br
;　先生が問う。@
`　The teacher asked.`@
;　私はその強い眼差しに負けないよう、力強く頷きながら答える。\
`　Without losing that self-confidence, with a strong nod I replied.`\

cl l,0
ld c,MID_Def5,23

;「楠木みどり。@魔女役を希望します。」@
`"Midori Kusunoki. `@`I want the role of the witch."`@
br
;　誰もが予想していた通りではあっても、みんなはおぉと低い声でどよめく。\
`　Even though it was what everyone expected, they all let out low gasps.`\

;「……結構。@それでは、演技をいくつか見せてもらいましょう。」@
`"...Splendid. `@`Then how about you show us a performance."`@
br
;　複雑な台詞、複雑な言い回し。@そして細やかな感情表現。@
`　Complicated lines, complicated delivery, `@`and a tender expression.`@
;　今日までずっと頑張ってきた成果が問われる。\
`　He was asking to see the fruits of all my labors from so long ago up to this day.\

ld c,MID_Def1,80

;　先生に演技を促され、……私は静かに精神を統一する。\
`　After being urged to perform by my teacher ...I quietly began to focus.`\











E_A

mbg "BMP\background\efe\red1.bmp",1
ld c,MID_K2,0
mcbg 22

;　その時、………また痛みが走った。@
`　At that moment, ...that pain ran through me once again.`@

me1v 17,50

br
;　……こんな時にまで、……また……。\
`　...Even now, at a time like this ... again...`\

;　今度は肩だった。@
`　This time it was my shoulder.`@
;　もちろん、誰かが叩いたわけでもないし、何かが飛んできたわけでもない。@
`　Of course, it wasn't like anyone hit my shoulder or like anything flew and hit it.`@
br
;　でも、何かにどんとぶつかられたような突然の痛み。\
`　But it was a pain as if I had suddenly been hit by something.`\

;「楠木、どうかしたか？」@
`"Kusunoki, what's wrong?"`@
br
;　部長が声を掛けてくる。\
`　The club president called out.`\

ld c,MID_Def2,80

;「…………いいえ、何でもありません。」@
`"...No. It's nothing."`@
br
;　一回、リラックスさせるように腕を回す。@……もう、何ともない。\
`　Hoping it would help ease my mind I circled my arm around once. `@`...There wasn't any pain anymore.`\

ld l,SIN_Def1,22

;「どうしました？@　いよいよ、今日までの成果を見せる時ですよ。」@
`"What's the matter? `@`It's finally time to show them what you've been working for until today, you know."`@
br
;　紅茶紳士さんも励ましてくれる。\
`　Even the Black Tea Gentleman was cheering me on.`\

ld c,MID_Def1,80

;　……やっぱり私、緊張してるのかな。@
`　...Perhaps I'm just nervous`@
br
;　それとも、川田のぞみを意識し過ぎてしまったせいだろうか。\
`　Or perhaps it's because I was too worried about Nozomi Kawada.`\

;　蘇るのだ。@……彼女を見ていると、……生まれ変わる前の自分を見ているようで。@
`　She stirs my memory. `@`...When I look at her ...it's as if I'm looking at myself before I was born again.`@
br
;　みどりは、魔女役の演技を見せながら、@……かつての、一学期の頃の自分を思い出していた………。\
`　As Midori was trying to perform the role of the witch `@`...she remembered herself as she was during one semester...`\

bg black,2
fede 0,2000
E_A









bgm1 14

;　生まれ変わる以前のこと。\
`　It was before I was born again.`\

;　それは私にとっては前世のように遠くて。@……そして時間的には、ほんの２ヶ月前の、一学期のことを指す。@
`　For me, that time was as far away as a past life. `@`...But in terms of time, it was a reminder of the semester from a mere two months ago.`@
br
;　私にとってはもう、思い返すのもおぼろげな、遠い記憶だ……。\
`　Even trying to remember is hazy and the memory seems distant now...`\

mono 1
bg kyou_02,22

;「みどりちゃんてさ、何か高慢ちきだよね。@お金持ち自慢が過ぎるって言うかさ。」@
`"That Midori-chan, she's always so haughty. `@`It's like she's showing off how rich she is way too much."`@
br
;　クラスメートの少女の一人が、みどりを指して唐突にそう言ったのだ。\
`　One of the female classmates suddenly pointed at Midori as she said that.`\


;　彼女は容姿もよくて成績優秀ということもあって、クラスでも人気のある、@当時の私よりヒエラルキーのはるかに高い子だった。\
`　The girl had good looks, excellent grades, and even popularity among her classmates. `@`At the time, she stood far above me in terms of class hierarchy.`\

;　………そう。@私が姫などと呼ばれてちやほやされているのは、遠い過去からのことではない。@今学期になってからなのだ。\
`　...That's right. `@`It wasn't far in the distant past when I started being pampered with the name princess. `@`It started this semester.`\

;　私にとっては、前世のことのように遠いけれど、……それはつい、前の学期のことなのだ。\
`　For me this seems as far away as a past life, ...but in reality it only happened just last semester.`\

;　その子のその指摘は、……瞬く間にクラスメートたちに共有された。\
`　As that girl began to point ...in a flash, my other classmates joined in.`\

bg black,22
mono 0
bg e010,2
;quakey 1,100

me1v 5,50

;　楠木みどりは、お金持ち自慢の高慢ちき。@
`　Midori Kusunoki is an arrogant and rich snob.`@
br
;　そうレッテルが貼られ、三日と開けずに、クラス全員によるみどりへのいじめが始まったのだ。\
`　When that label stuck, for three days straight, the entire class all began to bully Midori.`\

;　それは、思い返すだけでも辛い日々だった。@
`　Those were painful days to remember.`@
br
;　心が押し潰され、死んでしまいたいと思ったことも、一度や二度ではない。@
`　Her heart was crushed, and it didn't just cross her mind once or twice that she wanted to up and die.`@
;　そしてそのいじめは、クラスだけでなく、演劇部にも伝染した。\
`　And that bullying didn't just stay in the class, but it also spread to the drama club.`\

bg black,22
mono 1
bg engeki_01,22

;　それまでは発表会の時には何かしらの役には付けていたのに、@雑用ばかりをやらされるようになった。@
`　It even went so far as to affect her role in the performance at the time. `@`She was made to perform only the unwanted work.`@
br
;　仲の良かった部員たちも次第にみどりと口をきかなくなり、@みどりはクラスでも演劇部でも孤立した。\
`　Even her fellow club members that she got along with began to spread rumors about Midori. `@`She was isolated both in the classroom and the clubroom.`\

bg black,22
mono 0

;　まさに、……今の川田のぞみのように。\
`　I was exactly ...like Nozomi Kawada is now.`\

;　あぁ、わかった。@だから、……彼女を見ていると、…………疼くんだ。@
`　Ohh, I get it. `@`Because ...when I'm looking at her ...it hurts.`@
br
;　心の古傷が。@……前世の古傷が。\
`　The scars on my heart. `@`...From my past life.`\

fede 10,1000
E_MA

;　そんな、ある日。@
`　Then one day.`@
br
;　私は出会ったのだ。@
`　I met him.`@
;　紅茶紳士と名乗る、人ならざる存在に。\
`　That otherworldly man. The one known as the Black Tea Gentleman.`\

fede 0,1000
E_A












mono 1
bg engeki_03,22

bgm1 5

;　その日、みどりは演劇部の雑用を全て押し付けられ、@日が落ちてからも部室に残って小道具作りを行っていた。@
`　That day, Midori was forced to do all of the odd jobs for the drama club. `@`She was left in the clubroom after the sun went down, and she was making props for the play.`@
br
;　段ボールに銀紙を貼った剣を作りながら、これが本物だったら、と思った。\
`　As she was pasting silver paper on a cardboard sword, she thought 'if only this was real.'`\

;　部内でみどりを虐めるリーダー格の子は、今回の演目で主役を演じる。@ラストシーンで、彼女はこの剣で胸をついて自害するのだ。\
`　The girl who was the ringleader of Midori's bullying was the leading actress in the upcoming play. `@`In the last scene, she would commit suicide by piercing her heart with this sword.`\

;mono 0
;print 0
;bg white,1
;bg blood_1aR,22
;quakey 1,100

;　体育館のステージが彼女の血で真っ赤に染まることを、根暗に想像する。@だが、すぐにそれが、下らない妄想だと思い直した。\
`　In her dark imagination, she thought of seeing the gymnasium stage stained with her dark red blood. `@`But that kind of thinking was beneath her, so she quickly corrected herself.`\

;bg black,23
;mono 1
;bg engeki_03,23
;bgcopy
;csp -1
;mono 0

bg black,22
mono 0

;　演劇部に入ったのは、……舞台の上での輝かしい瞬間を求めてだった。@
`　When I joined the drama club, ...I wanted a moment in the spotlight up on the stage.`@
br
;　なのに、今の自分は何の役にも就けず舞台にも上がれない。@……許されているのは、こんな時間までの、たった一人での小道具作り……。\
`　Yet without any kind of role to play, I couldn't even go up on the stage. `@`...The only thing I'd been allowed to do until then was making props all by myself...`\

;　悲しくて悔しくて。@
`　I was sad. Frustrated.`@
;　でも、思い返してみれば、事の発端は全て、自業自得のような気もして。@
`　But as I try to remember, I felt I was paying for my mistakes.`@
br
;　……お金持ち自慢の高慢ちき、というレッテルを貼られる前に戻ることが出来たらと、@ひとり悲しく夢想していた…。\
`　...As I tried to remember back before I was labeled a rich arrogant snob, `@`I day dreamed sadly ― alone...`\

;　涙を零したって、仕事は終わらない。@
`　Even though I shed my tears, the work didn't end.`@
br
;　みどりは大きく深呼吸をした。@……薄暗い部室のカビと塗料の臭いが、鼻を通り抜けていった。\
`　Midori took a deep breath. `@`...And the smell of mold and paint in that gloomy clubroom passed through her nose.`\

;　……しかし、もう一度、深呼吸をした時。@みどりは不意に、香ばしい素敵な香りを嗅いだ気がした。@
`　...And yet, when she took another deep breath, `@`Midori suddenly caught the wonderful smell of a sweet fragrance.`@
br
;　それはあまりにこの場には不似合いな、………紅茶の香りだった。\
`　It was something totally unfitting for a place like this ...It was the smell of tea.`\

fede 0,1000
E_A

;bg white,23
mono 1
bg engeki_01,23













me1v 11,90

;　思わず部室を見回したみどりの目は、ある一点に注がれた。@
`　Without realizing it, suddenly Midori's eyes focused on a fixed location within the clubroom.`@
br
;　………閉じられた窓の前に、湯気のたつティーカップが浮いていた。@……そう、浮いていたのだ。@何もない空中にふわふわと。\
`　...In front of a closed window, a steaming teacup was floating. `@`...Yes, it was floating. `@`Dangling in the middle of the air.`\ 

;　小道具作りに疲れ切っていたせいもあっただろう。@……みどりはただ呆然と、その不思議な光景を凝視していた。\
`　It might have been because she was exhausted from making all those props. `@`...Midori just stared blankly at that strange sight.`\

;　…………自分が見ているのは幻に違いない。@
`　...She had to be seeing things.`@
br
;　毎日のいじめと小道具作りの作業で、心身共に疲れきっていたみどりは、そう思い込もうとした。@
`　Being bullied every day into making props and exhausted both physically and mentally, Midori thought as much.@
E_A
;　だからそのティーカップがいきなりしゃべりだした時にも、大して驚きはしなかった……。\
`　Because she wasn't even that shocked when that very teacup suddenly spoke...`\

bgm1 18

;「……このような時間まで部活動とは。@……熱心なお嬢さんですねぇ。」@
`"...Continuing club activities until a time like this~. `@`...You must be quite a dedicated young lady."`@
br
;　成人男性の声だった。@若いのかお年寄りなのかすら分からない、@まるでエコーでもかかったのかの様な不思議な響きのある声だった。\
`　It was the voice of a grown man. `@`I couldn't tell if he was young or old, `@`but it was a mysterious voice that seemed to resonate like an echo.`\

mono 0
print 2

;「失礼。@驚かせてしまいましたか……？」@
`"I apologize. `@`Did I scare you...?"`@

ld l,MID_Def2a,22

;「い、………いいえ。」\
`"Er ...No."`\

;「ふむ。@……どうやら、お嬢さんの心のチャンネルと、@私の波長が偶然にも合ってしまったようですね。」@
`"Hmm. `@`...Somehow, it seems the channel to your mind has coincidentally met with my own wavelength."`@
br
;　ティーカップが動きながら、そうしゃべる。\
`　The teacup said as it moved about.`\


;　次第に、それが透明人間が手にティーカップを持っているのだと理解できるようになる。@
`　Gradually I began to tell that it was as if an invisible man was holding the teacup in his hand.`@
br
;　すると、まるでカメラのピントが合うみたいに、@………ティーカップを持つ、男の姿が見えてくるようになる……。\
`　Then, as if coming into focus, `@`...the man who held the teacup began to appear...`\

se1v 56,50

bg white,8
bg engeki_01,0
ld l,MID_Def2a,0
ld r,SIN_Def1,22

;　それは、タキシード…？　をアレンジしたような、不思議な服を着た大人の男性だった。\
`　He was a man wearing a strange outfit arranged with a ...tuxedo?`\

;　……先生には見えない。@もちろん生徒にも見えない。@
`　...He didn't look like a teacher. `@`Of course, he didn't look like a student either.`@
br
;　しかしその奇抜な服装は、むしろ演劇部にぴったりのようにも思えた。\
`　But that eccentric attire seemed perfectly suited for the drama club.`\

ld r,SIN_Def3,80

;「おや。@すっかり私の姿が見えるようになったみたいですねぇ。」@
`"Oh my. `@`It seems you can see all of me now."`@
br
;　不思議な男は、にっこりと微笑みながらもう一度、紅茶をすする。\
`　With a smile on his face, the mysterious man took another slurp of his tea.`\

ld r,SIN_Def2,80

;「こんばんは、お嬢さん。@……部活動に熱心なのは良いことですが、@女の子には少々、遅過ぎる時間ですよ。」@
`"Good evening, young lady. `@`...Being dedicated to your club activities is good, `@`but isn't it a bit too late for a girl like yourself to be out?"`@
br
;　それが、みどりと紅茶紳士の、初めての出会いだった。\
`　That was the first time that Midori met the Black Tea Gentleman.`\

bg black,22

;　紅茶紳士は、小道具作りを手伝ってくれたわけではない。@
`　The Black Tea Gentleman didn't offer to help her put together the props or anything like that.`@
br
;　しかし、窓辺でティーカップを傾けながら、みどりの身の上話に静かに相槌を打ってくれた。\
`　However, he did quietly listen to Midori tell her story while inclining his teacup by the window.`\

bg engeki_03,0
ld r,MID_K1,0
ld l,SIN_Def1,2

ld l,SIN_Def3,80

;「……可哀想に。@クラスにも部活にも居場所がないとは、実に気の毒な限りです。」@
`"...You poor thing. `@`Being an outsider in your own classroom and even in the clubs is truly regrettable."`@

ld r,MID_Def2,80

;「クラスは、……別にいいんです。@元々、学校なんて、好きじゃなかったし。」\
`"Well, class ... that's fine. `@`I didn't really like school since the very beginning."`\

ld l,SIN_Def1,80

;「では、貴方が悲しんでいるのは、……演劇部のことなのですね。」\
`"So what's troubling you must be the... drama club then?"`\

ld r,MID_Def2a,80

;「私、……本当に演劇が好きなんです。@………舞台の上では、色んな自分になれる。@別の世界や、別の人生が体験できる。@それが好きで、演劇部に入ったんです。」\
`"I ...really love drama. `@`...On the stage, I can become whatever I want. `@`I can experience different worlds ― different lives. `@`Because I love that, I entered the drama club."`\

ld l,SIN_Def2,80

;「……なのに、貴方は理不尽に扱われ、今や小道具作りを押し付けられるこの扱い。@……お気の毒なことです。」\
`"...And yet, you're treated unreasonably. Even now, you're being forced into making props.  `@`...How regrettable."`\

ld r,MID_K2,80

;「………………………………。」@
`"........."`@
br
;　みどりは手を止め、……しくしくと涙を零す。@
`　Midori stopped working... And she began to sob.`@
br
;　小道具作りがしたくて、演劇部に入ったわけではないのだ。\
`　She hadn't joined the drama club because she wanted to make props.`\

;bg white,28
bg black,22

;　輝きたかった。@声援を浴びたかった。@
`　She wanted to shine. `@`She wanted to be showered with applause.`@
br
;　クラスでいじめられようとも、@……せめて舞台の上でだけでも輝けたなら、まだ堪えることは出来たのだ。\
`　Even if she were bullied in class, `@`...she could endure as long as she could at least shine upon the stage.`\

bg engeki_03,0
;ld r,MID_Def1,0
ld c,SIN_Def1,22

ld c,SIN_Def3,80

;「………可哀想に。@……しかし、これも何かの縁です。」@
`"You poor thing,`@`...But, this is also some kind of fate."`@`

ld l,MID_K1,80

;「縁、って……？」\
`"Fate?"`\
cl c,0
ld r,SIN_Def2,23

;「私たちが望まずして姿を見ることが出来るニンゲンは、なかなか存在しませんよ。@私と貴方のこの出会いは、とても奇跡的なのです。」@
`"There are hardly any humans that exist who can see us unless we wish it to be so. `@`In other words, our meeting here is quite miraculous indeed."`@
br
;　確かに奇跡だろう。@
`　It certainly is a miracle.`@
;　人の人生において、人ならざる者と出会う機会など、普通、あるわけもないのだ。\
`　Meeting an otherworldly creature in one's life is by no means ordinary.`\

ld r,SIN_Def1,80

;「せっかくの機会です。@……私の力で、貴方のささやかな夢を一つ、叶えてあげましょう。」@
`"Now is your long awaited chance. `@`...With my power, allow me to make your dream come true."`@

ld l,MID_K2,80

;「私の、……夢………。」\
`"My ...dream...."`\

cl r,0
ld c,SIN_Def4,24

;「貴方は、クラスでどんなにいじめられようとも、@舞台の上で輝けたならそれで満足とまで仰いました。@……演劇部員として、実に見上げた根性です。@それに敬意を表し、……そんな貴方の夢を一つだけ、一度だけ叶えてあげましょう。」@
`"No matter how much you might be bullied in class, `@`as long as you can shine up on the stage, you said you'd be happy. `@`...As a drama club member, that is truly an admirable spirit. `@`As a token of my respect, ...allow me to grant your one dream ― your one wish."`@
br
;　男はそう言うと、左手をツイと上げる。\
`　When he said that, the man quickly raised his left hand.`\

se1v 56,50

;　すると、部室の隅に詰まれた、舞台脚本を詰めたダンボール箱がいくつも、ふわりと浮き上がる。@
`　Then, from the corners of the room, countless packed cardboard boxes filled with scripts gently began to float.`@ 
br
;　そこから何冊もの舞台脚本が飛び出し、……私の周りを、ゆっくりと漂いながら回り始める。\
`　From those boxes leaped out innumerous scripts springing forth ...and they floated and began to twirl around me.`\

me1v 17,70

se1v 56,50

bg white,28
bg black,28

se2v 22,50

bg white,23

se3v 1010,50

bg engeki_01,0
ld r,SIN_Def2,23
ld r,SIN_Def1,80

;「お好きな役を選んで下さい。@貴方にその役を与えてあげましょう。」@
`"Please pick the role you desire. `@`And I'll give you that role."`@

ld l,MID_Def2a,22

;「ほ、本当に……？@　ど、どんな役でも……？！」\
`"R- Really...? `@`A- Any role?!"`\

ld r,SIN_Def3,80

;「えぇ、どんな役でもですよ。@悪を倒すヒーローにも愛を囁かれるヒロインにも。@望むなら犬にも猫にも、背景の木の役にだってして差し上げますよ……。」\
`"Yes, any role! `@`A hero who topples evil. A heroine who receives whispers of love. `@`If you wish it, I'll give you the role of a dog, a cat, or even a tree in the background...."`\

;ld l,MID_Def1,80

me2v 16,50

;　いくつもの素敵な舞台脚本がみどりの前を過ぎる。@
`　Countless wondrous scripts passed in front of Midori.`@
br
;　どの脚本も、どの役も、……憧れて止まなかったものばかり。\
`　Any script, any role ...she couldn't contain her excitement.`\

ld r,SIN_Def1,80

;「一つだけ、選んで下さい。@それを以って、私たちの契約と致しましょう。」@
`"Please, choose only one. `@`With that, we'll make our contract."`@

ld l,MID_K1,80

;「……契約って……？」\
`"...Contract...?"`\

ld r,SIN_Def4,80

;「すでにご想像されていると思いますが。@私はニンゲンではありません。@……むしろ、ニンゲンの皆さんの魂のカケラを少々。@お裾分けしてもらって糊口を凌ぐ身です。」\
`"It may have already come to your attention, `@`but I am not human. `@`...Rather, I take a little off the top of fragments of souls of all you humans. `@`I am a creature that ekes out a living on what is given to me."`\

bg black,22

;　みどりもすぐに察する。@
`　Midori quickly realized it.`@
br
;　どんな役でも。@一つ願いを叶える代わりに、……魂を渡すという契約をせよと言っているのだ。\
`　No matter what role. `@`In exchange for granting a single wish, ...he was saying it was a contract in exchange for her soul.`\

;bg white,1
bg engeki_02,0
ld c,SIN_Def1,22
;ld l,MID_Def1,22

ld c,SIN_Def2,80

;「おっと。@誤解させてしまいましたね。@……私は決して、死神ではありません。@私と契約したからと言って、貴方のお命を頂戴するような物騒は致しません。@魂のカケラをほんの少々。@かじらせてもらう程度です。@貴方には自覚できない程度のわずかですので、どうぞご心配をなさいませんように……。」\
`"Oh. `@`It seems you've misunderstood me. `@`...I am most certainly not a god of death. `@`A contract with me doesn't mean you would be giving me your life in exchange. `@`Just a tiny sliver of your soul. `@`I'd take just enough to nibble on. `@`Since it'd be so little, you wouldn't even be able to notice, so please don't worry..."`\

;　男はそう言ってにこやかに笑う。@
`　The man said with a smile.`@
br
;　……その笑いは確かに、命と引き換えに…、という物騒さは感じさせないものだった。\
`　...From a smile like that, she couldn't sense any danger of giving her life away.`\

fede 10,1000
E_MA

ld l,MID_K5,80

;　みどりは、逡巡せず決断する。@
`　Midori made her decision without hesitation.`@
br
;　このままの日々を繰り返したって、……自分の心は日々、殺されていくだけなのだ。\
`　Repeating her days like this... she was slowly being killed with the passing of each day.`\

;　なら、彼と契約しよう。@
`　So she would make the contract with him.`@
br
;　日々、緩慢に殺されていくくらいなら。@………自らの意思で魂のカケラを支払い、何かを切り開く方がずっとマシだ。\
`　...Cutting off something, offering a piece of her soul, `@`seemed a much better option than being slowly killed.`\

cl c,0
ld r,SIN_Def4,23

;「素晴らしい。@……貴方の心の強さに敬意を表します。@……貴方は必ずや得るでしょう。@この貴重な機会を活かし、それを切っ掛けに、まったく別の人生を切り開けると。@……貴方は必ずや今夜の奇跡を活かし、生まれ変われるに違いありません。」\
`"Wonderful. `@`...I respect the strength of your spirit. `@`...Of course you will take the contract. `@`Take this precious opportunity ― take advantage of it and start a whole new life. `@`...You will make the best of tonight's miracle, and you will be born again."`\

bg black,22

;　時に、舞台の上での神秘体験が、……実生活にも影響を及ぼすことはある。@
`　Occasionally... I've had the mystical experience of being on stage affect my real life.`@ 
br
;　そう。@これは私にとって、一度だけお芝居で抜擢してもらえるというだけの奇跡ではない。@
`　That's right. `@`For me, this isn't a miracle that's just for a role in a play.`@
br
;　これを機会に、……自分を、人生を、運命を、変えるのだ。\
`　This is a chance to... change myself, change my life, and change my fate.`\

;　彼はそのチャンスを与えてくれた。@……でも、掴むのは私なんだ。@
`　He gave me that chance. `@`...But I am the one taking it.`@
br
;　絶対に掴む。@……そして、変えるんだ……。@
`　I will take it`@` ...and, change...`@
br
;　そして私は、………役を、選んだ。\
`　So, I chose ...my role.`\

bg engeki_01,22
;ld r,SIN_Def1,0
ld c,MID_Def2,22

;ld l,MID_Def1,80

;「……あなたのことは、何て呼べば……。」@
`"...What should I call you...?"`@

ld l,SIN_Def1,22

;「そうですね。@……では、私の大好きな紅茶にちなみ。@紅茶紳士とでも名乗るとしましょう。」\
`"That's right. `@`...Well, since I do love tea, `@`you may refer to me as the Black Tea Gentleman."`\
















bg black,2

fede 0,2000
E_A

bg engeki_02,2

bgm1 5

;　そして、紅茶紳士さんは約束を守った。@
`　So the Black Tea Gentleman kept his promise.`@
br
;　次の演目で、私は大抜擢を受けたのだ。\
`　For the next play, I was chosen for the lead role.`\

;　その役の子が本番の直前に部長と大喧嘩をして、部を飛び出してしまったのだ。@
`　The girl who was playing the part had a big fight with the club president and ran out of the club.`@
br
;　私は偶然にも、彼女の不在の折に代役を務めるため、その台本を熟読していた。@だから、本当の代役が見つかるまで、@仮ではあるが大抜擢を受けることとなったのだ……。\
`  Since I could take up her role in the performance by chance, I carefully read her script. `@`So until a real substitute was found, `@`although it was temporary, I hadn't been selected for any major roles before...`\

;se1 01
;bg white,28
;bg engeki_02,2

bg black,22

;　………それは私が願って止まなかった、可憐な可憐な、……お姫様の役だった。\
`　......I never stopped wanting it. ...The sweet, sweet role of the princess.`\
;　私など、突然の穴に抜擢された、あくまでも急場凌ぎ。@……先生も部長も、誰も期待などしていなかった。\
`　That someone like me was chosen to fill a sudden opening in a last minute emergency. `@`...My teacher, even the club president ― no one expected it.`\

;　でも、私はその役に、全ての魂をぶつけた。@
`　But I thrust all of my soul into that role.`@
br
;　紅茶紳士さんが与えてくれた、たった一度のチャンスに、@……いや、一度と知るからこそ、全てをぶつけたのだ。\
`　Into that once-in-a-lifetime chance that the Black Tea Gentleman gave to me... `@`No, it was because I knew it was my only chance that I gave it everything I had.`\

;se1 77
bg white,22
bg engeki_05,2

;　お稽古も舞台の上も、……頭の中は真っ白だった。@
`　In practice and on stage, ...my mind was empty.`@
br
;　それは緊張していて真っ白だった、という意味じゃない。@
`　I don't mean empty as if my mind went blank from nervousness.`@
;　私の全てを、内側が空っぽになるくらいに、全て全て出し切ったという意味。\
` I mean it was as if everything about me, everything inside of me, had been hollowed out and everything had been used up.`\
;　全てが無我夢中。@……舞台が幕を下ろすまで、何も記憶に残ってはいなかった。\
`　Everything was a dream. `@`...I have no memory of what happened until the curtain dropped.`\

se1v 54,70
wait 100
se2v 54,70

;　……だから、全てが終わり、我に返った時。@
`....But when everything was over, I returned to my senses.`@
br
;　私は割れんばかりの歓声と拍手の中にいた。\
`　I was surrounded by cheers and roaring applause.`\

;　何が何やら、わからない。@眩いスポットライトに照らし出され、目が眩んでしまい、何もわからない。@
`　I don't know what happened. `@`I was caught wide-eyed and confused in the dazzling spotlight, and I have no idea what happened.`@
br
;　主演の部長が私の手を取って、………アンコールに応えてあげる。\
`　The club president who was playing the lead took my hand... and asked for an encore.`\

se1v 54,100
wait 100
se2v 54,100
wait 100
se3v 54,100

;　その時、私はようやく理解し、実感した。@
`　At that moment, I finally realized and experienced it.`@
br
;　舞台は、……私のお姫様の役は、……大成功に終わったのだ……。\
`　On that stage... my part as the princess,... was a massive success...`\

bg black,23
bg engeki_06,0
ld r,SIN_Def1,23
;ld r,SIN_Def1,80

me1v 24,50

wait 500

ld l,MID_Def2,22

;「紅茶……紳士さん…………。」@
`"Black Tea Gentleman..."`@

ld r,SIN_Def2,80

;「お見事でしたね。@ここでずっと見ていましたよ。」@
`"You did wonderful. `@`I've been watching from here for some time."`@
br
;　舞台袖のカーテンの陰で。@紅茶紳士さんもずっと手を叩いていてくれた。\
`　In the shadows behind the curtain. `@`The Black Tea Gentleman had been applauding for a while as well.`\

ld l,MID_Def5,80

;「あなたの……お陰です……。@……私は、………最高の役を得ました……。」\
`"I... had the best role... `@`...And it's all thanks... to you..."`\

ld r,SIN_Def3,80

;「えぇ。@私は貴方の望む最高の役を与えました。@しかし、それを演じ切ったのは貴方の力ですよ。@……この大歓声に讃えられるに相応しい、素晴らしい才能でしたよ。」\
`"Yes. `@`I gave you the best role that you wanted. `@`However, the role was played through your strength. `@`...Receiving roaring cheers was most befitting your wondrous talents."`\

cl l,5
;ld l,MID_Def1,80

;「………嬉しい……。@……嬉しいです……。@……私、……眩し過ぎて、……何も見えない……。」\
`"...I'm happy... `@`...I'm happy... `@`...It was so bright ...I couldn't see anything..."`\

ld r,SIN_Def1,80

;「もう、貴方は生まれ変わったのです。@チャンスを得て、貴方が掴んだ。@……その力を忘れずに。@貴方の人生を切り開き、ますますに豊かなものにしてくれるでしょう。」\
`"You've already been reborn. `@`You got your chance and took it. `@`...You mustn't forget that strength, `@`and since you've cleared your past life, you'll be much better for it, wouldn't you say?"`\

ld l,MID_Def4a,26

;「忘れませんっ。@私、……今のこの気持ちを、絶対に……。」\
`"I will not forget. `@`I will never... forget this feeling..."`\

ld l,MID_Def3,80
cl l,2

wait 1000

ld r,SIN_Def4,80

;「それと、私との約束も、お忘れなく。」\
`"And, do not forget our contract either."`\

cl r,2

;　紅茶紳士はにやりと笑い、それだけを言い残すと姿を消す。\
`　The Black Tea Gentleman said with a smile. And with those words, he disappeared.`\

bg white,1
bg engeki_05,22
se1v 54,70
wait 100
se2v 54,70


;　でも、今この場で魂を抜き取られて殺されたとしても。@……構わないくらいに、彼女は絶頂の中にいた。\
`　Even if she were to be killed by having her soul torn out from her right there `@`...it no longer mattered, because she was on top of the world.`\

fede 0,2000
E_A











bg black,2

bgm1 1

;　奇跡の大抜擢。@奇跡のお姫様。@
`　The miraculous choice. `@`The miraculous princess.`@
br
;　彼女はその日より、みどり姫と呼ばれ、@学校中の女子から憧れられ、一目を置かれるようになったのだ……。\
`　From that day forward, she was called Princess Midori. `@`She was admired by the girls at school and became well respected...`\

bg kyou_01,2

;　そして夏休みが終わって、新学期になると。@
`　Summer vacation ended and a new semester began.`@
br
;　一学期の頃が嘘だったかのように、みどりに対するいじめは、綺麗さっぱりなくなっていた。\
`　As if that semester had never happened, the bullying of Midori stopped entirely.`\

;　かつて自分をいじめていた子たちは、皆、それがまるでなかったかのように振舞った。@
`　Those that had once bullied her, everyone, acted almost as if it had never happened.`@
br
;　みどりにちやほやし、姫と呼んで持て囃してくれた。\
`　They fussed over Midori, called her princess, and gave her praise.`\

;　最初はちょっぴり、何て調子のいい人たちとも思った。@
`　At first she thought everyone was a little inconsistent.`@ 
br
;　でも、手の平返しではあっても、………尊敬し、敬愛してもらえるのは悪い気持ちではない。\
`　And yet on the other hand, ...it didn't feel bad to be respected and loved.`\

;　……そこで浮かれたくなる気持ちを、彼女はぐっと堪える。@
`　...It was then that a feeling of delight began to take hold of her.`@
br
;　もう、お金持ち自慢の高慢ちきなんて、絶対に言われないようにしよう。@
`　She decided that she wouldn't flaunt her wealth anymore.`@
;　あのお姫様のように、……可憐でやさしくて、誰からも愛される心の美しいお姫様になるんだ……。\
`　Just like that princess ...she would become sweet, kind ― a beautiful princess with a heart loved by all...`\

bg black,22
bg kyou_03,22

;　あの舞台を機に、私は生まれ変わったのだ。@
`　From that chance on stage, I was reborn.`@
br
;　今ではもう、一学期のことなんて、誰も覚えていない。\
`　Even now, no one remembers what happened that semester anymore.`\

;　男子なら、私が側を通り過ぎるだけで、見惚れて顔を赤くし。@
`　As for the boys, their faces turn bright red just from seeing me walk past them.`@
br
;　女子なら、私に憧れ、友達と呼んでもらいたがる。\
`　And the girls adore me and want to call me their friend.`\

;　私のわずかの振る舞いに、みんなは一喜一憂する。@
`　Based on how I act, everyone is moved to joy or sorrow.`@
br
;　私の何気ない仕草が、まるで偉人のように扱われ、学校の伝説になっていく。\
`　It's as if my casual actions are treated like those of a celebrity, and I've started to become a legend at school.`\

bg black,23
bg rouka_03,0
ld r,MID_Def1,23

cl r,2

;『みどりちゃんって凄いよね、かっこいいよね！@　私もあんな風になりたいっ。』@
`"Midori-chan is awesome! She's so cute! `@`I want to be just like her!"`@
;『みどり姫、マジ可憐……。@一度でいいから、名前呼んで微笑んでくれねぇかなぁ……。』@
`"Princess Midori is so sweet... `@`It would be so nice if she would call my name just once and smile..."`@
;『みどり姫、主演の演劇、またやらないのかな！@　演劇部、目が離せな～い！』\
`"I wonder if Princess Midori is going to do another performance?! `@`Better keep an eye on that drama club~!"`\

bg black,23
bg engeki_01,23

;『さぁっ、レッスンレッスン！@　浮かれないで！@　基礎を忘れずに！』@
`"Alright, lesson time! `@`Don't get excited! `@`And don't forget what you've learned!"`@
;『……楠木の実力を見誤ってたよ。@これまでを申し訳なく思う…。』\
`"...I really misjudged Kusunoki's true potential. `@`I have no excuse for how I've acted lately..."`\

ld r,MID_Def3,22

;『いいんですよ、部長。@私、これからもお稽古をがんばって、もっともっと素敵な演技が出来るように努力しますね。』\
`"It's fine, club president. `@`I'm also going to do my best at practice, and I'm going to work hard to become an even better actress."`\

;『さすがみどり姫～……。@何であんな素敵な子が同じ部にいるのに、私たちはずっと気付かなかったの？』@
`"That's our Princess Midori~... `@`How come we never noticed there was such a wonderful girl like her in our class before?"`@
br
;　教室でも部室でも、みどりを賞賛する声が溢れる。\
`　In the classroom and in the clubroom, voices of praise washed over Midori.`\

bg black,22

;　それらはみどりに自信と勇気を与えた。@
`　Those voices gave Midori self-confidence and courage.`@
br
;　そしてみどりも慢心することなく、稽古に励み。@何より、誰からも愛される自分になろうと、心を入れ替えた。\
`　And so, without being conceited, Midori strived at practice. `@`Most of all, she changed her heart so she could become someone loved by all.`\

;　心が変われば、それは身体も変わる。\
`　If one's heart changes, that changes the body as well.`\

;bg white,28
bg black,0
ld r,MID_Def1,22

;　いつも俯いて猫背だった背筋はピンと伸び、美しい姿勢に変わった。\
`　Her slumped shoulders that had always hung her head in shame suddenly lifted and straightened, and her posture became exquisite.`\

bg rouka_02,0
ld r,MID_Def5,22

;　声にも凛とした響きが宿り、その声を聞いた人は思わず振り返らずにはいられなくなった。@
`　Even her voice held a dignified tone, and those that heard her voice couldn't help but turn their heads and to listen.`@ 
br
;　顔も、誰もが溜め息を漏らしたくなるほどに美しく変わっていった。\
`　Her face also changed beautifully ― making onlookers want to sigh.`\

ld r,MID_Def3,22
cl r,22

;　もう、一学期の彼女とはまるで別人。@
`　She was already a different person from the first semester.`@
br
;　まさに、彼女は生まれ変わったのだ。\
`　She had truly been reborn.`\

bg black,22
bg white,29
bg air_02,2

;　今日もみどりは部活動に勤しんでいる。@
`　Even today, Midori is working hard in the club activities.`@
br
;　校庭を走り込んでの体力作り。@
`　She's running around the courtyard building her endurance.`@
;　他の部活の子たちが、みどりの姿が見える度に、手を振ったり声援を送ったりする。\
`　Each time the other club members see Midori, they throw out their hands and cheer.`\

;　………私、本当に幸せだ………。@
`　......I, ...am truly happy......`@
br
;　みどりはこうして、……誰からも愛される“姫”になったのだ……。\
`　Like so, ...Midori became the 'princess' loved by all...`\

















bg black,22
bg gakkou_03,22

me1v 17,50

;「…………たった一つの小さな切っ掛けで、ニンゲンはここまで変われるものなのですねぇ。」@
`"............It seems that humans can change from just this one little chance."`@
br
;校舎の物陰で、誰にも見えないティーカップが、ツイっと傾く。\
`　Under cover of the school building, nobody could see a teacup tip back.`\
ld r,SIN_def2,22

fede 1,1000
E_B

wait 1000

ld r,SIN_def4,80

;「ですが、みどりさん？@　一応、これ。@……ギブアンドテイクですので、@その辺りだけは、お忘れないようお願いしますよ。@……っくっくっく。」@
`"Oh Midori-san?`@`......Remember, this is a give and take. `@`So please don't forget that. ......Kukuku."`@
br
;もう一度、ティーカップが、ツイっと傾いた。\
`And once again, he took a sip from the teacup.`\

cl r,22










bg black,2

E_A

bg white,1
bg engeki_01,22

;「結構ですっ。」@
`"That'll be all."`@`
br
;　先生がパンと手を打つ。
`　The teacher clapped his hands together.`
;　……私は魔女役の演技を止めた。@
` ......I ceased my performance as the witch.`@`
br
;　しばしの沈黙の後、先生と部長が無言で頷き合う。\
`　In the brief silence, the teacher and the club leader nodded wordlessly.'\
bgm1 

bgm1 5

;「合格です。@楠木さん、あなたを『六軒島』の主役に決定します。」@
`"Congratulations. `@`Kusunoki-san, we have decided you will play the leading part in 'Rokkenjima'."@

ld c,MID_Def3,22
;ld c,MID_Def1,80

;「あ、ありがとうございますっ。」\
`"Th, thank you!"`\

;「みんなも楠木の演技をよく見て、各自、自己研鑽に励めよ…！！」@
`"Everybody, take a good look at Kusunoki's performance and strive to improve yourselves as well...!!"` `@`

;quake 2,200

;「「「はいッ！！！」」」\
`"""Yes!!!"""`\

bg black,24
bg engeki_03,24
se1v 54,70

;「みどりっ、魔女役おめでとう！！」@
`"Midori, congratulations on getting the witch's role!!` `@`
br
;　温かな拍手が広がっていく。\
`　A warm applause began to spread.`\

;　そんなに思い切り叩いたら、手が痛くなるんじゃないのと、@こっちが心配してしまうほどの大きな拍手だった。\
`　If one claps with all their might, wouldn't their hands hurt? `@` This applause was so big it might cause one to worry thus.`\
;「あの可憐なみどり姫が、今度はミステリアスな魔女役に挑戦なんて…。@すっごい反響がありそうだね！」@
`"To think that lovely Princess Midori will take on the role of a mysterious witch this time... `@` It sounds like it'll get an incredible reaction!`" `@`
;「もちろんっ。@みどり姫が主演の大作だもん。@すごい話題になるよ！」\
`"Of course. `@`With Princess Midori at the lead, it'll be huge. It'll be the talk of the town!"`\
;「発表会、ものすごい盛り上がりそう！@　うわぁ、今から緊張するー！」@
`"The performance sounds so incredibly exciting!`@` Uwaa, I'm already getting nervous―!"` `@`
;「……わ、私たちも、足を引っ張らないようにしないとねー。」\
`"......W-we should make sure we don't hold her back, too."` \


ld r,MID_Def1,24

;　拍手の中、花道を歩くかのような気持ちで、……私は自分の座る場所に戻る。\
`　In the applause, with a feeling like being on a runway train, ......I returned to my seat.`\

;　………前回は、突然の降板による穴埋めの抜擢だった。@
`　.........Last time, I was chosen due to a sudden resignation.` `@`
br
;　しかし今回は違う。@実力で役を掴み取った。@
`　But this time is different. `@` I got the role with my own power.` `@`
;　たった一段だけれども、確実に踏み越えた。@そんな達成感があった。\
`　It may be by just one step, but it's one I've definitely overcome. `@` It was that feeling of accomplishment.`\

;　………みんなの拍手に包まれながら、座る時。@
`　.........At the moment I sat down, enveloped by everyone's applause.` `@`
br
;　また、………川田のぞみと目が合った。\
`　Once again.........I met Nozomi Kawada's gaze.`\

bg black,22
;ld r,MID_Def1,80

;　みんなは満面の笑みで祝福してくれているのに、………彼女だけは違った。@
`　Even though everyone was blessing me with their full smiles, .........She was the only exception.` `@`
br
;　ただ、ジッと私を見ていた。\
`　She just, stared at me.`\

;　その瞳からは何の感情も読み取れない。@わかるのは、祝福の気持ちがないということだけ。@
`　I couldn't read what kind of emotions those eyes had. `@`I only knew that it was not a feeling of celebration.` `@`
br
;　……そんな彼女の姿に、まるで一学期の頃の自分を見ているような、@……不安と焦燥を覚えてしまう。\
`　......It was as if I was gazing upon myself from my first semester. `@`......It forced me to remember the anxiety and uneasiness.`\

;bg black,22
mono 2
bg Different_spiral_1a,22

;　何で、そんな嫌な目でずっと私を見ているの…？@
`　Why is she always watching me with such disgust in her eyes...?` `@`
br

;　………わかってる。@……私が、妬ましいんだよね……？\
`　.........I know. `@`......She's, jealous of me, isn't she......?` \

;bg Different_spiral_1b,22

;　かつては自分がお姫様だとちやほやされてたのに、@……今ではお金持ち自慢の高慢ちきだと嫌われ、いじめられ。@
`　Even though she once was pampered as a princess, `@`......Now, she is hated and bullied for being proud, rich, and haughty.``@` 
br
;　……それがかつての自分そのものだから、……痛いくらいに彼女の胸中がわかるのだ。\
`　......I understood her pain so well it hurt ......because that was who I used to be.`\
bg black,22
mono 0
;bg white,28

;　でもね、川田さん。@
`　But you know, Kawada-san.` `@`
br
;　変われるよ、人間は。@
`　Humans can change.` `@`
br
;　あなたは、かつての私。\
`　You are my former self.`\

;　その私も、たった一度のチャンスで、自分が生まれ変わるほどの変化を得た。@
`　Even I, with just one chance, was able to transform so much, it was as though I was reborn.` `@`
br
;　ならあなたにだってきっと。@そんなチャンスがやがてあるよ……。\
`　I'm sure you can too. `@`Your chance will come someday......` \










E_A

bg "BMP\background\efe\red1.bmp",1
bg engeki_03,22

wait 2000

ld r,MID_K2,6

me1v 28,70

;「…………痛ッ、…………………。」\
`"............Ow!..............."`\

;　その時、何の前触れもなく、また、………痛みが走る。@
`　Suddenly, without warning, I was struck with pain again.` `@`
br
;　足に、思わず身をよじってしまうような激痛が。\
`　A severe pain in my foot, one that caused me to unconsciously contort my body.` \

bg black,23
bg engeki_01,23

;「……ちょっと、みどり。@……大丈夫…？」@
`"......Hey Midori. `@`......Are you okay...?` `@`
;「顔色悪いよ？」@
`"You don't look so good."` `@`

ld c,MID_Def2a,22

;「………ん、……大…、丈夫…………。」\
`".........Rgh,......I'm...,I'm fi-............"`\

;「保健室行った方がいいよっ。@私、付き添うよっ。」@
`"You should go to the nurse.`@` I'll escort you there."``@`

br
;　みんながみどりの身を案じる。\
`Everyone was concerned about Midori's health.`\

bg black,22

;　もう何度目になるかもわからない、突然の謎の痛み。@
`　This mysterious sudden pain that keeps happening to me.` `@`
br
;　……良い機会かもしれない。@一度、保健室で見てもらおう。\
`　......This might be a good opportunity. `@` I'll try getting it looked at in the infirmary.`\

;　きっと、緊張のし過ぎなんだ。@普通の人は腹痛に出る。@……私はきっと、それが体の痛みに出るタイプに違いない。\
`　It has to be because I'm so nervous. `@` Most people would get a stomach-ache. `@` ......I must be the type that gets pains all over.`\

;　リラックスしてれば大丈夫と、保健の先生に太鼓判を押されれば、またがんばれる…。@
`　If I relax, I should be okay. I'll get the nurse's seal of approval, then I'll be able to do my best again...` `@`
br
;　みどりは部員の肩を借りて、保健室へ向かうのだった……。\
`　While leaning on the club member's shoulder, she headed toward the infirmary......`\

fede 0,1000
E_A
wait 1000






bg gakkou_02,22

me1v 31,50

wait 2000

bg hoken_01,22
ld r,HOK_Def1,22

me2v 11,90

;「特に異常はないみたいね。」@
`"It doesn't look like there's anything particularly wrong."` `@`
br
;　保健室の先生はあっさりとした口調でそう言った。@
`　The school nurse put it bluntly.`@

;　足に感じていた痛みは、保健室にくるまでに完全に消えていた。\
`　The pain in her foot had completely disappeared when she'd come to the infirmary.'\

ld r,HOK_Def4,80

;「何もないのに、突然、痛くなるなんて。@………もし、頻繁に繰り返すようなら、大きな病院で見てもらった方がいいわね。」\
`"There seems to be nothing wrong so you shouldn't have sudden pains like that... `@`......If it keeps happening all the time, you should get checked out in a real hospital."`\

ld l,MID_Def2,22

;「い、いいえ、大丈夫です。@私、緊張したり疲れたりすると、痛みを感じるタイプなんだと思うので……。」@
`"N-no, I'm fine. `@`I'm think I'm just the type who feels pain when I get nervous or wear myself out......"` `@`
br
;　それを友達が大袈裟がっちゃって。@……大騒ぎしちゃってすみませんでしたと、みどりは謝る。\
`　Her friends made a big deal about it. `@`......Midori apologized, saying she was sorry for causing the commotion.`\

bg black,22

;　病院には行きたくなかった。@
`　She did not want to go to the hospital.`@
br
;　もしも本当に何か悪い病気だとしたら、発表会に出られなくなるかもしれない。@
`　If she really did have a terrible illness, she might not be able to go to the performance.`@
;　せっかく主役を演じることが決まったのに、それだけは絶対にごめんだった。\
`　Since she'd just been chosen as the lead role, that was the one thing she absolutely couldn't accept.`\

bg hoken_04,22
;ld r,HOK_Def1,80

;　もう平気だと言われては、保健の先生に何も出来ることはない。@不思議なこともあるものだと、鉛筆を鼻の下に挟んで小首を傾げる。\
`　Once she said she was fine, the nurse couldn't do anything else for her. `@`Strange things happen sometimes, and with that she held her pencil between her nose and upper lip and tilted her head.\

;　特に異常はない。@……その言葉にみどりは少し安堵するが、@ならばこの痛みの正体は何なのかと、かえってもやもやした気持ちになるのだった。\
`　Nothing particularly wrong. `@`......Those words relieved Midori, `@`but wondering what the true reason was for the pain caused her mind to wander.\

fede 11,1000
E_M1






bg black,22

;　かつては十日くらいに一度、唐突に痛む程度だった。@
`　Before, the pain would come once every ten days.`@`
br
;　しかし、少しずつその頻度が増えてきた気がする。\
`　However, little by little she got the feeling they had become more frequent.`\

;　痛みも、かつては触る程度や、あるいは鈍痛程度だったのに、@最近は顔をしかめてしまうような激痛も多い。\
`　Even though the pain used to hurt only when it was touched, or would just be a dull pain,`@` lately, the pain had become more frequent, and intense enough that her face would show it.`\

;　これからは、発表会に向けて、ますますにお稽古に集中していかなければならない。@
`　From here on, in preparation for the performance, she must focus on practicing more and more.`@
br
;　なのに、このおかしな痛みがどんどん酷くなっていったら、きっと差し支えるに違いない……。\
`　But still, if this strange pain gets worse and worse, it's definitely going to interfere ......\

bg hoken_02,22
;ld l,SIN_Def1,24

E_A

;「…………気にしないことですよ。@/
`".........It's something you don't need to worry about.`@/
bgm1 18
;　痛みなどに、かまけているほど貴方はお暇ではないでしょう。」@
` You don't have the time to become so preoccupied with pain."``@`

ld r,MID_K1,22

;「紅茶紳士さん……。」\
`"Black Tea Gentleman......"`\

ld l,SIN_Def2,22

;「あの、舞台の上での集中力を忘れてしまいましたか？@　貴方は発表会に向けて、役作りに励まねばなりません。@それが疎かだから、痛みなどというものが気になってしまうのではありませんか？」@
`"Have you forgotten about the concentration you'll need on stage? `@` You must focus on your performance and perfect your character. `@`It's foolish to pay attention to such pain, is it not?"`@

ld r,MID_Def2a,80

;「……………………。」\
`".........."\

;　痛みのことなど気にするな。@
`　Don't worry about the pain.@
;　紅茶紳士さんは、いつもそう言う。\
`　The Black Tea Gentleman is always saying that.`\
;ld r,MID_Def1,80

;　確かに、気にしても仕方がないのなら、彼の言う通りだ。@
`　Certainly, even if I worry about it, it's still as he says.` `@`
br
;　結局は、自分の集中力が足りないから。@
`　In the end, my ability to concentrate isn't enough.`@`
;　舞台のことだけを考え、お稽古に専念したなら、こんな痛み、気にもならないはず……。\
`　Think only of the stage, and if I give my undivided attention to practice, then I shouldn't pay this pain any mind......`\
bg black,23
bg hoken_01,23
;ld r,HOK_Def1,23
;ld l,MID_Def1,23
;ld l,MID_Def1,80
;cl l,4

;　みどりはそう納得し、先生に頭を下げてから保健室を出る。\
`　After Midori gave her consent, she bowed her head to the nurse and left the infirmary.`\

;bg black,24
;bg hoken_02,0
;ld c,SIN_Def1,24

;　……紅茶紳士はそれを背中で見送りながら、紅茶のティーカップを傾ける。\
`　......While The Black Tea Gentleman watched her go, he sipped his black tea.`\

ld c,SIN_Def2,22

;「そうですか。@……痛みの頻度が、増しているのですか。@……っくっくっく、それは困りましたねぇ……。@っくっくっくっく……。」\
`"Is that so. `@`......You're feeling those pains more often? `@`.......Kukuku, that is a dilemma, isn't it......`@`Kukukuku......`"\

ld c,SIN_Def4,22

cl c,2

;　人ならざる者にしか聞こえない笑い声を残し、紅茶紳士の姿は消える。\
`　Leaving only a laugh no human could hear, The Black Tea Gentleman disappeared.`\
fede 0,1000
E_A

;　………人ならざる者にしか、聞こえない。@
`　.........It was something no -human- could hear.`@
br
;　だから、それを人ならざる者が聞いていた。\
`　So, someone who wasn't human heard it.`\

bg black,22
bg hoken_04,22
ld_p MAR_Def4
lsp2 2,$ld_pass,10,400,-100,100,0
lsp2 3,$ld_pass2,10,400,-100,100,0
print 22

ld_p MAR_Def4a
lsp2 2,$ld_pass,90,400,-100,100,0
lsp2 3,$ld_pass2,90,400,-100,100,0
print 3

bgm1 14

;「……………………。」@
"..........."@

br
;　薬品棚の物陰から、恐る恐る毬枝が顔を覗かせる……。\
`　From the cover of medicine shelf, Marie timidly peeked her face......`\
;　その手には、職員室かどこかからちょろまかしてきた、栗饅頭が握られている。@
`　In her hand, she gripped chestnut steamed buns that may have been taken from the staff room or elsewhere.`@
br
;　……美味しそうなお茶菓子を見つけたので、彼岸花にお裾分けを持ってきたのだ。\
`　......After finding these delicious buns, she brought them to the infirmary share with Higanbana over tea.`\

;　ちなみに、毬枝にはどういうわけか、お茶菓子を発見するという奇妙な才能が、……死後に発現したのだった。\
`　How did Marie find them you ask? After she died, Marie discovered she had the miraculous power to home in on buns....`\

;　彼岸花は留守だった。@
`　Higanbana was gone.@
br
;　代わりに、………見慣れない男の姿を見てしまった。\
`　In her place,.......She saw the figure of a man she was not familiar with.`\

csp2 -1

ld c,MAR_def4a,22

;ld_p MAR_Def1
;lsp2 2,$ld_pass,90,400,-100,100,0
;lsp2 3,$ld_pass2,90,400,-100,100,0
;print 80

;「……誰、……だろう。@……今の人は……。」@
`"......I wonder.......@......that person just now was......"@
br
;　人ならざる者の直感が、紅茶紳士もまた同類であることを毬枝にも報せる。\
`　Her otherworldly senses told her that the Black Tea Gentleman was the same as she.\

;　……妖怪だろうか。@
`　......a youkai?@
br
;　先に出て行った女の子に、取り憑いてるように見えた。\
`　It looked to her that he was haunting the girl who had just left.\

;ld_p MAR_Def1
;lsp2 2,$ld_pass,90,400,-100,100,0
;lsp2 3,$ld_pass2,90,400,-100,100,0
;print 80

ld c,MAR_def1,80

;「…………………………。」\
`"............"\

bg black,2

fede 0,1000
E_A












bg engeki_01,22

bgm1 5

;　翌週から始まった『六軒島』の稽古は想像以上に大変だった。@
` Practice began on 'Rokkenjima' the following week, which was even more difficult than imagined.`@
br
;　まず、何よりも台詞が多い。@一人芝居と言っても過言ではないほどに、主役の台詞量が膨大なのだ。\
`　First, above all else, there were a lot of lines. `@`The leading part's lines were of an incredible volume, so to call it a one man show wouldn't have been an exaggeration.`\

;　覚えるだけでも大変だし、@その一つ一つの言葉の意味をきちんと理解した上で、感情を込めねばならない。@
` Memorizing them was hard enough. `@`Then she had to understand the meaning of each and every word and place an emotion to it.`@
br
;　１シーンだけでも相当な集中力を必要とする。\
`　Just one scene alone needed a considerable amount of concentration.`\

;　相手役との呼吸が一つ合わなかったりするだけで、@途端に台詞が出てこなくなったり、小道具の扱いを間違えてしまったりする。\
`　If she were to be out of sync with her partner even once, `@`one line may be left out or a prop may be used the wrong way.`\

se1v 19,50

mbg white,1
mcbg 22

;「ほら、楠木さんッ。@体だけで演技しては駄目！@　心から演技しなさいッ！@　もう一度やり直し！！」\
`"Come on, Kusunoki-san~. `@`You can't just give a performance with your body! `@`You have to give it from your heart! `@`Do it over again!!"`\

;「……みどり、すごいよね。@よく、あんな長い台詞、覚えられるよ…。」@
`"......Midori is so amazing.`@` She remembers all those good lines so well..."`@
;「大変な役だよね…。@あんなのみどり姫以外には不可能だよ……。」\
`"What a tough role...`@` If anybody but Princess Midori did it, it would be impossible......"`\

;　部員たちはみどりの演技を素晴らしいと褒めるが、先生は容赦ない。@
`　Though the club members all praised Midori's performance as brilliant, the teacher was relentless.`@
br
;　無論、みどりも、その期待に応えるため、全力で稽古に臨んでいた。\
`　Of course, in order to live up to those expectations, Midori practiced with everything she had.\
;　……かつては、好きな演劇のためとは言っても、体力作りや柔軟などは苦手だった。@
`　......Before, she was not good at training or flexibility, even if she said it was for her favorite play.`@
br
;　でも、今は全然、苦にならない。\
`　But now, she isn't bothered by it at all.`\
;　あの日の、舞台での感動が、眩しく記憶に焼きついている。@
`　The deep emotion of that day on the stage was vividly burned into her memory.`@
; あの感動をもう一度得られるなら、どんな苦しい稽古にだって耐えられる。@
` In order to obtain that excitement once more, she was able to withstand any excruciating exercise.`@
 br
;　そんなみどりが流す汗は、透き通っていて輝いていた。\
` The sweat that flowed from Midori was transparent and glistening.`\
bg black,24
bg engeki_03,0
ld r,MID_Def1,24

me1v 11,90

;「…………ふぅっ……。」@
`"......Phew......"`@
br
;　一息入れて汗を拭っていると。@………部室の片隅で衣装の綻びを直す、川田のぞみの姿が目に入った。\
` She took a breath and wiped away the sweat. `@`......In the corner of the clubroom she caught sight of Nozomi Kawada fixing a tear in a costume.`\
mbg black,22

;　……彼女は今回も、何の役も得られなかった。@
`　......She wasn't able to obtain a role this time either.`@
br
;　誰もが予想した通り、今回も雑用係を押し付けられた。\
`　Just as everyone expected, she was forced into being in charge of all the odd jobs.`\

;　発声練習も柔軟体操も、何の役にも立たない。@
`　Vocal warm-ups and stretching ― she wasn't good at anything.`@
br
;　相変わらず、ひとり暗く孤立して、……時折、私に妬みの眼差しを向ける。\
` Just as always, she was darkly isolated,......and sometimes, she would glare at me with envy.`\

ld r,MID_K1,0
mcbg 22

;　……川田さん。@妬んだって、何も変わらないんだよ。@
` ......Kawada-san. `@` Being jealous won't change anything, you know.`@
br
;　そうやって、押し付けられた仕事だけを、渋々とやっている内は、何も変われない。\
`　If you do that, and reluctantly do the work pushed onto you, nothing will change.`\

;　……私だって、かつては雑用係だった。@夜の遅くまで小道具作りをさせられた。@
`......Because even I was once in charge of miscellaneous jobs. `@`I was made to work until late at night making small props.`@
br
;　でも、夢は諦めなかった。\
` But, I didn't give up my dream.`\

;　こっそり台本を読み、お姫様役の台詞を全て頭に叩き込んだ。@
` I would secretly read the script, and drove all of the princess' lines into my mind.`@
br
;　誰もいない薄暗い部室の鏡に向かって、たったひとりでずっとずっと稽古をしてきたのだ。\
` In the gloomy clubroom with nobody around, I faced the mirror and practiced for hours and hours by myself.`\

;bg white,28

bg black,22

;　だからこそ、……突然の抜擢にも応えることが出来たのだ。\
` Because of that ...I was able to live up to my chance selection for the role.`\
;　……私だって、みんなを妬んだことはある。@でも、努力をしたんだよ。@
` ......I was envious of everyone. `@`But I worked hard and gave it my all.`@
;　努力をしなきゃ、チャンスだって掴めないんだよ。@
` You have to give it your all, or you can't seize your chance.`@
br
;　私は掴んだ。@だから手放さない。@全力で、……自分とその役を、全うするからね。\
` I grasped mine. `@`That's why I won't let go. `@`With all my strength, ......I will carry out my role.`\

;bg black,28
bg engeki_03,22
;ld r,MID_Def1,22

;　のぞみが顔を上げる。@……目が合った。@
` Nozomi lifted her face. `@`......Our eyes met.`@

br
;　その目は、無気力で、相変わらず何を考えているかわからない。\
` Those eyes were empty, and like always I couldn't tell what she was thinking.`\

;ld r,MID_Def1,80

;　……でも、今日は何か違う。@
` ......But, today was different.`@

br
;　少し、ぞっとするものを感じさせた。\
` I felt something that made me shiver just a little.`\

bg black,22

fede 0,1000
E_A

me1v 16,50







;　彼女が訴えるのだ。@……彼女の、目が。@
` She was calling to me. `@`......Her eyes seemed to say.`@

br
;　………私だって、……ただ妬んでるだけじゃ、ないんだよ、……と。\
` ......'Me? ......It's not like I'm just... jealous'....`\

;　のぞみの傍らに、開いたままの『六軒島』の台本が、そのまま伏せて置かれている。@
` Next to Nozomi, the script of 'Rokkenjima', was lying upside down.`@
br
;　衣装の綻びを直す仕事に、台本が必要とは思えない。\
` I didn't think the script was needed to repair tears in costumes.`\

bgm1 6

bg engeki_03,2









;　彼女は、ただ妬んでいるわけではない。@
` She was, not only just jealous.`@
br
;　……うかがっているのだ。@……虎視、眈々と。@
`　......She was watching me. `@`......She was lying in wait.`@
;　誰もが私以外に適任はいないと言って、“諦める”魔女の役。\
` Her eyes seemed to say there were none suitable but her, that I should 'abandon' the role of the witch.`\
;　もし、……私が、発表会の直前に、……体調不良か何かで、突然、降板するようなことになったなら。@……誰にも代役を務めることは出来ない。@
` If,......just before the play, I......perhaps were to fall ill, and suddenly drop out. `@`......There wouldn't be anybody else to stand-in for the part.`@
br
;　……私が、……落ちることを見越して、……耽々と台本を読んでいる彼女を除いて……。\
`　......She is,......anticipating my downfall,......lying in wait, reading the script until I am out of her way......\`
bg black,22

me2v 17,70

mono 2
bg Different_spiral_1a,22

;　そうか……、そういうことか………。@
` I see...... So that's what it is......@`
br
;　みどりは根拠なく、理解する。\
` Without anything to base it on, Midori understood.`\

;　日ごとに増していく謎の痛み。@
`　The mysterious pain increasing daily.`@
br
;　……きっとこれは、川田のぞみの呪いか何かなのだ。\
` Surely this was, something like Nozomi Kawada's curse.`\

;bg Different_spiral_1b,22

ld r,MID_K2,22

;　私が突然のお姫様役の降板によって、大抜擢を受けたように。@……彼女も私が、突然降板することを願っているのだ。\
` If I suddenly dropped the role of the princess, she could get the main role. `@`......So she is hoping I will suddenly drop out.`\
;　楠木みどりに出来たことなら、自分に出来ないはずはないとでも言うつもりだろうか。@
` Perhaps her eyes were trying to say, 'If Midori Kusunoki did it, there shouldn't be any reason I can't do it too.'`@
br
;　……無感情な、……見ているだけで不快になる、その眼差し。@
` ......That blank expression, ......Her gaze made me uncomfortable just by looking towards her. `@
;　きっとそれが、……私に、おかしな痛みを送っているに違いないのだ……。\
` ......Without a doubt, she must be the one sending me those strange pains.......`\














bg black,22
mono 0

fede 1,2000
E_B

me5v 24,50

fedexx 0,0,0,0,0,50,2000

E_M1
E_M2

;「みどり？@　どしたの？」@
`"Midori?`@` Are you okay?"`@

bg white,1
bg engeki_03,0
ld r,MID_Def2a,22

;「………っ。」@
`"......ah."`@
br
;　友達に呼ばれ、我に返る。\
` My friend called, and I returned to myself.`\
;　……川田さんが、私に呪いを送って、それで体が痛むなんて、@……私もおかしなことを考えてしまう。@……疲れてるのかな。\
` ......To think that Kawada-san is sending me a curse and causing my body pain~ `@`......Even I am starting to think strange things. `@` ......I wonder if I'm worn out.`\
;　でも。@
` However.`@
br
;　私に、紅茶紳士さんという不思議な存在が現れて力を貸してくれたのだ。@
` I was given this power by the mysterious Black Tea Gentleman who revealed himself to me.`@
; 彼女にも、不思議な何かがあったとしても、おかしくはないのかもしれない。\
` It might not be that strange if she was something mysterious too.`\
bg black,22

;ld r,MID_Def1,80

;　……うん。@紅茶紳士さんの言う通りなんだ。@
`......Yes.`@` It's just as The Black Tea Gentleman said.`@
br
;　気にしたら負けだ。@彼女が私の代役を狙っているかどうかなんて、関係ない。@
` If I worry about it, it's over.`@` It doesn't matter if she's after my role.`@
br
;　私が完璧な魔女役で、発表会に臨むだけのこと。@全ては、私個人の問題なのだ。\
`　I am the perfect person for the role of the witch, so I'm the one dealing with the performance. `@`Everything is my own personal problem.`\

;ld r,MID_Def1,80

;　……気にしたら負けだ。@……負けて、堪るか……。@
`　......If I worry, I will mess up. @ ......Me mess up? Like hell......`@
br

;　そうとも、川田のぞみの不気味な眼差しに怯えている時間など、私にはないのだ。\
`　And with that, the time to be afraid of Nozomi Kawada's ominous gaze, was over.`\

;bg black,2

fede 0,2000
E_A














bg engeki_01,22

bgm1 8

;　発表会に向けた、猛稽古の日々が続いた。@
`　While she worked towards the performance, her days of energetic practice continued.`@`
br
;　一分たりとも無駄にできる稽古などなく、時間が経つのが本当にあっという間に感じられた。\
`　She deemed no exercise unworthy of her time, and that time passed in the blink of an eye.`\
bg black,22
bg Air_01,22

;　部活を終えて家に帰る頃にはいつも夜。@夕食もそこそこに済ませると、ベッドに倒れ込み泥の様に眠ってしまう。@それの繰り返しだった。@
`　It would always be night by the time the club ended and she went home.`@` She would finish her dinner in a hurry, splatter into bed like mud, and sleep.`@` That was how her daily cycle went.`@`
br
;　体力的には辛いけれど、……最高に充実した日々だった。\
`　It was difficult on the body, ...everyday was satisfying and productive.`\
bg black,22

;　………痛み。@……それさえなければ。@
`　...That pain.`@` ...If it weren't for that pain.`@`
br
;　あの不思議な痛みの間隔が日に日に短くなっていた。\
`　The time between days that the she would experience the mysterious pain became shorter.`\

bg "BMP\background\efe\red1.bmp",1
bg engeki_02,0
ld c,MID_K2,2

;「……みどり？@　どうしたの？」@
`"...Midori?`@` What's the matter?"`@`

ld c,MID_Def2a,80

;「…………何でもないの…。@ごめんね……。」\
`"...It's nothing...`@` Sorry..."`\

;　あまりに頻繁が過ぎると、周りに不審に思われてしまう。@
`　On the contrary, she felt suspicious that the frequency had become excessive.`@`
br
;　すでに一度、保健室沙汰になっているのだ。@……騒がれたら、降板させられてしまうかもしれない。\
`　She had already been to the infirmary about the matter once.`@` ...If she were to panic, she might have to drop her role.`\

bg black,23
bg rouka_02,23

me1v 16,50

;　お手洗いに行って来るからと誤魔化し、ひとりになる。\
`　By pretending that she had to go to the bathroom, she was alone again.`\

;　さっきの激痛も、……いつもと同じ。@
`　That intense pain...was the same as always.`@`
br
;　相変わらず傷らしい傷はどこにもない。\
`　Just as always, though it seemed like there would be a visible cause, there wasn't a scratch on her.`\


;　……もう、嫌になる。@
`　...I've had enough.`@`
br
;　一度は振り払った考えだけれど、……やはりこれは、川田のぞみの呪いなのだろうか。\
`　I shook off the thought once, but... Just as I thought, maybe this is Nozomi Kawada's curse.`\

;　だって、痛みはいつも、学校にいる時に限られる。@
`　Because the pain is always restricted to when I'm at school.`@`
;　さらに言えば、川田のぞみが近くにいる時に感じることが、多い気もする。@
`　Furthermore, I've also considered that the times I've felt it while I'm near Nozomi Kawada have increased.`@`
br
;　この痛みの時も、振り返ったら彼女の眼差しがあったから。\
`　Also when I have this pain, if I turn around, her gaze will be on me.`\

bg black,22
mono 2
bg Different_spiral_1a,22

me2v 17,50

;　……やっぱり。@
`　...Just like I thought.`@`
br
;　負けて堪るものか、……堪るものか……。\
`　You think I'll give up and lose... Like I'll let that happen...`\

;　私は絶対に発表会に出る。@降板など絶対にしない。@
`　I will definitely be in that play.`@` There's no way I'll step down.`@`
br
;　一度掴んだチャンスは、絶対に手放さない。\
`　I will never let go of my once-in-a-lifetime chance.`\

;bg Different_spiral_1b,22

bg black,22
mono 0

;　……悪いけれど、……川田さんに、絶対に譲るものか………。@
`　...Sorry, but...there's no way I'll ever hand this over to you, Kawada-san...`@`
br
;　発表会までもう何日もない。\
`　There's not many days until the performance.`\

;bg black,22
;bg rouka_02,0
ld r,SIN_Def4,22

;「気にしないことです。@そのようなことに、心を割く余裕など貴方にはないではありませんか。」@
`"It's not something to worry about.`@` You don't really have the time to let it tear you apart, do you?"`@
br
;　紅茶紳士さんは繰り返す。@気にしないことですと。\
`　The Black Tea Gentleman kept repeating that.`@` It's not something to worry about.`\

bg black,22

;　……気にしない、気にしない。@
`　...Don't worry, don't worry.`@`
br
;　おかしな痛みなどに……、負けるものか………。\
`　There's no way I'll give up...over this bizarre pain...`\

fede 1,1000
E_B

;　しかし。@
`　But.`@`
br
;　私を蝕む謎の呪いは、……“痛み”だけではなかった。\
`　The riddle of my curse that's eating away at me...is not just limited to 'pain'.`\

fede 0,2000
E_A












bg kyou_01,22

me1v 24,50

;　それはある日の給食の時間だった。\
`　It was one day during lunch time.`\


;　給食係によそってもらったカレーを持って席に戻ると、@サキエやフミエら、他の取り巻きたちが一斉に集まってくる。@
`　Once I'd received my curry from the lunch lady and returned to my seat,`@` Sakie, Fumie, and all the other people I surround myself with simultaneously gathered.`@`
br
;　囲まれながらの楽しい昼食。@……いつもの光景だった。\
`　An enjoyable lunch surrounded by friends.`@` ...It was a familiar scene.`\


;「姫、大丈夫？@　最近、顔色良くないみたいだけど……。」@
`"Princess, are you okay? You've been looking pretty pale lately..."`@`

ld r,MID_Def2,22

;「そ、そう…？@　気のせいよ。@気にしないでね。」\
`"R, really...?`@` It's just your imagination.`@` Don't worry about it."`\

;「稽古、ほとんど毎日なんでしょ？@　無理しないでね。」@
`"You've been practicing almost every day, haven't you?`@` Try not to push yourself, all right?"`@`
;「だけど、みどりが主役の舞台が見れるなんてすっごい楽しみ。@今週末だよね？@　頑張ってね、みどり！」\
`"But, I just can't wait to see Midori on the stage as the lead.`@` It's this weekend, right?`@` Good luck, Midori!"`\

ld r,MID_K1,22

;　痛みの呪いは、やはり私を疲弊させているようだった。@
`　It seemed that the curse of my pain was wearing me out.`@`
br
;　素振りを見せているつもりはないのだが、@いつも身近にいるサキエたちにはわかるようだった。\
`　I hadn't intended it to show through my mannerisms,`@` but it seemed that Sakie and the others who were always around me could tell.`\

;　……お姫様が病気、なんてことになったらきっと、みんな大仰に大騒ぎする。@
`　...If their princess had fallen ill, everyone would cause an uproar.`@`

br
;　そうしたら演劇部にも話が届いて、………先生や部長の耳にも入って……。\
`　If that happened, word would reach the drama club,...and the teacher and club leader would hear about it...`\

bg black,22

;　………冗談じゃない。@
`　...It's no laughing matter.`@`

br
;　絶対に降りない。@……発表会で、舞台の中央でスポットライトを浴びるのは私なんだから。@
`　I won't ever step down.`@` ...I'm the one who will stand in the middle of the stage, bathing in the spotlight during this play.`@
br
;　こんな呪いに、………川田のぞみに、………負けるものか……。\
`　I will never lose...to a curse...or to Nozomi Kawada...`\


bg kyou_01,22

;「ねーねー、昨日の『シーキャット』のアニメ見たぁ？」@
`"Hey, hey, did you watch yesterday's 'Sea Cats' anime?"`@`
;「見た見た！@　欠かさず見てるよ～！@　声が素敵だよねっ、斧さん最高～！」@
`"I did, I did!`@` I didn't miss a thing~!`@` The voices were so good, weren't they? Ono-san is just the best~!"`@`
;「ってゆうか、声優みんなすごいよね！」@
`"Speaking of which, all of the voice actors were incredible, huh!"`@`
;「ねぇねぇ、みどりは誰が好き？！」\
`"Hey, Midori, who do you like?!"`\
ld r,MID_Def2a,22
;ld r,MID_Def1,80

;「……え？@　………あ、……うん。@私、帰るの遅いから、ほとんど見てないの。」@
`"...Huh?`@` ...Oh, ...yeah.`@` Since I don't get home until late, I didn't get to see most of it."`@
br
;　毎日、遅くまで稽古なので、帰る頃にはとっくに放送が終わっているのだ。\
`　Because I practice so late every day, by the time I go home the broadcast is already long over.`\

;　好きな作品だけれど、今はまったく興味ない。@……発表会に、集中しなきゃ。@
`　I like the show, but I'm not interested in it at all right now. `@`...I have to concentrate on the performance.`@
br
;　サキエたちは、私が連日の稽古で疲れているのだろうと察し、自分たちだけで勝手に盛り上がってくれた。\
`　Showing that they understood my exhaustion from my daily practice, Sakie and the rest left me alone and kept their excitement among themselves.`\

;　私はそれをぼんやりと聞きながら、作業の様に給食を口に運んだ。@
`　As I absent-mindedly listened, I mechanically transported some school lunch to my lips.`@
br
;　安っぽいカレーの味が口の中に広がる。\
`　The taste of cheap curry filled the inside of my mouth.`\

ld r,MID_K1,22

;　食欲は全然なく、一口食べるのにもかなりの時間がかかった。@
`　I had no appetite for food, and even eating a mouthful took a long time.`@
br
;　でも、無理矢理でも食べなければならない。\
`　But I had to eat, even if it was against my own free will.`\

;　今週に入ってからは毎日のように本番用の衣装を着けて通し稽古をしている。@食べなければ身体が持たないのだ。\
`　Starting this week, we would wear the clothes for our parts every day while practicing. `@`If I don't eat, then my body won't be able to handle it.`\










E_A

mbg "BMP\background\efe\red1.bmp",1
quakex 1,100
mcbg 22
ld r,MID_K2,80

bgm1 11

;　その時、……またあの、呪いの痛み。@
`　At that moment, ...it was that pain again.`@
br
;　今度は後頭部だった。@誰かに激しく叩かれたかのような痛み。\
`　This time it was the back of her head. `@`It hurt like someone just struck her violently.`\

;　どうせ振り返っても誰もいないので、もはや私は振り返りさえしない。@
`　Even if she turned around no one would be there, so she didn't even turn around to check.`@
br
;　代わりに、川田のぞみの背中を憎々しげに睨むのだ。\
`　Rather, she glared at Kawada Nozomi's back.`\


mbg black,22

;　……悔しい。@
`　...How frustrating.`@
br
;　何の証拠もない。@でも、絶対に川田さんのせいだって、わかってる。\
`　I have no evidence. `@`However, it has to be Kawada-san's fault. I know it.`\

;　でも、気にしたら負けだ。@
`　But if I let it get to me, I'll lose it.`@
br
;　こんな呪いで、私を妨害することが彼女には関の山なのだ。\
`　For her, using this kind of curse to disturb me is the best she can do.`\

ld r,MID_K3,0
mcbg 22

;　あんたなんかに、私の役は譲らない。@……負けるものか、絶対、絶対。@
`　I won't give my role up to someone like you. `@`...I'll never give up, never.`@
br
;　下唇を噛み締めながら、……目を給食に戻す。\
`　As she was biting her lower lip, ...she turned her gaze back to her lunch.`\

mbg white,0
print 99,2000,"trvswave.dll/l"
print 1

me1v 17,50

;　すると。@……ゆらりと、……給食のカレーが、歪んだ気がした。@
`　When she did. `@`...The curry lunch began to sway ...and blur.`@
br
;　湯気とか、そういう感じじゃない。@……疲れ目？@　……そんな感じだった。\
`　It didn't seem to be steam or anything like that. `@`...Tired eyes perhaps? `@`...It felt like that.`\

cl r,0
mcbg 22

;　私は霞んだ目を擦り、違和感を感じるそれを凝視する。@
`　I rubbed my hazy eyes, and I stared at something that made me feel uncomfortable.`@
br
;　……たった今、自分が食べている、給食のカレー。@
`　...Just now I was eating the school's curry lunch.`@
;　そこに、……ゆらりと、………黒い物が混じるのだ。\
`　But now... swirling... it had these black things mixed in.`\

;ld r,MID_Def1,80

bg black,22

fede 0,1000
E_A

;　中から浮いてきた？@　……そんなはずない。@
`　Did it float from the bottom? `@`...There's no way.`@
br
;　でも……、……そのカレーには、……無数の、……/
`　But..., in that curry, ...were countless...`/
se1 34
;虫の死骸があった……。\
`dead insects...`\

bg aka2,1
quakey 3,200

;「ッ？！@/
`"?!`@/
bgm1 12
;　……………………ッ！！！」@
`　..........!!!"`@
br
;　あまりの驚愕に、窒息しそうになる。@
`　The sudden shock nearly made her choke.`@
br
;　カレーの上には、……紛れもなく、それらがぶちまけられていた。\
`　On top of the curry, ...without a doubt, those things were scattered about.`\

;　私が川田さんを睨んでいる間に誰かが悪戯したとか、カレーの下から浮いてきたとか、@そんなことは断じてありえない。@
`　It was impossible for someone to pull a prank while I was staring at Kawada-san, `@`and there was no way these things just floated up from the bottom of my curry. `@`There's just no way!`@
br
;　私の目の前で。@それはゆらりと、現れたのだ……。\
`　Before my very eyes,`@` they warped into existence...`\

me1v 28,90

;　てらてらと黒光りする虫の背中。@節の様な足、髪の毛の様な触覚。@
`　The glistening backs of their lustrous black husks.`@` Knotted legs. Hair-like feelers.`@
br
;　それらが茶色いカレーのルーと白いライスに混じっている壮絶な光景。\
`　They were mixed with the brown curry sauce and the white rice in a gruesome display.`\

;　私の手はスプーンを握り、そこにずっと突き立てたままだった。@
`　Gripping my spoon, I had been drawing from the bowl for some time.`@
br
;　さっきまでそれは、カレーの中に突き立てられていたのだ。@
`　Just moments ago, I had been driving my utensils into curry.`@
br
;　しかし今は、カレーだけじゃない。\
`　But now, there wasn't just curry on them.`\

me2v 3,90

;　……先割れスプーンは、……深々と、……黒い昆虫に、……突き刺さっていて。@
`　...My fork and spoon were now thickly encrusted... and stuck with ...black bugs.`@
br
;　そこから、何色とも形容し難い、体液と内臓を溢れ出させているのだ……。\
`　And there were a variety of indescribable colors composing the bodily fluids and guts that flowed out from them...`\

;bg black,22
bg kyou_03,1
quakey 3,300

me3v 16,90

;　私は食べていた物を全て吐き出しそうになり、慌てて口を押さえる。@
`　I was about to throw up everything I had eaten, and I frantically covered my mouth.`@
br
;　目の前にあるそれのせいだけで、嘔吐を覚えたわけじゃない。\
`　It wasn't just because of what I was seeing in front of me that caused my queasiness.`\

;　……さっきまで食べていた物の中にも、……それが混じっていたのではないかと感じて、@……ぅ、……うぅううぅぅ……。\
`　...Inside what I had ate just now ...I sensed they had mixed in there as well, `@`...uhh ..UuUUuu...`\

bg black,22

;「ちょっと、大丈夫？！」@
`"Hey, are you alright?!"`@
;「どうしたの、みどり？！@　気分悪いの？！」@
`"What's wrong, Midori?! `@`Are you sick?!"`
br
;　みどりの様子にサキエたちが気付き、不安そうに声を掛ける。\
`　Sakie and the others noticed Midori's behavior, and they uneasily called out to her.`\

;　……やっぱり。@彼女らには、このカレーの異常が見えていない。@
`　...I knew it. `@`Those girls don't see what's wrong with this curry.`@
br
;　痛みと同じ。@……私だけに感じられる、“呪い”なのだ。\
`　It's the same as the pain. `@`...It's a 'curse' that only I can sense.`\


bg kyou_01,22
ld l,SIN_Def1,22

;「どうなさいましたか？」@
`"What's the matter?"`@

ld r,MID_K2,22

;「……紅茶紳士さんにはこれ、……見えていますか。」\
`"...Black Tea Gentleman, ...are you seeing this?"`\

ld l,SIN_Def2,80

;「…………………。@私から貴方に申し上げることはただ一つ。」@
`"......... `@`I have only one thing to tell you."`@

ld r,MID_Def4a,80

;「気にしないことです…？」\
`"Don't worry about it...?"`\

ld l,SIN_Def4,80

;「っくっくっくっく。@その通りです。」@
"Kukukuku. `@`Exactly."`@
br
;　紅茶紳士さんは他人事のようにくすくすと笑う。\
`　The Black Tea Gentleman snickers as if it were someone else's problem.`\

;　……見えている。@
`　...He sees it.`@
;　彼にも、このカレーの惨状が見えているのだ。@
`　He's also seeing this terrifying curry.`@
br
;　その時、……私の頭の中で、……嫌なピースが合わさり、一つの想像を形作る。\
`　At that moment ...in my mind ...the puzzle pieces came together, and a detestable idea took shape in my mind.`\

ld r,MID_K5,80

;「……紅茶紳士さん、ですね……。」@
`"...You're the Black Tea Gentleman... right?"`@

ld l,SIN_Def1,80

;「おや。@何の話ですかな？」\
`"Oh my.`@` Whatever are you talking about?"`\

bg black,22
bg kyou_02,22

;ld r,MID_Def1,80

;「………惚けないで下さい。@……あのおかしな痛みも、このカレーも。@……紅茶紳士さんの力じゃないんですか。」@
`"...Please don't act like a fool. `@`...That strange pain, this curry `@`― isn't this all your doing?"`@

;ld l,SIN_Def1,80

;「これはこれは。@心外ですねぇ。@どうして私がそのような真似をするのですか…？@　私は貴方の味方ではありませんか。」\
`"My oh my. `@`How unfortunate~ `@`Why do you think I'd do things like that...? `@`Am I not on your side?"`\

;ld r,MID_Def1,80

mbg black,22

;「…………確かに、私の味方だと思います。@……でも、ひょっとして。@……他にも味方している子が、……いるんじゃありませんか？」@
`"...Sure, I do think you're on my side. `@`...But, for some reason. `@`...Is there another girl ...who is on your side?"`@

;ld l,SIN_Def1,80

;「おや。@それはどういう意味ですかな…？」\
`"Oh my. `@`What do you mean by that I wonder...?"`\

mcbg 22

ld c,MID_K5,22

;「演劇部で。@……私に出会い、力を貸してくれたように。@………川田さんにも出会って。@……何かの力を貸したんじゃないですか。」\
`"In the drama club. `@`...Just as you offered your power to me when we met. `@`...You met with Kawada-san. `@`...You lent her some kind of power didn't you?"`\

ld r,SIN_Def4,22

;「なるほど。@……川田さんが主役の座に就けるよう、貴方を降板させようと私が企んでいると。@なるほどなるほど……、っくっくっく。」@
`"I see. `@`...In order to get the lead role, Kawada-san entrusts me with causing you to resign. `@`I see, I see... Kukuku."`@
br
;　紅茶紳士さんは意味深に笑う。\
`　The Black Tea Gentleman smiles widely.`\

cl c,0
ld l,MID_K5,24

;　……今まで、彼を恩人と思ってきたけれど。@彼は正体不明の、人ならざる者なのだ。@
`　...Until now, although I had thought of him as my benefactor, `@`he was an incomprehensible supernatural being.`@
br
;　私に気紛れに力を貸してくれただけで、……味方のつもりなんて、初めからないのだ。\
`　He had given his power to me on a whim, ...and he was never on my side from the very beginning.`\

ld r,SIN_Def1,80

;「みどりさん。@それはとても心外な想像です。」@
`"Midori-san. `@`That is a very upsetting thought."`@

ld l,MID_U1,80

;「……だって、そうじゃなきゃ説明がつかないッ！」\
`"...But, if that's not it then what is it!!"`\

ld r,SIN_Def3,80

;「みどりさん。@……私は貴方の味方です。@だからこそ、こうしていつも、貴方の側にいるのではありませんか。」\
`"Midori-san. `@`...I am your ally. `@`Therefore, I'll always be here with you like this."`\

ld l,MID_K3,80

;「…………川田さんの呪いのために、……私に取り憑いてるのかもしれないです。」\
`"...You might just be clinging to me ...for the sake of Kawada-san's curse."`\

ld r,SIN_Def2,80

;「………………………。@私は、貴方の味方です。@そして、貴方が耳を貸さないとしても、同じことを言いましょう。」@
`".........`@ `I am your ally. `@`And even if you won't lend me your ears to hear it, I'll say the same thing."`@

ld l,MID_K5,80

;「“気にしないことです”？」\
`"`Don't worry about it`?"`\

bg black,22

;ld l,SIN_Def1,80

;「その通りです。@そして、それ以上の何も申し上げるつもりはありません。」@
`"Indeed. `@`Aside from that, I have no intents of telling you anything otherwise."`@

;ld r,MID_Def1,80

;「……おかしなことが起こっても、何も気にせず、発表会へのお稽古に励めと…？@　……こんなおかしなことが繰り返し起こるんじゃ、集中なんて出来ない！！」\
`"...Even if strange things happen, you're saying I should dedicate myself to practice without giving it a thought...?`@` ...If weird things like this keep happening, there's no way I can concentrate!!"`\

ld c,SIN_Def2,22

;「ならばお稽古を止め、主役を川田さんに譲るのですか？」@
`"Then you'll stop practicing and give the lead role to Kawada-san?"`@

;ld r,MID_Def1,80

;「そ、そんなことはさせない…！@　主役は私…！@　私が掴んだ役！@　絶対に私が演じてみせる…！」\
`"I, I won't let that happen...! `@`I am the lead...! `@`The role is mine! `@`I will be the one...!"`\

bg Aka1,0
ld c,SIN_Def2,22

ld c,SIN_Def4,80

;「っくっくくくくく……。@……良いことを仰います。@その通りです。@主役は貴方。@誰にも譲ってはなりません。」@
`"Ku Kukukukuku... `@`...Well said. `@`Exactly. `@`You are the lead. `@`It will go to no one else."`@

;ld r,MID_Def1,80

;「あなたが、……何を考えているのか、私にはわからない…！」\
`"Just what are you thinking? ...I can't tell...!"`\

bg black,22

fede 0,2000
E_A










;bg black,26

se1v 13,50

bg kyou_03,1
quakey 2,200

;　みどりは勢い良く立ち上がる。@
`　Midori flew up from her seat.`@

me1v 24,50

br
;　その荒々しさにみんなが驚くが、みどりは何も気にしない。\
`　Her wildness startled everyone, but Midori didn't care.`\

;　食べ掛けの給食を乱暴に持つと、残飯入れの中に食器ごと突っ込む。@
`　Recklessly taking up her school lunch tray, she threw it in the garbage, silverware and all.`@
br
;　そしてそのまま、教室を飛び出していった。\
`　And with that, she flew out of the classroom.`\

bg black,22

fede 0,1000
E_A

bg kyou_01,0
ld c,SIN_Def2,22

bgm1 13

;「……っくっくくくくくくくく。@……やれやれ。@若々しいですねぇ。」@
`"...Ku Ku kukukukukuku. `@`...Dear oh dear. `@`So very young."`@
br
;　紅茶紳士は肩を竦めて笑う。\
`　The Black Tea Gentleman shrugged his shoulders and laughed.`\

se1v 22,50

mbg white,9
mcbg 22

;　……彼の目には、不思議なものが見えていた。@
`　...Something strange caught his eye.`@
br
;　荒々しく席を立ち、教室から出て行ったみどりは、@全身からうっすらと、湯気かお線香の煙のようなものを棚引かせていた。\
`　Midori, who roughly flew out her chair and out the classroom, `@`steam or smoke and trailed out from her body and hung in the air like steam or incense.`\
;　それは人ならざる者の目にしか見えない。@
`　That was something only a supernatural being could see.`@
br
;　紅茶紳士は空のティーカップをふわりと持つと、@……その煙のようなものが、すぅっと集まり、カップに満たされていく。\
`　The Black Tea Gentleman gently held his teacup in the air, `@`...and that smoke-like entity slowly gathered and began to fill his cup.`\

;　そしてそれは渦を巻きながら茶色く透き通り、@……彼好みの、鮮烈な香りを放つ、良い紅茶となった。@
`　And as that swirl wound itself, it turned brown. `@`...It became a delicious black tea with a pleasant fragrance.`@
br
;　一口すすり、にんまりと笑う………。\
`　He took a sip and smiled peacefully...`\

ld c,SIN_Def4,80

;「……実に初々しい味わいです。@……みどりさん。@貴方の魂は、……実に良い香りの紅茶になりますよ。@っくっくくくくくくくく………！」\
`"...It truly tastes of innocence. `@`...Midori-san. `@`Your soul ...will truly make a delightfully fragrant tea. `@`Ku Kukukukukukuku...!"`\

bg black,2

fede 0,2000
E_A

wait 2000










bg rouka_02,22

me1v 16,50

;　みどりは小走りで部室に向かった。@
`　Midori ran towards the clubroom.`@
br
;　まだ昼休みではあるけれど。@
`　It was still lunch break.`@
;　稽古がしたかった。@演劇がしたかった。@誰か他の人間を演じたかった。\
`　She wanted to practice. `@`She wanted the theater. `@`She wanted to be someone else.`\

se1 82

bg white,63
bg engeki_01,22
;quakex 1,100

;　部室へ飛び込む。@
`　She flew into the clubroom.`@
br
;　教室の並びから離れているため、昼休みの喧騒が遠くて、それだけでも心地良かった。\
`　She was separated from the line and file of the classroom. The hustle and bustle of lunch break was far away, and that made her feel a bit better.`\

;　みどりは部室の奥にある衣装置き場にまっすぐ向かう。@
`　Midori headed straight for the costume storeroom in the clubroom.`@
br
;　そして主役の衣装である、ドレスを手に取り、@まだ昼休みであるにも関わらず、着替え始める……。\
`　Then she took the dress of the lead role in her arms. `@`Regardless of the fact that it was still lunch break, she began changing her clothes...`\

bg black,24
bg engeki_04,0
ld c,MID_Def2a,24

;「………私が主役、……私が主役……。@……誰にも譲らない、……誰にも譲らないッ……。」@
`"...I am the lead actress... I am the lead actress... `@`...I won't let anyone else, ...I won't let anyone elssse..."`@
br
;　お気に入りのワンピースを脱ぐ。\
`　She took off her favorite dress.`\

;bg white,28

bg black,1

;　その時、……鏡に映る自分の姿を見て、……みどりは息を呑んだ。\
`　Just then, ...looking at herself reflected in the mirror, ...Midori's heart stopped.`\

E_A






se1 24

bg aka2,1
quake 3,300

;「な、………何よ、………これ………。」@
`"Wh, ...what is,...this..."`@`
br
;　露になった二の腕に、シミの様なものがついていた。@鮮やかな色の何かが。\
`　On both her exposed arms, something that looked like a moth was stuck.`@` A vivid something.`\
;　絵の具だろうか……？@　そう思って顔を近づける。\
`　Was it paint...?`@` Thinking that, she drew her face nearer.`\


bgm1 16

;「……………何よ、……これ……。」\
`"...What the hell,...is this..."`\

;　痣だった。@
`　It was a bruise.`@`
br
;　一つや二つではない。@
`　Not just one or two.`@`
;　赤、青、紫…………………鮮やかな痣が腕一面に浮かんでいた。@
`　Red, blue, purple, ...vibrant bruises were stuck all over her arms.`@`
br
;　腕がガタガタと震えだした。\
`　Her arms began to shake.`\
me1v 17,70

;「……なんなのよ、これ。」@
`"...What is this."`@`
br
;　服に覆われて隠れていた部分に、……背中にも、お腹にも。@いくつもの、いくつもの痣が。@内出血の痕が。\
`　The parts that were hidden by her clothes, ...on her back, on her stomach.`@` Countless, countless bruises.`@` Traces of internal bleeding.`\
;bg black,22
bg engeki_04,0
ld c,MID_U1,22

me2v 3,70

;「何よ、………これ………、…………これ……ッ…！！！」@
`"What...what is this...this...!!!"`@`
br
;　静寂の部室に、……みどりの悲鳴が木霊した……。\
`　In the silent room... Midori's screams resounded.`\

bg black,22
bg engeki_01,22

;　部室の片隅に浮かぶティーカップが、くいっと傾く。@
`　A teacup floating in the corner of the clubroom tipped with a slurp.`@`
br
;　衝撃を受けて放心しているみどりには、紅茶紳士の姿は見えていないようだった。\
`　Due to the shock on her peace of mind, it seemed like Midori couldn't see The Black Tea Gentleman's form.`\

ld l,SIN_Def1,2
ld l,SIN_Def4,22

;「気にしないことですよ、みどりさん。@………もっとも、それを口にしたところで、もう耳には届かないようですがねぇ。@……っくっくっくっくっくっく！」\
`"It's nothing to worry about, Midori-san.`@`...But then again, even if you were to speak of it, it seems it wouldn't reach anyone's ears.`@` ...Kukukukuku!"`\

;ld r,MAR_Def1,42

mbg black,22

E_A

;「……その子を、そっとしてあげて下さい。」\
`"...Leave that girl alone."`\

mcbg 22
ld l,SIN_Def1,80

me1v 17,50

;「………おや。」@
`"...Oh my."`@`

br
;　紅茶紳士の前に、……毬枝が、ゆっくりと姿を現す。@
`　In front of The Black Tea Gentleman, ...Marie slowly showed herself.`@`
;　鋭い目線で、紅茶紳士を睨んでいた。\
`　She glared at The Black Tea Gentleman with a perceptive gaze.`\

ld l,SIN_Def4,80

;「学校妖怪、序列第８位の。@……めそめその毬枝さんではありませんか。」\
`"If it isn't our 8th Ranking School Youkai.`@` ...Mesomeso Marie."`\

E_A

bgm1 15

ld r,MAR_i4,2
ld r,MAR_i3,22

;「……妖怪ですね。@あなたも。」@
`"...A youkai.`@` You're one too."`@`

ld l,SIN_Def2,80

;「えぇ。@ご同業ですよ。@……ニンゲンから魂のささやかなカケラをお譲りいただき、糊口を凌ぐささやかな存在です。」\
`"Indeed.`@` We are in the same trade.`@`...I am a being who survives, by receiving a modest portion of a human's soul."`\

ld r,MAR_i1,80

;「楠木みどりさんは、がんばり屋さんで、とても心の綺麗な女の子です。@……今も、発表会に向けて一生懸命、努力しています。」@
`"Midori Kusunoki is a hard worker, a girl with a beautiful heart.`@` ...Even now, she is endeavoring with all her might for the play.`@

ld l,SIN_Def3,80

;「えぇ。@それは誰よりもよく承知しておりますよ……。」\
`"Yes.`@` I acknowledge that more than anyone..."`\

bg black,22

;ld l,MAR_Def1,80

;「そんな彼女をいじめて、……楽しいですか。」@
`"Is it fun, ...to bully that girl?"`@`

;ld r,SIN_Def1,80

;「それは誤解ですねぇ。@どうして私がみどりさんをいじめるのでしょうか。」\
`"Now that's a misunderstanding.`@` How am I bullying Midori-san?"`\

bg engeki_03,22
ld l,MAR_i3a,22

;「……彼女の魂を、あなたは食べています。@……これは、あなたの狩りです。」@
`"...You're consuming her soul.`@`...That's what you're hunting."`@`

ld r,SIN_Def2,22

;「ささやかなものでしょう？@　強欲な学校妖怪たちと違い、私は命を奪うようなことは好みませんので。」\
`"It's only a little bit, right?`@` Unlike the greedy school youkai, it is not to my liking to steal one's life."`\ 

ld l,MAR_i4,80

;「………はい。@だから、もうこれで。@……彼女を見逃してあげて下さい。」@
`"...Yes.`@` So let's leave it at this.`@` ...Please leave her alone."`@`

ld r,SIN_Def3,80

;「見逃す、とは……？」\
`"Leave her alone...?"`\

bg black,23
bg engeki_01,0
ld c,MID_K2,23

wait 1000

;ld l,MAR_Def1,80

;「彼女をずっと見てきました。@……おかしな呪いは日増しに酷くなり、彼女を追い詰めています。@……彼女は発表会で最高の演技をしたいだけ。@あなたの呪いが、それを妨げようとしています。」\
`"I have been watching her this whole time.`@`...This bizarre curse has been getting worse day by day and has driven her into a corner.`@` ...All she wants is to give the greatest performance at the play.`@` Your curse is preventing that."`\

;ld r,SIN_Def1,80

;「痛みとやらが気になるのは。@彼女の集中力が足らないからに他なりません。@……彼女が演技について本当に集中してくれたなら、気になるようなものではないのですが。」\
`"The reason she worries about pain and the like,`@` is due to none other than her lack of concentration.`@`...If she were truly concentrating on her performance, there would be nothing else on her mind."`\

mld r,MAR_i3,22

;「………もう一度言います。@みどりさんを、見逃してあげて下さい。」@
`"...I'll say it one more time.`@` Please let Midori-san go."`@`

mld l,SIN_Def3,22

;「出来ませんね。@彼女は、私の獲物です。」\
`"I can't do that.`@` She is my prey."`\

;bg black,24
;bg engeki_02,0
mld r,MAR_i2a,80

;「………なら。@……学校妖怪のルールに、従わせてもらいます。」@
`"Then,`@` ...I'll ask that you abide by the school youkai's rules."`@`

mld l,SIN_Def2,80

;「ルール？@　はて。@如何なる束縛も嫌う私たちが、何のルールを？」\
`"Rules?`@` Well then.`@` For ones who despise any kind of shackles like us, what rules?"`\

mld r,MAR_i3a,80

;「誰を獲物とするも自由。@……そして、誰の獲物を奪うも、自由。」\
`"We can make anyone our prey.`@`...And we can take anyone's prey."`\

mld l,SIN_Def4,80

;「くっくくく。@っくっくくくくくくくくくくく！@　なるほどッ、確かに妖怪が従う、唯一のルールですねぇ。」@
`"Kukukuku.`@` KU KUKUKUKUKU!`@` I seeeee, youkai certainly do follow that one rule, don't we?"`@`
br
;　紅茶紳士は、一本取られたとでも言うように肩を揺すって笑う。\
`　As if to say, 'You've got me there', The Black Tea Gentleman's shoulders shook with laughter.`\

mcl a,0
bg black,23
bg engeki_02,23
ld c,MAR_i4a,22

;「妖怪にも、生きるために魂を食らわねばならない都合があることはわかっています。@……だから、ここで引き下がってくれれば、私も事を荒立てません。」@
`"I understand that youkai are under the circumstances where we must consume souls to live.`@` ...Therefore, if you depart now, I will not exacerbate this."`@`
br
;　毬枝は強い意思の宿る眼差しで、紅茶紳士を射抜く。\
`　Marie's strong will shot through The Black Tea Gentleman, just with her gaze.`\

ld l,SIN_Def2,22

;「これは困りました。@学校妖怪八席のめそめそさんに凄まれては。@序列を持たぬ弱小妖怪の私など、塵にされてしまいますねぇ。」\
`"This is a problem.`@` Being threatened by Mesomeso-san of the 8th Seat of School Youkai.`@` A puny youkai with no ranking like myself will surely be no match for you."`\

ld c,MAR_i3,80

;「私だってしたくないし。@あなただって、されたくないはずです。」\
`"I don't want to do this.`@` And I'm sure you don't want this to be done to you."`\

ld l,SIN_Def3,80

;「……しかし、みどりさんという素晴らしき茶葉をここで譲るには余りに惜しい。」@
`"...However, I think giving up Midori-san right here would be truly regrettable, considering she would make such brilliant tea leaves."`@`

cl c,0
ld r,MAR_i4,23

;「………………わかってます。@妖怪同士が、話し合いで決着するわけもないと。」\
`"...I know.`@` As a fellow youkai, I don't intend to settle this through talking."`\

ld l,SIN_Def4,80

;「………………………たくましい。@元いじめられっことは思えませんね。」\
`"...How strong.`@` I would never have thought you were a bullied child once."`\

ld r,MAR_i2,80

;「元いじめられっこだからこそ。@………私には人の心が、誰よりもわかるんです。@……あなたはがんばり屋の少女を蝕んでいる。@……そんな努力を蔑ろにしようとするあなたを、私は見過ごすわけには行きません。」\
`"It is because I was once bullied.`@` ...I understand people's hearts, more than anybody else.`@` ...You are consuming that hard-working girl.`@` ...I have no intentions of letting you, the man who toys with her struggles, get away with it."`\

cl l,0
mld l,SIN_Def1,80

;「めそめそさんは、扉を挟んでこそ、真価を発揮する妖怪と聞きましたが…？」@
`"I've heard Mesomeso-san is a youkai who demonstrates her true worth from behind a door?"`@`

ld r,MAR_i3a,80

;「……仮にも学校妖怪八席。@……あなたを、……この腕で、……駆逐しますッ。」\
`"...Right now I am in the 8th Ranked Seat of School Youkai.`@` ...I will destroy you... with my bare hands~!"`\

se1v 22,50
bg white,8

;　いつの間にか、紅茶紳士のティーカップの湯気が、部室中に充満していた。@
`　At some point, the steam from The Black Tea Gentleman's cup, had filled the entire club room.`@`
br
;　それは霧のようというより、@……まるでティーカップから、霧の腕が何本も生え出したかのよう。\
`　Rather than a mist,`@` ...it was as if from the teacup, countless arms of fog had sprung up.`\
se2v 22,50

mcl l,0
mbg white,0
print 99,2000,"trvswave.dll/l"
print 1

;mbg "BMP\background\efe\red1.bmp",1
;quakex 1,100
;mcbg 22
;;bg black,22
;bg aka2,1
;quakey 1,100
;bg aka3,1
;quakex 1,100


;　それらが揺らめき、……爬虫類のように毬枝を睨みつけ、…………襲う。@
`　They were swaying,... glaring at Marie like reptiles,...they attacked.`@`
br
;　何本もの霧の腕が毬枝に飛び掛る。@ぐるぐる巻きにして締め上げる。\
`　Those countless arms of mist leapt at Marie.`@` They coiled around her and constricted her.`\

mcbg 0

se1v 20,50
bg black,23

se2v 20,60
bg white,24

se3v 20,70
bg black,23

se1v 20,90
bg white,24

se2v 55,70
quakex 3,300

quakey 3,200


ld l,SIN_Def1,22

;「……………………………。」@
`"..."`@`
br
;　紅茶紳士は、ふっと笑う。\
　The Black Tea Gentleman laughed with a huff.

;　あっさりと決着がついたから？@　違う。@
`　Was it because he settled things so quickly?`@` No.`@`　
br
;　わかっているのだ。@仮にも、学校妖怪八席。@……この程度で、仕留められるわけもない。\
`　He realized it.`@` Even if she was temporarily in that rank, he was up against The Eighth Ranked School Youkai.`@`...There was no way he could take her down using attacks like that.`\


mbg "BMP\background\efe\red1.bmp",1
mcbg 22

;　毬枝をぐるぐる巻きにしている霧の腕が、……ぶるぶると震える。@
`　The arms of mist that were constricting Marie all around, ...were shuddering.`@`
br
;　そして、……内側から引き剥がすかのように、……一本一本、……千切られていく。\
`　And, ...As though tearing them apart from within, ...One by one...She tore them to shreds.`\
ld l,SIN_Def3,80

;「……めそめそさんは豪腕怪力の妖怪だそうですね。@……なるほど、恐ろしい力です。」@
`"...Mesomeso-san appears to be a youkai with superhuman strength.`@` ...I see, what a dreadful power."`@`
br
;　繭を内側から破るように。@……激しい音がして、霧の腕が霧散する。\
`　With a violent sound like tearing apart a cocoon from within,`@` ...the arms of mist were dispatched.`\
se1v 55,70

bg white,28

se2v 12,50

bg black,28
bg engeki_02,22

mld c,MAR_i4,25

se3v 13,50
quakey 2,200

;　再び姿を見せた毬枝は、@……学校を代表する妖怪たちの末席を務める者に相応しい貫禄を見せていた。\
`　The figure of Marie was seen once more,`@` ...Marie displayed a presence befitting of one representing the school's lowest seat of power among the youkai.`\
mld c,MAR_i2,80

;「…………私は、まだ自分の力をよくわかっていません。@………私に抱き締められタラ、……手加減は、無理……デス……。」\
`"...I, still do not understand my own power.`@`...If you try to stOP ME, ...I won't be able to ...HOLD BACK..."`\

me1v 16,70

bg black,2
bg aka1,0
mld c,MAR_o1,2

me2v 28,90

;　毬枝の体から、重い冷気が噴出し、床を満たす……。@
`　From Marie's body, a heavy chill gushed out and covered the floor...`@`

br
;　鉛のような質量を伴った両腕は、@まるで丸太を思わせるほどの太ささえ感じさせる威圧感を放っていた。\
`　Both her arms were as heavy as lead, @` and they were so large they seemed like tree trunks.`\
mcl c,0
bg engeki_01,0
mld l,SIN_Def1,22
;ld l,SIN_Def1,80

;「やはり、……敵いませんか。@……では、最後に一花とさせていただきましょう。」@
`"I suppose that didn't work.`@` ...Well then, let's continue until something does."`@`
br
;　紅茶紳士が手をかざすと、そこに霧の蛇が巻きつき、……槍のような鋭さを見せる。\
`　The Black Tea Gentleman raised his hand, and a snake of mist twined around, ...and sharpened like a lance.`\

se1v 22,50

bg white,8

ld r,MAR_o1,2

;「…………………………………。」@
`"............"`@`

mld l,SIN_Def2,80

;「……おや。@足音が近付いてきますね。@……これ以上、ニンゲンが増えると居心地が良くありません。@この一撃で、決着とさせていただきましょう。」\
`"...Oh my. `@`I hear some footsteps coming closer.`@`...If we go on, more 'humans' than I am comfortable with will be here.`@` Allow me to settle this with this one blow."`\

;　確かに、誰かの足音が近付いてくる。@
`　Indeed, someone's footsteps were nearing.`@`
;　まっすぐ、この部室に近付いてくる。@
`　They were coming closer, directly to this clubroom.`@`
br
;　それが、二人の決闘の、秒読みとなる………。\
`　That was to be the countdown for their duel...`\
E_A

se1v 82,100

mcl l,0
bg white,64



;　がらりと部室の引き戸が開け放たれた瞬間。@/
`　The instant the club's sliding door was thrown open,`@`/
me1v 28,70
;……毬枝と紅茶紳士は、電光のような閃きで交差した。\
`...Marie and the Black Tea Gentleman, crossed paths with a flash like lightning.`\


ld_p MAR_i2
lsp2 4,$ld_pass,130,550,200,200,0
lsp2 5,$ld_pass2,130,550,200,200,0
print 24

;「…………………………。」@
`"............"`@`

ld_p SIN_Def3
lsp2 2,$ld_pass,480,480,-200,200,0
lsp2 3,$ld_pass2,480,480,-200,200,0
print 23

;「………ですよねぇ…………。」\
`".....I see..."`\

ld_p MAR_i3
lsp2 4,$ld_pass,130,550,200,200,0
lsp2 5,$ld_pass2,130,550,200,200,0
print 80

;「……負けを認めて下さい。@……手加減は、本当に難しいんです。」@
`"...Accept your defeat.`@` ...It'm really struggling to hold back."`@`

ld_p SIN_Def1
lsp2 2,$ld_pass,480,480,-200,200,0
lsp2 3,$ld_pass2,480,480,-200,200,0
print 80

;「恐ろしい。@……これで、………手加減と、……は………。」\
`"How frightening.`@` ...That this...is you going...easy..."`\

textoff

E_A

csp2 -1
print 0

se3v 20,70

bg white,24
bg black,24
bg engeki_03,24

wait 500

se1v 1006,70
se2v 12,70

quakex 3,300

se3v 13,50

quakey 2,300

me1v 5,50

;　雷鳴のような音が轟き、……紅茶紳士の体は、豪腕によって殴り飛ばされたことを、思い出す。@
`　With a roar like the sound of thunder, ...The Black Black Tea Gentleman's body was knocked off his feet by her strong arms.`@`
;　一番奥の壁まで吹き飛ばされ、大の字に叩き付けられた。@
`　He was blown clear across the room and strewn against the furthest wall.`@`
br
;　紅茶紳士は、見事な一撃です…、と言いながら、親指を立てる仕草をしてみせる…。\
`　The Black Tea Gentleman said, "a splendid strike," and gave a thumbs up as he spoke...`\
se1v 1100,30
mbg white,1
mcbg 22

;　それと同時に、小さな割れる音。@
`　At that same time, a small breaking sound.`@`
;　みどりに及んでいた紅茶紳士の力が砕け、彼女が解放されたことを示すものだった。@
`　It was to signify that The Black Tea Gentleman's power had been broken, and Midori had been set free.`@`
br
;　毬枝は安堵の溜め息を漏らしながら、ゆっくりと両拳の力を抜いていく………。\
`　While letting out a sigh of relief, Marie drew back the power in both her fists...`\
bg black,2

fede 0,1000
E_A
wait 1000

bg engeki_04,22

me1v 11,90

;「………何やってんの、あんた。」\
`"...What are YOU doing here?"`\

;　部室に入ってきたのは、……川田のぞみだった。@
`　The one who entered the club room...was Nozomi Kawada.`@`
br
;　そして、ドレスを着て鏡の前に立つみどりを睨み付けた。\
`　And she scowled at Midori, who was standing in front of the mirror in a dress.`\

ld c,MID_K2,22

;「………川田……さん……………？」@
`"...Kawada...san...?"`@`
;「………何、勝手に、………人の衣装、着てんのよ。」\
`"...What, you think you can just...wear someone's costume?"`\

ld c,MID_K1,80

E_A

;「え……………………。」@
`"Wha...."`@`

bgm1 7

br
;　川田のぞみが、ぞっとするほど冷たい目でみどりを見下ろしていた。\
`　Nozomi Kawada looked down on Midori with eyes so cold it caused her to shiver.

;「ほら。@………さっさと脱ぎなさいよ。」@
`"Come on.`@`...Hurry and take it off."`@`
br
;　みどりは困惑した。@のぞみがいきなり現れたこともそうだが、@彼女が何を言っているのか、心の底から理解できなかった。\
`　Midori was bewildered.`@` Certainly, Nozomi had appeared suddenly, `@` but honestly, from the bottom of her heart, she could not comprehend what she was saying.`\
;　……人の衣装？@　人の衣装って何？@　だってこれは私のドレスじゃない。@主役である、私の衣装。\
`　...Someone's costume?`@` What does that mean, 'someone's costume?'`@` I mean, this is my dress.`@` This is my costume, as the main role.`\
bg black,22

;「何ボーッとしてんのよ。@叩かれ過ぎて頭おかしくなった？」@
`"What are you spacing out for?`@` Did you get hit on the head too many times and lose it or something?"`@`
br
;　川田さんは厳しい口調できびきびと私にそう言い放つ。\
`　Kawada-san snapped at me in such a strict tone of voice.`\
me1v 17,50

;　……彼女って、こんなにもはっきりとしゃべる子だったっけ…？@
`　This girl - was it really even like her to speak so bluntly...?`@
br
;　妬ましそうに、無言でじっと睨むくらいしか出来ない子だと思ってたのに……。\
`　I thought she could only silently stare at me in jealousy...`\

;「とっとと脱げって言ってんのよ。@あんたの臭いニオイが染み付くでしょ。@あんたが私の衣装に触れていいのは、雑用係として手入れをする時だけよ。」\
`"I said hurry up, take it off. `@`Your stink is going to stick to it. `@`The only time you can touch my stuff is when you're doing your job as the chore girl."`\

ld c,MID_Def4a,22

;　雑用係……？@
`　Chore girl...?`@
br
;　それは、……川田さんのことじゃないの？@　……私は、……主役……。\
`　Isn't that... Kawada-san's job? `@`...I'm ... the lead...`\

bg engeki_01,1
quakex 2,200

;「脱げって言ってんのよ…！@　あんたみたいな根暗な子が主役の衣装を着ようなんて、千年早いのよッ！」@
`"I said take it off! `@`It's a thousand years too early for some moody girl like you to wear the costume of the lead actress~!"`@

ld c,MID_Def2a,22

;「な、………何を言ってるの、……あなた………。」\
`"Wh- ....What are you saying...?"`\

;「わけわかんねーこと言ってんのはテメーだろーが！@　脱げっツってんだよッ！！」@
`"The one who doesn't fucking understand is YOU! `@`STRIP damn it!!"`@
br

se1v 8,50
quakex 2,200
cl c,23
se1 13

quakey 2,200

;　川田さんは私をどんと突き飛ばす。@
`　Kawada-san suddenly lunged at me.`@
;　私はふらりとよろめいて転び、……道具入れの木箱の角に激しく頭をぶつける。\
`　I fell over and rolled, ...I hit my head hard on the edge of the wooden toolbox.`\

;se1 1100

E_B

mbg aka1,1
mcbg 22

;　その時、……何かが、割れた。@
`　That instant ...something snapped.`@

me2v 16,50

br
;　頭蓋骨がじゃない。@……もっと胸の奥の、深いところにある頑丈な何かが、びしりと割れた。\
`　It wasn't her skull. `@`...It was something by her chest, something deep inside had cleanly broken.`\

bg black,22
mono 1

ld l,SIN_def4,22

;　紅茶紳士は、一つだけ願いを叶えようと言った。@
`　The Black Tea Gentleman had said he would grant one wish.`@
br
;　どんな役でも一つ、与えてあげようと言った。\
`　That he would give her any one role she wanted.`\

;　みどりが選んだ役は、“お姫様”ではなかった。@
`　The role Midori had chosen was not 'the princess.'`@
br
;　彼女が望んだ役は…………。\
`　The role she chose was...`\











bg black,28

mono 0

E_A

se1 1100
bg white,1
bg engeki_01,0
ld r,MID_U1,22

se1 1100
bg white,1
bg engeki_02,0
ld l,MID_K4,22

se1 1100
bg white,1
bg engeki_03,0
ld c,MID_U2,22

se1v 1100,90
bg black,1
bg white,22

bgm1 6

;　心の中の亀裂から、次々に、……“真実”が、溢れ出して来る。@
`　'Truths' from deep in the crevices of her mind began to come out... one after another.`@
br
;　彼女が演じた虚偽ではなく、“本当”が、溢れ出す。\
`　Not the pretend acting, but the 'truth' flows.`\

bg black,28
bg white,28
se1 1100
bg white,1
bg kyou_04,22
se1 1100
bg white,1
bg kyou_01,22
se1 1100
bg black,1
bg white,22


;　それはまるで、録画した映像が巻き戻されるかのよう。@
`　It was almost like watching a movie on rewind.`@
br
;　過去の記憶が鮮明に蘇る。@嘘で上書きされる前の、正しい“本当”の姿で。\
`　Memories of the past were clearly resurrected. `@`From the lies that covered it came the real 'truth'.`\

bg kyou_02,2

me1v 24,50

;　朝、教室に入る私を、クラスメート全員が見る。@そして笑いながら近寄ってくる。@
`　It's morning, I enter the classroom and my classmates look at me. `@`They laugh as they draw near.`@
br
;　私を敬愛して、挨拶するためではない。\
`　It wasn't because they wanted to greet me with love and respect.`\

;　私を、叩くために。@
`　It was to hit me.`@
;　笑いながら集まってきて、私を叩いて、叩いて、嘲笑う。\
`　They'd come and gather while laughing and beat me, beat me, and sneer.`\

;　宿題やってきたよね？@　サキエが言う。@
`　You brought your homework? `@`Sakie would say.`@
br
;　そして彼女が差し出すノートを受け取る。@
`　And then she'd give me her notebook and I would take it.`@
;　私のやってきた宿題を、彼女のノートに写すために。\
`　So I could copy my homework in her notebook.`\

mbg "BMP\background\efe\red1.bmp",1
se1 12
mcbg 22

me2v 17,70

;　写している間。@サキエが定規を取り出し、私の腕を叩く。@フミエが私の顔面に上履きを投げつけてくる。@
`　While I was copying, `@`Sakie would take out a ruler, and beat my arms. `@`Fumie would throw indoor slippers at my face.`@
br
;　彼女らの宿題をしてあげてるのに、彼女たちは私に酷い仕打ちをするのだ。\
`　Even though I was doing their homework, they treated me terribly.`\

bg black,22

fede 11,1000
E_M1

bg engeki_01,22

;　放課後、部室に入る私に部長が言う。\
`　After school, the club leader said to me after he got into the clubroom.`\

;「楠木、お前も最近遅刻が多いぞ。」@
`"Kusunoki, you've been late quite a bit lately."`@
br
;　着替えるのに手間取ってしまって。@私はそう言い訳した。\
`　I was delayed because I had to change clothes. `@`That was the excuse I gave.`\

;　……その私の着ている体操着はシミだらけ。@ついさっきまでゴミ箱にでも突っ込まれていたかのような悪臭がする。\
`　...The gym outfit I was wearing was covered in stains. `@`It smelled just as if it had been pulled out of a garbage bin.`\

bg black,22
bg engeki_03,22

;　私がストレッチをする場所を探していると、みんなが「臭い」といって一斉によける。@
`　As I looked for a place to stretch, everyone said 'you stink' and moved away from me.`@
br
;　ぽっかりとあけられた広すぎるスペース。\
`　When they left me it created a vast distance of space.`\

mbg "BMP\background\efe\red1.bmp",1
se1 12
mcbg 22

;　そこで身体を伸ばし始める私の肩を、部員たちが次々に踏みつけていく。\
`　As I started to stretch my shoulders, the club members began kicking me, one after another.`\

;　女子の部員たちのひそひそ話が聞こえてくる。\
`　I could hear the club girls' whispers.`\

;「雑用係になったら大変だよね。@今回、小道具とかも多そうだし……。」@
`"I would hate being a chore girl. `@`This time, there's a ton of props and what not..."`@
;「くす。@それは心配しなくても大丈夫でしょ。@ほら、全部一人でやってくれそうな子がいるじゃない。」\
`"Hehe. `@`Don't worry about it. `@`Look, we have a girl who'll do everything for us all by herself."`\

;　彼女たちが私を見る。@いくつもの醜い笑いが並んでいる。@
`　They look at me. `@`Many cruel smiles spread.`@
br
;　私に役が与えられることなんてない。@……いつだって、万年雑用係なのだ。\
`　It wasn't as if I was given the position. `@`...Since when did I become the eternal chore girl.`\

E_MA

se1 1100
bg white,1
bg engeki_01,22

;「次。@川田のぞみさん。」@
`"Next. `@`Nozomi Kawada-san."`@



;「はい。@川田のぞみ。@魔女役を希望します。」@
`"Here. `@`Nozomi Kawada. `@`I want to be the witch."`@
br
;　『六軒島』の主役を堂々と立候補する。@みんな拍手でそれを祝福した。\
`　She splendidly announced her candidacy for the role of lead actress of 'Rokkenjima'. `@`Everyone applauded their blessings.`\

;「のぞみ姫しかありえないよね！」@
`"It could only be Princess Nozomi!"`@
;「のぞみーっ、がんばってねー！」\
`"Nozomi~ do your best~!"`\

ld r,MID_def4a,22

;「………………………。」@
`"........."`@
br
;　私はひとり、……その背中を、祝福でない眼差しで見つめていた…。\
`　I looked at everyone's backs ...I was the only one who wasn't cheering...`\

;　次々と配役が決まっていく。@
`　One after another the roles were being decided.`@
br
;　私も勇気を出していくつかの役に立候補するのだが、@演技が硬い、感情表現がダメとさんざん言われ、どの役ももらえない。\
`　I had the courage to announce my candidacy for all sorts of roles, `@`but acting is hard, and I was told my facial expressions were all wrong, so I couldn't get any role.`\

bg black,22

;　結局、当然のように、……雑用係だった。\
`　In the end, just as I expected ...I was the chore girl.`\

bg engeki_03,22
mbg "BMP\background\efe\red1.bmp",1
se1 12
mcbg 22

;「あんたが余計な立候補したから、余計な時間を食ったじゃない。」@
`"Since you kept stupidly nominating yourself, you wasted everyone's time."`@
;「あんたに一番お似合いの役が雑用係なのよ。@それくらいわかれよなー。」\
`"The role that best suits you is taking care of the odd jobs. `@`That being said, we're out of here~"`\

;「がんばってね、万年雑用係～。」@
`"Good luck, eternal chore girl~"`@
;「二度と立候補なんかしないでよね、ウザイから。」@
`"Don't ever nominate yourself again, you hear? It's ANNOYING."`@
br
;　みんなが私の背中を蹴りながら言う。@体操着の背中に無数の足跡がついていく。\
`　They said as they kicked my back. `@`Putting countless shoe stains on the back of my gym outfit.`\

bg black,22

;　部活の後、私は部室に残ってたった一人で小道具を作り、衣装を縫った。@
`　After the meeting, I was the only person left in the club. I worked on props and sewing clothes.`@
br
;　その合間に、こっそり『六軒島』の台本を読み、主役の魔女の台詞を口に出して言う。@
`　During that time, I'd secretly read "Rokkenjima"'s script, and practice the lines for the role of the witch.`@
;　最初は小さく、徐々に大きく。\
`　This practice started small at first, but it gradually grew larger.`\

se1v 13,30

;　やがて私は、………こっそりと、主役のドレスを纏い、たった一人の通し稽古を始める。@
`　Before long, ...secretly, I began wearing the lead's dress and put on the entire rehearsal by myself.`@

me1v 5,50

br
;　相手はいない。@でも、私には見えていたし、聞こえていた。\
`　I had no partner. `@`But I could see them, I could hear them.`\

bg Different_spiral_1a,22

;　……だから毎日、家に帰る頃にはすっかり夜になっている。@
`　...So every day, I would return home in the complete darkness of night.`@
br
;　『シーキャット』のアニメなんて、とっくに終わっている。@
`　The anime 'Sea Cats' was already long since over.`@
;　そしてベッドに倒れ込むように横になり、……頭を空っぽにして、泥のように眠った。\
`　So I'd tumble into bed and turn on my side ...empty my mind, and slept like a sack of potatoes.`\

bg black,22

fede 10,2000
E_MA

bg kyou_01,2

me1v 24,50

;　給食の時間。@……意地悪な誰かが、虫の死骸を私のカレーに入れた。@
`　Time for lunch. `@`...Some horrible person put dead bugs in my curry.`@
br
;　先生に見られないよう、意地悪な女子たちが私を囲むように座り、@……ちゃんと食べるかどうか、見張っていた。\
`　They sat around me in a circle so they wouldn't be seen by the teacher, `@`...they were watching me to see if I would eat it or not.`\

mbg "BMP\background\efe\red1.bmp",1
se1 12
mcbg 22

me2v 28,70

;　いつまでも口にしない私の後頭部を、フミエがトレイで叩く。@痛かった。\
`　Fumie was always hitting me in the back of the head with the tray while I kept quiet. `@`It hurt.`\

;「さっさと喰えよ、金持ち自慢のお嬢様。」@
`"Hurry up and eat, you haughty rich snobby princess."`@
;「良かったじゃん、みどりだけ特別カレーじゃん！」@
`"Aren't you happy? It's a special curry made just for you, Midori!"`@
;「お金持ちなんだから、特別メニューじゃないとねー。」@
`"Since you're so rich, you get a special menu~!"`@
;「喰えよほら。@健康にいいと思うよー、マジで。」\
`"Look, eat it. `@`It's good for your health, seriously."`\

;　私へのいじめは、１学期と何も変わっていなかったのだ。@
`　Nothing about the bullying towards me had changed since my first semester.`@
br
;　何も、何も。\
`　Nothing, nothing.`\


bg black,24
bg kyou_02,24

me3v 16,70

;　そんな中、……川田のぞみは、お姫様だった。\
`　In the middle of it all ...Nozomi Kawada was a princess.`\

;　“お姫様”役で、学校中で大人気でちやほやされてて。@
`　With the role of "the princess," she was fussed over and very popular all over school.`@
;　羨ましかった。@妬ましかった。@
`　I was envious. `@`Jealous.`@
br
;　舞台の中央はいつも彼女のものだった！\
`　She was always on the center of the stage!`\

bg black,22

me4v 3,70

;　だから、紅茶紳士に何の役を演じたいのかと問われて、私は答えたんだ。@
`　So when the Black Tea Gentleman asked what kind of role I wanted to play, I answered him.`@
br
;　私は、川田のぞみになりたいって……！\
`　I said, I wanted to be Nozomi Kawada...!`\

fede 10,2000
E_MA

bg engeki_04,6
;ld c,MID_def1,6

;　後頭部から血を滴らせ、……魔女のドレスを血に染めながら。@みどりはゆっくりと立ち上がる。@
`　The back of my head filled with blood, ... as she slowly stained the witch's dress with blood, `@`Midori slowly stood up.`@
br
;　そして、壁に寄り掛かり、苦しそうにしている紅茶紳士の姿を見つけた。\
`　And she leaned against the wall, she saw the Black Tea Gentleman, who seemed to be in anguish.`\

bg black,24
bg engeki_03,24
;ld l,SIN_Def1,24
ld r,MID_K5,22

wait 1000

ld r,MID_def4a,22

;「私は、……川田のぞみさんに、なりたい。」@
`"I... want to become Nozomi Kawada."`@

ld l,SIN_Def1,22

;「……えぇ。@知っていますよ。」\
`"...Yes. `@`I know."`\

ld r,MID_def2a,80

;「姫と呼ばれて、……ちやほやされたい。@演劇部でも、素敵な役を与えられて、舞台の中央でスポットライトを浴びたい…。@私を、彼女にして。@……川田のぞみにして……。」\
`"I want to be called princess ...I want to be loved. `@`Even in the drama club, I want to earn a spectacular role, and bathe in the spotlight of the center stage... `@`Make me her. `@`...Make me Nozomi Kawada..."`\

ld l,SIN_Def3,80

;「えぇ。@なれます。@……貴方が演じさえするならば、いつだって、これからだって、@……貴方は川田のぞみとなれるのですよ……。」\
`"Yes. `@`You can become her. `@`...As long as you keep acting, you can always from henceforth, `@`...become Nozomi Kawada..."`\

mbg black,22

me1v 16,70

;ld r,MID_def1,80

;「でも、……おかしいの……、おかしいの……。@……みんなが、みんなが……私をいじめるの……。@……川田さんもおかしいの……。@このドレス、私のじゃないって……、私のこと、……雑用係だって……！！」\
`"But... something is wrong... something is wrong... `@`...Everyone, everyone is bullying me... `@`...Even Kawada-san is wrong... `@`They're saying... this dress isn't mine ― they're saying... I'm the chore girl!!"`\

;ld l,SIN_Def1,80

;「みどりさん。@気にしないことです。」@
`"Midori-san. `@`Please don't worry."`@

;ld r,MID_def1,80

;「気に、……しない…………。」\
`"Don't... worry...."`\

cl a,0
mcbg 22

ld c,SIN_Def1,22

;「貴方は、川田のぞみさんのように演じて下さい。@何も気にせず、耳を傾けず。@演技に集中するのです。」\
`"Please act as if you were Nozomi Kawada-san. `@`Don't pay heed to anything or listen to anyone. `@`You must focus on acting."`\

bg black,0
ld c,SIN_Def1,22

;「……貴方は川田さんがのぞみ姫と呼ばれているように、貴方もみどり姫と呼ばれている。@クラスメートたちの憧れを一心に浴び、サキエさんやフミエさんにも親しく接し。@演劇部では常に主役を与えられて祝福されるのです。」\
`"...Just as you call Kawada-san Princess Nozomi, you too shall be called Princess Midori. `@`You will bathe in the love of your classmates. Even Sakie-san and Fumie-san will become close to you. `@`You'll be showered with praise and always selected for the lead roles in the drama club."`\

mld r,MID_def2a,22

;「………それが、……私……。@……私は、……姫……。@……みどり姫………。」\
`"...That...I could... `@`...Me... a princess... `@`...Princess Midori..."`\

bg black,2

;　みどりの世界が、少しずつ薄暗くなっていく。@
`　Midori's world began to dim little by little.`@
br
;　まだ昼間だというのに、みどりの世界は暗くなっていく。\
`　Even though it was still daytime, Midori's world began turning dark.`\

;　当然だ。@舞台の上は薄暗い。@……そして、目立つべき人物に対し、鋭くスポットライトが浴びせられ、その姿を浮き立たせるのだ。\
`　It's only natural. `@`The top of the stage is dim. `@`...And with a striking person bathed in the sharp spotlight, their figure stands out.`\


se1 77

mcl r,0
bg white,1
bg engeki_05,22

;　それは、主役のドレスを纏った、みどりの姿。@
`　There she stood - Midori's figure, clad in the dress of the lead actress.`@
br
;　『六軒島』の舞台を最高の演技で締めくくり、盛大な拍手と歓声を独り占めにするところ。\
`　At the end of the supreme climax for the play "Rokkenjima," she would monopolize a grand cheer and applause.`\

;　ほら、聞こえてきた……。@聞こえてきた……。@拍手、歓声……。@私を姫と呼んで讃えるみんなの声…………。\
`　See, I can hear it... `@`...I'm hearing it... `@`The applause, the cheers... `@`The praises of everyone's voices calling me Princess......`\

bg black,22
bg engeki_03,0
ld c,MID_U2,22

;　何なのこいつ……。@川田のぞみは、呆然とする他ない。@
`　What's with this girl... `@`Nozomi Kawada was dumbfounded.`@
br
;　みどりは鏡に向かって一人、深々とお辞儀をしている。@
`　Midori faced the mirror and began deeply bowing to herself.`@
;　……誰かに手を取られるかのようにしながら。\
`　...Then she seemingly reached out to take someone's hand.`\

bg black,0
ld c,MID_U2,0
ld l,SIN_Def2,2

;　その手を、紅茶紳士が握っている。@
`　The Black Tea Gentleman took that hand.`@`
br
;　毬枝もまた、その光景を呆然と見ている他なかった。\
`　Marie was also watching this spectacle in bewilderment.`\

ld l,SIN_Def1,80

;「………こういうことです。@めそめその毬枝さん。@………私はそれでも、……みどりさんにお邪魔な存在ですかな…？\
`"...That's how it is.`@` Mesomeso Marie-san.`@`...Am I still...such a hindrance to Midori-san?"`\
ld r,MAR_i3a,22

;「…………………………。」@
`"......"`@`
br
;　毬枝は絶句する。@何も言い返せない。\
`　Marie was at a loss for words.`@` She could say nothing in return.`\

cl l,0
mld l,SIN_Def2,22

;「私は嘘を信じさせる妖怪です。@………嘘と聞けば、良からぬものにも思えるでしょう。@しかし。@痛み止めや麻酔薬のように。@人には生きていくために、忘れねばならぬ痛みもあるのではないでしょうか。@私はこの少女の痛みを、こうして和らげているのです。」\
`"I am a youkai that allows one to believe lies.`@`...When you hear the word 'lie', you can only think it is wrong, correct?`@` However,`@` It's the same with painkillers or anesthetics.`@` Isn't there some pain that must be forgotten in order to keep living?`@` This is how I relieved this girl of her pain."`\
ld r,MAR_i2a,22

fede 1,1000
E_B

mcl a,0
bg black,22
;bg engeki_01,0
;ld r,HIG_Def1,23

E_A

;「……毬枝。@相手が悪いわ。@そのくらいになさい。」\
`"...Marie.`@` You're out of your league.`@` Leave it at that."`\
bg engeki_01,22
ld l,MAR_i1,22

bgm1 14

;「彼岸花さんっ。」@
`"Higanbana-san...!"`@`
br
;　いつの間にか彼岸花の姿もあった。\
`　There was no telling when she arrived, but Higanbana was there.`\

ld r,HIG_Def2,22

;「元々。@………楠木みどりは私の獲物だった。」@
`"Furthermore,`@` Midori Kusunoki... was my prey."`@`

ld l,MAR_i1a,80

;「え…？」\
`"Huh...?"`\

ld r,HIG_W3,80

;「お金持ち自慢が過ぎて、クラス中に嫌われていじめられて。@……私好みの美味しい魂になりそうだった。@……それを、そいつに掻っ攫われたの。」\
`"Someone so proud of her money that she was hated in her class and bullied.`@`...That sounded like a delicious soul to my taste.`@`...Then this guy snatched it away."`\


bg black,24
bg engeki_03,0
ld c,MID_U2,0
ld l,SIN_Def2,24

ld l,SIN_Def1,80

;「私がみどりさんを獲物としなければ。@……今頃は彼岸花さんの甘言に耳を貸し。@……ひょっとしたら、自らの命を軽んじていたかもしれませんねぇ。」\
`"If Midori-san hadn't been my prey.`@`...Well, listen to what Higanbana-san said just now.`@`...She would have probably had her life toyed with."`\

ld r,MAR_i1a,22

;「………………………………。」\
`"......"`\

ld l,SIN_Def4,80

;「ニンゲンには、辛い現実から逃避する権利もあります。@そしてそれが当人にとって、幸せな夢を叶えるものに思えるならば。@……それは素敵なことではありませんか？」\
`"Humans have the right to run away from harsh realities.`@` And if you think of it as granting the person involved a happy dream,`@` ...is that not a beautiful thing?"`\

bg black,24
bg engeki_01,0
ld c,HIG_W3,24
ld c,HIG_Def5,80

;「詭弁だわ。@ニンゲンは現実に生きる。@……それから逃げたツケを、いつかは支払うことになるわ。」\
`"How sophisticated.`@` Humans live in reality.`@`...If one runs away, they will have to pay for it dearly one day."`\
;＜彼岸花

ld l,SIN_Def1,22

;「そうですね。@現実に戻る時、支払うことになるでしょう。@……しかし、戻らないならば、永遠に支払わなくても良い。」\
`"That's correct, isn't it?`@` Once they return to reality, they will have to pay for it.`@`...However, if they do not come back, they'd be fine never paying it back."`\

ld r,MAR_i3a,22

;「……そんなのが、……彼女にとって、……幸せなんですか……。」@
`"...Is that...what happiness...is to her...?"`@`

ld l,SIN_Def4,80

;「元いじめられっこの貴方なら。@……彼女の今の気持ちも、察してあげて欲しいものですがねぇ。」\
`"If you were once bullied.`@`...Then you would want to sympathize with how she feels now."`\

ld r,MAR_i2a,80

;「……………………………。」\
`"......"`\

cl c,22

bg black,23
bg engeki_02,23
ld r,HIG_w3,22

;「もう毬枝に文句がないならば。@その子はそいつの獲物よ。@……行きましょう、毬枝。@どうせ、あんたには太刀打ち出来ない相手なのだから。」\
`"If you have no more complaints, Marie.`@` That girl is his prey.`@`...Let's go, Marie.`@` He's not someone you can oppose anyway."`\

ld l,MAR_i4a,22

;「彼は紅茶紳士と名乗りましたが、……一体、何者なんですか。」@
`"The man used the name 'Black Tea Gentleman'...but just who on earth is he?"`@`

ld r,HIG_Def3,80

;「学校妖怪八席に序列は持たないわ。@……でも、実力はある。@そうね。@影の序列第２位ってところかしら。@………校長先生の右腕よ。@私たちは、“教頭先生”と呼んでる。」\
`"He does not have a rank in the 8 Seats of School Youkai.`@`...However, he has a real ability.`@` Well,`@` perhaps he would be about the second rank in the shadows?`@`...He's the Headmaster's right hand man. `@` We call him "Vice Principal."`\

bg black,0
ld c,SIN_Def1,22

;　学校妖怪序列第１位の校長先生の右腕、教頭先生。@
` The first rank of the school youkai, the Headmaster's right-hand-man, the Vice Principal.`@`
br
;　嘘を叶える力を持つ、恐ろしい妖怪。\
`　A fearsome youkai who holds the power to make lies reality.`\
;　ただし、嘘は嘘。@いくら叶えても、それは気付けば虚ろな嘘に過ぎない。@
`　However, lies are lies.`@` Once one realizes it's a lie, no matter how believable it is, it can be nothing else but a lie.`@`
;　しかしそれはあまりに甘美で、……抗えるニンゲンなど、きっと誰もいない。@
`　But his power is extremely tempting, ...and surely no human can resist it.`@`
br
;　校長先生の手下という扱いなので、序列は持たないが、@その実力は影の序列第２位と囁かれている……。\
`　This is what the Headmaster's underling is capable of `@`― the power of the shadow second ranked youkai spoken of in whispers...`\

bg engeki_01,0
ld c,SIN_Def1,22

;「ご謙遜を。@私など、名も無い一妖怪に過ぎません。」\
`"You flatter me.`@` I am nothing but a nameless youkai."`\

bg black,22
bg engeki_02,0
;ld l,MAR_Def1,0
ld r,HIG_w3,22

ld r,HIG_Def2,80

;「行きましょう、毬枝。@楠木みどりが、自ら望んだ顛末よ。@……現実を直視せず、嘘の世界を望み、ツケを払うことさえ拒んだ。@………あの子はもう、素敵な世界のお姫様。@……毎日が幸せでしょうから、自殺なんて金輪際、考えないでしょうし。@……残念ね、もう私好みの魂じゃないわ。」\
`"Let's go, Marie.`@` This is what Midori Kusunoki wished for.`@` ...Unable to face reality, wishing for a world of lies, she refuses to pay the price.`@`...That girl is still the princess of a beautiful world.`@`...Since every day should be happy, she would never possibly think of suicide.`@`...Pity, she's no longer my type of soul."`\

cl r,2

;　彼岸花はくるりと姿を翻して姿を消す。@
`　Higanbana turned around, then disappeared.`@`

br
;　毬枝は呆然と、……紅茶紳士とみどりのアンコールを見ていた……。\
`　Marie was speechless...and watched The Black Tea Gentleman and Midori's encore...`\

bg black,22
;bg engeki_03,0
;ld c,MID_Def1,24

;　川田のぞみも呆然としている。@……もう、みどりには誰の姿も目に入らない。@
`　Nozomi Kawada was also at a loss for words.`@`...And Midori's eyes could no longer see anyone.`@`
;　彼女の瞳に浮かぶのは、……満場の観客席だけだ。\
`　But reflected in those eyes, ...was an auditorium full of spectators.`\
se1v 77,70

bg white,1
bg engeki_05,22

wait 1000


se1v 54,100
wait 100
se2v 54,85
wait 100
se3v 54,70

ld c,MID_U2,22
ld c,MID_def3,2

;「ありがとう、みんな。@ありがとう、みんな…。@この舞台を、私を愛してくれる皆さんに捧げます。@……ありがとう、……本当にありがとう……。」@
`"Thank you, everyone.`@` Thank you, everyone...`@` I offer this stage to everyone who has loved me.`@`...Thank you...thank you so much..."`@`
br
;　いつまでもいつまでも。@割れんばかりの大歓声が、彼女を祝福し続けるのだった……。\
`　Forever and ever.`@` The thunderous applause and cheering, continued to praise her...`\

se1v 54,85

cl c,2

se2v 54,70
se3v 55,50

bg white,2

;＜おしまい＞

fede 1,2000
E_B
wait 2000

se1v 77,70

bg e022,1

wait 2000

bg black,42
bgcopy ;背景をリセット

if %UMINEKOEND < 3 mov %UMINEKOEND,3 : mov %END_FLG,3 ;クリアフラグの変更
	saveoff            ;セーブオフで、処理を高速化する。
	erasetextwindow 0  ;テキストエフェクトを切る事で処理を高速化
	rmode 0            ;右クリックのメニュー表示の無効化
	textoff


goto *b_title
;reset

*higan4_opning
texton
csp -1

bg black,2
bgcopy ;背景をリセット

setwindow 31,16,22,16,26,26,0,2,20,1,1,#999999,0,0,639,479

!sd

mono 0
E_A

;■鎮守神さまの祠

me1v 5,50

wait 2000

bg gakkou_03,2
