;Chapter 6
;　転んで膝を擦り剥いた。@
`　I tripped and skinned my knee.`@`
;　その上、遅刻した。@
`　And on top of that, I was late.`@`
br
;　楽しかった。\
`　It was fun.`\

bgm1 1

bg white,2
bg roji_03a,42


;　私は走っている。@
`　I was running.`@`
;　学校で走るなんてこと、三つしか考えられない。\
`　There have only been three times I can think of that I've run at school.`\
;　一つ。体育の時間。@
`　First, was for gym.`@`
br
;　体操が終わった後、校庭を何周も周らせられるのが、いつもとにかく苦手だった。@
`　After physical exercises were over, they would make us run tons and tons of laps around the campus, and I was always bad at it.`@`
;　でも、今は体操服を着ていないから、体育の時間じゃない。\
`　But, now I'm not wearing a gym uniform, so it's not gym class.`\

;　一つ。休み時間。@
`　Second. During break.`@`
br
;　友達とふざけていて、はしゃぎながら追いかけたり、追いかけられたり。@こっちは楽しい。@大好き。@
`　I was messing around with my friends while causing a commotion, chasing and being chased by them.`@` This was fun.`@` I loved it.`@`
;　でも、今はランドセルを背負っているから、休み時間じゃない。\
`　But right now I'm carrying a backpack, so it's not during break.`\

me1 33

bg black,22

;　ということは、最後の一つ。@
`　Which means, it must be the last one.`@`
br
;　あぁ、何てこと。@こんな悠長な思考が現実逃避だったなんてっ。\
`　Oh, how awful.`@` This easygoing thinking was just a form of escapism.`\

;bg "bmp\background\town\roji_02.bmp",25
bg roji_04a,23

;　私のように、走っている生徒の姿さえない。@
`　There weren't any other students running like me.`@`
;　あぁ、何てことっ、遅刻なんて絶対に嫌っ！\
`　Aah, this is awful, being late it the absolute worse!!`\
;　そこの曲がり角を曲がって、最後の直線を駆け抜ければ校門だ。@
`　I'll turn at that corner, and make the last straight line into the school gate.`@`
br
;　曲がってッ、ラストスパート…！！@
`　Turn, now for the home stretch...!!!`@`
br
;　……きゃあッ？！\
`　...Kyaa?!`\

se1 13
bg roji_03a,1
quakey 3,300

;　その時、私は見えない何かに躓いた。@
`　Just then, I stumbled over something I couldn't see.`@`
br
;　まぁ、見えていたなら躓かない。@……躓いたということは見えなかったということなのだから。\
`　Well, if I could've seen it I wouldn't have tripped.`@` ...The fact that I tripped over something pretty much means that I didn't see it.`\

;　私は盛大に転んで、膝を擦り剥く。@
`　I took a tremendous fall, and skinned my knee.`@`
;　……痛たたたたたたたた……。@
`　...Owwwwowowowowow...`@`
br
;　膝がカーッと熱くなって、ジンジンと痛み出す。\
`　My knee started burning hot, and a throbbing pain began.`\

;　じわっと、血がほんのり滲み出した。@
(?)`　At the wrinkles, blood started oozing out slightly.`@`
;　……それをそっと、人差し指でなぞる。@
`　...I gently, traced it with my index finger.`@`
br
;　ほんのり、指先が赤く汚れた。\
`　My fingertip was slightly stained red.`\

bg black,22

;　……………………。@
`　............`@`
;　あはは、面白い。\
`　Ahaha, how interesting.`\

;bg "bmp\background\town\roji_02.bmp",0

bg roji_03a,22

;ld l,hig_def1,0
;ld r,mar_def1,22

;　そんな彼女を、塀の上から見下ろす学校妖怪が二人……。\
`　Looking down on her from the top of a wall, were two school youkai...`\

ld c,mar_def2a,22

;「……彼岸花さん、酷いです。@何も転ばすことは……。」\
`"...Higanbana-san, that wasn't nice.`@` There was no reason to trip her..."`\

ld r,hig_def3,22
ld r,hig_w3,80

;「いいじゃない。@遅刻しそうで走って転んで、膝を擦り剥いて。@誰もが懐かしい日に、一度は体験しておきたいことだと思うけれど？」\
`"It's fine.`@` Running because it looks like you'll be late, tripping and skinning your knee.`@` I think it's a day that everybody should want to experience at least once."`\
;　くすくすと笑う、彼岸花。@
`　Higanbana giggled.`@`
;　もちろん、その姿が少女に見えることはない。\
`　Of course, the girl could not see those figures.`\

bg black,22

;「……あ痛たたた……。@……ふふ。」\
`"...Aahh, ow ow ow ow...`@` ...Hehe."`\

textoff
bg roji_04a,26

wait 1000

bg gakkou_01a,22

;　私は立ち上がり、彼方の校門を見る。@
`　I got up, and looked at the other side of the school gate.`@`
;　そこで無情のチャイム。@
`　And then, that ruthless chime.`@`
br
se1 69

;　校門がガラガラと閉められ、駆け込む生徒たちと締め出される生徒たちの悲喜劇が繰り広げられている。\
`　The gates rattled closed, and the tragicomedy of shutting out the students who rushed by at the last minute unfolded.`\
bg roji_04a,22

;　というわけで、ここから見ている自分は、……１００％の遅刻決定。@
`　Which means, that looking at myself here, ...it's 100% decided that I'm late.`@`
;　ということは、今さら走っても仕方ないってこと。\
`　Which means, that even if I run now, it's no use.`\

;「なら、歩こっ。@もう遅刻してるのに、走るなんて馬鹿馬鹿しいもんっ。」@
`"Then, I'll walk.`@` Even if I'm already late, running now would just be ridiculous."`@`
br
;　私はあっけらかんと笑いながら、悠然と歩き出す。\
`　While laughing indifferently, I calmly began to walk.`\

bg roji_03a,22

;　向こうでは生活指導の先生が、早くしろと急き立てている。@
`　From afar, the educational guidance instructors, were urging us to hurry it up.`@`
br
;　急いでも急がなくても、どーせ遅刻で怒られるわけじゃん？\
`　Even if we hurry or not, what's it matter if you're gonna get mad at us for being late anyway?`\
;　じゃあせめて、怒られることと引き換えに、@校門まで１００ｍほどの、朝の散歩をのんびりと楽しませてもらわなくちゃ。\
`　So at the very least, in exchange for you getting mad at us,`@` you have to let us enjoy the leisurely morning 100 meter stroll to the gate.`\
bg "bmp\background\school\Air_02.bmp",22

;　いい季節だった。@
`　This was a good season.`@`
br
;　さっきまで全力疾走だったから汗だく。@
`　I was dripping with sweat from sprinting with all my might up until now.`@`
;　そんな汗を涼しく癒してくれる風が、すっごく気持ちいい。@
`　The wind that cooled my sweat and rejuvenated me, felt incredibly good.`@`
br
;　私はたっぷりと新鮮な朝を満喫してから、悠然と校門に辿り着く。\
`　Now that I'd had my fill of this refreshing morning, I calmly arrived at the school gate.`\

;se1 10

;mbg white,1
;quakey 2,200
;mcbg 22

bg black,22

bg gakkou_01a,1
quakey 3,300

;　ごつん。@先生にゲンコツをもらう。@
`　Thump.`@` I got hit by the teacher's fist.`@`
br
;「何をちんたら歩いてるんだッ。@遅刻だぞ、遅刻！！」@
`"What are you walkin' so slowly for!?`@` You're late, you know! Late!!"`@`
;「知ってまーす。@間に合うなら走りましたけど、もう遅刻確定だったんで。」@
`"Yeah, I knoooow.`@` I'll run if I can make it, but it was already settled I was late."`@`
;「屁理屈を言うなッ。@走るのが嫌なら、明日からはもっと早く家を出ろ！」\
`"Enough with the excuses.`@` If you don't like running, you can start leaving your house earlier tomorrow!"`\

;mbg white,1
;quakey 2,400
;mcbg 22

;　ごつん。@割と容赦ない角度で脳天にもう一発もらう。@
`　Thud.`@` I took another relentless blow to the crown of my head.`@`
;　痛てて。@ジンジンする。@
`　Owowow.`@` It's throbbing now.`@`
br
;　……………。@
`　.......`@`
;　あはは、面白い。\
`　Ahaha, how fun.`\

;bg gakkou_01,22

;「ほら、早く入って教室へ急げッ。@明日からはもう遅刻するんじゃないぞ！」@
`"Alright, get your butt in gear and hurry to your class.`@` You'd better not be late again after today!"`@`
;「はーーーい！」@
`"Got iiiiit!"`@`
;「やれやれ…、返事だけはいいんだがなー。@ほら、早く行けっ。@廊下は走っちゃいかんぞっ。」\
`"Geez..., just your response is decent.`@` Alright, get going.`@` Don't run in the halls."`\

;　と言いつつ、先生もまんざらでない感じ。@
`　And with that, the teacher was satisfied.`@`
;　笑顔と素直な返事は、何にも勝る子供の武器なんだから。@
`　Because a smile and honest response, was a child's best weapon.`@`

br
;　そんなやりとりも、何だかちょっぴり面白い。\
`　That kind of exchange, was also a little bit interesting.`\

;bg white,24
mbg black,22

;　先生に開けてもらった校門の隙間を通り、私は駆け出していく。@
`　I went through the gap that the teacher had opened in the gate, and broke into a run.`@`
br
;　うん。@今日は素敵なことがありそうな一日だった。\
`　Yes.`@` Today felt like a day that something wonderful would happen.`\

textoff

mcbg 22

wait 1000

ld r,hig_def2,22

;「転んで遅刻して、先生にゲンコツまでもらって、素敵な一日…？　くすくすくすくす、前向きな子ねぇ。」@
`"Tripping, being late, and getting smacked by your teacher, and that's a wonderful day...? Teeheehee, what an optimistic kid."`@`

ld c,mar_def4a,22

;「や、やめましょうよ。@こんな悪戯。」\
`"L, let's stop.`@` This kind of teasing."`\ 

ld r,hig_def4,80

;「いいじゃない。@試してみたくなったわ。@あの子が、どこまでされても、今日を素敵な一日って言えるかをね。@……くす、くすくすくすくすくすくすくす。」\
`"Oh, it's fine.`@` I just wanted to try it out.`@` Whether that kid would say it was a wonderful day no matter what is done to her.`@` ...Teehee, heehehehehe."`\

cl a,22

;　彼岸花はニヤリと笑って、校舎を見上げる。@
`　Higanbana grinned, and looked up at the school building.`@`
br
;　毬枝は、悪戯好きな妖怪に好かれてしまった気の毒な犠牲者の今日一日を、心より同情するのだった……。\
`　To today's unfortunate victim of this mischievous youkai's hobby, Marie felt the deepest compassion...`\


bg black,22
fede 0,2000
E_A

bg kyou_03,22

bgm1 2

wait 2000
bg kyou_02a,6

;「出席を取ります。@相川くん。」@
`"I'll take attendance now.`@` Aikawa-kun."`@`
;「はぁい。」@
`"Here."`@`
;「安達くん。」@
`"Adachi-kun."`@`
;「ふぁーい。」\
`"Yeeeeeah."`\

;　朝の出席。@これに答えることが、学校の一日の始まり。@
`　Morning role.`@` To answer this, was the beginning of the school day.
;　学校が退屈な子や、まだまだ眠い子は、かったるい返事をする。\
`　Those that are bored of school, or those who are still tired, respond sluggishly.`\

;　何だか、勿体ないよね。@
`　It feels, like such a waste.`@`
;　だって、ここで元気良く返事をしたら、その分、一日が素敵になるかもしれないじゃない。\
`　Because, if you respond cheerfully, you could have a wonderful day of that same extent.`\

;　だから、自分の名が呼ばれた時。@私は飛びきり元気な声で返事をした。@
`　That's why, when my name was called.`@` I replied in an exceptionally energetic voice.`@`
br
;「はーーーい！」@
`"Heeeeeeeere!"`@~
br
;　直前までの低いテンションから、明らかに浮いた私の声に、みんなはきょとんと驚いてから、くすくすと笑う。\
`　The low spirits of before, in light of my clearly cheerful voice, surprised everyone with their blank faces, and they giggled.`\

;　笑いたくば笑え。@学校での一日に、同じ日など二度と訪れはしないのだ。@だから、今日という二度とない一日の始まりを、元気に挨拶するのは当り前っ。\
`　If you want to laugh, then laugh.`@` There cannot be the same day over again, or a repeat of this same day at school.`@` That's why at the start of this day that can't be repeated, it's obvious that you should greet it cheerfully.`\

bg kyou_01,23

;「おや、良いお返事ですね！@　みんなもこの調子で行きましょう。@次、野上さん。」@
`"Well well, there's a good response!`@` Everyone else, do it like that too.`@` Next, Nogami-san."`@`
;「はーーい！」@
`"Heeeere!"`@`
br
;　私の返事から、がらりとクラスの雰囲気が変わる。@
`　Starting from my response, the atmosphere of the class suddenly changed.`@`
;　みんな、直前の子に負けないように元気な声で返事をし始める。\
`　Everyone began responding with cheerful voices, as though to keep from losing against the person before them.`\


;　ほら。@元気な挨拶ひとつで一日が変わるの。@
`　See.`@` With just one happy greeting, the day can change.`@`
;　こんな当り前なこと、どうして私たちはいつもやれなかったんだろう。@
`　I wonder why we never do these obvious things.`@`
br
;　退屈そうに返事をして、一日を退屈に過ごしてしまった日々や人たちが、気の毒でならない。\
`　The people who respond like they're bored, and then spend the rest of their day bored, are just too unfortunate.`\

bg kyou_03,22

;「では、宿題を集めます、ドリルを後ろから回収して先生のところへ持ってきて下さい。@まさか忘れた子はいませんよね？！@　忘れたらどうなるか、言ってありますよね？！」\
`"Alright, I'm going to collect your homework, so I want everyone from the back to pass it up to the teacher.`@` I hope there's nobody who forgot to do it!!`@` I shouldn't have to say what will happen if you forgot!!"`\
;　先生がニヤリと凄む。@
`　The teacher threatened with a grin.
;　宿題を忘れた子には、ほっぺたをつねってグリグリする刑が待ち受けている。@
`　If you forgot your homework, a punishment of having your cheeks pinched and grinded.`@`
;　痛いし、つねられてる時の表情が面白おかしくてみんなの笑い者になるので、好んで宿題を忘れる子はいない。\
`　It hurts, and the expressions of people who get pinched is silly, so it makes everyone laugh, so there isn't a person here who would want to forget their homework.`\
;　それでも、ずぼらな男子が何人か、開き直るような笑顔で、忘れましたーと元気に宣言して席を立っている。@
`　But still, there are a few reckless boys that will smile defiantly, and proclaim, 'Yeahhhh I forgot~' and stand up from their seat.`@`
br
;　男子はだらしないなぁ。@女子には忘れる人なんてひとりもいない。@
`　Boys are just so careless.`@` There's not a single girl who would forget.`@`
br
;　………あれ？\
`　...Huh?`\

bg kyou_04,0
ld c,hig_def1,23
ld c,hig_w2,80

;「ドリルって、つくづく面白くないわよね。@こんなものを何ページもやらされるんだから、同情するわ。」@
`"Drills are really just not fun at all.`@` I don't even know how many pages of those I had to do, so I can sympathize."`@`

ld r,mar_def2a,24

;「彼岸花さん、それ……、あの子のドリルじゃ……。」\
`"Higanbana-san, um, ...that girl's worksheet..."`\

ld c,hig_w3,80

;　彼岸花がぺらぺらと乱雑に扇ぐそれは、紛れもなく少女のドリル帳だ。@
`　That disorderly thing that Higanbana was blabbing about, was without a doubt that girl's practice notebook.`@`
;　それは彼女の机の中に入っていたはず……。@
`　That should have been in her desk...`@`
br
;　少女は、おかしいおかしいと、机の中を覗きこんでまで探している……。\
`　The girl, muttering how strange it was, was still searching around in her desk...`\

bg black,22

;「おかしいな、おかしいな……。@ちゃんとランドセルに入れたはずなのに……。@何で何で、どうしてどうして……。」@
`"But, that's weird...`@` Even though I swear I put it right in my backpack...`@` Why, why, why, why...."`@`
br
;　後ろの席の子が、ドリルを集めながら私の席にやってくる。@
`　The person behind me was collecting everyone's drills, and was bringing it to me.`@`
;　いけないいけない、早く提出しないと……。@どうして、ないんだろう。おかしいなぁ……。\
`　No, this is no good, if I don't turn it in...`@` Why, isn't it here? This is too weird...`\

;　……結局。@ランドセルの中まで引っ繰り返したが、私のドリルは出てこなかった。\
`　...In the end,`@` even going so far as to turn her backpack upside down, her worksheet never appeared.`\

bg kyou_02a,22

;「ほらっ、忘れた子は前に出てきなさいッ！@　忘れちゃ駄目よって、あれだけ言ったのに…！　もーーー！！」@
`"Alright now, all of you who forgot it, come to the front!`@` Even though all I say is that it's not okay to forget...! Really!!!"`@`
br
;　男子５人に、女子は私だけ。@
`　There were 5 boys, and I was the only girl.`@`
;　えーもー、何でー？！@　ちゃんと宿題してランドセルに入れたはずなのにー！\
`　Ohh, whhyyy?!`@` Even though I know I did my homework and put it in my bag!!`\

;　いつまでもそんなことをしてると、往生際が悪いと思われているようで気まずい。@
(?)`　I kept thinking that way, like I didn't know when to give up.`@`
;　うーーん、きっと家の机の上に忘れてきちゃったんだろうな。@
`　Hmm, I bet I just left it in my desk at home.`@`
br
;　ママがいつも、寝る前に忘れ物がないか確認しなさいって言ってたのを、面倒臭がってたからバチが当たったんだな…、トホホ。\
`　Mama always says, "Before you go to sleep, make sure you aren't forgetting anything," and thinking it was a pain, now I'm getting punished...tohoho.`\

bg kyou_01,22

;　忘れた６人は一列に並ばされ、次々に先生にほっぺたをつねられグリグリされていく。@
`　The six that forgot lined up, and one after the other had their cheeks pinched and grinded against.`@`
;　どの男子たちも忘れ物の常習犯ばかり。\
`　These boys were all habitually forgetful.`\

;「もー！@　あなたたちには何回言えば忘れ物がなくなるんです？！@　次からは忘れたら、ダブルですよダブル！@　ブルドックになっちゃうくらい引っ張っちゃいますからね！」@
`"Really!`@` How many times do I have to tell you before you stop forgetting?!`@` Next time you forget, I'll do this double, you hear? Double!!`@` I'll pull on your cheeks till your face looks like a bulldog's!!"`@~

br

;　と凄みながら、次々にほっぺたを抓り上げて、まるでお餅のようにひん伸ばす。\
`　While she threatened them, she pinched each of their cheeks one by one, exactly the way you'd pinch and stretch mochi.`\

;　その歪んだ面白い顔を、みんながげらげら笑っている。@
`　Seeing those warped, funny faces, everybody laughed hysterically.`@`
br
;　……あー、普段なら私も笑ってる側なのにー、何たる失態。\
`　...Man, normally I'd be laughing with them~ what a disgrace.`\
bg kyou_03,23

;「あら、珍しい。@あなたも忘れちゃったの？！」@
`"Oh, now this is rare.`@` Did you forget yours too?!"`@`
;「……は、はい。@……ちゃんと宿題やったはずなんですけど……、ランドセルに入れ忘れたみたいで……。」\
`"...Y, yes.`@` ...Even though I thought I did my homework..., I guess I forgot to put it in my backpack..."`\
;「あら、もー。@せっかく宿題やったのに、忘れ物で全部台無しじゃがっかりでしょう？　次からは気を付けなさいね。」\
`"Well, really. `@` It's pretty disappointing to have done your homework and let it all go to waste because you forgot it, right? Be more careful next time, alright?"`\

;　私は常習犯じゃないから、先生もやさしく諭してくれる。@
`　I wasn't someone who constantly forgot my work, so the teacher only admonished me gently.`@`
;　元気良く頷いて、次から気を付けますと明るく返事。@/
`　I nodded cheerfully, and brightly replied that I'd be careful next time.`@`/

;……これで何とか誤魔化せたー、と思ったら、後ろ襟をむんず。\
`...As I thought it was just a put-on, my collar was pulled violently back.`\

se1 47
;mbg white,1
quakey 2,200
;mcbg 22

;「でも、お仕置きはしますからねっ。@これに懲りて、二度と忘れないことですよっ。」@
`"But, I still need to punish you.`@` Learn from this experience, and don't forget again."`@`
;「ふぎゃッ！@　むぎぎぎぎぎぎぎぎぎー！」\
`"Bggyaa!`@` Hnnnnghhhhhhhh!!!"`\

se1 48
quakex 3,300
se2 47
quakey 3,300
se1 48
quakex 3,300
se2 47
quakey 3,300


;　私のやわらかーなほっぺが、ぐににぃと伸びて歪む。@
`　My soft, soft cheeks were grinded, pushed, and manipulated.`@`
;　よほど私は面白い顔をしているのだろう。@みんな大笑いする。@
`　I could guess my face was very funny.`@` Everybody was bursting with laughter.`@`
br
;　それが何だか面白くて。@痛いはずなのに、私まで笑い出してしまう。\
`　That was somehow funny.`@` Even though it should've hurt, it made me laugh too.`\

bg kyou_02a,22

;「はい、おしまいっ。@席に戻って！」@
`"Right, we're done here.`@` Go back to your seat!"`@`
br
;　そう言いながら解放する先生も、つられて笑っているように見えた。\
`　While saying this and freeing me, I could see even my teacher seemed to be laughing.`\

bg black,22

;　ほっぺ痛い。@
`　My cheeks hurt.`@`
;　みんなにも笑われた。@
`　I was laughed at by everyone.`@`
;　でも、楽しい。@
`　But, it was fun.`@`
br
;　私は、自分だけ先生にご褒美をもらえたかのような気持ちになりながら、席に揚々と戻る。@
`　While feeling like I was the only one who was given a reward from the teacher, I triumphantly returned to my seat.`@`
br
;　頬の痛みは、今はくすぐったく、微笑ましいものに感じられた。\
`　The pain in my cheeks, now had become a pleasant feeling.`\

;bg black,23
bg rouka_03,0
ld c,mar_def3a,0
ld r,hig_w2,23

ld c,mar_def2a,80

;「痛そう…。@ほっぺたが、あんなに伸びるなんて……。」@
`"That looked like it hurt...`@` Having your cheeks pinched and pulled like that..."`@`

ld r,hig_def3,80

;「やるわね。@あんな目に遭っても、楽しいなんて思ってられるなんて。」\
`"She's not bad.`@` Even after going through that, she's still thinking it was fun."`\

ld c,mar_w1,80

;「くす。@何だか素敵ですよね。」@
`"Teehee.`@` It's kind of nice, isn't it?"`@`

ld r,hig_w3,80

;「うふふ。@……面白いじゃない。@試してみたくなっちゃったわ。」@
`"Ehehe.`@` ...Isn't this interesting.`@` It makes me want to test her more."`@`
br
;　彼岸花の笑みが、邪まなものに歪む。@……もっとも、清楚に歪んだ試しはないのだけれど。\
`　Higanbana's smile, twisted wickedly.`@` ...Though really, there aren't any ways of attempting to twist something cleanly.`\

cl c,0
ld l,mar_def4a,24

;「……試すって、何をですか。」@
`"...what do you mean, by test?"`@`

ld r,hig_w4,80

;「決まってるじゃない。@あの子が、どこまでされても、楽しいなんて思っちゃえるのかをよ。」@
`"Isn't it obvious?`@` Testing whether she'll think things are fun regardless of how far she's pushed."`@`

ld l,mar_def2,80

;「……………………。」\
`"........"`\

;　彼岸花は瞳をキラキラさせてほくそえむが、毬枝は、はぁっと深いため息。@
`　While Higanbana's eyes glittered and narrowed, Marie sighed deeply.`@`
;　彼女が上機嫌な時に、変に口を挟むと妙に拗ねることを、毬枝は最近、理解し始めている。@
`　Marie was starting to realize that while she was in a good mood, if she were to cut into it with something strange, she would get uncharacteristically pouty.`@`
br
;　……命に危害を加えようと言い出さない限りは、まぁ、大目に見ておくか。\
`　...As long as she doesn't start saying she'll cause any harm, I suppose I can tolerate it.`\

bg black,22

;　そんな毬枝の無言の嘆きなど、彼岸花が察するわけもない。@
`　There was no way Higanbana could guess Marie's wordless laments.`@`
br
;se1 27
;bg white,1
;quakey 2,300
;bg rouka_03,0
;ld c,mar_def1,22

;「さぁ、試してあげようかしら。@何が起こっても、どこまであんたが楽しいなんて思ってられるかをね…！」\
`"Alright, let's try it out!`@` If you'll still think everything is fun no matter what happens or how far you're pushed...!"`\

fede 0,2000
E_A

bgm1 3

bg white,22
bg "bmp\background\school\Air_02.bmp",2

;　性質の悪い学校妖怪に目を付けられた少女の今日一日は、とにかく不幸の連続だった。\
`　The girl who caught the bad-natured school youkai's eye, in any case had a series of unfortunate events all day.`\

;　どういうわけかその日に限って、日差しが気持ちよくて。@
`　On just this day, the rays of the sun felt really good.`@`
;　ついうとうととしてしまったところで、唐突に先生に当てられて、今が教科書の何ページかわからなかったり。\
`　And without thinking, just as I dozed off, I was suddenly hit by my teacher, and I didn't know what page we were on in my textbook.`\
bg white,23
bg kyou_02a,23

;「続きを読んで下さい。@さぁ？」@
`"Continue reading.`@` Go on."`@`
;「えっと、………あー……うー……。」@
`"Ummm, ...er...uh...."`@`
br
;　うわー、先生が疑ってる。@居眠りしてたんだろーって疑ってるー、あーうー！\
`　Waahhh, my teacher's doubting me.`@` He's suspecting that I was falling asleep...auuu....!`\

se1 47
;「………４８ページぃ～。」@
`"...Page 48~"`@~
;「わ、ありがとっ。」@
`"Wah, thank you!"`@`
br
;　完全に焦りかけてたところで、後ろの子が助け舟。@
`　Right as people were getting impatient, the person behind me became my lifesaver.`@`
;　こういう時、女の子の素敵な友情を感じずにはいられない。\
`　During these times, there's not a girl who wouldn't feel she had wonderful friends.`\

;　居眠りしちゃってたのはピンチだったけど、ちょっと素敵な気持ちになれたから良かったかな。\
`　Even though I was in quite a pickle falling asleep, since it became such a wonderful feeling it was okay.`\

bg black,22

bg rika_02,22
;wait 1000
;bg rika_04,22

;　お次は理科室での実験。@試験管の中の温度を測ることになった。@
`　Next was the science incident.`@` We were measuring the temperature inside a test tube.`@`
br
;　先生に、温度計を注意して入れないと、試験管を壊してしまうと注意されていたにも関わらず、@/
`　The teacher said if we didn't pay attention to the thermometer, the test tube could break in spite of everything.`@`/
se1 1006
;……バリン。\
`...crunch.`\
;「うわ、っちゃ……、やっちゃったぁ……。」@
`"Oh no...! Now I've done it..."`@`
br
;　何で唐突につるんと温度計が滑るの？！@
`　Why did the thermometer have to get slippery all of a sudden?!`@`
ld r,HIG_W3,80
;　彼女の後ろで意地悪な学校妖怪がくすくすと笑う。\
`　Behind her, the unkind school youkai giggled.`\

bg rika_03,23

;「もー、何やってんのよー。」@
`"Really, what are you doing?"`@`
;「えへへ、ごめーん。@こんなんなっちゃった。」@
`"Ehehe, soooorry.`@` It turned out like this."`@`
br
se1 48
;　試験管の底から顔を覗かせる温度計。@
`　The thermometer stuck out from the bottom of the test tube.`@`
se2 47
wait 300
se3 48
;　水鉄砲みたいにしゅこしゅこやると、それがすっごく滑稽だったらしく、班のみんながくすくすげらげらと笑ってくれた。\
`　When it started squirting out like a water gun, it got to be really funny, and everyone in my group started giggling and laughing.`\

se1 69
bg gakkou_02,22

;　まぁ、あとで先生に怒られるわけだけど、@……こういうのもすっごく楽しい。\
`　Well, later the teacher got mad at me, but,`@` ...This too, was extremely fun.`\

;wait 2000
;bg kyou_02,22

;　そして、給食の時間も、どういうわけかツイてない。@
`　Then there was the time at lunch, which for some reason I just couldn't follow.`@`
;　牛乳を飲んでたら、唐突に鼻がムズっと来て、ハックションと大くしゃみ！@
`　When I was drinking my milk, it suddenly went up my nose and a humongous sneeze came out!`@`
br
;　幸いにも誰の顔にもブチまけずに済んだけど、私の鼻からは牛乳の雫がたらりと糸を引いて、クラス中が大笑い。\
(?)`　Fortunately, I was able to save face, but then a little string of milk stretched out from my nose, and everyone in the class cracked up.`\

;　それにつられたのか、数人の男子が同じように牛乳を噴き出したものだから、もうクラス中、大パニックの大爆笑。@
`　It must have been infectious, because countless boys started spurting out milk in the same way, and the whole class erupted in explosive laughter.`@`
br
;　私も、みんなも、牛乳まみれになって笑い転げた。\
`　I, and everybody else, was reeking of milk and rolling in laughter.`\

bg black,22

;　酷い目に遭ったけど、こんな大笑いの給食は、きっとどんな素敵な献立にも負けない。@
(?)`　Even though I suffered through that, during this lunch filled with raucous laughter, I couldn't lose no matter what was on the menu.`@`
;　だから私は、ハンカチで顔を拭いながらも、まだ笑いが止まらないのだった。\
`　That's why, as I wiped my face with my handkerchief, I still couldn't stop laughing.`\

;bg rouka_02,0
bg kyou_02,0

ld r,mar_def4a,22
ld r,mar_def2a,80

;「さ、さすがに牛乳飲んでる時は可哀想ですよ……。」@
`"Y, you know, maybe while she's drinking milk is going too far..."`@`

ld c,hig_w4,22

;「……こんな目に遭っても楽しいっての？　なかなか手強いじゃない。@もう、意地でもあの子の泣き顔を見たくなったわ。」\
`"...Even after that, she still thinks it's fun? She's pretty tough after all.`@` Oh, she's making me want to see her cry no matter what it takes."`\
ld c,hig_w6,80

;「泣かすッ、/
`"I'll make you cry,`/
se1 2
quakey 4,300
;絶対に泣かしてやるんだからっ！@　学校妖怪序列第３位、踊る彼岸花の名にかけてっ。」@
`I'll definitely make you cry!!`@` I bet my title of the Dancing Higanbana, the number three school youkai on it."`@`
ld r,mar_def3a,80

;「そんなことに名をかけないで下さい……。」\
`"Please don't bet your name on that..."`\

bg white,23

me1 31

bg "bmp\background\school\Air_02.bmp",0
print 22

;　給食の後は楽しい昼休み。@学校で一番楽しい時間だ。@
`　After lunch was a fun afternoon break.`@` It's the most fun time at school.`@`
;　男子たちが一斉に教室を飛び出していく。@こんな天気のいい日に校庭を元気一杯に走り回ったら、さぞや楽しいだろう。@
`　The boys all dashed out of their classrooms at once.`@` Running around the court yard brimming with energy on a day with weather like this, would surely be fun.`@`
br
;　私も友達と一緒に教室を飛び出す。\
`　I also dashed out of the class with my friends.`\

se1v 82,90
bg rouka_02,1
quakex 3,300

;「早く行こ行こ…！@　また男子にボールを全部取られちゃうよ…！」@
`"Hurry, let's go, let's go...!`@` The boys are gonna take all the balls from us again...!"`@`
;「遅れると、空気の抜けたボールしか残らないもんねー。」@
`"If we're late, only the flat balls will be left~"`@`
;「どこで遊ぶ？！」@
`"Where should we play?!"`@`
;「百葉箱のところは？　あそこの芝生は気持ちいいよねー！」\
`"Over by the Stevenson Screen? The grass over there feels so good~!"`\
;　数人で集まって、温かい芝生の上でボールが一つあれば。@それだけで、昼休みのひと時は虹色に輝くのだ。\
`　If you get a bunch of people together and you have a ball and the warm grass.`@` Just by that, the afternoon break glittered vividly.`\

bg white,23
bg k_kaidan_01,23
bg white,26
bg k_kaidan_02,26
bg shoukou_01,24

wait 500

E_A

se1v 10,90

ld c,HIG_W3,1

;bg white,1
quakex 4,300

se2v 13,90

bg white,1
quakey 3,400

bg black,22



;　あッ。/
`　Ah./
se3v 13,50
quakey 2,200
`@`
br
;　興奮気味に走っていた為、前方が不注意だった。@
`　Because I was running around excitedly, I wasn't paying attention to what was in front of me.`@`
;　下駄箱の陰にいた子に、激しく左肩をぶつけてしまう。@
`　There was a girl hiding by the shoe rack, and I violently slammed into her with my right shoulder.`@`
;　……多分、上級生の女子だろう。@髪が長くてとても綺麗なのが印象的だった。\
`　...She was, probably an upperclassman.`@` Her hair was long, beautiful, and incredibly impressive.`\

me1 28

bg different_spiral_1a,22
;「ごッ、ごめんなさい…？！@　…………あッ……、」@
`"I, I'm sorry...!!`@` ...Ah..."`@`
br
;　あまりに勢いよく片方の肩をぶつけたので、私はぐるぐるとコマのように回りながら転んでいく。@
`　I moved the side of my busted up shoulder too much, and started spinning round and round like something out of a comic, then fell over.`@`
;　あははは、思い切り回した、遊園地のコーヒーカップみたい……。\
`　Ahahaha, I'm spinning like crazy, like a tea cup at an amusement park...`\

;se1 35
se1 12

mbg white,1

mono 2

mcbg 22


;　そんな気持ちは、激しい痛みの衝撃で粉々に吹き飛んだ。@
`　That feeling, was likely coming in small pieces due to the shock of that intense pain.`@`
;　まるで斧の分厚い刃を額にざっくりと打ち付けられたような激痛。\
`　It was a pain so sharp that it felt like the bulky blade of an axe was splitting apart my forehead.`\

;bg different_spiral_1b,22

me2 16

;　転んで下駄箱の角に、激しく打ち付けたに違いない。@
`　I must've hit myself hard against the corner of the shoe rack.`@`
;　私は下駄箱に寄りかかりながら、……ずるりとしゃがみ込む。\
`　While I stopped at the shoe rack, ...I spun around and squatted down.`\

bg black,22
mono 0

bg shoukou_01,0
lsp 4,":c;bmp\efe\down.bmp",0,0,200
print 0

ld c,hig_W1,6
ld c,hig_W4,80

;「……廊下は走っちゃいけないわ。@くすくすくすくす……。」@
`"...You shouldn't run in the hallways.`@` Teeheeheehee..."`@`
;＜彼岸花
;「ご、………ごめん……な……さい…………。」@
`"I, ...I'm so...rr...y..."`@`
br
;　努めて平静を装って笑顔で、私はそう言う。@
`　She said this, while putting on a pretend serene smile.`@`
;　でも、あまりの痛みと眩暈で、目を開けることさえ出来ない……。\
`　But, because the pain had made me dizzy, I couldn't even open my eyes...`\

lsp 4,":c;bmp\efe\down.bmp",0,0,240
print 2

;「だ、大丈夫ッ？！」@
`"A, Are you okay?!"`@`
;「きゃ、きゃーーッ！！@　血、血がすごい出てるよ？！」@
`"Kyaa, kyaaaaaa!!!!`@` That's, that's so much blood!!"`@`
;「………そ、………そ…う………？　………ぅ……く………。」\
`"...R, ...rea...lly...? ....u....kkkghh...."`\

;　そんな大袈裟な怪我のつもりなんてない。@
`　I didn't mean to get such a terrible injury.`@`
;　それより、早くボールを取りに行かないと、……また全部、男子に取られちゃう……。@
`　More importantly, if we don't go and get a ball, ...they'll all be taken by the boys...`@`
br
;　……私のことはいいから……、みんな早…く……、ボール……、………取って来て………。\
`　...I'm fine, so...., everyone hurr...y...and go...get a ball......`\

bg black,25
csp 4
print 25

E_M1
se1 13

;　…………ぅ、……………ぁぅ………………。@
`　...Ng, ....aghh....`@`
br
;　きゃーー、しっかりしてーー、先生ぇー、誰か先生を呼んでーー………。@
`　Kyaa~~!!! Hang in there, somebody, somebody call a teacher~~~~.....`@`
br
;　……………………………………。\
`　...................`\

bg e014,5

;　少女は意識を失い、ずるりと姿勢を崩して床に倒れる。@
`　She lost her consciousness, and ungracefully her stance collapsed to the floor.`@`
;　彼女がずるりと額でなぞった下駄箱には、血の帯がべっとりと付いている。@
`　On the shoe rack that she had clumsily gone over with her forehead, a slash of blood was thickly plastered.`@`
br
;　それを見て、女子たちが絹を裂くような悲鳴をあげる。\
`　Look at that, the girls let out a blood-curdling scream.`\

bg black,22

;　それを聞き付け、生徒たちが集まってくる。@何事かと先生たちが駆けて来る。@
`　Hearing that, the students began to gather near.`@` The teachers, thinking something was wrong, also came dashing.`@`
;　その人だかりの輪の中で、……少女は鮮血を零し続けながら、意識を失う。\
`　In the middle of the circled crowd, ...the girl whose fresh blood continued to spill, lost consciousness.`\

se1 83
;ld r,hig_def1,0
;ld c,mar_def1,3

;　その輪を抜けて、平然と歩み去る上級生らしい女子の姿は、ニンゲンたちには見えていないようだった……。\
`　Breaking out from that circle, what looked like the figure of an upperclassman calmly walked. It looked as though the h u m a n s could not see her...`\

bg shoukou_01,22

ld c,mar_i2a,24

;「い、いくら何でもやり過ぎですっ！」@
`"N, no matter how you look at this, this is taking it too far!"`@`

ld r,hig_def2,22

;「保健室程度の怪我だからいいじゃない。@命に別状があるわけじゃないし。」\
`"It's fine, it's just enough of an injury to send her to the nurse's office.`@` It's not like it's life-threatening or anything."`\

ld c,mar_i3a,80

;「度合いの問題じゃないですっ、怪我をさせるなんてやり過ぎだって言ってるんですっ。」\
`"It's not a matter of the degree, I'm telling you hurting someone is taking it too far."`\

ld r,hig_w3,80

;「……何を甘えてるのよ、毬枝？　私は妖怪よ？@　気に入った生徒を保健室へと引きずり込む、踊る彼岸花。@……その私が気に入ってしまったのよ？@　転んでも遅刻しても、忘れ物をしても抓られても、@何をやっても楽しい楽しいと言ってしまうあの子を、私は何が何でも泣かせてやりたいのよ。@くす、くすくすくすくすくすくすくす。」\
`"...Why're you being so spoiled, Marie? I'm a youkai, aren't I?`@` I'm the Dancing Higanbana, that drags the students I take interest in to the infirmary.`@` ...She's someone I took interest in, right?`@` Even if she falls down, or she's late, she forgets something, or gets pinched,`@` no matter what happens to her she just keeps saying it's so much fun, and I wanted to make her cry no matter what it took.`@` Teehee, Teeheeheeheeheehee."`\

;bg black,22
;wait 1000
bg rouka_02,22

;　少女は保健室へ担ぎ込まれていく。@
`　The girl was carried to the school infirmary.`@`

br
;　心配そうに友人たちも付いてくるが、保健室の中までは入れてもらえない。@
`　Although her worried friends stuck by her side, they were not allowed in the infirmary.`@`
;　無事を祈り、すごすごと引き上げる他なかった。\
`　There was nothing to do, but pray for her well-being and dejectedly return home.`\

bg black,22
fede 0,2000
E_A

bg hoken_01,22

me1v 11,90

;　保健室の中では、保健の先生たちが容態を見ている。@
`　In the infirmary, the nurses were watching her condition.`@`
br
;「どうですか、先生っ。@救急車を呼んだ方がいいですか…。」\
"What do you think, nurse?`@` Would it be best for us to call an ambulance...?"`\

ld c,HOK_def4,22

;「大丈夫っ。@額を綺麗に切っちゃっただけでしょ。」@
`"It's fine.`@` She cut her forehead quite cleanly."`@`
;「で、でも、意識を失ってますし……。」\
`"B, but, she's been passing out..."`\

ld c,HOK_def2,80

;「大丈夫だってっ。@子供はね、そんなヤワじゃないの！@　たくさん血が出たのを見ちゃったから、ちょっとびっくりしちゃったんでしょ。@しばらく休ませて様子を見ましょう。@担任の先生に、しばらく休ませると伝えてもらえます？」@
`"She's just fine.`@` Kids aren't that breakable!`@` She probably was just a bit surprised when she saw a lot of blood coming out.`@` Let's just let her rest for a while and keep an eye on her condition.`@` Could you let her homeroom teacher know that she'll be resting for a while?"`@`
;「あ、はい、わかりましたっ。」\
`"Ah, yes, I understand."`\

bg hoken_03,24

;　幸いにも、見た目ほどの大怪我ではないらしい。@
`　Fortunately, it didn't seem to be as bad of an injury as it looked.`@`
br
;　少女は包帯を頭にぐるぐる巻きにして、ベッドで横になっている。@
`　A bandage had been wrapped all around the girl's head, and she was lying down on the bed.`@`
;　確かにその姿は痛々しいが、……表情を見る限り、確かに穏やかそうだった。\
`　Certainly, her appearance was painful to look at but, ...according to her expression, she looked rather serene.`\

;　実際、少女自身も、そう深刻な怪我をしたとは思っていない。@
`　In actuality, she also didn't think that she'd sustained that serious of an injury.`@`
;　意識は少し遠いがちゃんとある。@先生たちには眠っているように見えているが、実際は少しだけ周りの様子が聞き取れていた。\
`　My consciousness is a little far off, but it's still there.`@` From what the teachers could tell, I was sleeping, but in reality I was just listening in on what was happening around me.`\

bg black,22

fede 0,1000
E_A

bgm1 4

;　……良かった。@大した怪我じゃ、ないみたい。@
`　...Thank goodness.`@` It looks like it's not, a serious injury.`@`
br
;　安堵するけれど、……ちょっと残念な気持ちにもなる。\
`　It's a relief, but...it also feels a bit disappointing.`\

;　こんなお天気のいい日に、チャイムと同時に教室を駆け出して、……目一杯遊ぶつもりだったのに。@
`　On a day with such nice weather like this, when the chime went off we simultaneously dashed out of the classroom, ...I was planning on playing like crazy.`@`
;　下駄箱に頭をぶつけて、……台無し。@
`　And it was ruined, ...by hitting my head on a shoe rack.`@`
br
;　……たんこぶくらいで済むと思ったのにな。@まさか、倒れちゃうなんて……。\
`　...Still, I thought I'd at least end up with a bump.`@` By no means, did I think I would collapse...`\

;　はぁ。@……………今日は、何かツイてないな。@
`　Haa.`@` .....Today, just isn't really going along with me.`@`
br
;　でも、……ま、……いいか。@
`　But, ...well, ...I guess it's fine.`@`
;　保健室のベッドって、……一度、寝てみたいと思ってたし。@
`　I was thinking, ...I wanted to sleep in the infirmary bed at least once.`@`
;　その夢が叶ったから、よしとする……か。\
`　Thinking that that wish came true, I thought I'd leave it at that...`\
se1v 69,20
bg hoken_01,2
wait 2000

;　遠くで、昼休みの終わりを告げるチャイムが聞こえる。@
`　From far away, I could hear the chime that signaled the end of the lunch break.`@`
;　……５時間目、何だっけ。\
`　...I think, it's fifth period.`\

;　そうだ。体育だ。@
`　That's right. P.E.`@`
;　今からすぐ起き上がれれば、昼休みに遊べなかった分、思い切り体を動かせるかも。@
`　If I get up right now, I could use the fact that I didn't play during my lunch break, and exercise with all my might.`@`
br
;　……………………………。@
`　...............`@`
br
;　気持ちはもう元気なのに、……体が、まるで寝惚けてるみたいに重くて、言うことを聞かない。\
`　Even though I feel more energetic, ...my body feels heavy like it was half asleep, and won't listen to what I tell it to do.`\

bg hoken_03,22

;　……あーあ……。@
`　...Man...`@`
;　今日という、○月○日○曜日という素晴らしい一日は、もう二度とないというのに。@
`　Even though this spectacular looking day, Xmonth, Xdate, Xday, will never happen another time.`@`
;　何でその貴重な学校生活の一日を、……こんなところで寝て過ごしてるんだろ。\
`　Why am I spending this precious school day, ...sleeping in this place.`\

;　…………転んだり。@忘れ物をしたり。@
`　....I tripped and fell.`@` Forgot my things.`@`
;　はぁ。@
`　Ugh.`@`
br
;　………やっぱり、……今日はツイてないや……。\
`　...Seriously, ...today just isn't so great...`\
'　保健室のベッドで寝る夢が叶ったと、精一杯プラス思考で考えていた少女も、@……重なる不運に、さすがに落胆する。\
`　The girl who was trying with all her might to think of her dream of sleeping in the infirmary bed as a plus,`@` ...as could be expected with all these misfortunes piling up, was getting discouraged.`\

bg hoken_01,22

;「…………はぁ…………。」@
`"....Sigh...."`@`
;「起きた？」@
`"Oh, you're awake?"`@`
br
;　保健の先生が気付く。\
`　The nurse noticed.`\

;「……………はぃ……。」@
`"....Yes..."`@`

ld l,HOK_def3,23

;「具合はどう？　頭痛とかある？」@
`"How do you feel? Do you have a headache or anything?"`@`
;「……全然へっちゃらです。」@
`"...Nothing to be concerned about."`@`

ld l,HOK_def2,80

;「ふむ。@判決っ、もうちょっと寝てなさい。」\
`"Hmm.`@` By my decree, you should sleep a bit longer."`\

;　保健の先生の表情は明るい。@大怪我じゃないことがわかって嬉しかった。@
`　The nurse had a bright expression.`@` She was glad that it wasn't a serious injury.`@`

br
;　……なら、すぐにも授業に戻りたい。@
`　...Then, I just want to go back to class soon.`@`
;　今日という日の５時間目という授業は、今日にしかない。@
`　The only day I can attend today's fifth period class is today.`@`
;　その、たった一度の今日という日の授業を、こんなところで寝て過ごしたくなんかない…。\
`　I don't want to waste my one chance of going to today's fifth period class sleeping in a place like this...`\

bg black,22
se1 82
bg hoken_04,24

;「大丈夫ですか？！@　廊下を走ったりするからこういうことになるんですよ、もうっ。」@
`"Are you okay?!`@` It's because you were running in the halls that you wound up like this, really."`@`
br
;　担任の先生がやってきて、怒られた。@
`　My homeroom teacher came and got mad at me.`@`
;　保健の先生が、まぁまぁと庇ってくれる。\
`　The school nurse, saying 'there, there', was standing up for me.`\

;「走ってはいけないということは、本人もガツンと痛い思いをして勉強したでしょうから。@ね？@　もう走ったりしないわよね～？」@
`"I suppose you could learn that running in the halls is a bad thing if you yourself hit your head and remember how much it hurt.`@` Right?`@` You won't run or anything anymore, right~?"`@`
;「………はい。」@
`"...No."`@`
br
;　私が頷き返すと、先生たちも安堵の微笑みを浮かべる。\
`　I responded with a nod, and a relieved smile came from both teachers.`\

;「もうしばらく寝かせてあげようと思います。@帰りのホームルームには多分、戻れると思います。」@
`"I think I'll let you sleep for a little longer.`@` (?) I think you will probably be able to go back to your homeroom to go home."`@`
;「そうですか、ありがとうございます。@じゃ、ゆっくり休んでね？　無理しちゃ駄目よっ。」\
`"If that's how it is, thank you very much.`@` So, please rest for a while, okay?`@` You mustn't push yourself."`\

;「体育、したいです……。」@
`"I want, to go to gym..."`@`
;「運動して傷が開いちゃったらどうするんですっ。@５時間目が終わって、起きれそうだったら戻ってらっしゃい。@いいですね。」\
`"What would happen if you exercised and your wound opened up?`@` After 5th period is over, if you look like you're awake, you can go back.`@` That should be fine."`\

;　５時間目が終わったら、もう授業はない。@
`　After 5th period, there aren't any more classes.`@`
;　つまり、……今日という日の学校生活は、もうこれで終わってしまうのだ。\
`　In short, ...my school life of today, is going to end here.`\

;　私は、もう全然へっちゃらなんですと言いながら起き上がろうとする。@
`　While saying I feel just fine, I tried to get up.`@`
;　それを先生に制止され、寝てないと駄目ですっ、と怒られる。@
`　Then the nurse kept me from getting up and got mad at me, saying that I have to get some sleep.`@`
br
;　私なりに元気さをアピールしようと思ったのだが、ことごとく駄目だった。\
`　I thought I'd try to protest that I was energetic in my own way, but it was altogether no good.`\

se1v 69,20
bg black,2
;bg gakkou_01,22

　やがて担任の先生は出て行き、@５時間目の始まりを告げるチャイムが鳴る。\

me1v 31,40

　校庭から聞こえるホイッスルの短い音や、みんなの元気な掛け声が聞こえてくる。@
　私のクラスメートたちの声だ。@彼らの姿が見えなくても、ここで聞いているだけでわかる。\

　……また、藤井くんたちがはしゃいでふざけてる。@
　それを、女子のリーダー格、根岸さんたちが注意して、口論になって、……それを先生に注意されてる。\

bg hoken_03,22

　……あはは。@校庭を見ることは出来なくても、この保健室の中から耳を澄ますだけで、手に取るようにわかる。@
br
　保健室は校庭に面しているのだから、校庭の声はとてもよく聞こえるのだ。@
　だから、こうして保健室の天井を見上げることしか出来なくても、……こんなにもみんなのことがわかる。\

bg black,22
fede 10,1000
E_MA

　こんなにも、みんなのことがわかるくらい、すぐ近くなのに。@
　……なのに、私にはみんなの姿が見えなくて。@……私だけが、みんなの中に加われない。@
br
　そんな、とても近いのに、とても遠い世界に自分がいることが、…………悲しかった。\

bg hoken_02,2
ld r,hig_w4,22

「くすくすくすくすくす……。@……さすがに今度は堪えたようね。@私の勝ちだわ、うっふふふふふ……。」\

ld c,mar_def2,22

「……はぁっ。@こういう時の彼岸花さんは、ちょっと軽蔑します。」@

ld r,hig_w3,80

「いいじゃない。@保健室のベッドで寝てみたいという夢を、叶えてあげたのだし。」\

ld c,mar_def3,80

「……可哀想に。@みんなと一緒に体育、したかったでしょうに。」\

bg hoken_05,22

me1v 31,0

fedexx 70,40,0,0,0,0,3000

「保健室はね、校庭の声がとてもよく聞こえるのよ。@……誰が、どんなことをして、どんな遊びをしているのか。@……とてもよくわかるのよ。」@
br
　保健室の主は、遠くを見るような目で、そう言った。\

「……こんなにも、みんなが楽しそうにしているのをすぐ近くで感じることが出来るのに。@……その姿を見ることも、加わることも出来ない。」@
br
「それは、……彼岸花さんのこと、ですか……？」\

「…………………。@それが学校妖怪の、……いえ、人ならざる世界の話だというだけのことよ。」\

bg black,22

fede 10,1000
E_MA

　……死後の世界って、……こういうところなのかな。@
br
　少女も、同じことを思う。\

　もし。@私が死んだなら。@
br
　……まだまだこの世に未練があるから、きっと成仏しないで、幽霊になりたいと願うだろう。\

　幽霊になったら、私はどこにいるんだろう？@
br
　私は学校が楽しいし。@
　考えてみれば、家で過ごすより、学校で過ごす時間の方が多いと思う。@
br
　だからきっと、……私が幽霊になったら、学校に出る幽霊になると思う。@
br
　そんなことを、これまで漠然と考えてきた。\

　……しかし、今、こうして保健室で横になり、@……校庭で楽しそうにしているみんなの声だけが聞こえていると。@
br
　それはちょっぴり、………寂しいことなのかなと、思えてしまうのだ。\

　私はこんなにもみんなの近くにいて。@
　みんなが何をして遊んでいるのか、手に取るようにわかるのに。@
br
　………でも、みんなに加わることは出来なくて。@その姿を見ることさえ、叶わない。\

bg hoken_03,22

「…………やだな。@………そんな幽霊。」@
br
　でも、ここで寝ている自分は今、学校の幽霊なのだ。@
　……私、……ひょっとして、さっき下駄箱で頭を打った時。@……実は死んでいて、……ベッドの上で、死体になっているんじゃないか。@
　そんな妄想が過ぎる。\

　それが怖くて、……両手の指をもぞもぞと動かす。@
　……動く。@……私は、死体じゃない。\

　でも、ここで寝てる限り、………死体なんだ。@幽霊なんだ。@
br
　……幽霊って、もっと楽しいものだと思ってた。@
　好きに姿を消したり、不思議な悪戯をしたりして、……いつまでもみんなと一緒にいられるものだと思ってた。\

　嫌だ。@
　こんなの幽霊ですらない。@……嫌だ、こんな死体みたいな自分………。\

bg black,22
bg hoken_02,22
se1v 69,20

　チャイムが鳴り、５時間目の終わりを告げる。@
me1v 23,20
　すると、電話が鳴った。@
br
e_m1
se1 53
　保健の先生が受話器を取る。\

　あーあー、お世話になってますー、えぇえぇ、どーもー。@
br
　そんなことを言いながら受話器を置くと、私の様子をちらりと見てから、保健室を出て行ってしまった。\

bg black,22

fede 0,1000
E_A
wait 1000

bg hoken_03,2

me1v 11,90

　足音が遠ざかり、……保健室はシンと静まり返る。@
br
　私はゆっくりと体を起こす。@
br
　……あ、いつの間にか大丈夫。@
　運びこまれた時は、あんなにも体が重かったのに。@今はもう、すっかり元通りだった。\


「……私、いつまでここにいればいいのかな……。」@
br
　首を回したり、肩を回したりしてみる。@
　恐る恐る頭の包帯にも触れてみる。@
　…………………。\

「うん。@へっちゃら。」@
br
　……早く、保健の先生、戻ってこないかな。@
br
　今から戻れば、清掃の時間には間に合う。@
　今日の学校生活で、今から参加可能な、最後の行事だ。\

bg black,2

　しばらく先生の帰りを待ってみたが、……一向に帰って来ない。@
　……………………………。\

bgm1 1

E_MA
se1v 13,50
bg hoken_01,26

「もう、死体の役、やーめた。@……私、幽霊になっちゃおう。」@
br
　私はベッドから起き出し、上履きを履く。\

　私のなりたい幽霊というのは、自由に学校を闊歩して、みんなと一緒に色々と遊べる存在。@
br
　今からそれになろう。\

se2 82
bg white,24
bg "bmp\background\school\rouka_03.bmp",24

　保健室の扉をそろりと開ける。@
br
　廊下は、たくさんの喧騒で溢れていた。@
　はしゃぎ声や笑い声。@大勢が行き交う音や階段の音。@
　人間の、確かに生きてることを示す、生活感に満ちた音が溢れていた。\

　そうだ。@こっちが生きてる世界なんだ。@
br
　私は保健室で死んでるのを止め、……廊下に出る。\

bg white,23
bg kaidan_01,23

　帰ろう。@自分の教室へ。@
　そして掃除に参加しよう。@
br
　私はささっと抜け出し、教室へ戻る。\

bg kaidan_02,23
wait 1000
bg kyou_04,25

wait 2000

「陽子ちゃん、大丈夫？！　その頭ぁ！」@
「うん、もう全然平気。@包帯も痒いし。」@
「勝手に取らない方がいいよー。」@
br
　包帯の頭にみんなが心配の声を掛けてくれる。\

　普段、あまり縁のない子まで、大丈夫？と声を掛けてくれた。@
　そういう気持ちがとても嬉しい。\

bg kyou_03,22

　みんなは、掃除しないで休んでればと言ってくれたが、私はそれを断る。@
br
　せめてお掃除くらい、みんなと一緒にしたい！@
　だって、楽しいもの。@
br
　学校の一日の、最後の行事じゃない。\

bg white,2
bg rika_04,2

　私の班は理科室の掃除。@
br
　椅子を机の上に上げ、みんなで箒を持って駆け回る。@
　掃き掃除をしてるというより、追いかけっこをしてる感じ。\

　だって、私は昼休みも体育の時間もやってない。@
　だから、一日のエネルギーの全てをこの掃除の時間に吐き出すのだ。\

bg rika_03,24

「あっはははははは…！@　待ちなさいよ、こらーっ。」@
「やめてやめて、ちょっとやめてよ、陽子ー！@　あっはははははははは…！」\

　どったんばったんと。@まるで猫が鼠を追い回す古いアニメみたいに、私たちははしゃぎ合う。@
br
　時に滑って転んだり、机の角に体をぶつけたりもするが、あまりに楽しくてへっちゃらだった。\

ld c,non_def6a,24

「……何やってんのかな、女子は。@あれじゃあ、物を壊すぞ…。」@
;＜野々宮
se1 3
「ごめんね、野々宮くーん！@　そこどいてー！@/
cl c,0
ld r,non_def6a,23
　きゃー！@　あっはははははははは！」@
「ちょこまかとー！@　こら待てー！@/
se2 3
　そりゃー！」\

se3 7

　理科準備室から理科室へ逃げる友達を追う私の箒が、何かを引っ掛けた。@
;se1 1006
se1 12
quakey 2,300

　え、何？　と思ったら、………ガッシャーンと大きな音。\

「ぅわ、…………ひゃあ…………。」@

ld r,non_def5a,80

「……ほら。@言わんこっちゃない。」@
;＜野々宮
「だ、大丈夫ぅ？　陽子ぉ……。」\

bg rika_04,22

「私は大丈夫だけど……。@……こっちの人は、大丈夫じゃないみたい。」@
br
　私が引っ掛けたのは、……あの理科室でお馴染みの、グロテスクな人体標本。@
　床に引っ繰り返って、いくつかの部品にばらけて壊れてしまった。\

「だ、大丈夫……。@黙ってればバレないよ……。」@

「………………………………。」@
;＜野々宮
「行こ、陽子……。@……陽子？」\

bg black,22
bg rika_02,0
ld c,non_def4a,22

　同じ班の、……眼鏡を掛けた男子と、目が合う。@
　……えっと、確か、野々宮くん。@
　あんまり話したことがない男子だけど、………………………。@
br
　呆れた顔をしてる。@
　…………………。\

「ごめんね、野々宮くん。@……物を壊すぞって注意してくれたのに。ごめんね。」@

ld c,non_def5a,80

「……僕に謝られても困るよ。@先生に謝ってよ。」\

「うん。@そうだね。@/
se1 82
bg white,23
bg rouka_02,23
………ごめーん、なっちゃーん。@私、先生に謝ってくるね！」@
「えー、黙ってればわからないってー。」@
「だーめ。@謝るのっ。@壊したのは私だし。@なっちゃんは関係ないから待ってて。」@
「ちょっと、……陽子ぉ～！」\

bg black,23

　私は野々宮くんの前を通り過ぎて、……職員室へ駆けていく。@
　そこには保健の先生もいて、黙って帰らないようにとダブルで怒られた。\

　……心の中にちょっぴり、黙ってればバレないかもって気持ちがあったのは事実。@
br
　でも、そんな気持ちのまま今日を終えたら、ずっと心にそれが残って、気分がすっきりしないに決まってる。@
br
　だから、先生には怒られたけれど、………心はとっても晴れやかだった。\

bg white,2
bg kyou_02,2

　掃除の時間の悪ふざけをいっぱい満喫して。@
　いよいよ帰りのホームルーム。@
　先生から連絡事項を聞き、気を付けて帰るようにと念を押される。@
br
　そして、起立。@
　礼。\

bg kyou_03,22

「「「さよーならーーーー！！」」」@
br
　クラスメート全員での最後の大合唱。@
　朝のおはようございますに比べ、開放感から、みんなが一番気持ちよく合唱できるのだ。\

se1v 82,90
quakex 3,300
　そして、がたがたと一斉に賑やかになって。@
　帰ろー、一緒に帰ろー。@今日、帰り、誰々ん家に寄ってかね？　いーねー、いこいこ！@
　なんて感じに賑やかになる。\

「陽子～、一緒に帰ろー！」@
br
　友達が声を掛けてくる。@
　私は満面の笑顔で応えるのだ。\

「ごめん。@今日はちょっと学校で用事があるの。@だから、みんなは先に帰ってて。」@
「そう？　ふーん。@……じゃあね！@　また明日ね！@　ばいば～い！！」@
「うんっ。@ばいばーい！@　また明日ねーっ。」\

　みんなは一斉に駆け出して教室を飛び出していく。@
　他のクラスもそれぞれホームルームを終え、廊下は帰りを急ぐ子たちで大賑わいになる。\

　その賑わいも、わいわいざわざわも、少しずつ遠退いていく。@

bg rouka_03,2
wait 2000
bg kaidan_01,2

br
　廊下から階段へ。@/
bg shoukou_01,22
階段から昇降口へ。@
br
　そして校庭へと散り、……学校は静寂に、満たされていく。\

bg black,2

fede 0,2000
E_A

wait 2000

bg kyou_02u,42

bgm1 4

　日は少しずつ傾き、教室の中を黄昏色に染める。@
　先生が閉め忘れた窓から、涼しい風が入って、わずかにカーテンを揺らした。@
br
　その、風が膨らます白いカーテンの束が、……私が小さい頃に大好きだった、白いドレスのことを思い出させる。\

　また明日ね。@ばいばい、か。@
　また明日、会えるから。@それまでばいばいって意味だよね。\

bg black,22
　…………ばいばい、みんな。@
　さよなら……。\

　私は黄昏色の教室をもう一度見渡す。@
　それから、ゆっくりと立ち上がり、教室を後にする。\

bg kyou_04,3
wait 1000
bg kaidan_02,2

　みんなは、昇降口へ向かうから階段を下へ。@
　私は、上へ。@
br
　一歩一歩を踏みしめながら、上へ、上へ。屋上へ。\

bg "bmp\background\school\kaidan_03u.bmp",5
wait 2000
bg "bmp\background\school\kaidan_04u.bmp",4

wait 2000

se1 16
bg black,3
wait 1000

me1v 16,50

bg white,2

bg "bmp\background\school\Air_01.bmp",6

　屋上の扉を開けると、……素晴らしい夕日が私を迎えてくれた。@
br
　その夕日を背負って、二人の人影が。\

bg okujou_01u,42
wait 2000


ld l,hig_w1,0
ld c,mar_w1,2

wait 2000


ld c,mar_w2,80
「…………どうでしたか。@沼田陽子さん。」\

bg "bmp\background\school\Air_01.bmp",3

ld r,yo2_def1,24
「はい。@……とっても楽しい一日でした。」@

ld l,hig_w2,22
「くすくす。@色々と酷い目にも遭ったんじゃない？」\

ld r,yo2_def2,80
「はい。@転んだり、遅刻したり。@忘れ物をしたり怒られたり。@怪我をして保健室に運ばれたりもしたけれど。@………もう、色んなことがいっぱいいっぱいで、……とても、楽しかったです。」\

ld l,hig_w1,80
「………………くす。@負けたわ。@どう？　これで気が済んだ？」@

ld r,yo2_def1,80
「はい。@……幽霊として居残るのは、やっぱりとても寂しいことです。@私には、ちょっと出来そうにありません。」\

ld l,hig_def1,80
「私もそれがいいと思うわ。@幽霊なんて、楽しいことなんて何もないわよ。@……妖怪だってそう。@だって、私たちには下校はない。@……帰るところはないんだから。」\

;bg "bmp\background\school\Air_01.bmp",6

cl a,2

「……はい。@……だからもう、帰ろうと思います。」\

　私は夕日に照らされる校庭を見下ろす。@
　部活に勤しむ子。@まだまだ遊び足りなくて遊具で遊んでる子。@色んな子が見えた。@
br


　かつて、私もあの中の一人だったんだ。@
　そして今日。@私は確かに、あの中の一人だったんだ。\

　もう。@思い残すことなんてない。@
　今日の感想はたったの一言。\

bg okujou_01u,22
mld c,yo2_def3n,22

「すごく、……楽しかったです。@学校って、……こんなにも楽しい一日だったんですね。@……生きてる内に、気付きたかったな。@はは、はははははははは……。」@

ld r,MAR_def4,22

「……沼田さん……。」\ ;＜毬枝

mld c,yo2_def2n,80

　私は笑い続けた。@
　愉快だったから。@楽しかったから。@
　こんな素敵な一日の終わりを、笑って終えられるなんて。@
　それがとてもとても嬉しくて。@……いつまでもいつまでも、笑っていた…。\

mcl c,0
bg "bmp\background\school\Air_01.bmp",42
;bg okujou_01u,42
;ld r,you_def1,0
ld r,hig_w1,22
ld r,hig_w3,80

「約束。@……忘れてないわよね？」@

ld c,yo2_def1,24

「はい。@よろしくお願いします。」\

ld l,mar_def4a,22

「……彼岸花さん。@……どうしても、……食べるんですか。」\

;cl r,0
ld r,hig_def2,80

「そういう約束だから、今日という奇跡をプレゼントしたのよ。@……未だ生に未練のある魂に、もう一度学校生活を味わわせて、未練を強めて苦しめて、その去り際の魂をいただく。@……どんな味の魂に仕上がってくれたか、楽しみで舌なめずりしちゃうんだから。」@
br
　彼岸花はくすりと笑って、小さな舌で唇を拭う仕草を見せる。\

bg okujou_01u,24

ld r,mar_def3n,22

「……ごめんね、沼田さん。@……私にもっと力があれば……。」@

ld c,yo2_def2n,22

「いいんです。@ありがとう。@……二人ともお元気で。@ばいばい。@……さよなら。」@
br
　最後に、少女はそう言って。@……親しい友達と別れるように、手を振った。\

cl c,0
mld c,yo2_def3n,2

wait 2000

mld c,yo2_def1n,2
mcl c,0

lsp 4,":a;bmp\background\efe\red_Waku.bmp",0,0,120
print 8

se1 22

bg white,2
csp 4
print 0
bg black,2
　そして、……彼女の姿がゆっくりと崩れていく。@

　ふわりと、………白い魂が、線香の煙のように、……そして風船のように、ゆっくりと風に棚引きながら浮かび上がっていく。\
lsp 4,"bmp\background\efe\punch_l1.bmp",0,0,60
print 6
wait 1000
lsp 4,"bmp\background\efe\punch_r2.bmp",0,0,100
print 6

　それを彼岸花は白い指で、そっと摘んで捕まえる。@
　そして、……小さな唇で、その尾を食む。\
;se1 9
;bg white,1
csp -1
;print 0
bg black,22

bg "bmp\background\school\Air_01.bmp",2
;bg okujou_02,2

ld r,mar_def1,22

「…………………………………。」@
;＜毬枝

ld l,HIG_def5,22

「……何？　あげないわよ。@私の獲物だもの。」@

;bg okujou_01u,0
;ld r,mar_def1,0
;ld l,hig_def1,23
ld r,mar_def2,80

「欲しいなんて言ってません。@……じゃ、私は戻りますね。」\

cl r,22

ld l,hig_def2,80

「あら、嫌にあっさりね。@その子を見逃してあげて云々って、もう少し騒ぐかと思ったら。」@
「騒いでも、私の言うことなんていつも聞いてくれないじゃないですか。」\

;cl l,0
ld l,hig_w3,80

「それもそうだわ。@じゃあ確かに、言うだけ無駄というものね。」\

;bg black,22

「私は戻って、ひとりでお茶にしようと思います。@昨日、職員室で美味しそうな苺入りの大福を見つけたので。」@

cl l,0
ld c,hig_def5,23

「…………それ、当然、二つあるのよね？」\

bg black,23
bg kaidan_04u,0
ld r,mar_Def2,23
ld r,mar_Def4,80

「ありますよ。@だから二つとも食べることにします。@彼岸花さんはこれからお食事で満腹でしょうから。」@
br

cl r,22

　毬枝はそれだけを言い残すと、さっさと階段を降りていく。\

「ちょ、ちょっと待ちなさいよ、毬枝ぇーーっ。@もーー……！」\

bg black,22

　彼岸花は、毬枝の背中と、摘んでいる魂の双方を見比べる。@
　そしてもう一度、魂の尾をぱくりと食んで、……悩み込むように眉をしかめる。\

bg okujou_01u,22
;ld c,hig_def5,2
wait 2000
ld c,hig_def5,22

「……やっぱり、私の好みの味じゃないわ。」@
br
　魂をプイっと吐き出すと、ハンカチを取り出して口元を拭う。@
　その拍子に、……魂はするりと彼女の指先を潜り抜け、……ゆっくりと空へ昇っていく。\

se1v 22,40

bg "bmp\background\school\Air_01.bmp",0
lsp 4,"bmp\background\efe\punch_r3.bmp",0,0,200
print 2
lsp 4,"bmp\background\efe\punch_r2.bmp",0,0,100
print 2
lsp 4,"bmp\background\efe\punch_r1.bmp",0,0,100
print 2
csp 4
print 42

　あら、いけない。@……彼岸花は苦笑いしながらそれを見上げる。@
br
　黄昏色の空に、それはどんどん吸い込まれるように、……遠く、小さくなっていく。\

ld r,hig_def2,22

「……とんだタダ働きだわ。」@
br
　彼岸花は肩を竦め、ハンカチをしまう。\

;bg white,2
;bg kaidan_02,23
;ld c,hig_def1,23

cl r,22

「毬枝っ。@まさか本気で独り占めするつもりじゃないわよね…？！@　一個は私にも寄越しなさい？！@/
;cl c,23
;ld r,hig_def1,23
　じゃないともう、保健室のテレビ、見せてあげないわよ…！@　ねぇ、ちょっと聞こえてるかしらー？！」\


;cl r,23

bg black,2
;bg white,2

fede 10,2000
E_MA

me1v 31,0 ;輪廻的なイメージ

fedexx 70,70,0,0,0,0,3000

lsp 4,"bmp\background\efe\punch_r3.bmp",0,0,100
print 22
lsp 4,"bmp\background\efe\punch_r2.bmp",0,0,50
print 22
lsp 4,"bmp\background\efe\punch_r1.bmp",0,0,20
print 22
csp -1
print 22



bg e022,42
wait 1000
bg black,42




;bg black,2
bgcopy ;背景をリセット

fede 0,2000
E_A

wait 2000

;;＜おしまい＞













if %UMINEKOEND < 6 mov %UMINEKOEND,6 : mov %END_FLG,6 ;クリアフラグの変更
	saveoff            ;セーブオフで、処理を高速化する。
	erasetextwindow 0  ;テキストエフェクトを切る事で処理を高速化
	rmode 0            ;右クリックのメニュー表示の無効化
	textoff


goto *b_title
;reset
